USE JBlue;
DROP TABLE IF EXISTS `pym_payments`;
CREATE TABLE `pym_payments` (
  `id` int NOT NULL AUTO_INCREMENT,
  `payment_type` int DEFAULT NULL,
  `uudi` char(36) NOT NULL,
  `employee` int NOT NULL,
  `user` int NOT NULL COMMENT 'usuario de la toma(puede tener multiples tomas con diferentes tipos)',
  `water_intake` int NOT NULL COMMENT 'numero de toma que se registra(unico)',
  `water_intake_type` int NOT NULL COMMENT 'tipo de toma de agua potable(define el costo)',
  `payment_method` int NOT NULL DEFAULT '1' COMMENT '1 EFECTIVO\\\\n2 TRANFERENCIA\\\\n3 TARJETA DE CREDITO\\\\n4 TARJETA DE DEBITO',
  `total_cost` decimal(10,2) NOT NULL,
  `amount_paid` decimal(10,2) NOT NULL,
  `change_amount` decimal(10,2) NOT NULL DEFAULT '0.00',
  `month_paid` date NOT NULL COMMENT 'MES PAGADO',
  `status` int NOT NULL DEFAULT '7' COMMENT 'STATUS POR DEFECTO: ''PENDIENTE''',
  `date_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'FECHA DE ACTUALIZACION DEL REGISTRO(EN CASO DE QUE EL PAGO QUEDE PENDIENTE O SE CANCELE)',
  `date_register` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DE REGISTRO DEL PAGO',
  `date_end` timestamp NULL DEFAULT NULL COMMENT 'FECHA ASIGNADA EN CASO DE CANCELAR EL PAGO',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uudi_UNIQUE` (`uudi`),
  KEY `fk_payment_employee_idx` (`employee`),
  KEY `fk_payment_user_idx` (`user`),
  KEY `fk_payment_wi_idx` (`water_intake`),
  KEY `fk_payment_wit_idx` (`water_intake_type`),
  KEY `fk_payment_status_idx` (`status`),
  KEY `fk_payment_type_idx` (`payment_type`),
  CONSTRAINT `fk_payment_employee` FOREIGN KEY (`employee`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_payment_status` FOREIGN KEY (`status`) REFERENCES `cat_status` (`id`),
  CONSTRAINT `fk_payment_type` FOREIGN KEY (`payment_type`) REFERENCES `cat_payment_type` (`id`),
  CONSTRAINT `fk_payment_user` FOREIGN KEY (`user`) REFERENCES `usr_user` (`id`),
  CONSTRAINT `fk_payment_wi` FOREIGN KEY (`water_intake`) REFERENCES `wki_water_intakes` (`id`),
  CONSTRAINT `fk_payment_wit` FOREIGN KEY (`water_intake_type`) REFERENCES `wki_water_intake_type` (`id`)
) COMMENT='TABLA DE PAGOS REGISTRADOS, EN PROCESO Y REALIZADOS'