USE JBlue;
DROP TABLE IF EXISTS `pro_process`;
DROP TABLE IF EXISTS `usr_users_consumers`;
DROP TABLE IF EXISTS `wki_water_intakes`;
DROP TABLE IF EXISTS `hys_administration_history`;

CREATE TABLE `hys_administration_history` (
  `id` int NOT NULL AUTO_INCREMENT,
  `year_of_administration` int NOT NULL,
  `root` int NOT NULL DEFAULT '1',
  `administrator` int DEFAULT NULL,
  `president` int NOT NULL,
  `treasurer` int NOT NULL,
  `secretary` int DEFAULT NULL,
  `plumber` int DEFAULT NULL,
  `intern_1` int DEFAULT NULL,
  `intern_2` int DEFAULT NULL,
  `internt_3` int DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `status` int NOT NULL DEFAULT '1',
  `date_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `date_register` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_adm_his_root_idx` (`root`),
  KEY `fk_adm_his_admind_idx` (`administrator`),
  KEY `fk_adm_his_president_idx` (`president`),
  KEY `fk_adm_his_tesure_idx` (`treasurer`),
  KEY `fk_adm_his_secretary_idx` (`secretary`),
  KEY `fk_adm_his_plumber_idx` (`plumber`),
  KEY `fk_adm_his_inter_1_idx` (`intern_1`),
  KEY `fk_adm_his_inter_2_idx` (`intern_2`),
  KEY `fk_adm_his_inter_3_idx` (`internt_3`),
  KEY `fk_adm_his_status_idx` (`status`),
  CONSTRAINT `fk_adm_his_admind` FOREIGN KEY (`administrator`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_inter_1` FOREIGN KEY (`intern_1`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_inter_2` FOREIGN KEY (`intern_2`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_inter_3` FOREIGN KEY (`internt_3`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_plumber` FOREIGN KEY (`plumber`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_president` FOREIGN KEY (`president`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_root` FOREIGN KEY (`root`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_secretary` FOREIGN KEY (`secretary`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_adm_his_status` FOREIGN KEY (`status`) REFERENCES `cat_status` (`id`),
  CONSTRAINT `fk_adm_his_treasurer` FOREIGN KEY (`treasurer`) REFERENCES `emp_employee` (`id`)
) COMMENT = 'TABLA DE LA ADMINISTRACION ACTUAL';


CREATE TABLE `wki_water_intakes` (
  `id` int NOT NULL AUTO_INCREMENT,
  `cost_procedure` decimal(10,2) DEFAULT NULL COMMENT 'costo del tramite',
  `water_intake_type` int NOT NULL,
  `user` int NOT NULL,
  `user_name` varchar(90) NOT NULL,
  `street1` int NOT NULL,
  `street2` int DEFAULT NULL,
  `location` tinytext,
  `description` mediumtext,
  `status` int NOT NULL DEFAULT '2',
  `date_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `date_register` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_wi_water_intake_type_idx` (`water_intake_type`),
  KEY `fk_wi_user_idx` (`user`),
  KEY `fk_wi_street1_idx` (`street1`),
  KEY `fk_wi_street2_idx` (`street2`),
  KEY `fk_wi_status_idx` (`status`),
  CONSTRAINT `fk_wi_status` FOREIGN KEY (`status`) REFERENCES `cat_status` (`id`),
  CONSTRAINT `fk_wi_street1` FOREIGN KEY (`street1`) REFERENCES `cat_street` (`id`),
  CONSTRAINT `fk_wi_street2` FOREIGN KEY (`street2`) REFERENCES `cat_street` (`id`),
  CONSTRAINT `fk_wi_user` FOREIGN KEY (`user`) REFERENCES `usr_user` (`id`),
  CONSTRAINT `fk_wi_water_intake_type` FOREIGN KEY (`water_intake_type`) REFERENCES `wki_water_intake_type` (`id`)
) COMMENT = 'TOMAS DE AGUAS REGISTRADAS';


CREATE TABLE `usr_users_consumers` (
  `id` int NOT NULL AUTO_INCREMENT,
  `water_intake` int NOT NULL,
  `holder` int NOT NULL,
  `consumer` int NOT NULL,
  `status` int NOT NULL DEFAULT '1',
  `date_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `date_register` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `date_end` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_users_consumers_wi_idx` (`water_intake`),
  KEY `fk_users_consumers_holder_idx` (`holder`),
  KEY `fk_users_consumers_consumer_idx` (`consumer`),
  KEY `fk_users_consumers_status_idx` (`status`),
  CONSTRAINT `fk_users_consumers_consumer` FOREIGN KEY (`consumer`) REFERENCES `usr_user` (`id`),
  CONSTRAINT `fk_users_consumers_holder` FOREIGN KEY (`holder`) REFERENCES `usr_user` (`id`),
  CONSTRAINT `fk_users_consumers_status` FOREIGN KEY (`status`) REFERENCES `cat_status` (`id`),
  CONSTRAINT `fk_users_consumers_wi` FOREIGN KEY (`water_intake`) REFERENCES `wki_water_intakes` (`id`)
) COMMENT = 'CONSUMIDORES ASOCIADOS A UNA TOMA DE AGUA';

CREATE TABLE `pro_process` (
  `id` int NOT NULL AUTO_INCREMENT,
  `process_type` int NOT NULL,
  `employee_start` int NOT NULL,
  `date_start` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `employee_valid` int DEFAULT NULL,
  `date_valid` timestamp NULL DEFAULT NULL,
  `employee_payment` int DEFAULT NULL,
  `date_payment` timestamp NULL DEFAULT NULL,
  `employee_ends` int DEFAULT NULL,
  `date_end` timestamp NULL DEFAULT NULL,
  `employe_print` int DEFAULT NULL,
  `date_print` timestamp NULL DEFAULT NULL,
  `administration` int NOT NULL,
  `last_employee_update` int NOT NULL,
  `current_db_user` varchar(45) NOT NULL,
  `original_user` int NOT NULL,
  `water_intake` int DEFAULT NULL,
  `status` int NOT NULL DEFAULT '1',
  `date_register` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `fk_cp_employe_start_idx1` (`employee_valid`),
  KEY `fk_cp_employe_start_idx` (`employee_ends`),
  KEY `fk_cp_employe_start` (`employee_start`),
  KEY `fk_cp_current_user_idx` (`last_employee_update`),
  KEY `fk_cp_orignal_user_idx` (`original_user`),
  KEY `fk_cp_water_intake_idx` (`water_intake`),
  KEY `fk_cp_status_idx` (`status`),
  KEY `fk_cp_process_idx` (`process_type`),
  KEY `fk_cp_administration_idx` (`administration`),
  KEY `fk_cp_employee_pay_idx` (`employee_payment`),
  KEY `fk_cp_employee_print_idx` (`employe_print`),
  CONSTRAINT `fk_cp_administration` FOREIGN KEY (`administration`) REFERENCES `hys_administration_history` (`id`),
  CONSTRAINT `fk_cp_current_user` FOREIGN KEY (`last_employee_update`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_cp_employe_end` FOREIGN KEY (`employee_ends`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_cp_employe_start` FOREIGN KEY (`employee_start`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_cp_employe_valid` FOREIGN KEY (`employee_valid`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_cp_employee_pay` FOREIGN KEY (`employee_payment`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_cp_employee_print` FOREIGN KEY (`employe_print`) REFERENCES `emp_employee` (`id`),
  CONSTRAINT `fk_cp_orignal_user` FOREIGN KEY (`original_user`) REFERENCES `usr_user` (`id`),
  CONSTRAINT `fk_cp_process` FOREIGN KEY (`process_type`) REFERENCES `cat_process_type` (`id`),
  CONSTRAINT `fk_cp_status` FOREIGN KEY (`status`) REFERENCES `cat_status` (`id`),
  CONSTRAINT `fk_cp_water_intake` FOREIGN KEY (`water_intake`) REFERENCES `wki_water_intakes` (`id`)
) COMMENT = 'TABLA DE TRAMITES REALIZADOS';