/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.model.constants;

import jsoftware.com.jutil.db.JDBTable;

/**
 *
 * @author juanp
 */
public class _ConstTables extends _TableNameConsts {

    public static final JDBTable CAT_GROUP_PREFIX_TABLE = new JDBTable(CAT_GROUP_PREFIX_TABLE_NAME, CAT_GROUP_PREFIX_FIELDS, CAT_GROUP_PREFIX_FIELDS_GS);
    public static final JDBTable CAT_HISTORY_TYPE_MOV_TABLE = new JDBTable(CAT_HISTORY_TYPE_MOV_TABLE_NAME, CAT_HISTORY_TYPE_MOV_FIELDS, CAT_HISTORY_TYPE_MOV_FIELDS_GS);
    public static final JDBTable CAT_PROCESS_TYPE_TABLE = new JDBTable(CAT_PROCESS_TYPE_TABLE_NAME, CAT_PROCESS_TYPE_FIELDS, CAT_PROCESS_TYPE_FIELDS_GS);
    public static final JDBTable CAT_STATUS_TABLE = new JDBTable(CAT_STATUS_TABLE_NAME, CAT_STATUS_FIELDS, CAT_STATUS_FIELDS_GS);
    public static final JDBTable CAT_STREET_TABLE = new JDBTable(CAT_STREET_TABLE_NAME, CAT_STREET_FIELDS, CAT_STREET_FIELDS_GS);
    public static final JDBTable CAT_TABLES_DB_TABLE = new JDBTable(CAT_TABLES_DB_TABLE_NAME, CAT_TABLES_DB_FIELDS, CAT_TABLES_DB_FIELDS_GS);
    public static final JDBTable CAT_USER_MOVEMENTS_TABLE = new JDBTable(CAT_USER_MOVEMENTS_TABLE_NAME, CAT_USER_MOVEMENTS_FIELDS, CAT_USER_MOVEMENTS_FIELDS_GS);
    public static final JDBTable DEV_PARAMETERS_TABLE = new JDBTable(DEV_PARAMETERS_TABLE_NAME, DEV_PARAMETERS_FIELDS, DEV_PARAMETERS_FIELDS_GS);
    public static final JDBTable EMP_EMPLOYEE_TYPES_TABLE = new JDBTable(EMP_EMPLOYEE_TYPES_TABLE_NAME, EMP_EMPLOYEE_TYPES_FIELDS, EMP_EMPLOYEE_TYPES_FIELDS_GS);
    public static final JDBTable EMP_EMPLOYEES_TABLE = new JDBTable(EMP_EMPLOYEES_TABLE_NAME, EMP_EMPLOYEES_FIELDS, EMP_EMPLOYEES_FIELDS_GS);
    public static final JDBTable HYS_HISTORY_TABLE = new JDBTable(HYS_HISTORY_TABLE_NAME, HYS_HISTORY_FIELDS, HYS_HISTORY_FIELDS_GS);
    public static final JDBTable HYS_PROGRAM_HISTORY_TABLE = new JDBTable(HYS_PROGRAM_HISTORY_TABLE_NAME, HYS_PROGRAM_HISTORY_FIELDS, HYS_PROGRAM_HISTORY_FIELDS_GS);
    public static final JDBTable LOGBOOK_TO_PAYMENTS_TABLE = new JDBTable(LOGBOOK_TO_PAYMENTS_TABLE_NAME, LOGBOOK_TO_PAYMENTS_FIELDS, LOGBOOK_TO_PAYMENTS_FIELDS_GS);
    public static final JDBTable LOGBOOK_TO_USERS_TABLE = new JDBTable(LOGBOOK_TO_USERS_TABLE_NAME, LOGBOOK_TO_USERS_FIELDS, LOGBOOK_TO_USERS_FIELDS_GS);
    public static final JDBTable LOGBOOK_TO_WATER_INTAKES_TABLE = new JDBTable(LOGBOOK_TO_WATER_INTAKES_TABLE_NAME, LOGBOOK_TO_WATER_INTAKES_FIELDS, LOGBOOK_TO_WATER_INTAKES_FIELDS_GS);
    public static final JDBTable LOGBOOK_TO_WATER_INTAKES_TYPE_TABLE = new JDBTable(LOGBOOK_TO_WATER_INTAKES_TYPE_TABLE_NAME, LOGBOOK_TO_WATER_INTAKES_TYPE_FIELDS, LOGBOOK_TO_WATER_INTAKES_TYPE_FIELDS_GS);
    public static final JDBTable PRO_CHANGE_OWNER_TABLE = new JDBTable(PRO_CHANGE_OWNER_TABLE_NAME, PRO_CHANGE_OWNER_FIELDS, PRO_CHANGE_OWNER_FIELDS_GS);
    public static final JDBTable PRO_PROCESS_TABLE = new JDBTable(PRO_PROCESS_TABLE_NAME, PRO_PROCESS_FIELDS, PRO_PROCESS_FIELDS_GS);
    public static final JDBTable PYM_OTHER_PAYMENTS_TABLE = new JDBTable(PYM_OTHER_PAYMENTS_TABLE_NAME, PYM_OTHER_PAYMENTS_FIELDS, PYM_OTHER_PAYMENTS_FIELDS_GS);
    public static final JDBTable PYM_OTHER_PAYMENTS_TYPE_TABLE = new JDBTable(PYM_OTHER_PAYMENTS_TYPE_TABLE_NAME, PYM_OTHER_PAYMENTS_TYPE_FIELDS, PYM_OTHER_PAYMENTS_TYPE_FIELDS_GS);
    public static final JDBTable PYM_PROCEDURE_PAYMENTS_TABLE = new JDBTable(PYM_PROCEDURE_PAYMENTS_TABLE_NAME, PYM_PROCEDURE_PAYMENTS_FIELDS, PYM_PROCEDURE_PAYMENTS_FIELDS_GS);
    public static final JDBTable PYM_SERVICE_PAYMENTS_TABLE = new JDBTable(PYM_SERVICE_PAYMENTS_TABLE_NAME, PYM_SERVICE_PAYMENTS_FIELDS, PYM_SERVICE_PAYMENTS_FIELDS_GS);
    public static final JDBTable PYM_SURCHARGE_PAYMENTS_TABLE = new JDBTable(PYM_SURCHARGE_PAYMENTS_TABLE_NAME, PYM_SURCHARGE_PAYMENTS_FIELDS, PYM_SURCHARGE_PAYMENTS_FIELDS_GS);
    public static final JDBTable USR_USER_TYPE_TABLE = new JDBTable(USR_USER_TYPE_TABLE_NAME, USR_USER_TYPE_FIELDS, USR_USER_TYPE_FIELDS_GS);
    public static final JDBTable USR_USERS_TABLE = new JDBTable(USR_USERS_TABLE_NAME, USR_USERS_FIELDS, USR_USERS_FIELDS_GS);
    public static final JDBTable USR_USERS_CONSUMERS_TABLE = new JDBTable(USR_USERS_CONSUMERS_TABLE_NAME, USR_USERS_CONSUMERS_FIELDS, USR_USERS_CONSUMERS_FIELDS_GS);
    public static final JDBTable WKI_WATER_INTAKE_TYPE_TABLE = new JDBTable(WKI_WATER_INTAKE_TYPE_TABLE_NAME, WKI_WATER_INTAKE_TYPE_FIELDS, WKI_WATER_INTAKE_TYPE_FIELDS_GS);
    public static final JDBTable WKI_WATER_INTAKES_TABLE = new JDBTable(WKI_WATER_INTAKES_TABLE_NAME, WKI_WATER_INTAKES_FIELDS, WKI_WATER_INTAKES_FIELDS_GS);
}
