/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas.menucargos.administrador;

import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.MemoCache;
import com.jblue.vista.jbmarco.VistaExtendida;
import com.jblue.vista.vistas.menucargos.administrador.sub.PersonalC;
import com.jblue.vista.vistas.menucargos.administrador.sub.PersonalR;

/**
 *
 * @author jp
 */
public class VAdministrador extends VistaExtendida {

    /**
     * Creates new form VAdministrador
     */
    public VAdministrador() {
        initComponents();
        memo_cache = FabricaCache.MC_PERSONAL;
        personal_consultas = new PersonalC(this);
        personal_registros = new PersonalR(this);
        llamable();
    }

    @Override
    protected void llamable() {
    }

    @Override
    public void componentesEstadoInicial() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Administrador"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private final MemoCache memo_cache;
    private final PersonalC personal_consultas;
    private final PersonalR personal_registros;

    public MemoCache getMemo_cache() {
        return memo_cache;
    }

}
