/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.otros.news.vistas;

import com.jblue.otros.news.ventanas.NewMenuPrincipal;
import javax.swing.JButton;

/**
 *
 * @author juan-campos
 */
public class NewMenuType extends javax.swing.JPanel {

    private final NewMenuPrincipal father;
    private final JButton[] options;

    /**
     * Creates new form NewMenuType
     *
     * @param father
     */
    public NewMenuType(NewMenuPrincipal father) {
        initComponents();
        options = new JButton[]{
            jButton1, jButton2, jButton3,
            jButton4, jButton5, jButton6,
            jButton7, jButton8, jButton9, 
        };
        this.father = father;
        for (JButton i : options) {
            i.addActionListener(e -> {
                this.father.goToHome();
            });
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton9 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        jButton9.setText("Ayuda");
        add(jButton9);

        jButton1.setText("Perfil");
        add(jButton1);

        jButton4.setText("Secretario");
        add(jButton4);

        jButton7.setText("Tesorero");
        add(jButton7);

        jButton5.setText("Presidente");
        add(jButton5);

        jButton6.setText("Administrador");
        add(jButton6);

        jButton2.setText("Configuraciones");
        add(jButton2);

        jButton3.setText("Herramientas del Software");
        add(jButton3);

        jButton8.setText("Previos");
        jButton8.setName(""); // NOI18N
        add(jButton8);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
