/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.otros.news.vistas;

import com.jblue.modelo.objetos.OCalles;
import com.jblue.modelo.objetos.OTipoTomas;
import java.awt.CardLayout;

/**
 *
 * @author juan-campos
 */
public class NewUsuarios extends javax.swing.JPanel {

    private CardLayout ly;

    /**
     * Creates new form NewUsuarios
     */
    public NewUsuarios() {
        initComponents();
        ly = (CardLayout) root_panel.getLayout();
        ly.show(root_panel, register_panel.getName());
        eventos();
    }

    private void eventos() {
        register_button.addActionListener(e -> {
            ly.show(root_panel, register_panel.getName());
        });
        consult_button.addActionListener(e -> {
            ly.show(root_panel, search_panel.getName());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root_panel = new javax.swing.JPanel();
        search_panel = new javax.swing.JPanel();
        panel_filtros = new javax.swing.JPanel();
        pf_bar_super = new javax.swing.JPanel();
        filtro_quitar = new javax.swing.JButton();
        filtros = new javax.swing.JCheckBox();
        pf_filtros = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        filtro_calle = new javax.swing.JComboBox<>();
        jPanel26 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        filtro_toma = new javax.swing.JComboBox<>();
        jPanel28 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        filtro_estado = new javax.swing.JComboBox<>();
        jPanel24 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        filtro_is_titular = new javax.swing.JCheckBox();
        filtro_is_consumidor = new javax.swing.JCheckBox();
        jPanel31 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        filtro_Titular = new javax.swing.JTextField();
        panel_tabla = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        buscador_tabla = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        anterior = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        recargar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_usuarios = new javax.swing.JTable();
        register_panel = new javax.swing.JPanel();
        south_panel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        btn_guardar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_cancelar = new javax.swing.JButton();
        center_panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pc_tipo = new javax.swing.JPanel();
        campo_is_titular = new javax.swing.JCheckBox();
        campo_is_usuario = new javax.swing.JCheckBox();
        pc_nombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pc_ap = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campo_ap = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pc_am = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campo_am = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        pc_tipo_toma = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campo_tipo_toma = new javax.swing.JComboBox<>();
        man_tipo_toma = new javax.swing.JCheckBox();
        pc_calle = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campo_calle = new javax.swing.JComboBox<>();
        man_calle = new javax.swing.JCheckBox();
        pc_ncasa = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campo_no_casa = new javax.swing.JTextField();
        sn_numero = new javax.swing.JCheckBox();
        pc_estado = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        campo_estado = new javax.swing.JComboBox<>();
        man_estado = new javax.swing.JCheckBox();
        left_panel = new javax.swing.JPanel();
        right_panel = new javax.swing.JPanel();
        north_panel = new javax.swing.JPanel();
        np_cp_center = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        consult_button = new javax.swing.JButton();
        np_cp_west = new javax.swing.JPanel();
        buscar = new javax.swing.JButton();
        np_cp_east = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(450, 350));
        setName("Usuarios"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        root_panel.setLayout(new java.awt.CardLayout());

        search_panel.setName("Registar"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout());

        panel_filtros.setPreferredSize(new java.awt.Dimension(1000, 170));
        panel_filtros.setLayout(new java.awt.BorderLayout());

        pf_bar_super.setLayout(new java.awt.BorderLayout());

        filtro_quitar.setText("Quitar filtros");
        filtro_quitar.setPreferredSize(new java.awt.Dimension(150, 29));
        pf_bar_super.add(filtro_quitar, java.awt.BorderLayout.LINE_END);

        filtros.setText("Filtros");
        pf_bar_super.add(filtros, java.awt.BorderLayout.CENTER);

        panel_filtros.add(pf_bar_super, java.awt.BorderLayout.NORTH);

        pf_filtros.setLayout(new java.awt.GridLayout(1, 2));

        jPanel22.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel22.setLayout(new java.awt.GridLayout(4, 1));

        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Calle");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel25.add(jLabel12, java.awt.BorderLayout.WEST);

        filtro_calle.setName("calle"); // NOI18N
        jPanel25.add(filtro_calle, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel25);

        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("T. Toma");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel26.add(jLabel13, java.awt.BorderLayout.WEST);

        filtro_toma.setName("ttoma"); // NOI18N
        jPanel26.add(filtro_toma, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel26);

        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("Estado");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel28.add(jLabel15, java.awt.BorderLayout.WEST);

        filtro_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ESTADO", "ACTIVO", "INACTIVO" }));
        filtro_estado.setName("estado"); // NOI18N
        jPanel28.add(filtro_estado, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel28);

        pf_filtros.add(jPanel22);

        jPanel24.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel24.setLayout(new java.awt.GridLayout(4, 1));

        jPanel27.setLayout(new java.awt.GridLayout(1, 3));

        filtro_is_titular.setText("Titular");
        filtro_is_titular.setName("estitular"); // NOI18N
        filtro_is_titular.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel27.add(filtro_is_titular);

        filtro_is_consumidor.setText("Consumidor");
        filtro_is_consumidor.setName("esconsumidor"); // NOI18N
        filtro_is_consumidor.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel27.add(filtro_is_consumidor);

        jPanel24.add(jPanel27);

        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel16.setText("Titular");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel31.add(jLabel16, java.awt.BorderLayout.WEST);

        filtro_Titular.setName("titular"); // NOI18N
        jPanel31.add(filtro_Titular, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel31);

        pf_filtros.add(jPanel24);

        panel_filtros.add(pf_filtros, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_filtros, java.awt.BorderLayout.NORTH);

        panel_tabla.setPreferredSize(new java.awt.Dimension(1000, 500));
        panel_tabla.setLayout(new java.awt.BorderLayout());

        jPanel30.setMinimumSize(new java.awt.Dimension(980, 30));
        jPanel30.setPreferredSize(new java.awt.Dimension(980, 35));
        jPanel30.setLayout(new java.awt.BorderLayout());

        buscador_tabla.setName("buscador"); // NOI18N
        jPanel30.add(buscador_tabla, java.awt.BorderLayout.CENTER);

        jPanel23.setLayout(new java.awt.BorderLayout());

        anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        anterior.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel23.add(anterior, java.awt.BorderLayout.WEST);

        siguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        siguiente.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel23.add(siguiente, java.awt.BorderLayout.EAST);

        jPanel30.add(jPanel23, java.awt.BorderLayout.LINE_END);

        recargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        recargar.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel30.add(recargar, java.awt.BorderLayout.LINE_START);

        panel_tabla.add(jPanel30, java.awt.BorderLayout.NORTH);

        tabla_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_usuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_usuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tabla_usuarios);

        panel_tabla.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_tabla, java.awt.BorderLayout.CENTER);

        root_panel.add(search_panel, "Registar");

        register_panel.setName("Consultar"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        south_panel.setLayout(new java.awt.GridLayout(2, 0));

        jPanel13.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel13.setLayout(new java.awt.GridLayout(1, 3));

        btn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        btn_guardar.setText("Guardar");
        btn_guardar.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel13.add(btn_guardar);

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/actualizar.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel13.add(btn_actualizar);

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel13.add(btn_eliminar);

        south_panel.add(jPanel13);

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.setPreferredSize(new java.awt.Dimension(500, 40));
        south_panel.add(btn_cancelar);

        register_panel.add(south_panel, java.awt.BorderLayout.SOUTH);

        center_panel.setPreferredSize(new java.awt.Dimension(500, 600));
        center_panel.setLayout(new java.awt.GridLayout(10, 1, 10, 10));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Datos de usuario");
        center_panel.add(jLabel11);

        pc_tipo.setLayout(new java.awt.GridLayout(1, 2));

        campo_is_titular.setText("Titutlar");
        campo_is_titular.setToolTipText("Mantener el roll del usuario, seleccionado");
        campo_is_titular.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        campo_is_titular.setPreferredSize(new java.awt.Dimension(500, 30));
        pc_tipo.add(campo_is_titular);

        campo_is_usuario.setText("usuario");
        campo_is_usuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pc_tipo.add(campo_is_usuario);

        center_panel.add(pc_tipo);

        pc_nombre.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nombre: ");
        jLabel2.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_nombre.add(jLabel2, java.awt.BorderLayout.WEST);

        campo_nombre.setToolTipText("<html>\nCampo: Nombre\n<br>valores admitidos: Solo texto\n<br>tamaño maximo: 32 Caracteres");
        campo_nombre.setName("Nombre"); // NOI18N
        campo_nombre.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_nombre.add(campo_nombre, java.awt.BorderLayout.CENTER);

        jLabel7.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_nombre.add(jLabel7, java.awt.BorderLayout.LINE_END);

        center_panel.add(pc_nombre);

        pc_ap.setPreferredSize(new java.awt.Dimension(250, 30));
        pc_ap.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("A. Paterno: ");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_ap.add(jLabel3, java.awt.BorderLayout.WEST);

        campo_ap.setToolTipText("<html>\nCampos: Apellido Paterno\n<br>Valor: Solo texto \n<br>Longitud: 32 Caracteres");
        campo_ap.setName("A. Paterno"); // NOI18N
        campo_ap.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_ap.add(campo_ap, java.awt.BorderLayout.CENTER);

        jLabel9.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_ap.add(jLabel9, java.awt.BorderLayout.LINE_END);

        center_panel.add(pc_ap);

        pc_am.setPreferredSize(new java.awt.Dimension(250, 30));
        pc_am.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("A. Materno:");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_am.add(jLabel4, java.awt.BorderLayout.WEST);

        campo_am.setToolTipText("<html> Campos: Apellido Materno\n<br>Valor: Solo texto <br>Longitud: 32 Caracteres");
        campo_am.setName("A. Materno"); // NOI18N
        campo_am.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_am.add(campo_am, java.awt.BorderLayout.CENTER);

        jLabel10.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_am.add(jLabel10, java.awt.BorderLayout.LINE_END);

        center_panel.add(pc_am);

        pc_tipo_toma.setPreferredSize(new java.awt.Dimension(500, 50));
        pc_tipo_toma.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("T. Toma");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_tipo_toma.add(jLabel5, java.awt.BorderLayout.WEST);

        campo_tipo_toma.setName("Tipo de toma"); // NOI18N
        campo_tipo_toma.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_tipo_toma.add(campo_tipo_toma, java.awt.BorderLayout.CENTER);

        man_tipo_toma.setText("M.");
        man_tipo_toma.setToolTipText("Mantener el tipo de toma seleccionado");
        man_tipo_toma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        man_tipo_toma.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_tipo_toma.add(man_tipo_toma, java.awt.BorderLayout.EAST);

        center_panel.add(pc_tipo_toma);

        pc_calle.setPreferredSize(new java.awt.Dimension(500, 50));
        pc_calle.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Calle: ");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_calle.add(jLabel6, java.awt.BorderLayout.WEST);

        campo_calle.setName("Calle"); // NOI18N
        campo_calle.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_calle.add(campo_calle, java.awt.BorderLayout.CENTER);

        man_calle.setText("M.");
        man_calle.setToolTipText("Mantener la calle seleccionada\n");
        man_calle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        man_calle.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_calle.add(man_calle, java.awt.BorderLayout.EAST);

        center_panel.add(pc_calle);

        pc_ncasa.setPreferredSize(new java.awt.Dimension(500, 50));
        pc_ncasa.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("N. Casa");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_ncasa.add(jLabel1, java.awt.BorderLayout.WEST);

        campo_no_casa.setToolTipText("<html> Campo: Numero de casa  <br>Valor: Solo numeros <br>Longitud: 3 Caracteres");
        campo_no_casa.setName("Numero de Casa"); // NOI18N
        campo_no_casa.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_ncasa.add(campo_no_casa, java.awt.BorderLayout.CENTER);

        sn_numero.setText("S/N");
        sn_numero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        sn_numero.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_ncasa.add(sn_numero, java.awt.BorderLayout.EAST);

        center_panel.add(pc_ncasa);

        pc_estado.setPreferredSize(new java.awt.Dimension(500, 50));
        pc_estado.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Estado: ");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 25));
        pc_estado.add(jLabel8, java.awt.BorderLayout.WEST);

        campo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona Elemento.", "Activo.", "Inactivo.", "Baja." }));
        campo_estado.setName("Estado"); // NOI18N
        campo_estado.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_estado.add(campo_estado, java.awt.BorderLayout.CENTER);

        man_estado.setText("M.");
        man_estado.setToolTipText("Mantener el estado del usuario seleccionado\n");
        man_estado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        man_estado.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_estado.add(man_estado, java.awt.BorderLayout.EAST);

        center_panel.add(pc_estado);

        register_panel.add(center_panel, java.awt.BorderLayout.CENTER);

        left_panel.setPreferredSize(new java.awt.Dimension(30, 100));

        javax.swing.GroupLayout left_panelLayout = new javax.swing.GroupLayout(left_panel);
        left_panel.setLayout(left_panelLayout);
        left_panelLayout.setHorizontalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );
        left_panelLayout.setVerticalGroup(
            left_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        register_panel.add(left_panel, java.awt.BorderLayout.WEST);

        right_panel.setPreferredSize(new java.awt.Dimension(30, 100));

        javax.swing.GroupLayout right_panelLayout = new javax.swing.GroupLayout(right_panel);
        right_panel.setLayout(right_panelLayout);
        right_panelLayout.setHorizontalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        right_panelLayout.setVerticalGroup(
            right_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        register_panel.add(right_panel, java.awt.BorderLayout.EAST);

        root_panel.add(register_panel, "Consultar");

        add(root_panel, java.awt.BorderLayout.CENTER);

        north_panel.setPreferredSize(new java.awt.Dimension(900, 40));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        np_cp_center.setLayout(new java.awt.GridLayout());

        register_button.setText("Registar");
        np_cp_center.add(register_button);

        consult_button.setText("Consultar");
        np_cp_center.add(consult_button);

        north_panel.add(np_cp_center, java.awt.BorderLayout.CENTER);

        np_cp_west.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_west.setLayout(new java.awt.BorderLayout());

        buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        np_cp_west.add(buscar, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_west, java.awt.BorderLayout.WEST);

        np_cp_east.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_east.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        np_cp_east.add(jButton3, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_east, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anterior;
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_guardar;
    private javax.swing.JTextField buscador_tabla;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField campo_am;
    private javax.swing.JTextField campo_ap;
    private javax.swing.JComboBox<OCalles> campo_calle;
    private javax.swing.JComboBox<String> campo_estado;
    private javax.swing.JCheckBox campo_is_titular;
    private javax.swing.JCheckBox campo_is_usuario;
    private javax.swing.JTextField campo_no_casa;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JComboBox<OTipoTomas> campo_tipo_toma;
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton consult_button;
    private javax.swing.JTextField filtro_Titular;
    private javax.swing.JComboBox<OCalles> filtro_calle;
    private javax.swing.JComboBox<String> filtro_estado;
    private javax.swing.JCheckBox filtro_is_consumidor;
    private javax.swing.JCheckBox filtro_is_titular;
    private javax.swing.JButton filtro_quitar;
    private javax.swing.JComboBox<OTipoTomas> filtro_toma;
    private javax.swing.JCheckBox filtros;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel left_panel;
    private javax.swing.JCheckBox man_calle;
    private javax.swing.JCheckBox man_estado;
    private javax.swing.JCheckBox man_tipo_toma;
    private javax.swing.JPanel north_panel;
    private javax.swing.JPanel np_cp_center;
    private javax.swing.JPanel np_cp_east;
    private javax.swing.JPanel np_cp_west;
    private javax.swing.JPanel panel_filtros;
    private javax.swing.JPanel panel_tabla;
    private javax.swing.JPanel pc_am;
    private javax.swing.JPanel pc_ap;
    private javax.swing.JPanel pc_calle;
    private javax.swing.JPanel pc_estado;
    private javax.swing.JPanel pc_ncasa;
    private javax.swing.JPanel pc_nombre;
    private javax.swing.JPanel pc_tipo;
    private javax.swing.JPanel pc_tipo_toma;
    private javax.swing.JPanel pf_bar_super;
    private javax.swing.JPanel pf_filtros;
    private javax.swing.JButton recargar;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JPanel right_panel;
    private javax.swing.JPanel root_panel;
    private javax.swing.JPanel search_panel;
    private javax.swing.JButton siguiente;
    private javax.swing.JCheckBox sn_numero;
    private javax.swing.JPanel south_panel;
    private javax.swing.JTable tabla_usuarios;
    // End of variables declaration//GEN-END:variables
}
