/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.menus.administracion;

import com.jblue.modelo.ConstBD;
import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.objetos.OPersonal;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.FabricaOpraciones;
import com.jblue.util.crypto.EncriptadoAES;
import com.jblue.util.tiempo.Fecha;
import com.jblue.vista.normas.SuperVentana;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.SwingUtilities;

/**
 *
 * @author jp
 */
public class MenuAdministrador extends SuperVentana {

    private final JCheckBox[] PERMISOS;

    private final int SEC_USUARIOS,
            SEC_CALLES,
            SEC_TIPO_TOMAS,
            SEC_TOMAS_REG;

    private final JComponent componentes[];
    private Fecha fecha;

    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        _TITULO = 13;
        fecha = new Fecha();
        SEC_USUARIOS = 0;
        SEC_CALLES = 3;
        SEC_TIPO_TOMAS = 6;
        SEC_TOMAS_REG = 9;
        initComponents();
        this.PERMISOS = new JCheckBox[]{
            usuarios_ac, usuarios_es, usuarios_lc,
            calles_ac, calles_es, calles_lc,
            tipotomas_ac, tipotomas_es, tipotomas_lc,
            tomasreg_ac, tomasreg_es, tomasreg_lc
        };

        this.componentes = new JComponent[]{
            nombre, apellidos, estado, cargo, usuario, contra, periodo
        };

        panel_periodo.setVisible(periodo.isSelected());
        _blq(false);
        _botones(false);
        llamable();
    }

    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    public void estadoInicial() {
        nombre.setText(null);
        apellidos.setText(null);
        estado.setSelectedIndex(0);
        fecha_registro.setText(null);
        cargo.setSelectedIndex(0);
        usuario.setText(null);
        contra.setText(null);
        periodo.setSelected(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        apellidos = new javax.swing.JTextField();
        jPanel19 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        estado = new javax.swing.JComboBox<>();
        jPanel34 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        fecha_registro = new javax.swing.JTextField();
        jPanel15 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        cargo = new javax.swing.JComboBox<>();
        jPanel16 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel17 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jPanel18 = new javax.swing.JPanel();
        periodo = new javax.swing.JCheckBox();
        panel_periodo = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        año_inicio = new javax.swing.JSpinner();
        jPanel24 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mes_inicio = new javax.swing.JComboBox<>();
        jPanel23 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        dia_inicio = new javax.swing.JSpinner();
        jPanel25 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel26 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        año_fin = new javax.swing.JSpinner();
        jPanel28 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        mes_fin = new javax.swing.JComboBox<>();
        jPanel29 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        dia_fin = new javax.swing.JSpinner();
        jPanel8 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        usuarios_ac = new javax.swing.JCheckBox();
        usuarios_es = new javax.swing.JCheckBox();
        usuarios_lc = new javax.swing.JCheckBox();
        jPanel31 = new javax.swing.JPanel();
        calles_ac = new javax.swing.JCheckBox();
        calles_es = new javax.swing.JCheckBox();
        calles_lc = new javax.swing.JCheckBox();
        jPanel32 = new javax.swing.JPanel();
        tipotomas_ac = new javax.swing.JCheckBox();
        tipotomas_es = new javax.swing.JCheckBox();
        tipotomas_lc = new javax.swing.JCheckBox();
        jPanel33 = new javax.swing.JPanel();
        tomasreg_ac = new javax.swing.JCheckBox();
        tomasreg_es = new javax.swing.JCheckBox();
        tomasreg_lc = new javax.swing.JCheckBox();
        jPanel10 = new javax.swing.JPanel();
        nuevo = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        cancelar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel9.setPreferredSize(new java.awt.Dimension(1000, 638));
        jPanel9.setLayout(new javax.swing.BoxLayout(jPanel9, javax.swing.BoxLayout.LINE_AXIS));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de usuario"));
        jPanel6.setPreferredSize(new java.awt.Dimension(333, 600));
        jPanel6.setLayout(new javax.swing.BoxLayout(jPanel6, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel11.setPreferredSize(new java.awt.Dimension(333, 60));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Nombre");
        jLabel1.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel11.add(jLabel1, java.awt.BorderLayout.NORTH);

        nombre.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel11.add(nombre, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(333, 60));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Apellidos");
        jLabel2.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel12.add(jLabel2, java.awt.BorderLayout.NORTH);

        apellidos.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel12.add(apellidos, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel12);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel14.setText("Estado");
        jLabel14.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel19.add(jLabel14, java.awt.BorderLayout.NORTH);

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Estado", "Activo", "Inactivo" }));
        estado.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel19.add(estado, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel19);

        jPanel34.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("Fecha de registro");
        jLabel15.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel34.add(jLabel15, java.awt.BorderLayout.NORTH);

        fecha_registro.setEnabled(false);
        fecha_registro.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel34.add(fecha_registro, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel34);

        jPanel15.setPreferredSize(new java.awt.Dimension(333, 200));
        jPanel15.setLayout(new java.awt.BorderLayout());
        jPanel6.add(jPanel15);

        jPanel9.add(jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del cargo"));
        jPanel7.setPreferredSize(new java.awt.Dimension(333, 600));
        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel5.setPreferredSize(new java.awt.Dimension(333, 60));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Cargo");
        jLabel3.setMinimumSize(new java.awt.Dimension(333, 18));
        jLabel3.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel5.add(jLabel3, java.awt.BorderLayout.NORTH);

        cargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccione cargo", "pasante", "secretario", "tesorero", "presidente", "administrador" }));
        cargo.setPreferredSize(new java.awt.Dimension(333, 30));
        cargo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cargoItemStateChanged(evt);
            }
        });
        jPanel5.add(cargo, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel5);

        jPanel16.setPreferredSize(new java.awt.Dimension(333, 60));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Usuario");
        jLabel4.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel16.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        usuario.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel16.add(usuario, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel16);

        jPanel17.setPreferredSize(new java.awt.Dimension(333, 60));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Contraseña");
        jLabel5.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel17.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        contra.setPreferredSize(new java.awt.Dimension(333, 30));
        jPanel17.add(contra, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel17);

        jPanel18.setPreferredSize(new java.awt.Dimension(333, 300));
        jPanel18.setLayout(new java.awt.BorderLayout());

        periodo.setText("Limitar Periodo");
        periodo.setPreferredSize(new java.awt.Dimension(333, 30));
        periodo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                periodoItemStateChanged(evt);
            }
        });
        periodo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                periodoStateChanged(evt);
            }
        });
        jPanel18.add(periodo, java.awt.BorderLayout.CENTER);

        panel_periodo.setLayout(new java.awt.BorderLayout());

        jPanel20.setPreferredSize(new java.awt.Dimension(333, 100));
        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Fecha de inicio");
        jLabel6.setPreferredSize(new java.awt.Dimension(98, 30));
        jPanel20.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel21.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel21.setLayout(new java.awt.BorderLayout());

        jPanel22.setPreferredSize(new java.awt.Dimension(111, 60));
        jPanel22.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Año");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel22.add(jLabel9, java.awt.BorderLayout.PAGE_START);

        año_inicio.setModel(new javax.swing.SpinnerNumberModel(2023, 2023, null, 1));
        jPanel22.add(año_inicio, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel22, java.awt.BorderLayout.LINE_END);

        jPanel24.setPreferredSize(new java.awt.Dimension(111, 60));
        jPanel24.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Mes");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel24.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        mes_inicio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT", "NOV", "DIC" }));
        jPanel24.add(mes_inicio, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel24, java.awt.BorderLayout.CENTER);

        jPanel23.setPreferredSize(new java.awt.Dimension(111, 60));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Dia");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        dia_inicio.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel23.add(dia_inicio, java.awt.BorderLayout.CENTER);

        jPanel21.add(jPanel23, java.awt.BorderLayout.LINE_START);

        jPanel20.add(jPanel21, java.awt.BorderLayout.CENTER);

        panel_periodo.add(jPanel20, java.awt.BorderLayout.NORTH);

        jPanel25.setPreferredSize(new java.awt.Dimension(333, 100));
        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Fecha de fin");
        jLabel10.setPreferredSize(new java.awt.Dimension(98, 30));
        jPanel25.add(jLabel10, java.awt.BorderLayout.PAGE_START);

        jPanel26.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel27.setPreferredSize(new java.awt.Dimension(111, 60));
        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("Año");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel27.add(jLabel11, java.awt.BorderLayout.PAGE_START);

        año_fin.setModel(new javax.swing.SpinnerNumberModel(2023, 2023, null, 1));
        jPanel27.add(año_fin, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel27, java.awt.BorderLayout.LINE_END);

        jPanel28.setPreferredSize(new java.awt.Dimension(111, 60));
        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Mes");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel28.add(jLabel12, java.awt.BorderLayout.PAGE_START);

        mes_fin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT", "NOV", "DIC" }));
        jPanel28.add(mes_fin, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel28, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(111, 60));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel13.setText("Dia");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.add(jLabel13, java.awt.BorderLayout.PAGE_START);

        dia_fin.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        jPanel29.add(dia_fin, java.awt.BorderLayout.CENTER);

        jPanel26.add(jPanel29, java.awt.BorderLayout.LINE_START);

        jPanel25.add(jPanel26, java.awt.BorderLayout.CENTER);

        panel_periodo.add(jPanel25, java.awt.BorderLayout.SOUTH);

        jPanel18.add(panel_periodo, java.awt.BorderLayout.SOUTH);

        jPanel7.add(jPanel18);

        jPanel9.add(jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Permisos"));
        jPanel8.setPreferredSize(new java.awt.Dimension(333, 600));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel30.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));
        jPanel30.setPreferredSize(new java.awt.Dimension(333, 100));
        jPanel30.setLayout(new java.awt.BorderLayout());

        usuarios_ac.setText("AC");
        usuarios_ac.setToolTipText("Permiso de Acceso");
        usuarios_ac.setEnabled(false);
        usuarios_ac.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel30.add(usuarios_ac, java.awt.BorderLayout.LINE_START);

        usuarios_es.setText("ES");
        usuarios_es.setToolTipText("Permiso de Escritura");
        usuarios_es.setEnabled(false);
        usuarios_es.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel30.add(usuarios_es, java.awt.BorderLayout.CENTER);

        usuarios_lc.setText("LC");
        usuarios_lc.setToolTipText("Permiso de Lectura");
        usuarios_lc.setEnabled(false);
        usuarios_lc.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel30.add(usuarios_lc, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel30);

        jPanel31.setBorder(javax.swing.BorderFactory.createTitledBorder("Calles"));
        jPanel31.setPreferredSize(new java.awt.Dimension(333, 100));
        jPanel31.setLayout(new java.awt.BorderLayout());

        calles_ac.setText("AC");
        calles_ac.setToolTipText("Permiso de Acceso");
        calles_ac.setEnabled(false);
        calles_ac.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel31.add(calles_ac, java.awt.BorderLayout.LINE_START);

        calles_es.setText("ES");
        calles_es.setToolTipText("Permiso de Escritura");
        calles_es.setEnabled(false);
        calles_es.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel31.add(calles_es, java.awt.BorderLayout.CENTER);

        calles_lc.setText("LC");
        calles_lc.setToolTipText("Permiso de Lectura");
        calles_lc.setEnabled(false);
        calles_lc.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel31.add(calles_lc, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel31);

        jPanel32.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipo de tomas"));
        jPanel32.setPreferredSize(new java.awt.Dimension(333, 100));
        jPanel32.setLayout(new java.awt.BorderLayout());

        tipotomas_ac.setText("AC");
        tipotomas_ac.setToolTipText("Permiso de Acceso");
        tipotomas_ac.setEnabled(false);
        tipotomas_ac.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.add(tipotomas_ac, java.awt.BorderLayout.LINE_START);

        tipotomas_es.setText("ES");
        tipotomas_es.setToolTipText("Permiso de Escritura");
        tipotomas_es.setEnabled(false);
        tipotomas_es.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.add(tipotomas_es, java.awt.BorderLayout.CENTER);

        tipotomas_lc.setText("LC");
        tipotomas_lc.setToolTipText("Permiso de Lectura");
        tipotomas_lc.setEnabled(false);
        tipotomas_lc.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.add(tipotomas_lc, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel32);

        jPanel33.setBorder(javax.swing.BorderFactory.createTitledBorder("Tomas Registradas"));
        jPanel33.setPreferredSize(new java.awt.Dimension(333, 100));
        jPanel33.setLayout(new java.awt.BorderLayout());

        tomasreg_ac.setText("AC");
        tomasreg_ac.setToolTipText("Permiso de Acceso");
        tomasreg_ac.setEnabled(false);
        tomasreg_ac.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel33.add(tomasreg_ac, java.awt.BorderLayout.LINE_START);

        tomasreg_es.setText("ES");
        tomasreg_es.setToolTipText("Permiso de Escritura");
        tomasreg_es.setEnabled(false);
        tomasreg_es.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel33.add(tomasreg_es, java.awt.BorderLayout.CENTER);

        tomasreg_lc.setText("LC");
        tomasreg_lc.setToolTipText("Permiso de Lectura");
        tomasreg_lc.setEnabled(false);
        tomasreg_lc.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel33.add(tomasreg_lc, java.awt.BorderLayout.LINE_END);

        jPanel8.add(jPanel33);

        jPanel9.add(jPanel8);

        jPanel2.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel10.setPreferredSize(new java.awt.Dimension(1000, 100));

        nuevo.setText("Nuevo");
        nuevo.setPreferredSize(new java.awt.Dimension(200, 40));
        nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevoActionPerformed(evt);
            }
        });
        jPanel10.add(nuevo);

        guardar.setText("Guardar");
        guardar.setPreferredSize(new java.awt.Dimension(200, 40));
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });
        jPanel10.add(guardar);

        cancelar.setText("Cancelar");
        cancelar.setPreferredSize(new java.awt.Dimension(200, 40));
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        jPanel10.add(cancelar);

        jPanel2.add(jPanel10, java.awt.BorderLayout.SOUTH);

        jTabbedPane2.addTab("Registrar Personal", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 638, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Consultar Personal", jPanel3);

        jPanel1.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Personal", jPanel1);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1000, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 669, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Movimientos", jPanel4);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cargoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cargoItemStateChanged
        switch (cargo.getSelectedIndex()) {
            case 1 ->
                pasante();
            case 2 ->
                secretario();
            case 3 ->
                tesorero();
            case 4 ->
                presidente();
            default ->
                defecto();
        }
    }//GEN-LAST:event_cargoItemStateChanged

    private void periodoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_periodoItemStateChanged
        panel_periodo.setVisible(periodo.isSelected());
    }//GEN-LAST:event_periodoItemStateChanged

    private void nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevoActionPerformed
        _blq(true);
        _botones(true);
    }//GEN-LAST:event_nuevoActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        _blq(false);
        _botones(false);
    }//GEN-LAST:event_cancelarActionPerformed

    private void periodoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_periodoStateChanged
        if (periodo.isSelected()) {
            Dia(dia_inicio);
            mes_inicio.setSelectedIndex(fecha.getMes() - 1);
            Año(año_inicio);

            Dia(dia_fin);
            mes_fin.setSelectedIndex(fecha.getMes() - 1);
            Año(año_fin);
        }
    }//GEN-LAST:event_periodoStateChanged

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed

        Operaciones<OPersonal> personal = FabricaOpraciones.getPERSONAL();
        String[] o = _guardar();
        String[] cam = ConstBD.BD_PERSONAL;
        personal.insertar(o);
        estadoInicial();
        FabricaCache.MC_PERSONAL.actualizar();
        JOptionPane.showMessageDialog(this, "Operacion Exitosa");
    }//GEN-LAST:event_guardarActionPerformed

    EncriptadoAES encriptador = new EncriptadoAES();

    String[] _guardar() {
        try {
            String nom = nombre.getText();
            String ap = apellidos.getText();
            String car = String.valueOf(cargo.getSelectedIndex());
            String user = encriptador.encriptar(usuario.getText(), String.valueOf(contra.getPassword()));
            String pass = encriptador.encriptar(String.valueOf(contra.getPassword()), usuario.getText());
            String regis = fecha_registro.getText();
            String esta = estado.getSelectedIndex() == 1 ? "1" : "-1";
            String per;
            if (periodo.isSelected()) {
                per = getPeriodo();
            } else {
                per = "IND";
            }
            return new String[]{
                nom, ap, car, user, pass, regis, esta, "7777", per
            };
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
            Logger.getLogger(MenuAdministrador.class.getName()).log(Level.SEVERE, null, ex);
        }
        return null;
    }

    public String getPeriodo() {
        String inicio = consFecha(dia_inicio, mes_inicio, año_inicio);
        String fin = consFecha(dia_fin, mes_fin, año_fin);
        StringBuilder sb = new StringBuilder(20);
        sb.append(inicio).append(":");
        sb.append(fin);
        return sb.toString();
    }

    public String consFecha(JSpinner dia, JComboBox<String> mes, JSpinner año) {
        StringBuilder sb = new StringBuilder();
        //
        SpinnerNumberModel _dia = (SpinnerNumberModel) dia.getModel();
        String d = String.valueOf(_dia.getNumber().intValue());
        if (d.length() == 1) {
            sb.append("0");
        }
        sb.append(d).append("-");
        int m = mes.getSelectedIndex();
        m += 1;
        if (m <= 9) {
            sb.append("0");
        }
        sb.append(m).append("-");
        SpinnerNumberModel _año = (SpinnerNumberModel) año.getModel();
        int y = _año.getNumber().intValue();
        sb.append(y);
        return sb.toString();
    }

    public void Dia(JSpinner sp) {
        SpinnerNumberModel model = (SpinnerNumberModel) sp.getModel();
        model.setMaximum(fecha.getMaxDiaDelMes());
        model.setValue(fecha.getDiaDelMes());
    }

    public void Año(JSpinner sp) {
        SpinnerNumberModel model = (SpinnerNumberModel) sp.getModel();
        model.setMinimum(fecha.getAño());
        model.setMaximum(fecha.getAño() + 4);
        model.setValue(model.getMinimum());
    }

    final void _blq(boolean estado) {
        SwingUtilities.invokeLater(() -> {
            if (estado) {
                fecha_registro.setText(fecha.getNewFechaActualString());

            } else {
                fecha_registro.setText(null);
            }
            for (JComponent componente : componentes) {
                componente.setEnabled(estado);
            }
            if (periodo.isSelected()) {
                periodo.setSelected(false);
            }
            this.estado.setSelectedIndex(0);
            cargo.setSelectedIndex(0);
        });
    }

    final void _botones(boolean estado) {
        nuevo.setEnabled(!estado);
        guardar.setEnabled(estado);
        cancelar.setEnabled(estado);
    }

    public void validar() {
        JTextField[] comp = {
            nombre, apellidos, usuario, contra
        };

        for (JTextField jTextField : comp) {

        }
    }

    public void setPermisos(String permisos) {
        if (permisos.length() > 4) {
            return;
        }
        char[] arr = permisos.toCharArray();

    }

    private void defecto() {
        asignarPermisos(SEC_USUARIOS, 0);
        asignarPermisos(SEC_CALLES, 0);
        asignarPermisos(SEC_TIPO_TOMAS, 0);
        asignarPermisos(SEC_TOMAS_REG, 0);
    }

    public void pasante() {
        asignarPermisos(SEC_USUARIOS, 0);
        asignarPermisos(SEC_CALLES, 3);
        asignarPermisos(SEC_TIPO_TOMAS, 3);
        asignarPermisos(SEC_TOMAS_REG, 0);
    }

    public void secretario() {
        asignarPermisos(SEC_USUARIOS, 3);
        asignarPermisos(SEC_CALLES, 7);
        asignarPermisos(SEC_TIPO_TOMAS, 7);
        asignarPermisos(SEC_TOMAS_REG, 3);
    }

    public void tesorero() {
        asignarPermisos(SEC_USUARIOS, 7);
        asignarPermisos(SEC_CALLES, 7);
        asignarPermisos(SEC_TIPO_TOMAS, 7);
        asignarPermisos(SEC_TOMAS_REG, 3);
    }

    public void presidente() {
        asignarPermisos(SEC_USUARIOS, 7);
        asignarPermisos(SEC_CALLES, 7);
        asignarPermisos(SEC_TIPO_TOMAS, 7);
        asignarPermisos(SEC_TOMAS_REG, 7);
    }

    public void asignarPermisos(int seccion, int permisos) {
        int ac = seccion;
        int es = seccion + 1;
        int lc = seccion + 2;
        switch (permisos) {
            case 0 -> {
                PERMISOS[ac].setSelected(false);
                PERMISOS[es].setSelected(false);
                PERMISOS[lc].setSelected(false);
            }
            case 3 -> {
                PERMISOS[ac].setSelected(true);
                PERMISOS[es].setSelected(false);
                PERMISOS[lc].setSelected(true);
            }

            case 4 -> {
                PERMISOS[ac].setSelected(true);
                PERMISOS[es].setSelected(true);
                PERMISOS[lc].setSelected(false);
            }

            case 7 -> {
                PERMISOS[ac].setSelected(true);
                PERMISOS[es].setSelected(true);
                PERMISOS[lc].setSelected(true);
            }

        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apellidos;
    private javax.swing.JSpinner año_fin;
    private javax.swing.JSpinner año_inicio;
    private javax.swing.JCheckBox calles_ac;
    private javax.swing.JCheckBox calles_es;
    private javax.swing.JCheckBox calles_lc;
    private javax.swing.JButton cancelar;
    private javax.swing.JComboBox<String> cargo;
    private javax.swing.JPasswordField contra;
    private javax.swing.JSpinner dia_fin;
    private javax.swing.JSpinner dia_inicio;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JTextField fecha_registro;
    private javax.swing.JButton guardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JComboBox<String> mes_fin;
    private javax.swing.JComboBox<String> mes_inicio;
    private javax.swing.JTextField nombre;
    private javax.swing.JButton nuevo;
    private javax.swing.JPanel panel_periodo;
    private javax.swing.JCheckBox periodo;
    private javax.swing.JCheckBox tipotomas_ac;
    private javax.swing.JCheckBox tipotomas_es;
    private javax.swing.JCheckBox tipotomas_lc;
    private javax.swing.JCheckBox tomasreg_ac;
    private javax.swing.JCheckBox tomasreg_es;
    private javax.swing.JCheckBox tomasreg_lc;
    private javax.swing.JTextField usuario;
    private javax.swing.JCheckBox usuarios_ac;
    private javax.swing.JCheckBox usuarios_es;
    private javax.swing.JCheckBox usuarios_lc;
    // End of variables declaration//GEN-END:variables

}
