/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.ventanas.menus.administracion;

import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.sistema.app.Prop;
import com.jblue.util.cache.FabricaCache;
import com.jblue.vista.normas.SuperVentana;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author jp
 */
public class MenuDirectorios extends SuperVentana {

    private final File dir_usuarios;
    private final ArrayList<OUsuarios> cache;
    private final ArrayList<OUsuarios> lista_aux;
    private final DefaultListModel<String> modelo_lista;
    private int usuario_seleccionado;

    /**
     * Creates new form MenuDirectorios
     */
    public MenuDirectorios() {
        _TITULO = 10;
        dir_usuarios = Prop.FIL_DIR_PROG_USUARIOS;
        cache = FabricaCache.MC_USUARIOS.getLista();
        lista_aux = new ArrayList<>(cache.size());
        modelo_lista = new DefaultListModel<>();
        initComponents();
        usuarios_sin_dir.setModel(modelo_lista);
        crear_dir.setEnabled(false);
        llamable();
    }

    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    public void estadoInicial() {

    }

    final void cargarUsuariosSinDocumentos() {
        String[] dirs = dir_usuarios.list();
        if (dirs.length == cache.size()) {
            return;
        }
        ArrayList<String> lista = new ArrayList<>();
        lista.addAll(Arrays.asList(dirs));
        for (OUsuarios i : cache) {
            System.out.println(i.getStringR());
            int index = lista.indexOf(i.getStringR());
            System.out.println("index:" + index);
            if (index < 0) {
                modelo_lista.addElement(i.getStringR());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelDirectorios = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        panel_usuario_sin_dir = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuarios_sin_dir = new javax.swing.JList<>();
        jPanel8 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        crear_dir = new javax.swing.JButton();
        panel_usuarios_con_dir = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelDirectorios.setLayout(new java.awt.BorderLayout());

        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        panel_usuario_sin_dir.setName("Usuarios sin directorio"); // NOI18N
        panel_usuario_sin_dir.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 300));

        usuarios_sin_dir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarios_sin_dirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(usuarios_sin_dir);

        panel_usuario_sin_dir.add(jScrollPane2, java.awt.BorderLayout.LINE_START);

        jPanel8.setLayout(new java.awt.GridLayout(8, 0));

        jButton5.setText("Crear Directorio a todos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton5);

        crear_dir.setText("Crear Directorio");
        crear_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_dirActionPerformed(evt);
            }
        });
        jPanel8.add(crear_dir);

        panel_usuario_sin_dir.add(jPanel8, java.awt.BorderLayout.CENTER);

        jTabbedPane2.addTab("Usuarios sin Directorio", panel_usuario_sin_dir);

        panel_usuarios_con_dir.setName("Usuarios con directorio"); // NOI18N

        javax.swing.GroupLayout panel_usuarios_con_dirLayout = new javax.swing.GroupLayout(panel_usuarios_con_dir);
        panel_usuarios_con_dir.setLayout(panel_usuarios_con_dirLayout);
        panel_usuarios_con_dirLayout.setHorizontalGroup(
            panel_usuarios_con_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        panel_usuarios_con_dirLayout.setVerticalGroup(
            panel_usuarios_con_dirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Usuarios con directorio", panel_usuarios_con_dir);

        panelDirectorios.add(jTabbedPane2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panelDirectorios, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int x = 0;
        for (OUsuarios i : cache) {
            StringBuilder s = new StringBuilder(dir_usuarios.getAbsolutePath());
            s.append("/").append(i.getStringR());
            File j = new File(s.toString());
            if (j.mkdir()) {
                x++;
            }
        }
        JOptionPane.showMessageDialog(this, "Se crearon: " + x + " directorios");


    }//GEN-LAST:event_jButton5ActionPerformed

    private void usuarios_sin_dirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarios_sin_dirMouseClicked
        int index = usuarios_sin_dir.getSelectedIndex();
        if (index < 0 || index > modelo_lista.getSize()) {
            return;
        }
        crear_dir.setEnabled(true);
        usuario_seleccionado = index;
    }//GEN-LAST:event_usuarios_sin_dirMouseClicked

    private void crear_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_dirActionPerformed
        String rm = modelo_lista.remove(usuario_seleccionado);
        StringBuilder s = new StringBuilder(dir_usuarios.getAbsolutePath());
        s.append("/").append(rm);
        File f = new File(s.toString());
        System.out.println(f.getAbsolutePath());
        if (f.mkdir()) {
            JOptionPane.showMessageDialog(this, "El directorio se creo correctamente");
        }
    }//GEN-LAST:event_crear_dirActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged

        if (panel_usuario_sin_dir.isVisible()) {
            cargarUsuariosSinDocumentos();
        } else if (modelo_lista.isEmpty()) {
            modelo_lista.clear();
        }
    }//GEN-LAST:event_jTabbedPane2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear_dir;
    private javax.swing.JButton jButton5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JPanel panelDirectorios;
    private javax.swing.JPanel panel_usuario_sin_dir;
    private javax.swing.JPanel panel_usuarios_con_dir;
    private javax.swing.JList<String> usuarios_sin_dir;
    // End of variables declaration//GEN-END:variables
}
