/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.menus.administracion;

import com.jblue.vista.normas.SuperVentana;
import com.jblue.vista.ventanas.vistas.compartidos.VHistorialMovimietos;
import com.jblue.vista.ventanas.vistas.compartidos.VPersonal;
import javax.swing.JPanel;

/**
 *
 * @author jp
 */
public class MenuAdministrador extends SuperVentana {

    private final int NO_VISTAS = 2;
    private final JPanel[] vistas;
    
    /**
     * Creates new form MenuAdministrador
     */
    public MenuAdministrador() {
        vistas = new JPanel[NO_VISTAS];
        vistas[0] = new VPersonal();
        vistas[1] = new VHistorialMovimietos();
        initComponents();
        llamable();
    }

    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    public void estadoInicial() {
    }

    @Override
    protected void addComponentes() {
        for (JPanel vista : vistas) {
            tab_root.add(vista.getName(), vista);
        }
    }

    @Override
    protected void addEventos() {
        tab_root.addChangeListener(e -> {
            for (JPanel vista : vistas) {
                System.out.println(vista.getName() + "=" + vista.isVisible());
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tab_root = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().add(tab_root, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane tab_root;
    // End of variables declaration//GEN-END:variables

}
