/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.mod;

import java.awt.CardLayout;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jsoftware.com.jblue.model.dto.WaterIntakeTypeDTO;
import jsoftware.com.jblue.model.factories.TableModelFactory;
import jsoftware.com.jblue.model.models.AbstractValidation;
import jsoftware.com.jblue.util.Func;
import jsoftware.com.jblue.views.framework.AbstractProcessView;
import jsoftware.com.jblue.views.framework.DBObjectValues;
import jsoftware.com.jblue.views.framework.ProcessViewBuilder;
import jsoftware.com.jblue.views.framework.TableSearchViewModel;
import jsoftware.com.jutil.swingw.modelos.JTableModel;

/**
 *
 * @author juanp
 */
public final class WaterIntakeTypeView extends AbstractProcessView<WaterIntakeTypeDTO> implements DBObjectValues<WaterIntakeTypeDTO>, TableSearchViewModel<WaterIntakeTypeDTO> {

    private static final long serialVersionUID = 1L;

    private final CardLayout ly;
    private final JTableModel model;
    private WaterIntakeTypeDTO object_search;

    /**
     * Creates new form WaterIntakeTypeView
     */
    public WaterIntakeTypeView(ProcessViewBuilder builder) {
        super(builder);
        model = TableModelFactory.getWaterIntakeTypesTableModel();
        ly = (CardLayout) root_panel.getLayout();
        initComponents();
        build();
    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void components() {
    }

    @Override
    public void events() {
        apply_rules_field.addChangeListener((e) -> {
            JCheckBox o = (JCheckBox) e.getSource();
            round_field.setEnabled(o.isSelected());
            round_up_field.setEnabled(o.isSelected());
        });
        charge_unit_field.addChangeListener((e) -> {
            JCheckBox o = (JCheckBox) e.getSource();
            units_field.setEnabled(o.isSelected());
            unit_id_field.setEnabled(o.isSelected());
        });
    }

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tools_panel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel15 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        panel_campos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        type_name_field = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        base_price_field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        annual_increase_field = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        apply_rules_field = new javax.swing.JCheckBox();
        jPanel19 = new javax.swing.JPanel();
        charge_unit_field = new javax.swing.JCheckBox();
        jPanel17 = new javax.swing.JPanel();
        round_field = new javax.swing.JCheckBox();
        jPanel18 = new javax.swing.JPanel();
        round_up_field = new javax.swing.JCheckBox();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        units_field = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        unit_id_field = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        current_price_field = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        previous_price_field = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        surcharge_field = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        options_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        reload_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        panel_izq = new javax.swing.JPanel();
        tabla_usuarios = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        tools_panel.setName("tools_panel"); // NOI18N
        tools_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        tools_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jToggleButton2.setName("jToggleButton2"); // NOI18N
        jToggleButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/desbloquear.png"))); // NOI18N
        tools_panel.add(jToggleButton2, java.awt.BorderLayout.WEST);

        jPanel15.setName("jPanel15"); // NOI18N
        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/mod/Bundle"); // NOI18N
        register_button.setText(bundle.getString("WaterIntakeTypeView.register_button.text")); // NOI18N
        register_button.setActionCommand(bundle.getString("WaterIntakeTypeView.register_button.actionCommand")); // NOI18N
        register_button.setName("register_button"); // NOI18N
        jPanel15.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText(bundle.getString("WaterIntakeTypeView.search_button.text")); // NOI18N
        search_button.setActionCommand(bundle.getString("WaterIntakeTypeView.search_button.actionCommand")); // NOI18N
        search_button.setName("search_button"); // NOI18N
        jPanel15.add(search_button);

        tools_panel.add(jPanel15, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        tools_panel.add(jButton2, java.awt.BorderLayout.EAST);

        add(tools_panel, java.awt.BorderLayout.NORTH);

        root_panel.setName("root_panel"); // NOI18N
        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        panel_campos.setName("panel_campos"); // NOI18N
        panel_campos.setPreferredSize(new java.awt.Dimension(500, 620));
        panel_campos.setLayout(new java.awt.GridLayout(12, 0, 0, 10));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText(bundle.getString("WaterIntakeTypeView.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 100));
        panel_campos.add(jLabel4);

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel6.setText(bundle.getString("WaterIntakeTypeView.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel10.add(jLabel6, java.awt.BorderLayout.LINE_START);

        type_name_field.setText(bundle.getString("WaterIntakeTypeView.type_name_field.text")); // NOI18N
        type_name_field.setName("type_name_field"); // NOI18N
        jPanel10.add(type_name_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel10);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel2.setText(bundle.getString("WaterIntakeTypeView.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel1.add(jLabel2, java.awt.BorderLayout.LINE_START);

        base_price_field.setText(bundle.getString("WaterIntakeTypeView.base_price_field.text")); // NOI18N
        base_price_field.setName("base_price_field"); // NOI18N
        jPanel1.add(base_price_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel1);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel3.setText(bundle.getString("WaterIntakeTypeView.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel2.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jTextField2.setText(bundle.getString("WaterIntakeTypeView.jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        jPanel2.add(jTextField2, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel2);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel5.setText(bundle.getString("WaterIntakeTypeView.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel5, java.awt.BorderLayout.LINE_START);

        annual_increase_field.setText(bundle.getString("WaterIntakeTypeView.annual_increase_field.text")); // NOI18N
        annual_increase_field.setName("annual_increase_field"); // NOI18N
        jPanel4.add(annual_increase_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel4);

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.GridLayout(1, 3));

        jPanel16.setName("jPanel16"); // NOI18N
        jPanel16.setLayout(new java.awt.BorderLayout());

        apply_rules_field.setText(bundle.getString("WaterIntakeTypeView.apply_rules_field.text")); // NOI18N
        apply_rules_field.setName("apply_rules_field"); // NOI18N
        jPanel16.add(apply_rules_field, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel16);

        jPanel19.setName("jPanel19"); // NOI18N
        jPanel19.setLayout(new java.awt.BorderLayout());

        charge_unit_field.setText(bundle.getString("WaterIntakeTypeView.charge_unit_field.text")); // NOI18N
        charge_unit_field.setName("charge_unit_field"); // NOI18N
        jPanel19.add(charge_unit_field, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel19);

        jPanel17.setName("jPanel17"); // NOI18N
        jPanel17.setLayout(new java.awt.BorderLayout());

        round_field.setSelected(true);
        round_field.setText(bundle.getString("WaterIntakeTypeView.round_field.text")); // NOI18N
        round_field.setName("round_field"); // NOI18N
        jPanel17.add(round_field, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel17);

        jPanel18.setName("jPanel18"); // NOI18N
        jPanel18.setLayout(new java.awt.BorderLayout());

        round_up_field.setSelected(true);
        round_up_field.setText(bundle.getString("WaterIntakeTypeView.round_up_field.text")); // NOI18N
        round_up_field.setName("round_up_field"); // NOI18N
        jPanel18.add(round_up_field, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel18);

        panel_campos.add(jPanel7);

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setText(bundle.getString("WaterIntakeTypeView.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.add(jLabel7, java.awt.BorderLayout.LINE_START);

        units_field.setText(bundle.getString("WaterIntakeTypeView.units_field.text")); // NOI18N
        units_field.setEnabled(false);
        units_field.setName("units_field"); // NOI18N
        jPanel8.add(units_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel8);

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setText(bundle.getString("WaterIntakeTypeView.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel9.add(jLabel8, java.awt.BorderLayout.LINE_START);

        unit_id_field.setEnabled(false);
        unit_id_field.setName("unit_id_field"); // NOI18N
        jPanel9.add(unit_id_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel9);

        jPanel12.setName("jPanel12"); // NOI18N
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel10.setText(bundle.getString("WaterIntakeTypeView.jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel12.add(jLabel10, java.awt.BorderLayout.LINE_START);

        current_price_field.setEditable(false);
        current_price_field.setText(bundle.getString("WaterIntakeTypeView.current_price_field.text")); // NOI18N
        current_price_field.setName("current_price_field"); // NOI18N
        jPanel12.add(current_price_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel12);

        jPanel13.setName("jPanel13"); // NOI18N
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel11.setText(bundle.getString("WaterIntakeTypeView.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel13.add(jLabel11, java.awt.BorderLayout.LINE_START);

        previous_price_field.setEditable(false);
        previous_price_field.setText(bundle.getString("WaterIntakeTypeView.previous_price_field.text")); // NOI18N
        previous_price_field.setName("previous_price_field"); // NOI18N
        jPanel13.add(previous_price_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel13);

        jPanel14.setName("jPanel14"); // NOI18N
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel12.setText(bundle.getString("WaterIntakeTypeView.jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel14.add(jLabel12, java.awt.BorderLayout.LINE_START);

        surcharge_field.setEditable(false);
        surcharge_field.setText(bundle.getString("WaterIntakeTypeView.surcharge_field.text")); // NOI18N
        surcharge_field.setName("surcharge_field"); // NOI18N
        jPanel14.add(surcharge_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel14);

        jButton1.setText(bundle.getString("WaterIntakeTypeView.jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        panel_campos.add(jButton1);

        register_panel.add(panel_campos, java.awt.BorderLayout.CENTER);

        options_panel.setName("options_panel"); // NOI18N
        options_panel.setPreferredSize(new java.awt.Dimension(500, 80));
        options_panel.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        save_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText(bundle.getString("WaterIntakeTypeView.save_button.text")); // NOI18N
        save_button.setActionCommand(bundle.getString("WaterIntakeTypeView.save_button.actionCommand")); // NOI18N
        save_button.setName("save_button"); // NOI18N
        jPanel3.add(save_button);

        update_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/sincronizar.png"))); // NOI18N
        update_button.setText(bundle.getString("WaterIntakeTypeView.update_button.text")); // NOI18N
        update_button.setActionCommand(bundle.getString("WaterIntakeTypeView.update_button.actionCommand")); // NOI18N
        update_button.setName("update_button"); // NOI18N
        jPanel3.add(update_button);

        delete_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText(bundle.getString("WaterIntakeTypeView.delete_button.text")); // NOI18N
        delete_button.setActionCommand(bundle.getString("WaterIntakeTypeView.delete_button.actionCommand")); // NOI18N
        delete_button.setName("delete_button"); // NOI18N
        jPanel3.add(delete_button);

        options_panel.add(jPanel3);

        cancel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText(bundle.getString("WaterIntakeTypeView.cancel_button.text")); // NOI18N
        cancel_button.setActionCommand(bundle.getString("WaterIntakeTypeView.cancel_button.actionCommand")); // NOI18N
        cancel_button.setName("cancel_button"); // NOI18N
        options_panel.add(cancel_button);

        register_panel.add(options_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "register");

        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.setLayout(new java.awt.BorderLayout(5, 5));

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand(bundle.getString("WaterIntakeTypeView.reload_button.actionCommand")); // NOI18N
        reload_button.setName("reload_button"); // NOI18N
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(reload_button, java.awt.BorderLayout.WEST);

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.add(jLabel1, java.awt.BorderLayout.WEST);

        search_field.setName("search_field"); // NOI18N
        jPanel6.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        back_button.setActionCommand(bundle.getString("WaterIntakeTypeView.back_button.actionCommand")); // NOI18N
        back_button.setName("back_button"); // NOI18N
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(back_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand(bundle.getString("WaterIntakeTypeView.next_button.actionCommand")); // NOI18N
        next_button.setName("next_button"); // NOI18N
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(next_button);

        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        search_panel.add(jPanel5, java.awt.BorderLayout.NORTH);

        panel_izq.setName("panel_izq"); // NOI18N
        panel_izq.setPreferredSize(new java.awt.Dimension(500, 700));
        panel_izq.setLayout(new java.awt.BorderLayout(10, 10));

        tabla_usuarios.setName("tabla_usuarios"); // NOI18N

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setName("objects_table"); // NOI18N
        objects_table.setShowGrid(true);
        tabla_usuarios.setViewportView(objects_table);

        panel_izq.add(tabla_usuarios, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_izq, java.awt.BorderLayout.CENTER);

        status_bar_panel.setName("status_bar_panel"); // NOI18N
        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setName("jPanel32"); // NOI18N
        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText(bundle.getString("WaterIntakeTypeView.jLabel18.text")); // NOI18N
        jLabel18.setName("jLabel18"); // NOI18N
        jPanel32.add(jLabel18, java.awt.BorderLayout.CENTER);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText(bundle.getString("WaterIntakeTypeView.count.text")); // NOI18N
        count.setToolTipText(bundle.getString("WaterIntakeTypeView.count.toolTipText")); // NOI18N
        count.setName("count"); // NOI18N
        count.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range.setText(bundle.getString("WaterIntakeTypeView.range.text")); // NOI18N
        range.setToolTipText(bundle.getString("WaterIntakeTypeView.range.toolTipText")); // NOI18N
        range.setName("range"); // NOI18N
        status_bar_panel.add(range, java.awt.BorderLayout.CENTER);

        jPanel29.setName("jPanel29"); // NOI18N
        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText(bundle.getString("WaterIntakeTypeView.jLabel17.text")); // NOI18N
        jLabel17.setName("jLabel17"); // NOI18N
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText(bundle.getString("WaterIntakeTypeView.total.text")); // NOI18N
        total.setToolTipText(bundle.getString("WaterIntakeTypeView.total.toolTipText")); // NOI18N
        total.setName("total"); // NOI18N
        total.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void getDataView() {
    }

    @Override
    public boolean isValuesOK() {
        AbstractValidation validator = new AbstractValidation();
        validator.addRuler("current_price_field", current_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("previous_price_field", previous_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("surcharge_field", surcharge_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("charge_unit_field", charge_unit_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price_field", unit_id_field, t -> Func.isNotNull(t.getSelectedItem()));
        validator.addRuler("current_price_field", units_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price_field", current_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price_field", current_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price_field", current_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price", current_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price", current_price_field, t -> Func.isNotNull(t.getText()));
        validator.addRuler("current_price", current_price_field, t -> Func.isNotNull(t.getText()));
        boolean res = validator.isValid();
        if (!res) {
            JOptionPane.showMessageDialog(this, validator.getErrorMessage(), "Operacion Incorrecta", JOptionPane.ERROR_MESSAGE);
        }
        return res;
    }

    @Override
    public WaterIntakeTypeDTO getValues(boolean update) {
        object_search = new WaterIntakeTypeDTO();
        object_search.put("type_name", type_name_field.getText());
        object_search.put("current_price", current_price_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        object_search.put("type_name", type_name_field.getText());
        return object_search;
    }

    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    @Override
    public String getTextSearchTable() {
        return search_field.getText().trim().replace(" ", "");
    }

    @Override
    public JTable getTable() {
        return objects_table;
    }

    @Override
    public DefaultTableModel getModel() {
        return model;
    }

    @Override
    public void setViewShow(int view_show) {
        this.view_show = view_show;
        String op = switch (view_show) {
            case 2:
                yield search_panel.getName();
            default:
                yield register_panel.getName();
        };
        ly.show(root_panel, op);
    }

    @Override
    public int getViewShow() {
        return view_show;
    }

    @Override
    public void setObjectSearch(WaterIntakeTypeDTO o) {
        this.object_search = o;
    }

    @Override
    public WaterIntakeTypeDTO getObjectSearch() {
        return object_search;
    }

    @Override
    public void setRowsData(String... info) {
        count.setText(info[0]);
        range.setText(info[1]);
        total.setText(info[2]);
    }

    @Override
    public void setScreenTableInfo() {
        save_button.setEnabled(false);
        update_button.setEnabled(true);
        delete_button.setEnabled(true);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField annual_increase_field;
    private javax.swing.JCheckBox apply_rules_field;
    private javax.swing.JButton back_button;
    private javax.swing.JTextField base_price_field;
    private javax.swing.JButton cancel_button;
    private javax.swing.JCheckBox charge_unit_field;
    private javax.swing.JLabel count;
    private javax.swing.JTextField current_price_field;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton next_button;
    private javax.swing.JTable objects_table;
    private javax.swing.JPanel options_panel;
    private javax.swing.JPanel panel_campos;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JTextField previous_price_field;
    private javax.swing.JLabel range;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton reload_button;
    private javax.swing.JPanel root_panel;
    private javax.swing.JCheckBox round_field;
    private javax.swing.JCheckBox round_up_field;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_panel;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JTextField surcharge_field;
    private javax.swing.JScrollPane tabla_usuarios;
    private javax.swing.JPanel tools_panel;
    private javax.swing.JLabel total;
    private javax.swing.JTextField type_name_field;
    private javax.swing.JComboBox<String> unit_id_field;
    private javax.swing.JTextField units_field;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

}
