/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.vabst;

import java.io.IOException;
import javax.swing.JOptionPane;
import jsoftware.com.jblue.controllers.compc.WizardController;
import jsoftware.com.jblue.model.dto.wrp.ModuleWrapperDTO;
import jsoftware.com.jblue.sys.app.AppFiles;
import jsoftware.com.jblue.views.framework.AbstractModuleView;
import jsoftware.com.jblue.views.framework.WizardModel;
import jsoftware.com.jblue.views.mod.pro.EmployeeRegisterProcess;
import jsoftware.com.jutil.util.FuncLogs;

/**
 *
 * @author JUAN PABLO CAMPOS CASASANERO
 */
public abstract class AbstractWizardView<T extends ModuleWrapperDTO> extends AbstractModuleView<T> implements WizardModel<T> {

    private static final long serialVersionUID = 1L;

    public AbstractWizardView(T dto_wrapper) {
        super(dto_wrapper);
        //COMPONENTES INICIALES
        initComponents();
        this.setName(dto_wrapper.getModule_name());
        //CONTROLADOR DEL ASISTENTE
        WizardController wctronller = (WizardController) getDtoWrapper().getController("MAIN");
        wctronller.setView(this);

        //MOVIMIENTOS DE SIGUIENTE Y ATRAS
        next_panel_button.addActionListener(wctronller);
        last_panel_button.addActionListener(wctronller);
    }

    @Override
    public void initialState() {
        next_panel_button.setEnabled(true);
        last_panel_button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        np_cp_center = new javax.swing.JPanel();
        last_panel_button = new javax.swing.JButton();
        next_panel_button = new javax.swing.JButton();
        np_cp_west = new javax.swing.JPanel();
        search_object = new javax.swing.JButton();
        np_cp_east = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        north_panel.setName("north_panel"); // NOI18N
        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        np_cp_center.setName("np_cp_center"); // NOI18N
        np_cp_center.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        last_panel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/vabst/Bundle"); // NOI18N
        last_panel_button.setText(bundle.getString("AbstractWizardView.last_panel_button.text")); // NOI18N
        last_panel_button.setActionCommand(bundle.getString("AbstractWizardView.last_panel_button.actionCommand")); // NOI18N
        last_panel_button.setName("last_panel_button"); // NOI18N
        np_cp_center.add(last_panel_button);

        next_panel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        next_panel_button.setText(bundle.getString("AbstractWizardView.next_panel_button.text")); // NOI18N
        next_panel_button.setActionCommand(bundle.getString("AbstractWizardView.next_panel_button.actionCommand")); // NOI18N
        next_panel_button.setName("next_panel_button"); // NOI18N
        np_cp_center.add(next_panel_button);

        north_panel.add(np_cp_center, java.awt.BorderLayout.CENTER);

        np_cp_west.setName("np_cp_west"); // NOI18N
        np_cp_west.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_west.setLayout(new java.awt.BorderLayout());

        search_object.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_object.setActionCommand(bundle.getString("AbstractWizardView.search_object.actionCommand")); // NOI18N
        search_object.setName("search_object"); // NOI18N
        np_cp_west.add(search_object, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_west, java.awt.BorderLayout.WEST);

        np_cp_east.setName("np_cp_east"); // NOI18N
        np_cp_east.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_east.setLayout(new java.awt.BorderLayout());

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        np_cp_east.add(jButton6, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_east, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);

        root_panel.setName("root_panel"); // NOI18N
        root_panel.setLayout(new java.awt.CardLayout());
        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public boolean nextStep() {
        return true;
    }

    @Override
    public boolean previousStep() {
        return true;
    }

    @Override
    public void updateUi(int componentId) {
        try {
            if (views == null || views.isEmpty()) {
                return;
            }
            switch (componentId) {
                case NEXT_VIEW_BUTTON -> {
                    if (current_index == views.size() - 1) {
                        return;
                    }
                    card_layout.next(root_panel);
                }
                case PREVIOUS_VIEW_BUTTON -> {
                    if (current_index <= 0) {
                        return;
                    }
                    card_layout.previous(root_panel);
                }
                case NAVIGATION_STEP_BAR -> {
                    last_panel_button.setEnabled(current_index > 0);
                    if (current_index == views.size() - 1) {
                        next_panel_button.setText("Finalizar Registro");
                        next_panel_button.setActionCommand(EXECUTE_FINAL);
                    } else {
                        next_panel_button.setText("Siguiente");
                        next_panel_button.setActionCommand(NEXT_STEP);
                    }
                }
                default ->
                    throw new AssertionError("COMANDO NO DISPONIBLE: " + componentId);
            }
        } catch (Exception e) {
            log(e, "updateUi");
            JOptionPane.showMessageDialog(this, "ERROR AL CARGA LA VISTA");
        }
    }

    @Override
    public void getData() {
        try {
            if (current_index >= 0 && current_index < views.size()) {
                views.get(current_index).getData();
            }
        } catch (Exception e) {
            log(e, "getDataView");
            JOptionPane.showMessageDialog(this, "Error al capturar datos: " + e.getMessage());
        }
    }

    @Override
    public int getCurrentViewIndex() {
        return current_index;
    }

    @Override
    public void setCurrentViewIndex(int index) {
        try {
            current_index = index;
            if (index < 0 || index >= views.size()) {
                return;
            }
            card_layout.show(this, views.get(index).getName());
        } catch (Exception e) {
            log(e, "setCurrentViewIndex");
            JOptionPane.showMessageDialog(this, "INDICES CORRUPTOS");
        }
    }

    @Override
    public void nextIndex() {
        current_index++;
    }

    @Override
    public void previousIndex() {
        current_index--;
    }

    private void log(Exception e, String method_name) {
        try {
            FuncLogs.logError(
                    AppFiles.DIR_PROG_LOG_TODAY,
                    getClass(),
                    e,
                    getDtoWrapper().getModule_name(),
                    method_name,
                    e.getMessage()
            );
        } catch (IOException ex) {
            System.getLogger(EmployeeRegisterProcess.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jButton6;
    protected javax.swing.JButton last_panel_button;
    protected javax.swing.JButton next_panel_button;
    protected javax.swing.JPanel north_panel;
    private javax.swing.JPanel np_cp_center;
    private javax.swing.JPanel np_cp_east;
    private javax.swing.JPanel np_cp_west;
    protected javax.swing.JPanel root_panel;
    protected javax.swing.JButton search_object;
    // End of variables declaration//GEN-END:variables

}
