/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package jsoftware.com.jblue.model.constants.des;

/**
 *
 * @author juanp
 */
public class ArrayGsConst extends ArrayDBConst {

    protected static String[] CAT_GROUP_PREFIX_GS = {"ID", "PREFIX_TYPE", "DESCRIPTION", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] CAT_HISTORY_TYPE_MOV_GS = {"ID", "DESCRIPTION", "STATUS", "DATE_REGISTER"};
    protected static String[] CAT_PAYMENT_METHOD_GS = {"ID", "DESCRIPTION", "CODE", "STATUS", "DATE_REGISTER", "DATE_END"};
    protected static String[] CAT_PAYMENT_TYPE_GS = {"ID", "DESCRIPTION", "DESCRIPTION_LONG", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] CAT_PROCESS_TYPE_GS = {"ID", "TYPE_NAME", "DESCRIPTION", "STATUS", "DATE_REGISTER", "DATE_UPDATE", "DATE_END"};
    protected static String[] CAT_STATUS_GS = {"ID", "DESCRIPTION", "AFFECTED_GROUP", "DATE_UPDATE", "DATE_REGISTER", "DATE_FINALIZE"};
    protected static String[] CAT_STREET_GS = {"ID", "STREET_NAME", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] CAT_TABLES_DB_GS = {"ID", "GROUP_PREFIX", "TABLE_NAME", "DESCRIPTION", "USER_WHO_CREATES", "USER_WHO_CREATES_NAME", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] CAT_USER_CATEGORY_DOCUMENTS_GS = {"ID", "TYPE_DOCUMENT", "DESCRIPTION", "DATE_REGISTER"};
    protected static String[] CAT_USER_MOVEMENTS_GS = {"ID", "TYPE_MOV", "GROUP", "STATUS", "DATE_UPDATE", "DATE_REGISTER"};
    protected static String[] CAT_USER_TYPE_DOCUMENT_GS = {"ID", "USER_DOCUMENT", "DESCRIPTION", "TYPE_DOCUMENT", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] DEV_PARAMETERS_GS = {"ID", "PARAMETER", "DESCRIPTION", "VALUE", "UNIT", "DATA_TYPE", "STATUS", "DB_USER_CREATE", "DB_USER_UPDATE", "DATE_UPDATE", "DATE_REGISTER"};
    protected static String[] EMP_EMPLOYEE_GS = {"ID", "CURP", "FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "GENDER", "EMAIL", "DATE_BIRDAY", "PHONE_NUMBER1", "PHONE_NUMBER2", "EMPLOYEE_TYPE", "STATUS", "USER", "PASSWORD", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] EMP_EMPLOYEE_TYPE_GS = {"ID", "EMPLOYEE_TYPE", "STATUS", "DATE_REGISTER"};
    protected static String[] HYS_ADMINISTRATION_HISTORY_GS = {"ID", "YEAR_OF_ADMINISTRATION", "ROOT", "ADMINISTRATOR", "PRESIDENT", "TREASURER", "SECRETARY", "PLUMBER", "INTERN_1", "INTERN_2", "INTERNT_3", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] HYS_HISTORY_GS = {"ID", "AFFECTED_ENVIRONMENT_ID", "AFFECTED_ENVIRONMENT_DESC", "AFFECTED_TABLE", "AFFECTED_TABLE_DESCRIPTION", "ID_MOV", "DATE_REGISTER"};
    protected static String[] HYS_PROGRAM_HISTORY_GS = {"ID", "EMPLOYEE", "DB_USER", "AFFECTED_TABLE", "TYPE_MOV", "DESCRIPTION", "DATE_REGISTER"};
    protected static String[] LOGBOOK_TO_EMPLOYEE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
    protected static String[] LOGBOOK_TO_PARAMETES_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
    protected static String[] LOGBOOK_TO_PAYMENT_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
    protected static String[] LOGBOOK_TO_USER_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
    protected static String[] LOGBOOK_TO_WATER_INTAKE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
    protected static String[] LOGBOOK_TO_WATER_INTAKES_TYPE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
    protected static String[] PRO_PROCESS_GS = {"ID", "PROCESS_TYPE", "EMPLOYEE_START", "DATE_START", "EMPLOYEE_VALID", "DATE_VALID", "EMPLOYEE_PAYMENT", "DATE_PAYMENT", "EMPLOYEE_ENDS", "DATE_END", "EMPLOYE_PRINT", "DATE_PRINT", "ADMINISTRATION", "LAST_EMPLOYEE_UPDATE", "CURRENT_DB_USER", "ORIGINAL_USER", "WATER_INTAKE", "STATUS", "DATE_REGISTER"};
    protected static String[] PYM_PAYMENTS_GS = {"ID", "PAYMENT_TYPE", "UUDI", "EMPLOYEE", "USER", "WATER_INTAKE", "WATER_INTAKE_TYPE", "PAYMENT_METHOD", "TOTAL_COST", "AMOUNT_PAID", "CHANGE_AMOUNT", "MONTH_PAID", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] USR_BLOCKED_USER_GS = {"ID", "USER", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] USR_USER_GS = {"ID", "CURP", "FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "GENDER", "EMAIL", "PHONE_NUMBER1", "PHONE_NUMBER2", "STREET1", "STREET2", "INSIDE_NUMBER", "OUTSIDE_NUMBER", "WATER_INTAKE_TYPE", "USER_TYPE", "STATUS", "LAST_EMPLOYEE_UPDATE", "DATE_LAST_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] USR_USER_DOCUMENT_GS = {"ID", "USER", "DOCUMENT_NAME", "DOCUMENT_PATH", "DOC_FILE", "STATUS", "DATE_REGISTER", "DATE_END"};
    protected static String[] USR_USER_TYPE_GS = {"ID", "USER_TYPE", "STATUS", "DATE_REGISTER", "DATE_FINALIZE"};
    protected static String[] USR_USERS_CONSUMERS_GS = {"ID", "WATER_INTAKE", "HOLDER", "CONSUMER", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] WKI_WATER_INTAKE_TYPE_GS = {"ID", "TYPE_NAME", "CURRENT_PRICE", "PREVIOUS_PRICE", "SURCHARGE", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
    protected static String[] WKI_WATER_INTAKES_GS = {"ID", "COST_PROCEDURE", "WATER_INTAKE_TYPE", "USER", "USER_NAME", "STREET1", "STREET2", "LOCATION", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};

}
