/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package jsoftware.com.jblue.model.constants.des;

import jsoftware.com.jutil.db.JDBTable;

/**
 *
 * @author juanp
 */
public class ConstTable extends TableNameConst {

    public static final JDBTable CAT_HISTORY_TYPE_MOV_TABLE = new JDBTable(CAT_HISTORY_TYPE_MOV_NAME, CAT_HISTORY_TYPE_MOV_FIELDS, CAT_HISTORY_TYPE_MOV_GS);
    public static final JDBTable CAT_PAYMENT_METHOD_TABLE = new JDBTable(CAT_PAYMENT_METHOD_NAME, CAT_PAYMENT_METHOD_FIELDS, CAT_PAYMENT_METHOD_GS);
    public static final JDBTable CAT_PAYMENT_TYPE_TABLE = new JDBTable(CAT_PAYMENT_TYPE_NAME, CAT_PAYMENT_TYPE_FIELDS, CAT_PAYMENT_TYPE_GS);
    public static final JDBTable CAT_PROCESS_TYPE_TABLE = new JDBTable(CAT_PROCESS_TYPE_NAME, CAT_PROCESS_TYPE_FIELDS, CAT_PROCESS_TYPE_GS);
    public static final JDBTable CAT_STATUS_TABLE = new JDBTable(CAT_STATUS_NAME, CAT_STATUS_FIELDS, CAT_STATUS_GS);
    public static final JDBTable CAT_STREET_TABLE = new JDBTable(CAT_STREET_NAME, CAT_STREET_FIELDS, CAT_STREET_GS);
    public static final JDBTable CAT_TABLES_DB_TABLE = new JDBTable(CAT_TABLES_DB_NAME, CAT_TABLES_DB_FIELDS, CAT_TABLES_DB_GS);
    public static final JDBTable CAT_USER_CATEGORY_DOCUMENTS_TABLE = new JDBTable(CAT_USER_CATEGORY_DOCUMENTS_NAME, CAT_USER_CATEGORY_DOCUMENTS_FIELDS, CAT_USER_CATEGORY_DOCUMENTS_GS);
    public static final JDBTable CAT_USER_MOVEMENTS_TABLE = new JDBTable(CAT_USER_MOVEMENTS_NAME, CAT_USER_MOVEMENTS_FIELDS, CAT_USER_MOVEMENTS_GS);
    public static final JDBTable CAT_USER_TYPE_DOCUMENT_TABLE = new JDBTable(CAT_USER_TYPE_DOCUMENT_NAME, CAT_USER_TYPE_DOCUMENT_FIELDS, CAT_USER_TYPE_DOCUMENT_GS);
    public static final JDBTable DEV_PARAMETERS_TABLE = new JDBTable(DEV_PARAMETERS_NAME, DEV_PARAMETERS_FIELDS, DEV_PARAMETERS_GS);
    public static final JDBTable EMP_EMPLOYEE_TABLE = new JDBTable(EMP_EMPLOYEE_NAME, EMP_EMPLOYEE_FIELDS, EMP_EMPLOYEE_GS);
    public static final JDBTable EMP_EMPLOYEE_TYPE_TABLE = new JDBTable(EMP_EMPLOYEE_TYPE_NAME, EMP_EMPLOYEE_TYPE_FIELDS, EMP_EMPLOYEE_TYPE_GS);
    public static final JDBTable HYS_ADMINISTRATION_HISTORY_TABLE = new JDBTable(HYS_ADMINISTRATION_HISTORY_NAME, HYS_ADMINISTRATION_HISTORY_FIELDS, HYS_ADMINISTRATION_HISTORY_GS);
    public static final JDBTable HYS_HISTORY_TABLE = new JDBTable(HYS_HISTORY_NAME, HYS_HISTORY_FIELDS, HYS_HISTORY_GS);
    public static final JDBTable HYS_PROGRAM_HISTORY_TABLE = new JDBTable(HYS_PROGRAM_HISTORY_NAME, HYS_PROGRAM_HISTORY_FIELDS, HYS_PROGRAM_HISTORY_GS);
    public static final JDBTable LOGBOOK_TO_EMPLOYEE_TABLE = new JDBTable(LOGBOOK_TO_EMPLOYEE_NAME, LOGBOOK_TO_EMPLOYEE_FIELDS, LOGBOOK_TO_EMPLOYEE_GS);
    public static final JDBTable LOGBOOK_TO_PARAMETES_TABLE = new JDBTable(LOGBOOK_TO_PARAMETES_NAME, LOGBOOK_TO_PARAMETES_FIELDS, LOGBOOK_TO_PARAMETES_GS);
    public static final JDBTable LOGBOOK_TO_PAYMENT_TABLE = new JDBTable(LOGBOOK_TO_PAYMENT_NAME, LOGBOOK_TO_PAYMENT_FIELDS, LOGBOOK_TO_PAYMENT_GS);
    public static final JDBTable LOGBOOK_TO_USER_TABLE = new JDBTable(LOGBOOK_TO_USER_NAME, LOGBOOK_TO_USER_FIELDS, LOGBOOK_TO_USER_GS);
    public static final JDBTable LOGBOOK_TO_WATER_INTAKE_TABLE = new JDBTable(LOGBOOK_TO_WATER_INTAKE_NAME, LOGBOOK_TO_WATER_INTAKE_FIELDS, LOGBOOK_TO_WATER_INTAKE_GS);
    public static final JDBTable LOGBOOK_TO_WATER_INTAKES_TYPE_TABLE = new JDBTable(LOGBOOK_TO_WATER_INTAKES_TYPE_NAME, LOGBOOK_TO_WATER_INTAKES_TYPE_FIELDS, LOGBOOK_TO_WATER_INTAKES_TYPE_GS);
    public static final JDBTable PRO_PROCESS_TABLE = new JDBTable(PRO_PROCESS_NAME, PRO_PROCESS_FIELDS, PRO_PROCESS_GS);
    public static final JDBTable PYM_PAYMENTS_TABLE = new JDBTable(PYM_PAYMENTS_NAME, PYM_PAYMENTS_FIELDS, PYM_PAYMENTS_GS);
    public static final JDBTable USR_BLOCKED_USER_TABLE = new JDBTable(USR_BLOCKED_USER_NAME, USR_BLOCKED_USER_FIELDS, USR_BLOCKED_USER_GS);
    public static final JDBTable USR_USER_TABLE = new JDBTable(USR_USER_NAME, USR_USER_FIELDS, USR_USER_GS);
    public static final JDBTable USR_USER_DOCUMENT_TABLE = new JDBTable(USR_USER_DOCUMENT_NAME, USR_USER_DOCUMENT_FIELDS, USR_USER_DOCUMENT_GS);
    public static final JDBTable USR_USER_TYPE_TABLE = new JDBTable(USR_USER_TYPE_NAME, USR_USER_TYPE_FIELDS, USR_USER_TYPE_GS);
    public static final JDBTable USR_USERS_CONSUMERS_TABLE = new JDBTable(USR_USERS_CONSUMERS_NAME, USR_USERS_CONSUMERS_FIELDS, USR_USERS_CONSUMERS_GS);
    public static final JDBTable WKI_WATER_INTAKE_TYPE_TABLE = new JDBTable(WKI_WATER_INTAKE_TYPE_NAME, WKI_WATER_INTAKE_TYPE_FIELDS, WKI_WATER_INTAKE_TYPE_GS);
    public static final JDBTable WKI_WATER_INTAKES_TABLE = new JDBTable(WKI_WATER_INTAKES_NAME, WKI_WATER_INTAKES_FIELDS, WKI_WATER_INTAKES_GS);

}
