/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package jsoftware.com.jblue.model.constants.des;

import jsoftware.com.jutil.db.JDBTable;

/**
 * Central de Metadatos del Esquema de Base de Datos JBlue.
 * <p>
 * Esta clase actúa como un <b>Diccionario de Datos Dinámico</b>, consolidando
 * objetos {@link JDBTable} que representan la estructura completa de la base de
 * datos MySQL. Implementa un diseño basado en interfaces de constantes para
 * agrupar nombres de tablas, campos (fields) y mapeos de acceso (GS).</p>
 * *
 * * <p>
 * <b>Arquitectura de la Clase:</b></p>
 * <ul>
 * <li><b>Consistencia:</b> Garantiza que los nombres de las columnas y tablas
 * sean uniformes en todo el proyecto.</li>
 * <li><b>Abstracción:</b> Facilita la construcción de consultas dinámicas en
 * los DAOs sin escribir SQL puro ("Hard-coded").</li>
 * <li><b>Modularidad:</b> Agrupa las tablas por prefijos funcionales:
 * <ul>
 * <li>{@code CAT_}: Catálogos del sistema (Calles, Estados, Métodos de
 * Pago).</li>
 * <li>{@code USR_}: Gestión de Usuarios y Documentación.</li>
 * <li>{@code PYM_}: Procesamiento de Pagos y Conceptos.</li>
 * <li>{@code HYS_} / {@code LOGBOOK_}: Historiales y Auditoría.</li>
 * </ul>
 * </li>
 * </ul>
 *
 * @author JUAN PABLO CAMPOS CASASANERO
 * @see jsoftware.com.jutil.db.JDBTable
 */
public class TableConst implements TableFieldConst, TableFieldGsConst, TableIndexConst, TableNameConst {

    public static final JDBTable BITACORA_DE_TABLAS_TABLE = new JDBTable(BITACORA_DE_TABLAS_NAME, BITACORA_DE_TABLAS_FIELDS, BITACORA_DE_TABLAS_GS);
    public static final JDBTable CAT_COLONY_TABLE = new JDBTable(CAT_COLONY_NAME, CAT_COLONY_FIELDS, CAT_COLONY_GS);
    public static final JDBTable CAT_ESTATUS_TABLE = new JDBTable(CAT_ESTATUS_NAME, CAT_ESTATUS_FIELDS, CAT_ESTATUS_GS);
    public static final JDBTable CAT_GROUP_PREFIX_TABLE = new JDBTable(CAT_GROUP_PREFIX_NAME, CAT_GROUP_PREFIX_FIELDS, CAT_GROUP_PREFIX_GS);
    public static final JDBTable CAT_HISTORY_TYPE_MOV_TABLE = new JDBTable(CAT_HISTORY_TYPE_MOV_NAME, CAT_HISTORY_TYPE_MOV_FIELDS, CAT_HISTORY_TYPE_MOV_GS);
    public static final JDBTable CAT_MODULE_TABLE = new JDBTable(CAT_MODULE_NAME, CAT_MODULE_FIELDS, CAT_MODULE_GS);
    public static final JDBTable CAT_MUNICIPALITY_TABLE = new JDBTable(CAT_MUNICIPALITY_NAME, CAT_MUNICIPALITY_FIELDS, CAT_MUNICIPALITY_GS);
    public static final JDBTable CAT_OFFICE_TABLE = new JDBTable(CAT_OFFICE_NAME, CAT_OFFICE_FIELDS, CAT_OFFICE_GS);
    public static final JDBTable CAT_PAYMENT_METHOD_TABLE = new JDBTable(CAT_PAYMENT_METHOD_NAME, CAT_PAYMENT_METHOD_FIELDS, CAT_PAYMENT_METHOD_GS);
    public static final JDBTable CAT_PAYMENT_TYPE_TABLE = new JDBTable(CAT_PAYMENT_TYPE_NAME, CAT_PAYMENT_TYPE_FIELDS, CAT_PAYMENT_TYPE_GS);
    public static final JDBTable CAT_PROCESS_TYPE_TABLE = new JDBTable(CAT_PROCESS_TYPE_NAME, CAT_PROCESS_TYPE_FIELDS, CAT_PROCESS_TYPE_GS);
    public static final JDBTable CAT_STATES_TABLE = new JDBTable(CAT_STATES_NAME, CAT_STATES_FIELDS, CAT_STATES_GS);
    public static final JDBTable CAT_STATUS_TABLE = new JDBTable(CAT_STATUS_NAME, CAT_STATUS_FIELDS, CAT_STATUS_GS);
    public static final JDBTable CAT_STREET_TABLE = new JDBTable(CAT_STREET_NAME, CAT_STREET_FIELDS, CAT_STREET_GS);
    public static final JDBTable CAT_TABLES_DB_TABLE = new JDBTable(CAT_TABLES_DB_NAME, CAT_TABLES_DB_FIELDS, CAT_TABLES_DB_GS);
    public static final JDBTable CAT_UNIT_MEASURE_TABLE = new JDBTable(CAT_UNIT_MEASURE_NAME, CAT_UNIT_MEASURE_FIELDS, CAT_UNIT_MEASURE_GS);
    public static final JDBTable CAT_USER_CATEGORY_DOCUMENTS_TABLE = new JDBTable(CAT_USER_CATEGORY_DOCUMENTS_NAME, CAT_USER_CATEGORY_DOCUMENTS_FIELDS, CAT_USER_CATEGORY_DOCUMENTS_GS);
    public static final JDBTable CAT_USER_MOVEMENTS_TABLE = new JDBTable(CAT_USER_MOVEMENTS_NAME, CAT_USER_MOVEMENTS_FIELDS, CAT_USER_MOVEMENTS_GS);
    public static final JDBTable CAT_USER_TYPE_DOCUMENT_TABLE = new JDBTable(CAT_USER_TYPE_DOCUMENT_NAME, CAT_USER_TYPE_DOCUMENT_FIELDS, CAT_USER_TYPE_DOCUMENT_GS);
    public static final JDBTable DEV_PARAMETERS_TABLE = new JDBTable(DEV_PARAMETERS_NAME, DEV_PARAMETERS_FIELDS, DEV_PARAMETERS_GS);
    public static final JDBTable EMP_EMPLOYEE_TABLE = new JDBTable(EMP_EMPLOYEE_NAME, EMP_EMPLOYEE_FIELDS, EMP_EMPLOYEE_GS);
    public static final JDBTable EMP_EMPLOYEE_PERMISSIONS_TABLE = new JDBTable(EMP_EMPLOYEE_PERMISSIONS_NAME, EMP_EMPLOYEE_PERMISSIONS_FIELDS, EMP_EMPLOYEE_PERMISSIONS_GS);
    public static final JDBTable EMP_EMPLOYEE_PROFILE_TABLE = new JDBTable(EMP_EMPLOYEE_PROFILE_NAME, EMP_EMPLOYEE_PROFILE_FIELDS, EMP_EMPLOYEE_PROFILE_GS);
    public static final JDBTable EMP_EMPLOYEE_TYPE_TABLE = new JDBTable(EMP_EMPLOYEE_TYPE_NAME, EMP_EMPLOYEE_TYPE_FIELDS, EMP_EMPLOYEE_TYPE_GS);
    public static final JDBTable EMP_USER_TABLE = new JDBTable(EMP_USER_NAME, EMP_USER_FIELDS, EMP_USER_GS);
    public static final JDBTable ENTIDADES_REGISTRADAS_TABLE = new JDBTable(ENTIDADES_REGISTRADAS_NAME, ENTIDADES_REGISTRADAS_FIELDS, ENTIDADES_REGISTRADAS_GS);
    public static final JDBTable HISTORIAL_DE_MOVIMIENTOS_TABLE = new JDBTable(HISTORIAL_DE_MOVIMIENTOS_NAME, HISTORIAL_DE_MOVIMIENTOS_FIELDS, HISTORIAL_DE_MOVIMIENTOS_GS);
    public static final JDBTable HYS_ADMINISTRATION_HISTORY_TABLE = new JDBTable(HYS_ADMINISTRATION_HISTORY_NAME, HYS_ADMINISTRATION_HISTORY_FIELDS, HYS_ADMINISTRATION_HISTORY_GS);
    public static final JDBTable HYS_HISTORY_TABLE = new JDBTable(HYS_HISTORY_NAME, HYS_HISTORY_FIELDS, HYS_HISTORY_GS);
    public static final JDBTable HYS_PROGRAM_HISTORY_TABLE = new JDBTable(HYS_PROGRAM_HISTORY_NAME, HYS_PROGRAM_HISTORY_FIELDS, HYS_PROGRAM_HISTORY_GS);
    public static final JDBTable HYS_SESSION_TABLE = new JDBTable(HYS_SESSION_NAME, HYS_SESSION_FIELDS, HYS_SESSION_GS);
    public static final JDBTable LOGBOOK_TO_EMPLOYEE_TABLE = new JDBTable(LOGBOOK_TO_EMPLOYEE_NAME, LOGBOOK_TO_EMPLOYEE_FIELDS, LOGBOOK_TO_EMPLOYEE_GS);
    public static final JDBTable LOGBOOK_TO_GROUP_PREFIX_TABLE = new JDBTable(LOGBOOK_TO_GROUP_PREFIX_NAME, LOGBOOK_TO_GROUP_PREFIX_FIELDS, LOGBOOK_TO_GROUP_PREFIX_GS);
    public static final JDBTable LOGBOOK_TO_PARAMETERS_TABLE = new JDBTable(LOGBOOK_TO_PARAMETERS_NAME, LOGBOOK_TO_PARAMETERS_FIELDS, LOGBOOK_TO_PARAMETERS_GS);
    public static final JDBTable LOGBOOK_TO_PAYMENT_TABLE = new JDBTable(LOGBOOK_TO_PAYMENT_NAME, LOGBOOK_TO_PAYMENT_FIELDS, LOGBOOK_TO_PAYMENT_GS);
    public static final JDBTable LOGBOOK_TO_PAYMENT_CONCEPT_TABLE = new JDBTable(LOGBOOK_TO_PAYMENT_CONCEPT_NAME, LOGBOOK_TO_PAYMENT_CONCEPT_FIELDS, LOGBOOK_TO_PAYMENT_CONCEPT_GS);
    public static final JDBTable LOGBOOK_TO_PAYMENT_TYPE_TABLE = new JDBTable(LOGBOOK_TO_PAYMENT_TYPE_NAME, LOGBOOK_TO_PAYMENT_TYPE_FIELDS, LOGBOOK_TO_PAYMENT_TYPE_GS);
    public static final JDBTable LOGBOOK_TO_PROCESS_TYPE_TABLE = new JDBTable(LOGBOOK_TO_PROCESS_TYPE_NAME, LOGBOOK_TO_PROCESS_TYPE_FIELDS, LOGBOOK_TO_PROCESS_TYPE_GS);
    public static final JDBTable LOGBOOK_TO_TABLE_DB_TABLE = new JDBTable(LOGBOOK_TO_TABLE_DB_NAME, LOGBOOK_TO_TABLE_DB_FIELDS, LOGBOOK_TO_TABLE_DB_GS);
    public static final JDBTable LOGBOOK_TO_USER_TABLE = new JDBTable(LOGBOOK_TO_USER_NAME, LOGBOOK_TO_USER_FIELDS, LOGBOOK_TO_USER_GS);
    public static final JDBTable LOGBOOK_TO_WATER_INTAKE_TABLE = new JDBTable(LOGBOOK_TO_WATER_INTAKE_NAME, LOGBOOK_TO_WATER_INTAKE_FIELDS, LOGBOOK_TO_WATER_INTAKE_GS);
    public static final JDBTable LOGBOOK_TO_WATER_INTAKES_TYPE_TABLE = new JDBTable(LOGBOOK_TO_WATER_INTAKES_TYPE_NAME, LOGBOOK_TO_WATER_INTAKES_TYPE_FIELDS, LOGBOOK_TO_WATER_INTAKES_TYPE_GS);
    public static final JDBTable PRO_PROCESS_TABLE = new JDBTable(PRO_PROCESS_NAME, PRO_PROCESS_FIELDS, PRO_PROCESS_GS);
    public static final JDBTable PYM_PAYMENT_TABLE = new JDBTable(PYM_PAYMENT_NAME, PYM_PAYMENT_FIELDS, PYM_PAYMENT_GS);
    public static final JDBTable PYM_PAYMENT_CONCEPT_TABLE = new JDBTable(PYM_PAYMENT_CONCEPT_NAME, PYM_PAYMENT_CONCEPT_FIELDS, PYM_PAYMENT_CONCEPT_GS);
    public static final JDBTable PYM_PAYMENT_LIST_TABLE = new JDBTable(PYM_PAYMENT_LIST_NAME, PYM_PAYMENT_LIST_FIELDS, PYM_PAYMENT_LIST_GS);
    public static final JDBTable SYS_INSTANCE_AUTH_TABLE = new JDBTable(SYS_INSTANCE_AUTH_NAME, SYS_INSTANCE_AUTH_FIELDS, SYS_INSTANCE_AUTH_GS);
    public static final JDBTable USR_BLOCKED_USER_TABLE = new JDBTable(USR_BLOCKED_USER_NAME, USR_BLOCKED_USER_FIELDS, USR_BLOCKED_USER_GS);
    public static final JDBTable USR_USER_TABLE = new JDBTable(USR_USER_NAME, USR_USER_FIELDS, USR_USER_GS);
    public static final JDBTable USR_USER_DOCUMENT_TABLE = new JDBTable(USR_USER_DOCUMENT_NAME, USR_USER_DOCUMENT_FIELDS, USR_USER_DOCUMENT_GS);
    public static final JDBTable USR_USER_TYPE_TABLE = new JDBTable(USR_USER_TYPE_NAME, USR_USER_TYPE_FIELDS, USR_USER_TYPE_GS);
    public static final JDBTable USR_USERS_CONSUMERS_TABLE = new JDBTable(USR_USERS_CONSUMERS_NAME, USR_USERS_CONSUMERS_FIELDS, USR_USERS_CONSUMERS_GS);
    public static final JDBTable WKI_USER_TABLE = new JDBTable(WKI_USER_NAME, WKI_USER_FIELDS, WKI_USER_GS);
    public static final JDBTable WKI_WATER_INTAKE_TYPE_TABLE = new JDBTable(WKI_WATER_INTAKE_TYPE_NAME, WKI_WATER_INTAKE_TYPE_FIELDS, WKI_WATER_INTAKE_TYPE_GS);
    public static final JDBTable WKI_WATER_INTAKES_TABLE = new JDBTable(WKI_WATER_INTAKES_NAME, WKI_WATER_INTAKES_FIELDS, WKI_WATER_INTAKES_GS);
}
