/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package jsoftware.com.jblue.model.constants.des;

/**
 *
 * @author juanp
 */
public interface TableFieldGsConst {

     static final String[] BITACORA_DE_TABLAS_GS = {"LOG_ID", "FECHA_MOVIMIENTO", "TIPO_OPERACION", "REGISTRO_ID", "EJECUTADO_POR", "RESUMEN", "PREFIJO", "NOMBRE_TABLA", "DESCRIPCION_TABLA", "ESTADO_REGISTRO", "CREADOR_ORIGINAL", "FECHA_CREACION_SISTEMA", "JSON_ANTERIOR", "JSON_NUEVO"};
     static final String[] CAT_COLONY_GS = {"ID", "DESCRIPTION", "MUNICIPALITIES_ID", "ZIP_CODE", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_ESTATUS_GS = {"ID", "DESCRIPCION", "GRUPO AFECTADO", "FECHA DE ACTUALIZACION", "FECHA DE REGISTRO", "FECHA DE FINALIZACION"};
     static final String[] CAT_GROUP_PREFIX_GS = {"ID", "PREFIX_TYPE", "DESCRIPTION", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_HISTORY_TYPE_MOV_GS = {"ID", "DESCRIPTION", "STATUS", "DATE_REGISTER"};
     static final String[] CAT_MODULE_GS = {"ID", "MODULE_NAME", "DESCRIPTION", "DESCRIPTION_END", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_MUNICIPALITY_GS = {"ID", "DESCRIPTION", "STATE_ID", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_OFFICE_GS = {"ID", "DESCRIPTION", "ID_COLONY", "STREED_ID", "EXTERNAL_NUMBER", "INTERNAL_NUMBER", "EMAIL", "PHONE_NUMBER", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_PAYMENT_METHOD_GS = {"ID", "DESCRIPTION", "CODE", "STATUS", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_PAYMENT_TYPE_GS = {"ID", "TYPE_PAYMENT", "DESCRIPTION", "DESCRIPTION_LONG", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_PROCESS_TYPE_GS = {"ID", "TYPE_NAME", "DESCRIPTION", "STATUS", "DATE_REGISTER", "DATE_UPDATE", "DATE_END"};
     static final String[] CAT_STATES_GS = {"ID", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_STATUS_GS = {"ID", "DESCRIPTION", "AFFECTED_GROUP", "AFFECTED_TABLE", "DATE_UPDATE", "DATE_REGISTER", "DATE_FINALIZE"};
     static final String[] CAT_STREET_GS = {"ID", "STREET_NAME", "COLONY_ID", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_TABLES_DB_GS = {"ID", "GROUP_PREFIX", "TABLE_NAME", "DESCRIPTION", "UPDATE_DESCRIPTION", "END_DESCRIPTION", "USER_WHO_CREATES", "USER_WHO_CREATES_NAME", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] CAT_UNIT_MEASURE_GS = {"ID", "UNIT_NAME", "UNIT_SYMBOL", "FISCAL_CODE", "MAGNITUDE_TYPE", "BASE_FACTOR", "IS_BASE", "STATUS", "DATE_REGISTER"};
     static final String[] CAT_USER_CATEGORY_DOCUMENTS_GS = {"ID", "DESCRIPTION", "DESCRIPTION_LONG", "DATE_REGISTER"};
     static final String[] CAT_USER_MOVEMENTS_GS = {"ID", "TYPE_MOV", "GROUP", "STATUS", "DATE_UPDATE", "DATE_REGISTER"};
     static final String[] CAT_USER_TYPE_DOCUMENT_GS = {"ID", "DESCRIPTION", "DESCRIPTION_LONG", "CATEGORY", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] DEV_PARAMETERS_GS = {"ID", "PARAMETER", "DESCRIPTION", "VALUE", "UNIT", "DATA_TYPE", "STATUS", "DB_USER_CREATE", "DB_USER_UPDATE", "LAST_UPDATE EMPLOYEE", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] EMP_EMPLOYEE_GS = {"ID", "CURP", "FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "GENDER", "BIRTHDATE", "PERSONAL_EMAIL", "PERSONAL_PHONE", "STREET1", "STREET2", "INSIDE_NUMBER", "OUTSIDE_NUMBER", "EMPLOYEE_TYPE", "STATUS", "USER", "PASSWORD", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] EMP_EMPLOYEE_PERMISSIONS_GS = {"ID", "EMPLOYEE_ID", "PROCESS_TYPE_ID", "PROFILE_ID", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] EMP_EMPLOYEE_PROFILE_GS = {"ID", "DESCRIPTION", "DESCRIPTION_LONG", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] EMP_EMPLOYEE_TYPE_GS = {"ID", "EMPLOYEE_TYPE", "STATUS", "DATE_REGISTER"};
     static final String[] EMP_USER_GS = {"ID", "EMPLOYEE_ID", "OFFICE_ID", "USER", "PASSWORD", "DESCRIPTION", "EMAIL", "PHONE_NUMBER", "EMPLOYEE_TYPE", "STATUS", "LAST_EMPLOYEE_UPDATE", "LAST_UPDATE_PASSWORD", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] ENTIDADES_REGISTRADAS_GS = {"ID_ESTADO", "ESTATDO", "ID_MUNICIPIO", "MUNICIPIO", "ID_COLONIA", "COLONIA", "CODIGO POSTAL", "ESTATUS", "GRUPO AFECTADO", "FECHA_ACTUALIZACION", "FECHA_REGISTRO", "FECHA_FIN"};
     static final String[] HISTORIAL_DE_MOVIMIENTOS_GS = {"ID", "EMPLEADO", "USUARIO DB", "TABLA AFECTADA", "TIPO DE MOVIMIENTO", "DESCRIPCION", "FECHA DE REGISTRO"};
     static final String[] HYS_ADMINISTRATION_HISTORY_GS = {"ID", "YEAR_OF_ADMINISTRATION", "ROOT", "ADMINISTRATOR", "PRESIDENT", "TREASURER", "SECRETARY", "PLUMBER", "INTERN_1", "INTERN_2", "INTERNT_3", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] HYS_HISTORY_GS = {"ID", "DB_USER", "AFFECTED_ENVIRONMENT_ID", "AFFECTED_ENVIRONMENT_DESC", "TRIGGER_TABLE", "AFFECTED_TABLE", "TYPE_MOV", "ENTY_ID", "DATE_REGISTER"};
     static final String[] HYS_PROGRAM_HISTORY_GS = {"ID", "EMPLOYEE", "DB_USER", "AFFECTED_TABLE", "TYPE_MOV", "DESCRIPTION", "DATE_REGISTER"};
     static final String[] HYS_SESSION_GS = {"ID", "EMPLOYEE_ID", "HISTORY_ID", "DATE_IN", "DATE_OUT", "STATUS", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_EMPLOYEE_GS = {"ID", "ENTY_ID", "EMPLOYEE_UPDATE", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_GROUP_PREFIX_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_PARAMETERS_GS = {"ID", "ENTY_ID", "EMPLOYEE_UPDATE", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_PAYMENT_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_PAYMENT_CONCEPT_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_PAYMENT_TYPE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_PROCESS_TYPE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_TABLE_DB_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_USER_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_WATER_INTAKE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] LOGBOOK_TO_WATER_INTAKES_TYPE_GS = {"ID", "ENTY_ID", "TYPE_MOV", "OLD_VALUES", "NEW_VALUES", "DESCRIPTION", "DB_USER", "DATE_REGISTER"};
     static final String[] PRO_PROCESS_GS = {"ID", "PROCESS_TYPE", "EMPLOYEE_START", "DATE_START", "EMPLOYEE_VALID", "DATE_VALID", "EMPLOYEE_WKI_REGISTER", "DATE_WKI_REGISTER", "EMPLOYEE_PAYMENT", "DATE_PAYMENT", "EMPLOYEE_FINALIZE", "DATE_FINALIZE", "EMPLOYE_PRINT", "DATE_PRINT", "ADMINISTRATION_START", "ADMINISTRATION_END", "LAST_EMPLOYEE_UPDATE", "CURRENT_DB_USER", "USER_ID", "WATER_INTAKE", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] PYM_PAYMENT_GS = {"ID", "PAYMENT_TYPE", "UUDI", "EMPLOYEE", "USER", "WATER_INTAKE", "WATER_INTAKE_TYPE", "PAYMENT_METHOD", "PAYMENT_CONCEPT", "TOTAL_COST", "AMOUNT_PAID", "CHANGE_AMOUNT", "MONTH_PAID", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] PYM_PAYMENT_CONCEPT_GS = {"ID", "DESCRIPTION", "DESCRIPTION_LONG", "CURRENT_PRICE", "PREVIOUS_PRICE", "MANDATORY_PAYMENT", "UNIT", "MODULE", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] PYM_PAYMENT_LIST_GS = {"ID", "PAYMENT_ID", "PAYMENT_CONCEPT_ID", "DESCRIPTION", "QUANTITY", "UNIT_ID", "UNIT_PRICE", "TOTAL_PRICE", "STATUS", "DATE_REGISTER"};
     static final String[] SYS_INSTANCE_AUTH_GS = {"ID", "UUID", "OFFICE_SYS_NAME", "COLONY_ID", "MUNICIPALITY_ID", "STATE_ID", "OFFICE_ID", "MASTER_USER", "PASSWORD_USER", "OWNER_NAME", "DB_USER", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] USR_BLOCKED_USER_GS = {"ID", "USER", "DESCRIPTION", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] USR_USER_GS = {"ID", "CURP", "FIRST_NAME", "LAST_NAME1", "LAST_NAME2", "GENDER", "EMAIL", "BIRTHDATE", "PHONE_NUMBER1", "PHONE_NUMBER2", "STREET1", "STREET2", "INSIDE_NUMBER", "OUTSIDE_NUMBER", "USER_TYPE", "LAST_EMPLOYEE_UPDATE", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] USR_USER_DOCUMENT_GS = {"ID", "USER", "DOCUMENT_NAME", "DOCUMENT_PATH", "DOC_FILE", "DOCUMENT_TYPE_ID", "STATUS", "DATE_REGISTER", "DATE_END"};
     static final String[] USR_USER_TYPE_GS = {"ID", "USER_TYPE", "DESCRIPTION_LONG", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_FINALIZE"};
     static final String[] USR_USERS_CONSUMERS_GS = {"ID", "WATER_INTAKE", "HOLDER", "CONSUMER", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] WKI_USER_GS = {"ID", "USER_ID", "WATER_INTAKE_ID", "WATER_INTAKE_TYPE_ID", "OWNER_NAME", "DESCRIPTION", "EMPLOYEE_REGISTER", "LAST_EMPLOYEE_UPDATE", "ORIGINAL_PROCESS", "LAST_PROCESS_TYPE", "STATUS", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] WKI_WATER_INTAKE_TYPE_GS = {"ID", "TYPE_NAME", "CURRENT_PRICE", "PREVIOUS_PRICE", "SURCHARGE", "STATUS", "LAST_EMPLOYEE_UPDATE", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
     static final String[] WKI_WATER_INTAKES_GS = {"ID", "SERIAL_NUMBER", "WATER_INTAKE_TYPE", "STREET1", "STREET2", "DESCRIPTION", "STATUS", "LAST_EMPLOYEE_UPDATE", "DATE_UPDATE", "DATE_REGISTER", "DATE_END"};
}
