/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package jsoftware.com.jblue.model.constants.des;

/**
 *
 * @author juanp
 */
public interface TableFieldGsConst {

    static final String[] BITACORA_DE_TABLAS_GS = {"CREADOR_ORIGINAL", "DESCRIPCION_TABLA", "EJECUTADO_POR", "ESTADO_REGISTRO", "FECHA_CREACION_SISTEMA", "FECHA_MOVIMIENTO", "JSON_ANTERIOR", "JSON_NUEVO", "LOG_ID", "NOMBRE_TABLA", "PREFIJO", "REGISTRO_ID", "RESUMEN", "TIPO_OPERACION"};
    static final String[] CAT_GROUP_PREFIX_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID", "PREFIX_TYPE"};
    static final String[] CAT_HISTORY_TYPE_MOV_GS = {"DATE_REGISTER", "DESCRIPTION", "ID", "STATUS"};
    static final String[] CAT_MODULE_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "DESCRIPTION_END", "ID", "MODULE_NAME", "STATUS"};
    static final String[] CAT_PAYMENT_METHOD_GS = {"CODE", "DATE_END", "DATE_REGISTER", "DESCRIPTION", "ID", "STATUS"};
    static final String[] CAT_PAYMENT_TYPE_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "DESCRIPTION_LONG", "ID", "STATUS", "TYPE_PAYMENT"};
    static final String[] CAT_PROCESS_TYPE_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID", "STATUS", "TYPE_NAME"};
    static final String[] CAT_STATUS_GS = {"AFFECTED_GROUP", "AFFECTED_TABLE", "DATE_FINALIZE", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID"};
    static final String[] CAT_STREET_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "ID", "STATUS", "STREET_NAME"};
    static final String[] CAT_TABLES_DB_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "END_DESCRIPTION", "GROUP_PREFIX", "ID", "STATUS", "TABLE_NAME", "UPDATE_DESCRIPTION", "USER_WHO_CREATES", "USER_WHO_CREATES_NAME"};
    static final String[] CAT_USER_CATEGORY_DOCUMENTS_GS = {"DATE_REGISTER", "DESCRIPTION", "ID", "TYPE_DOCUMENT"};
    static final String[] CAT_USER_MOVEMENTS_GS = {"DATE_REGISTER", "DATE_UPDATE", "GROUP", "ID", "STATUS", "TYPE_MOV"};
    static final String[] CAT_USER_TYPE_DOCUMENT_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID", "TYPE_DOCUMENT", "USER_DOCUMENT"};
    static final String[] DEV_PARAMETERS_GS = {"DATA_TYPE", "DATE_REGISTER", "DATE_UPDATE", "DB_USER_CREATE", "DB_USER_UPDATE", "DESCRIPTION", "ID", "PARAMETER", "STATUS", "UNIT", "VALUE"};
    static final String[] EMP_EMPLOYEE_GS = {"BIRTHDATE", "CURP", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "EMAIL", "EMPLOYEE_TYPE", "FIRST_NAME", "GENDER", "ID", "LAST_NAME1", "LAST_NAME2", "PASSWORD", "PHONE_NUMBER1", "PHONE_NUMBER2", "STATUS", "USER"};
    static final String[] EMP_EMPLOYEE_PERMISSIONS_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "EMPLOYEE_ID", "ID", "PROCESS_TYPE_ID", "PROFILE_ID", "STATUS"};
    static final String[] EMP_EMPLOYEE_PROFILE_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "DESCRIPTION_LONG", "ID", "STATUS"};
    static final String[] EMP_EMPLOYEE_TYPE_GS = {"DATE_REGISTER", "EMPLOYEE_TYPE", "ID", "STATUS"};
    static final String[] EMP_USER_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "EMPLOYEE_ID", "ID", "STATUS", "USER_ID"};
    static final String[] HISTORIAL_DE_MOVIMIENTOS_GS = {"DESCRIPCION", "EMPLEADO", "FECHA DE REGISTRO", "ID", "TABLA AFECTADA", "TIPO DE MOVIMIENTO", "USUARIO DB"};
    static final String[] HYS_ADMINISTRATION_HISTORY_GS = {"ADMINISTRATOR", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID", "INTERN_1", "INTERN_2", "INTERNT_3", "PLUMBER", "PRESIDENT", "ROOT", "SECRETARY", "STATUS", "TREASURER", "YEAR_OF_ADMINISTRATION"};
    static final String[] HYS_HISTORY_GS = {"AFFECTED_ENVIRONMENT_DESC", "AFFECTED_ENVIRONMENT_ID", "AFFECTED_TABLE", "DATE_REGISTER", "DB_USER", "ENTY_ID", "ID", "TRIGGER_TABLE", "TYPE_MOV"};
    static final String[] HYS_PROGRAM_HISTORY_GS = {"AFFECTED_TABLE", "DATE_REGISTER", "DB_USER", "DESCRIPTION", "EMPLOYEE", "ID", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_EMPLOYEE_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "EMPLOYEE_UPDATE", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_GROUP_PREFIX_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_PARAMETERS_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "EMPLOYEE_UPDATE", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_PAYMENT_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_PAYMENT_TYPE_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_PROCESS_TYPE_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_TABLE_DB_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_USER_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_WATER_INTAKE_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOGBOOK_TO_WATER_INTAKES_TYPE_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] LOOGBOOK_TO_PAYMENT_CONCEPT_GS = {"DATE_REGISTER", "DB_USER", "DESCRIPTION", "ENTY_ID", "ID", "NEW_VALUES", "OLD_VALUES", "TYPE_MOV"};
    static final String[] NEW_VIEW_GS = {"DESCRIPCION", "FECHA DE ACTUALIZACION", "FECHA DE FINALIZACION", "FECHA DE REGISTRO", "GRUPO AFECTADO", "ID"};
    static final String[] PRO_PROCESS_GS = {"ADMINISTRATION", "CURRENT_DB_USER", "DATE_END", "DATE_FINALIZE", "DATE_PAYMENT", "DATE_PRINT", "DATE_REGISTER", "DATE_START", "DATE_UPDATE", "DATE_VALID", "EMPLOYE_PRINT", "EMPLOYEE_FINALIZE", "EMPLOYEE_PAYMENT", "EMPLOYEE_START", "EMPLOYEE_VALID", "ID", "LAST_EMPLOYEE_UPDATE", "ORIGINAL_USER", "PROCESS_TYPE", "STATUS", "WATER_INTAKE"};
    static final String[] PYM_PAYMENT_CONCEPT_GS = {"CURRENT_PRICE", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "DESCRIPTION_LONG", "ID", "MANDATORY_PAYMENT", "MODULE", "PREVIOUS_PRICE", "STATUS"};
    static final String[] PYM_PAYMENT_LIST_GS = {"COST", "DATE_REGISTER", "ID", "ITEM_NAME", "PAYMENT", "PAYMENT_CONCEPT", "STATUS"};
    static final String[] PYM_PAYMENTS_GS = {"AMOUNT_PAID", "CHANGE_AMOUNT", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "EMPLOYEE", "ID", "MONTH_PAID", "PAYMENT_CONCEPT", "PAYMENT_METHOD", "PAYMENT_TYPE", "STATUS", "TOTAL_COST", "USER", "UUDI", "WATER_INTAKE", "WATER_INTAKE_TYPE"};
    static final String[] USR_BLOCKED_USER_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID", "STATUS", "USER"};
    static final String[] USR_USER_GS = {"BIRTHDATE", "CURP", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "EMAIL", "FIRST_NAME", "GENDER", "ID", "INSIDE_NUMBER", "LAST_EMPLOYEE_UPDATE", "LAST_NAME1", "LAST_NAME2", "OUTSIDE_NUMBER", "PHONE_NUMBER1", "PHONE_NUMBER2", "STATUS", "STREET1", "STREET2", "USER_TYPE"};
    static final String[] USR_USER_DOCUMENT_GS = {"DATE_END", "DATE_REGISTER", "DOC_FILE", "DOCUMENT_NAME", "DOCUMENT_PATH", "ID", "STATUS", "USER"};
    static final String[] USR_USER_TYPE_GS = {"DATE_FINALIZE", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION_LONG", "ID", "STATUS", "USER_TYPE"};
    static final String[] USR_USERS_CONSUMERS_GS = {"CONSUMER", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "HOLDER", "ID", "STATUS", "WATER_INTAKE"};
    static final String[] WKI_USER_GS = {"DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "EMPLOYEE_REGISTER", "ID", "LAST_EMPLOYEE_UPDATE", "LAST_PROCESS_TYPE", "NOTES", "STATUS", "USER_ID", "WATER_INTAKE_ID", "WATER_INTAKE_TYPE_ID"};
    static final String[] WKI_WATER_INTAKE_TYPE_GS = {"CURRENT_PRICE", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "ID", "LAST_EMPLOYEE_UPDATE", "PREVIOUS_PRICE", "STATUS", "SURCHARGE", "TYPE_NAME"};
    static final String[] WKI_WATER_INTAKES_GS = {"COST_PROCEDURE", "DATE_END", "DATE_REGISTER", "DATE_UPDATE", "DESCRIPTION", "ID", "LAST_EMPLOYEE_UPDATE", "LOCATION", "STATUS", "STREET1", "STREET2", "USER", "USER_NAME", "WATER_INTAKE_TYPE"};

}
