/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas.menuprincipal.sub;

import com.jblue.modelo.ConstGs;
import com.jblue.modelo.objetos.OPagosServicio;
import com.jblue.util.Filtros;
import com.jblue.util.FuncJBlue;
import com.jblue.util.fabricas.FabricaOpraciones;
import com.jblue.util.modelo.MemoCache;
import com.jblue.vista.marco.vistas.VistaSimple;
import com.jblue.vista.vistas.menuprincipal.VCobros;
import com.jutil.swingw.modelos.TableModel;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jp
 */
public final class VCCobros extends VistaSimple {

    /**
     * Creates new form VCobrosR
     *
     * @param root
     */
    public VCCobros(VCobros root) {
        this.memo_cache = new MemoCache<>(FabricaOpraciones.getPAGOS_X_SERVICIO());
        memo_cache.setRangoActivo(true);
        memo_cache.cargar();
        cache = memo_cache.getLista();
        cache_aux = new ArrayList<>(cache.size());
        modelo = new TableModel(ConstGs.TABLA_PAGOS_X_SERVICIO, 0);
        modelo.setCellsEditables(false);
        initComponents();
        jTable2.setModel(modelo);
        llamable();
    }

    @Override
    protected void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    public void componentesEstadoInicial() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_filtros = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        panel_tabla = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_rec = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_ant = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        filtro_buscador = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        setName("Cobros realizados"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panel_filtros.setName("Cobros realizados"); // NOI18N
        panel_filtros.setPreferredSize(new java.awt.Dimension(1200, 100));
        panel_filtros.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("Filtros");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Quitar filtros");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 29));
        jPanel4.add(jButton1, java.awt.BorderLayout.LINE_END);

        panel_filtros.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Fecha de inicio.");
        jPanel5.add(jLabel1, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel5);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Fecha de fin.");
        jPanel7.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel8);

        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel1.add(jPanel6);

        panel_filtros.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(panel_filtros, java.awt.BorderLayout.NORTH);

        panel_tabla.setPreferredSize(new java.awt.Dimension(1000, 400));
        panel_tabla.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_rec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        btn_rec.setPreferredSize(new java.awt.Dimension(100, 27));
        btn_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rec, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        btn_ant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        btn_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_antActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ant);

        btn_sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sig);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        filtro_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtro_buscadorKeyTyped(evt);
            }
        });
        jPanel2.add(filtro_buscador, java.awt.BorderLayout.CENTER);

        panel_tabla.add(jPanel2, java.awt.BorderLayout.NORTH);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1000, 370));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        panel_tabla.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(panel_tabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recActionPerformed
        FuncJBlue.pintarTabla(modelo, memo_cache.getListaObj());
    }//GEN-LAST:event_btn_recActionPerformed

    private void btn_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_antActionPerformed
        SwingUtilities.invokeLater(() -> {
            memo_cache.ant();
            memo_cache.actualizar();
            if (memo_cache.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay usuarios", "Usuarios Buscados", JOptionPane.INFORMATION_MESSAGE);
                memo_cache.sig();
                memo_cache.actualizar();
            }
            FuncJBlue.pintarTabla(modelo, cache);
        });
    }//GEN-LAST:event_btn_antActionPerformed

    private void filtro_buscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtro_buscadorKeyTyped
        String aux = Filtros.limpiar(filtro_buscador.getText());
        if (Filtros.isNullOrBlank(aux)) {
            FuncJBlue.pintarTabla(modelo, cache);
            return;
        }
        buscador(aux);
    }//GEN-LAST:event_filtro_buscadorKeyTyped

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
        SwingUtilities.invokeLater(() -> {
            memo_cache.sig();
            memo_cache.actualizar();
            if (memo_cache.getLista().isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay usuarios", "Usuarios Buscados", JOptionPane.INFORMATION_MESSAGE);
                memo_cache.ant();
                memo_cache.actualizar();
            }
            FuncJBlue.pintarTabla(modelo, cache);
        });
    }//GEN-LAST:event_btn_sigActionPerformed

    private void buscador(final String aux) {
        List<OPagosServicio> lista = cache.stream().filter(e -> {
            String a = Filtros.limpiar(e.getInfoSinFK()[2]);
            return a.contains(aux);
        }).collect(Collectors.toList());

        FuncJBlue.pintarTabla(modelo, lista);
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            FuncJBlue.pintarTabla(modelo, memo_cache.getLista());
        } else {
            modelo.removeAllRows();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ant;
    private javax.swing.JButton btn_rec;
    private javax.swing.JButton btn_sig;
    private javax.swing.JTextField filtro_buscador;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel panel_filtros;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

    private final MemoCache<OPagosServicio> memo_cache;
    private final ArrayList<OPagosServicio> cache;
    private final ArrayList<OPagosServicio> cache_aux;
    private final TableModel modelo;
}
