/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.componentes;

import com.jblue.modelo.ConstGs;
import com.jutil.jbd.conexion.Conexion;
import com.jutil.jexception.Excp;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author juan-campos
 */
public class NewMenuConfigBD extends javax.swing.JDialog {

    public static String[] getConexion() throws SQLException {
        NewMenuConfigBD o = new NewMenuConfigBD(null, true);
        o.setVisible(true);
        return new String[]{
            o.getUsuario(), o.getContraseña(), o.getURL()
        };
    }

    /**
     * A return status code - returned if Cancel button has been pressed
     */
    public static final int RET_CANCEL = 0;
    /**
     * A return status code - returned if OK button has been pressed
     */
    public static final int RET_OK = 1;

    /**
     * Creates new form NewMenuConfigBD
     *
     * @param parent
     * @param modal
     */
    public NewMenuConfigBD(JFrame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Conexion a Base de datos");
        // Close the dialog when Esc is pressed
        String cancelName = "cancel";
        InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
        inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
        ActionMap actionMap = getRootPane().getActionMap();
        actionMap.put(cancelName, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent e) {
                doClose(RET_CANCEL);
            }
        });
    }

    /**
     * @return the return status of this dialog - one of RET_OK or RET_CANCEL
     */
    public int getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        usuario = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        contra = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jcbMotor = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jtfHost = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jtfPuerto = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jtfBDNombre = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        btn_probar_conexion = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        btn_ok = new javax.swing.JButton();

        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel3.setLayout(new java.awt.GridLayout(4, 1));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuario"));
        jPanel4.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        usuario.setText("root");
        jPanel4.add(usuario, java.awt.BorderLayout.CENTER);

        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jCheckBox1.setPreferredSize(new java.awt.Dimension(50, 50));
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jCheckBox1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox1StateChanged(evt);
            }
        });
        jPanel4.add(jCheckBox1, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraseña"));
        jPanel5.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        contra.setText("contraseña");
        contra.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel5.add(contra, java.awt.BorderLayout.CENTER);

        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jCheckBox2.setPreferredSize(new java.awt.Dimension(50, 50));
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jCheckBox2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jCheckBox2StateChanged(evt);
            }
        });
        jPanel5.add(jCheckBox2, java.awt.BorderLayout.EAST);

        jPanel3.add(jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Base de datos"));
        jPanel6.setPreferredSize(new java.awt.Dimension(800, 80));
        jPanel6.setLayout(new java.awt.GridLayout(1, 4));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Motor");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.add(jLabel9, java.awt.BorderLayout.NORTH);

        jcbMotor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mysql" }));
        jcbMotor.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel7.add(jcbMotor, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Host");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel12.add(jLabel10, java.awt.BorderLayout.NORTH);

        jtfHost.setText("localhost");
        jtfHost.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel12.add(jtfHost, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel12);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Puerto");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.add(jLabel3, java.awt.BorderLayout.NORTH);

        jtfPuerto.setText("3306");
        jtfPuerto.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel13.add(jtfPuerto, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("base de datos");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel14.add(jLabel11, java.awt.BorderLayout.NORTH);

        jtfBDNombre.setText("jblue");
        jtfBDNombre.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel14.add(jtfBDNombre, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel14);

        jPanel3.add(jPanel6);

        jPanel8.setLayout(new java.awt.GridLayout(2, 0));
        jPanel8.add(jLabel4);

        btn_probar_conexion.setText("Probar Conexion");
        btn_probar_conexion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_probar_conexionActionPerformed(evt);
            }
        });
        jPanel8.add(btn_probar_conexion);

        jPanel3.add(jPanel8);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        jLabel7.setFont(new java.awt.Font("Cantarell", 0, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/usuario.png"))); // NOI18N
        jLabel7.setText("Configuracion de Base de datos");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel7.setPreferredSize(new java.awt.Dimension(800, 170));
        jLabel7.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        jPanel1.add(jLabel7, java.awt.BorderLayout.NORTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        jPanel2.add(cancelButton);

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ok);
        getRootPane().setDefaultButton(btn_ok);

        getContentPane().add(jPanel2, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        doClose(RET_OK);
    }//GEN-LAST:event_btn_okActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        doClose(RET_CANCEL);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        doClose(RET_CANCEL);
    }//GEN-LAST:event_closeDialog

    private void jCheckBox1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox1StateChanged
        if (jCheckBox1.isSelected()) {
            usuario.setEchoChar((char) 0);
        } else {
            usuario.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox1StateChanged

    private void jCheckBox2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jCheckBox2StateChanged
        if (jCheckBox2.isSelected()) {
            contra.setEchoChar((char) 0);
        } else {
            contra.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBox2StateChanged

    private void btn_probar_conexionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_probar_conexionActionPerformed
        try {
            Conexion con = Conexion.getInstancia(getUsuario(), getContraseña(), getURL());
            boolean cerrado = con.getConexion().isClosed();

            String mensaje = "La conexion es: ";

            if (!cerrado) {
                mensaje += "valida";
            } else {
                mensaje += "no valida";
            }
            JOptionPane.showMessageDialog(this, mensaje);
            Conexion.ConexionNULL();

        } catch (SQLException ex) {
            Excp.imp(ex, getClass(), true, true);
        }
    }//GEN-LAST:event_btn_probar_conexionActionPerformed

    private void doClose(int retStatus) {
        returnStatus = retStatus;
        setVisible(false);
        dispose();
    }

    public String getUsuario() {
        return String.valueOf(usuario.getPassword());
    }

    public String getContraseña() {
        return String.valueOf(contra.getPassword());
    }

    public String getURL() {
        return String.format("jdbc:%s://%s:%s/%s",
                jcbMotor.getItemAt(jcbMotor.getSelectedIndex()),
                jtfHost.getText(),
                jtfPuerto.getText(),
                jtfBDNombre.getText()
        );

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_probar_conexion;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPasswordField contra;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JComboBox<String> jcbMotor;
    private javax.swing.JTextField jtfBDNombre;
    private javax.swing.JTextField jtfHost;
    private javax.swing.JTextField jtfPuerto;
    private javax.swing.JPasswordField usuario;
    // End of variables declaration//GEN-END:variables

    private int returnStatus = RET_CANCEL;
}
