/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.menus;

import com.jblue.sistema.Sesion;
import com.jblue.util.tiempo.Fecha;
import com.jblue.vista.normas.SuperVentana;
import com.jblue.vista.ventanas.Login;
import com.jblue.vista.ventanas.menus.bd.MenuCalles;
import com.jblue.vista.ventanas.menus.bd.MenuTomas;
import com.jblue.vista.ventanas.menus.bd.MenuUsuarios;
import com.jblue.vista.ventanas.menus.bd.MenuTRegistradas;
import com.jblue.vista.ventanas.menus.herramientas.MenuCVS;
import com.jblue.vista.ventanas.vistas.principal.VHistorialPagos;
import com.jblue.vista.ventanas.vistas.principal.VPrincipal;
import com.jblue.vista.ventanas.vistas.principal.VRecargos;
import java.awt.BorderLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

/**
 *
 * @author jp
 */
public class MenuPrincipal extends SuperVentana {
    
    private final Login login;
    private final MenuTesoreria menuTesoreria;
    private final MenuPresidente menuPresidente;
    //
    private final MenuUsuarios menuUsuarios;
    private final MenuCalles menuCalles;
    private final MenuTomas menuTipoTomas;
    private final MenuTRegistradas menuTomasRegistradas;
    private final JPanel[] vistas;
    private final JFrame[] menus;

    //
    private final Fecha fecha;

    //
    public MenuPrincipal(Login login) {
        
        this.vistas = new JPanel[3];
        
        this._TITULO = 2;
        
        this.login = login;
        //
        this.menuTesoreria = new MenuTesoreria();
        this.menuPresidente = new MenuPresidente();
        this.menuUsuarios = new MenuUsuarios();
        this.menuCalles = new MenuCalles();
        this.menuTipoTomas = new MenuTomas();
        this.menuTomasRegistradas = new MenuTRegistradas();
        
        this.menus = new JFrame[]{
            menuTesoreria,
            menuPresidente,
            menuUsuarios,
            menuCalles,
            menuTipoTomas,
            menuTomasRegistradas
        };
        //
        fecha = new Fecha();
        //
        this.initComponents();
        llamable();
    }
    
    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }
    
    @Override
    public void estadoInicial() {
        
    }
    
    @Override
    protected void estadoFinal() {
        super.estadoFinal();
    }
    
    @Override
    protected void addEventos() {
        super.addEventos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }
    
    @Override
    protected void addComponentes() {
        
        vistas[0] = new VPrincipal();
        vistas[1] = new VRecargos();
        vistas[2] = new VHistorialPagos();
        
        for (int i = 0; i < vistas.length; i++) {
            JPanel menu = (JPanel) jTabbedPane1.getComponentAt(i + 1);
            menu.add(vistas[i], BorderLayout.CENTER);
        }
        
        jTabbedPane1.remove(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpAreaPersonal = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jbtPerfil = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jbtCobros = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jbtRecargos = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jbtHistorialPagos = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jbtSalir = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jpVisor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jpCobros = new javax.swing.JPanel();
        jpRecargos = new javax.swing.JPanel();
        jpHistorialPagos = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        itemMenuTesorero = new javax.swing.JMenuItem();
        itemMenuPresidente = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        ItemBDUsuario = new javax.swing.JMenuItem();
        itemBDCalles = new javax.swing.JMenuItem();
        itemBDTomas = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setExtendedState(6);

        jTabbedPane1.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 675));

        jpAreaPersonal.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 100));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Areas de Trabajo");
        jLabel1.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel7.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jbtPerfil.setText("Perfil");
        jbtPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtPerfilActionPerformed(evt);
            }
        });
        jPanel7.add(jbtPerfil, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel4.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jbtCobros.setText("Cobros");
        jbtCobros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCobrosActionPerformed(evt);
            }
        });
        jPanel4.add(jbtCobros, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jbtRecargos.setText("Recargos");
        jbtRecargos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRecargosActionPerformed(evt);
            }
        });
        jPanel3.add(jbtRecargos, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jbtHistorialPagos.setText("Historial De Pagos");
        jbtHistorialPagos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtHistorialPagosActionPerformed(evt);
            }
        });
        jPanel5.add(jbtHistorialPagos, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel6.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel6);

        jPanel8.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel8.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel8);

        jPanel11.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel11.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel11);

        jPanel10.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel10.setLayout(new java.awt.BorderLayout());
        jPanel2.add(jPanel10);

        jPanel9.setPreferredSize(new java.awt.Dimension(300, 593));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jbtSalir.setText("Salir");
        jbtSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtSalirActionPerformed(evt);
            }
        });
        jPanel9.add(jbtSalir, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jpAreaPersonal.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jpVisor.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Sistema de cobranza del servicio de agua potable");
        jLabel3.setPreferredSize(new java.awt.Dimension(323, 50));
        jpVisor.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel12.add(jpVisor, java.awt.BorderLayout.CENTER);

        jpAreaPersonal.add(jPanel12, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Area Personal", jpAreaPersonal);

        jpCobros.setPreferredSize(new java.awt.Dimension(1200, 643));
        jpCobros.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Cobros", jpCobros);

        jpRecargos.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Recargos", jpRecargos);

        jpHistorialPagos.setLayout(new java.awt.BorderLayout());
        jTabbedPane1.addTab("Historial de pagos", jpHistorialPagos);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);
        jTabbedPane1.getAccessibleContext().setAccessibleName("tab_root");

        jMenuBar1.setPreferredSize(new java.awt.Dimension(1200, 25));

        jMenu1.setText("Menu");

        jMenuItem2.setText("Perfil");
        jMenu1.add(jMenuItem2);

        itemMenuTesorero.setText("Tesorero");
        itemMenuTesorero.setName("tesorero"); // NOI18N
        jMenu1.add(itemMenuTesorero);

        itemMenuPresidente.setText("Presidente");
        itemMenuPresidente.setName("presidente"); // NOI18N
        itemMenuPresidente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuPresidenteActionPerformed(evt);
            }
        });
        jMenu1.add(itemMenuPresidente);

        jMenu3.setText("Base de datos");
        jMenu3.setName("menu-bd"); // NOI18N

        jMenuItem1.setText("Tomas Registradas");
        jMenuItem1.setName("tomas -egistradas"); // NOI18N
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        ItemBDUsuario.setText("BD Usuarios");
        ItemBDUsuario.setName("usuarios"); // NOI18N
        ItemBDUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ItemBDUsuarioActionPerformed(evt);
            }
        });
        jMenu3.add(ItemBDUsuario);

        itemBDCalles.setText("BD Calles");
        itemBDCalles.setName("calles"); // NOI18N
        itemBDCalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBDCallesActionPerformed(evt);
            }
        });
        jMenu3.add(itemBDCalles);

        itemBDTomas.setText("BD Tipo de tomas");
        itemBDTomas.setName("tipo-de-tomas"); // NOI18N
        itemBDTomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemBDTomasActionPerformed(evt);
            }
        });
        jMenu3.add(itemBDTomas);

        jMenu1.add(jMenu3);
        jMenu1.add(jSeparator2);

        jMenuItem4.setText("Salir");
        jMenuItem4.setName("salir"); // NOI18N
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Herramientas");

        jMenu5.setText("Tablas");

        jMenuItem3.setText("Generar CSV");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem3);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Ayuda");
        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ItemBDUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ItemBDUsuarioActionPerformed
        SwingUtilities.invokeLater(() -> {
            menuUsuarios.setVisible(true);
        });
    }//GEN-LAST:event_ItemBDUsuarioActionPerformed

    private void itemBDCallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBDCallesActionPerformed
        SwingUtilities.invokeLater(() -> {
            menuCalles.setVisible(true);
        });
    }//GEN-LAST:event_itemBDCallesActionPerformed

    private void itemBDTomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemBDTomasActionPerformed
        SwingUtilities.invokeLater(() -> {
            menuTipoTomas.setVisible(true);
        });
    }//GEN-LAST:event_itemBDTomasActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jbtCobrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCobrosActionPerformed
        vistaSeleccionada(1);
    }//GEN-LAST:event_jbtCobrosActionPerformed

    private void jbtRecargosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRecargosActionPerformed
        vistaSeleccionada(2);
    }//GEN-LAST:event_jbtRecargosActionPerformed

    private void jbtHistorialPagosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtHistorialPagosActionPerformed
        vistaSeleccionada(3);
    }//GEN-LAST:event_jbtHistorialPagosActionPerformed

    private void jbtSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtSalirActionPerformed
        vistaSeleccionada(0);
        //

        dispose();
    }//GEN-LAST:event_jbtSalirActionPerformed

    private void itemMenuPresidenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuPresidenteActionPerformed
        SwingUtilities.invokeLater(() -> {
            menuPresidente.setVisible(true);
        });

    }//GEN-LAST:event_itemMenuPresidenteActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        SwingUtilities.invokeLater(() -> {
            menuTomasRegistradas.setVisible(true);
        });

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jbtPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtPerfilActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        MenuCVS menu = new MenuCVS();
        menu.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    public void vistaSeleccionada(int i) {
        SwingUtilities.invokeLater(() -> jTabbedPane1.setSelectedIndex(i));
    }
    
    @Override
    public void dispose() {
        irLogin();
        super.dispose();
    }
    
    private void irLogin() {
        cerrarMenusActivos();
        Sesion instancia = Sesion.getInstancia();
        
        boolean finSesion = instancia.finSesion();
        if (!finSesion) {
            JOptionPane.showMessageDialog(this, "ERROR AL REGISTRAR FIN DE SESION");
        }
        
        SwingUtilities.invokeLater(() -> {
            login.setVisible(true);
            login.limpiarInstancia();
        });
    }
    
    private void cerrarMenusActivos() {
        JFrame[] arr = menus;
        for (JFrame o : arr) {
            if (!o.isVisible() && !o.isActive()) {
                continue;
            }
            o.setVisible(true);
            sleep();
            o.setState(JFrame.ICONIFIED);
            //
            SwingUtilities.invokeLater(() -> {
                o.setVisible(false);
                o.dispose();
            });
            sleep();
        }
    }
    
    private void sleep() {
        try {
            Thread.sleep(300);
        } catch (InterruptedException ex) {
            Logger.getLogger(MenuPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    @Override
    public void permisos() {
        
    }

// <editor-fold defaultstate="collapsed" desc="Variables De Interfaz">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ItemBDUsuario;
    private javax.swing.JMenuItem itemBDCalles;
    private javax.swing.JMenuItem itemBDTomas;
    private javax.swing.JMenuItem itemMenuPresidente;
    private javax.swing.JMenuItem itemMenuTesorero;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton jbtCobros;
    private javax.swing.JButton jbtHistorialPagos;
    private javax.swing.JButton jbtPerfil;
    private javax.swing.JButton jbtRecargos;
    private javax.swing.JButton jbtSalir;
    private javax.swing.JPanel jpAreaPersonal;
    private javax.swing.JPanel jpCobros;
    private javax.swing.JPanel jpHistorialPagos;
    private javax.swing.JPanel jpRecargos;
    private javax.swing.JPanel jpVisor;
    // End of variables declaration//GEN-END:variables
// </editor-fold>

}
