/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas;

import com.jblue.vista.ventanas.menus.MenuPrincipal;
import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.objetos.OPersonal;
import com.jblue.sistema.Sesion;
import com.jblue.sistema.Sistema;
import com.jblue.util.cache.FabricaOpraciones;
import com.jblue.util.crypto.EncriptadoAES;
import com.jblue.vista.normas.SuperVentana;
import com.jutil.jbd.conexion.Conexion;
import com.jutil.jexception.Excp;
import com.jutil.jswing.jswingenv.EnvJTextField;
import java.awt.event.KeyEvent;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jp
 */
public class Login extends SuperVentana {

    private MenuPrincipal MENU_PRINCIPAL;
    private final MenuConfigBD MENU_CONFIG_BD;
    private final EnvJTextField env_jtf[];

    /**
     * Creates new form NewLogin
     *
     * @param MENU_CONFIG_BD
     */
    public Login(MenuConfigBD MENU_CONFIG_BD) {
        this._TITULO = 1;
        this.MENU_CONFIG_BD = MENU_CONFIG_BD;
        initComponents();
        env_jtf = new EnvJTextField[2];
        env_jtf[0] = new EnvJTextField(usuario, "ejem: david123");
        env_jtf[1] = new EnvJTextField(contra, "contraseña 12345");
        llamable();
    }

    @Override
    public final void llamable() {
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    public void estadoInicial() {
        usuario.requestFocusInWindow();
        mostrar.setToolTipText("mostrar");
        mostrar.setSelected(false);
        //
        for (EnvJTextField envjtf : env_jtf) {
            envjtf.defecto();
        }
        setDefaultLookAndFeelDecorated(false);
    }

    @Override
    protected void estadoFinal() {
        super.estadoFinal();
        try {
            Conexion instancia = Conexion.getInstancia();
            String estado = "Estado ";
            estado += instancia.isConectado() ? "Conectado" : "Desconectado";

            jlEstado.setText(estado);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    protected void addComponentes() {
        super.addComponentes();
    }

    @Override
    protected void addEventos() {
        jbtInicio.addActionListener(e -> login());
        for (EnvJTextField envjtf : env_jtf) {
            envjtf.borrarAlClick();
            envjtf.borrarAlEscribir();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbtInicio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        configuracionBD = new javax.swing.JButton();
        jlEstado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesion");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/img1.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(350, 150));
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 250));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jPanel5.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel5.setText("Usuario");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel5.add(jLabel5, java.awt.BorderLayout.LINE_START);

        usuario.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel5.add(usuario, java.awt.BorderLayout.CENTER);

        jLabel9.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel5.add(jLabel9, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel6.setText("Contraseña");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel6.add(jLabel6, java.awt.BorderLayout.LINE_START);

        contra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                contraKeyPressed(evt);
            }
        });
        jPanel6.add(contra, java.awt.BorderLayout.CENTER);

        mostrar.setToolTipText("mostrar");
        mostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        mostrar.setPreferredSize(new java.awt.Dimension(30, 40));
        mostrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarActionPerformed(evt);
            }
        });
        jPanel6.add(mostrar, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel7.setPreferredSize(new java.awt.Dimension(100, 18));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jbtInicio.setText("Iniciar Sesion");
        jPanel7.add(jbtInicio, java.awt.BorderLayout.CENTER);

        jLabel8.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel7.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel7);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 5));

        configuracionBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/img4.png"))); // NOI18N
        configuracionBD.setPreferredSize(new java.awt.Dimension(75, 40));
        configuracionBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionBDActionPerformed(evt);
            }
        });
        jPanel3.add(configuracionBD, java.awt.BorderLayout.WEST);
        jPanel3.add(jlEstado, java.awt.BorderLayout.CENTER);

        jLabel4.setPreferredSize(new java.awt.Dimension(75, 40));
        jPanel3.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarActionPerformed
        if (mostrar.isSelected()) {
            contra.setEchoChar((char) 0);
            mostrar.setToolTipText("ocultar");
        } else {
            contra.setEchoChar('*');
            mostrar.setToolTipText("mostrar");
        }
    }//GEN-LAST:event_mostrarActionPerformed

    private void configuracionBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionBDActionPerformed
        setVisible(false);
        dispose();
        SwingUtilities.invokeLater(() -> MENU_CONFIG_BD.setVisible(true));
    }//GEN-LAST:event_configuracionBDActionPerformed

    private void contraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_contraKeyPressed
        if (evt.getKeyChar() == KeyEvent.VK_ENTER) {
            login();
        }
    }//GEN-LAST:event_contraKeyPressed

    private boolean sesion = false;

    public synchronized void login() {
        if (sesion) {
            return;
        }
        sesion = true;
        if (!inicio()) {
            sesion = false;
            return;
        }
        if (!Sistema.getInstancia().datosCSache()) {
            System.out.println("ERROR AL CARGAR LA CACHE");
        }
        System.out.println("¡¡¡CACHE CARGADA!!!");

        SwingUtilities.invokeLater(() -> {
            this.setVisible(false);
            this.dispose();
        });
        SwingUtilities.invokeLater(() -> {
            MENU_PRINCIPAL = new MenuPrincipal(this);
            MENU_PRINCIPAL.permisos();
            MENU_PRINCIPAL.setVisible(true);
            
        });
    }

    public boolean inicio() {
        try {
            if (!datosValidos()) {
                return false;
            }
            String x = usuario.getText();
            String y = String.valueOf(contra.getPassword());
            Operaciones<OPersonal> log = FabricaOpraciones.getPERSONAL();
            EncriptadoAES en = new EncriptadoAES();
            String query = "usuario ='" + en.encriptar(x, y) + "' && contra ='" + en.encriptar(y, x) + "'";
            OPersonal get = log.get(query);
            if (get == null) {
                JOptionPane.showMessageDialog(this, "Usuario y/o contraseña incorrectos");
                return false;
            }
            Sesion ses = Sesion.getInstancia();
            ses.setUsuario(get);
            if (!ses.inicioSesion()) {
                JOptionPane.showMessageDialog(this, "ERROR AL REGISTRAR SESION");
                return false;
            }
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException
                | InvalidKeyException | NoSuchPaddingException
                | IllegalBlockSizeException | BadPaddingException ex) {
            Excp.impTerminal(ex, getClass(), true);
        }
        return true;
    }

    public boolean datosValidos() {
        String x = usuario.getText();
        String y = String.valueOf(contra.getPassword());
        return x != null && !x.isBlank() && y != null && !y.isBlank();
    }

    public void limpiarInstancia() {
        MENU_PRINCIPAL = null;
        sesion = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configuracionBD;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbtInicio;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables

//
    @Override
    public void dispose() {
        super.dispose();
        SwingUtilities.invokeLater(() -> estadoInicial());
    }
}
