/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas;

import com.jblue.controlador.CLogin;
import com.jblue.modelo.objetos.OPersonal;
import com.jblue.sistema.ConstSisMen;
import com.jblue.sistema.Sesion;
import com.jblue.sistema.Sistema;
import com.jblue.vista.marco.contruccion.ConstTitutlos;
import com.jblue.vista.marco.ventanas.VentanaSimple;
import com.jutil.jbd.conexion.Conexion;
import com.jutil.swingw.wrappers.TextFieldWrapper;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import com.jblue.otros.news.ventanas.NewMenuPrincipal;
import com.jblue.sistema.DevFlags;

/**
 *
 * @author jp
 */
public class Login extends VentanaSimple {

    private MenuPrincipal MENU_PRINCIPAL;
    private NewMenuPrincipal NEW_MAIN_MENU;
    private final MenuConfigBD MENU_CONFIG_BD;
    private final TextFieldWrapper campos[];

    /**
     * Creates new form NewLogin
     *
     */
    public Login() {
        super(ConstTitutlos.TL_INICIO_SESION, ConstTitutlos.TL_VENTANAS);
        this.MENU_CONFIG_BD = new MenuConfigBD();
        initComponents();
        campos = new TextFieldWrapper[2];
        campos[0] = new TextFieldWrapper(usuario, "ejem: david123");
        campos[1] = new TextFieldWrapper(contra, "contraseña 12345");
        llamable();
    }

    @Override
    public final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    public void componentesEstadoInicial() {
        usuario.requestFocusInWindow();
        mostrar.setToolTipText("mostrar");
        mostrar.setSelected(false);
        //
        for (TextFieldWrapper envjtf : campos) {
            envjtf.defecto();
        }
        setDefaultLookAndFeelDecorated(false);
    }

    @Override
    protected void componentesEstadoFinal() {
        super.componentesEstadoFinal();
        usuario.requestFocus();
        try {
            Conexion instancia = Conexion.getInstancia();
            String estado = "Estado ";
            estado = estado.concat(instancia.isConectado() ? "Conectado" : "Desconectado");
            jlEstado.setText(estado);
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    protected void manejoEventos() {
        jbtInicio.addActionListener(e -> login());

        mostrar.addItemListener((e) -> {
            char echo_char = mostrar.isSelected() ? ((char) 0) : '*';
            String tool_tip = mostrar.isSelected() ? "Ocultar" : "Mostrar";
            contra.setEchoChar(echo_char);
            mostrar.setToolTipText(tool_tip);
        });

        for (TextFieldWrapper envjtf : campos) {
            envjtf.borrarAlClick();
            envjtf.borrarAlEscribir();
        }

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                synchronized (Sistema.getInstancia()) {
                    Sistema.getInstancia().notify();
                }
            }
        });

        configuracionBD.addActionListener(e -> {
            setVisible(false);
            dispose();
            SwingUtilities.invokeLater(() -> MENU_CONFIG_BD.setVisible(true));
        });

        String enter = "ENTER";

        usuario.getInputMap().put(KeyStroke.getKeyStroke((char) KeyEvent.VK_ENTER), enter);
        usuario.getActionMap().put(enter, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                usuario.transferFocus();
            }
        });

        InputMap inputMap = contra.getInputMap(JComponent.WHEN_FOCUSED);
        inputMap.put(KeyStroke.getKeyStroke((char) KeyEvent.VK_ENTER), enter);

        contra.getActionMap().put(enter, new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                login();
            }
        });
        contra.getFocusTraversalPolicy();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        mostrar = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jbtInicio = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        configuracionBD = new javax.swing.JButton();
        jlEstado = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Inicio de sesion");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setPreferredSize(new java.awt.Dimension(350, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.NORTH);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/img1.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setIconTextGap(30);
        jLabel2.setPreferredSize(new java.awt.Dimension(350, 150));
        jLabel2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel1.add(jLabel2, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(350, 250));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel4.setLayout(new java.awt.GridLayout(5, 1, 5, 5));

        jPanel5.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel5.setText("Usuario");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel5.add(jLabel5, java.awt.BorderLayout.LINE_START);

        usuario.setNextFocusableComponent(contra);
        usuario.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel5.add(usuario, java.awt.BorderLayout.CENTER);

        jLabel9.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel5.add(jLabel9, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel6.setText("Contraseña");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel6.add(jLabel6, java.awt.BorderLayout.LINE_START);
        jPanel6.add(contra, java.awt.BorderLayout.CENTER);

        mostrar.setToolTipText("mostrar");
        mostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mostrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        mostrar.setPreferredSize(new java.awt.Dimension(30, 40));
        mostrar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jPanel6.add(mostrar, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel7.setPreferredSize(new java.awt.Dimension(100, 18));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jbtInicio.setText("Iniciar Sesion");
        jPanel7.add(jbtInicio, java.awt.BorderLayout.CENTER);

        jLabel8.setPreferredSize(new java.awt.Dimension(30, 40));
        jPanel7.add(jLabel8, java.awt.BorderLayout.LINE_END);

        jPanel4.add(jPanel7);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel3.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel3.setLayout(new java.awt.BorderLayout(5, 5));

        configuracionBD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/img4.png"))); // NOI18N
        configuracionBD.setPreferredSize(new java.awt.Dimension(75, 40));
        jPanel3.add(configuracionBD, java.awt.BorderLayout.WEST);
        jPanel3.add(jlEstado, java.awt.BorderLayout.CENTER);

        jLabel4.setPreferredSize(new java.awt.Dimension(75, 40));
        jPanel3.add(jLabel4, java.awt.BorderLayout.LINE_END);

        jPanel2.add(jPanel3, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public synchronized void login() {
        if (sesion_en_curso) {
            return;
        }

        sesion_en_curso = true;

        if (!iniciar()) {
            sesion_en_curso = false;
            return;
        }

// Las caches deberan cargarse solo cuando se requieran
        if (!Sistema.getInstancia()._CargarCache()) {
            System.out.println(ConstSisMen.MEN_CACHE_ERR);
        }
        System.out.println(ConstSisMen.MEN_CACHE_OK);

        this.dispose();

        SwingUtilities.invokeLater(() -> {
            if (DevFlags.FUTURE_VIEW) {
                //Nuevo menu estandarizado a las aplicaciones 
                NEW_MAIN_MENU = new NewMenuPrincipal(this);
                NEW_MAIN_MENU.setVisible(true);
            } else {
                //Menu anterior
                MENU_PRINCIPAL = new MenuPrincipal(this);
                MENU_PRINCIPAL.setVisible(true);
            }
        });
    }

    public boolean iniciar() {
        Optional<OPersonal> res = CLogin.login(usuario.getText(), String.valueOf(contra.getPassword()));
        if (res.isEmpty()) {
            return false;
        }

        Sesion sesion = Sesion.getInstancia();
        sesion.setUsuario(res.get());

        if (!sesion.inicioSesion()) {
            JOptionPane.showMessageDialog(this, "ERROR AL REGISTRAR SESION");
            return false;
        }
        return true;
    }

    public void limpiarInstancia() {
        //MENU_PRINCIPAL = null;
        NEW_MAIN_MENU = null;
        sesion_en_curso = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton configuracionBD;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JButton jbtInicio;
    private javax.swing.JLabel jlEstado;
    private javax.swing.JCheckBox mostrar;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
    private boolean sesion_en_curso = false;

    //
    @Override
    public void dispose() {
        super.dispose();
        SwingUtilities.invokeLater(() -> componentesEstadoInicial());
    }

}
