/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.ventanas;

import com.jblue.vista.normas.SuperVentana;
import com.jblue.vista.vistas.perfil.VPerfil;
import com.jblue.vista.vistas.perfil.tesorero.VTesorero;
import java.awt.CardLayout;
import java.awt.Container;

/**
 *
 * @author jp
 */
public class MenuCargos extends SuperVentana {

    /**
     * Creates new form MenuCargos
     */
    public MenuCargos() {
        initComponents();
        menu_tesorero = new VTesorero();
        menu_perfil = new VPerfil();
        ly = (CardLayout) getContentPane().getLayout();
        llamable();
    }

    @Override
    protected final void llamable() {
        addComponentes();
    }

    @Override
    protected void addComponentes() {
        Container panel = getContentPane();
        panel.add(menu_tesorero.getName(), menu_tesorero);
        panel.add(menu_perfil.getName(), menu_perfil);
    }

    @Override
    public void estadoInicial() {
    }

    public void showTesorero() {
        ly.show(getContentPane(), menu_tesorero.getName());
    }

    public void showPerfil() {
        ly.show(getContentPane(), menu_perfil.getName());
    }
    
    public void showPresidente(){}
    public void showSecretario(){}
    public void showAdministrador(){}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        jMenuBar1.setPreferredSize(new java.awt.Dimension(100, 30));
        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
    private final CardLayout ly;
    private final VTesorero menu_tesorero;
    private final VPerfil menu_perfil;

}
