/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.ventanas;

import com.jblue.vista.marco.contruccion.ConstTitutlos;
import com.jblue.vista.marco.ventanas.VentanaExtendida;
import com.jblue.vista.vistas.menubd.VCalles;
import com.jblue.vista.vistas.menubd.VConfiguraciones;
import com.jblue.vista.vistas.menubd.VPagosXOtros;
import com.jblue.vista.vistas.menubd.VTipoTomas;
import com.jblue.vista.vistas.menubd.usuarios.VUsuarios;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.Dimension;

/**
 *
 * @author jp
 */
public class MenuBD extends VentanaExtendida {

    private final CardLayout ly;
    private final VCalles menu_calles;
    private final VUsuarios menu_usuarios;
    private final VTipoTomas menu_tipo_tomas;
    private final VConfiguraciones menu_config;
    private final VPagosXOtros menu_pagos_x_otros;

    /**
     * Creates new form MenuBD
     */
    public MenuBD() {
        setTITULOS_VEN(ConstTitutlos.TL_BD);
        initComponents();
        menu_calles = new VCalles();
        menu_usuarios = new VUsuarios();
        menu_tipo_tomas = new VTipoTomas();
        menu_config = new VConfiguraciones();
        menu_pagos_x_otros = new VPagosXOtros();
        ly = (CardLayout) getContentPane().getLayout();
        llamable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_bar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.CardLayout());

        menu_bar.setPreferredSize(new java.awt.Dimension(148, 30));
        setJMenuBar(menu_bar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    protected final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    protected void construirComponentes() {
        Container panel = getContentPane();
        panel.add(menu_calles.getName(), menu_calles);
        panel.add(menu_usuarios.getName(), menu_usuarios);
        panel.add(menu_tipo_tomas.getName(), menu_tipo_tomas);
        panel.add(menu_config.getName(), menu_config);
        panel.add(menu_pagos_x_otros.getName(), menu_pagos_x_otros);
    }

    @Override
    public void componentesEstadoInicial() {
        //ly.show(getContentPane(), menu_calles.getName());
    }

    public void showCalles() {
        evtCambios(menu_bar, ly, menu_calles, ConstTitutlos.TL_BD_CALLES);
    }

    public void showUsuarios() {
        evtCambios(menu_bar, ly, menu_usuarios, ConstTitutlos.TL_BD_USUARIOS);
    }

    public void showTipoTomas() {
        evtCambios(menu_bar, ly, menu_tipo_tomas, ConstTitutlos.TL_BD_TIPO_TOMAS);
    }

    public void showConfiguraciones() {
        evtCambios(menu_bar, ly, menu_config, ConstTitutlos.TL_BD_TIPO_TOMAS);
    }

    public void showPagosXOtros() {
        evtCambios(menu_bar, ly, menu_pagos_x_otros, ConstTitutlos.TL_BD_TIPO_TOMAS);
    }

    @Override
    public void setPreferredSize(Dimension preferredSize) {
        super.setPreferredSize(preferredSize); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menu_bar;
    // End of variables declaration//GEN-END:variables
}
