/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas;

import com.jblue.controlador.CMenuPrincipal;
import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.util.cache.FabricaCache;
import com.jblue.vista.conf.SuperVentana;
import javax.swing.SpinnerNumberModel;
import com.jblue.util.tiempo.Fecha;
import com.jblue.vista.ventanas.bd.MenuUsuarios;
import com.jblue.vista.ventanas.bd.NewMenuCalles;
import com.jblue.vista.ventanas.bd.NewMenuTomas;
import com.jblue.vista.ventanas.bd.NewMenuUsuarios;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author jp
 */
public class MenuPrincipal extends SuperVentana {
    
    private int click_jtfBNU;
    //
    private final CMenuPrincipal CONTROLADOR;
    private final MenuTesoreria menuTesoreria;
    private final NewMenuUsuarios menuUsuarios;
    private final NewMenuCalles menuCalles;
    private final NewMenuTomas menuTipoTomas;
    private final Fecha fecha;
    
    private final DefaultListModel modelo;

    //
    private final ArrayList<OUsuarios> LISTA_AUX_USUARIOS;

    /**
     * Creates new form MenuPrincipal
     *
     * @param LOGIN
     */
    public MenuPrincipal(Login LOGIN) {
        this.menuUsuarios = new NewMenuUsuarios();
        this.menuCalles = new NewMenuCalles();
        this.menuTipoTomas = new NewMenuTomas();
        this.menuTesoreria = new MenuTesoreria();
        fecha = new Fecha();
        LISTA_AUX_USUARIOS = new ArrayList<>(50);
        //
        initComponents();
        
        this.modelo = new DefaultListModel();
        jlSugerencias.setModel(modelo);
        //
        llamable();
        //
        CONTROLADOR = new CMenuPrincipal(LOGIN, this, menuTesoreria);
    }
    
    @Override
    public final void llamable() {
        estadoFinal();
        estadoInicial();
        addComponentes();
        addEventos();
    }
    
    @Override
    public void estadoInicial() {
        click_jtfBNU = 0;
        initCobro();
        initPanelBuscar();
    }
    
    public void initPanelBuscar() {
        //Dia
        String[] mes = fecha.getMes();
        jsDia.setValue(fecha.getFechaActual().getDayOfMonth());
        //Mes
        jcbMes.setSelectedItem(mes[0]);
        //Año
        jsAnio.setValue(fecha.getFechaActual().getYear());
    }
    
    public void initCobro() {
        jtfBuscarNombreUsuario.setText("Ejem: Maria Rodriguez");
        jtfNombreUsuario.setText(null);
        jtfTipoToma.setText(null);
        //
        jtpMenus.setSelectedIndex(0);
        jlSugerencias.clearSelection();
        //
        SpinnerNumberModel model = (SpinnerNumberModel) jsMesesAPagar.getModel();
        jsMesesAPagar.setValue(model.getMinimum());
        //
    }
    
    @Override
    protected void estadoFinal() {
        this.setTitle(NOMBRE + VERSION + " - " + SECCION[1]);
        this.setExtendedState(MAXIMIZED_BOTH);
        ImageIcon o = new ImageIcon(this.getClass().getResource("/com/jblue/media/img/x128/jblue_icono.png"));
        this.setIconImage(o.getImage());
        //
        String[] mes = fecha.getMes();
        SpinnerNumberModel modelDia = (SpinnerNumberModel) jsDia.getModel();
        modelDia.setMinimum(Integer.valueOf(mes[1]));
        modelDia.setMaximum(Integer.valueOf(mes[2]));
    }
    
    @Override
    public void addEventos() {
        jtpMenus.addChangeListener((e) -> {
            if (jpBuscador.isVisible()) {
                CONTROLADOR.llenarCBCalles();
                CONTROLADOR.llenarCBTiposTomas();
            } else {
                CONTROLADOR.vaciarCBCalles();
                CONTROLADOR.vaciarCBTiposTomas();
            }
        });
        addOpciones();
        evtCobros();
        evtHistorialPagos();
    }
    
    public void addOpciones() {
        
    }
    
    public void evtCobros() {
        jtfBuscarNombreUsuario.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                if (click_jtfBNU == 0) {
                    jtfBuscarNombreUsuario.setText(null);
                }
                click_jtfBNU++;
            }
        });
        this.jbtCobrar.addActionListener(e -> initCobro());
    }
    
    public void evtHistorialPagos() {
        
    }
    
    @Override
    public void dispose() {
        super.dispose();
        CONTROLADOR.irLogin();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpConPrincipal = new javax.swing.JPanel();
        jtpMenus = new javax.swing.JTabbedPane();
        jpCobros = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        jtPagosDelDia = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jtfBuscarNombreUsuario = new javax.swing.JTextField();
        jScrollPane13 = new javax.swing.JScrollPane();
        jlSugerencias = new javax.swing.JList<>();
        jbtCobrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtfNombreUsuario = new javax.swing.JTextField();
        jtfTipoToma = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jsMesesAPagar = new javax.swing.JSpinner();
        jpBuscador = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtHistorial = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jcbMes = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jsDia = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jsAnio = new javax.swing.JSpinner();
        jLabel31 = new javax.swing.JLabel();
        jcbCalle = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jcbTipoToma = new javax.swing.JComboBox<>();
        jbtEliminarFiltros = new javax.swing.JButton();
        jbtBuscarHistorial = new javax.swing.JButton();
        jbtAnterior = new javax.swing.JButton();
        jbtRecargar = new javax.swing.JButton();
        jbtSiguiente = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));

        jpConPrincipal.setMinimumSize(new java.awt.Dimension(1200, 700));
        jpConPrincipal.setPreferredSize(new java.awt.Dimension(1200, 700));
        jpConPrincipal.setLayout(new java.awt.BorderLayout());

        jtpMenus.setAutoscrolls(true);
        jtpMenus.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtpMenus.setPreferredSize(new java.awt.Dimension(1200, 650));

        jpCobros.setMinimumSize(new java.awt.Dimension(1200, 700));

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Pagos del Dia");
        jLabel4.setPreferredSize(new java.awt.Dimension(92, 30));

        jtPagosDelDia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellidos", "Meses Pagados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtPagosDelDia.setOpaque(false);
        jtPagosDelDia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtPagosDelDia.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtPagosDelDia.setShowGrid(true);
        jtPagosDelDia.getTableHeader().setReorderingAllowed(false);
        jScrollPane12.setViewportView(jtPagosDelDia);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jtfBuscarNombreUsuario.setPreferredSize(new java.awt.Dimension(85, 35));
        jtfBuscarNombreUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarNombreUsuarioKeyReleased(evt);
            }
        });

        jlSugerencias.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlSugerencias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlSugerenciasMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(jlSugerencias);

        jbtCobrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/metodo-de-pago.png"))); // NOI18N
        jbtCobrar.setText("Cobrar");
        jbtCobrar.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel5.setText("Nombre");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 30));

        jPanel15.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Usuario"));
        jPanel15.setOpaque(false);

        jLabel8.setText("Nombre");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 30));

        jLabel9.setText("Tipo de toma");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));

        jtfNombreUsuario.setText("xd");
        jtfNombreUsuario.setEnabled(false);
        jtfNombreUsuario.setPreferredSize(new java.awt.Dimension(85, 30));

        jtfTipoToma.setText("xd");
        jtfTipoToma.setEnabled(false);
        jtfTipoToma.setPreferredSize(new java.awt.Dimension(85, 30));

        jLabel10.setText("Tipo de toma");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 30));

        jsMesesAPagar.setModel(new javax.swing.SpinnerNumberModel(1, 1, 12, 1));
        jsMesesAPagar.setPreferredSize(new java.awt.Dimension(64, 30));

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfTipoToma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jsMesesAPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfTipoToma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsMesesAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(103, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpCobrosLayout = new javax.swing.GroupLayout(jpCobros);
        jpCobros.setLayout(jpCobrosLayout);
        jpCobrosLayout.setHorizontalGroup(
            jpCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCobrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane13)
                    .addComponent(jbtCobrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpCobrosLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfBuscarNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE))
                    .addComponent(jPanel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpCobrosLayout.setVerticalGroup(
            jpCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCobrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCobrosLayout.createSequentialGroup()
                        .addGroup(jpCobrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfBuscarNombreUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(92, 92, 92)
                        .addComponent(jbtCobrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCobrosLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jtpMenus.addTab("Cobros", new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/metodo-de-pago.png")), jpCobros); // NOI18N

        jtHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtHistorial.setToolTipText("La tabla solo puede cargar hasta 1000 registros, para ver los registros posteriores o anteriores puede usar los botones anterior o siguiente");
        jScrollPane2.setViewportView(jtHistorial);

        jLabel11.setText("Mes");
        jLabel11.setPreferredSize(new java.awt.Dimension(0, 35));

        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT", "NOV", "DIC" }));
        jcbMes.setPreferredSize(new java.awt.Dimension(0, 35));

        jLabel12.setText("Dia");
        jLabel12.setPreferredSize(new java.awt.Dimension(0, 35));

        jsDia.setPreferredSize(new java.awt.Dimension(0, 35));

        jLabel13.setText("Año");
        jLabel13.setPreferredSize(new java.awt.Dimension(0, 35));

        jsAnio.setPreferredSize(new java.awt.Dimension(0, 35));

        jLabel31.setText("Calle");
        jLabel31.setPreferredSize(new java.awt.Dimension(0, 35));

        jcbCalle.setPreferredSize(new java.awt.Dimension(0, 35));

        jLabel32.setText("Tipo de toma");

        jcbTipoToma.setPreferredSize(new java.awt.Dimension(76, 30));

        jbtEliminarFiltros.setText("Eliminar Filtros");
        jbtEliminarFiltros.setPreferredSize(new java.awt.Dimension(127, 35));

        jbtBuscarHistorial.setText("Buscar");
        jbtBuscarHistorial.setPreferredSize(new java.awt.Dimension(58, 40));

        jbtAnterior.setText("Anterior");
        jbtAnterior.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtRecargar.setText("Recargar");
        jbtRecargar.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtSiguiente.setText("Siguiente");
        jbtSiguiente.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel33.setText("0 - 1000");
        jLabel33.setOpaque(true);
        jLabel33.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpBuscadorLayout = new javax.swing.GroupLayout(jpBuscador);
        jpBuscador.setLayout(jpBuscadorLayout);
        jpBuscadorLayout.setHorizontalGroup(
            jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpBuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jpBuscadorLayout.createSequentialGroup()
                        .addGroup(jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpBuscadorLayout.createSequentialGroup()
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jsAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpBuscadorLayout.createSequentialGroup()
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbTipoToma, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jcbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtBuscarHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtEliminarFiltros, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscadorLayout.createSequentialGroup()
                                .addComponent(jbtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jbtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jpBuscadorLayout.setVerticalGroup(
            jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpBuscadorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsDia, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jsAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtBuscarHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtEliminarFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbTipoToma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcbCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpBuscadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbtSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jtpMenus.addTab("Historial De Pagos", new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/factura.png")), jpBuscador, ""); // NOI18N

        jpConPrincipal.add(jtpMenus, java.awt.BorderLayout.CENTER);

        getContentPane().add(jpConPrincipal, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cofre-del-tesoro.png"))); // NOI18N
        jMenuItem1.setText("Tesoreria.");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiTesoreria(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem8.setText("Presidente");
        jMenu1.add(jMenuItem8);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerrar-sesion.png"))); // NOI18N
        jMenuItem2.setText("Salir");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalir(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Base De Datos");

        jMenuItem5.setText("Usuarios");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem4.setText("Tipos De Tomas");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem3.setText("Calles Registradas");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Herramientas");

        jMenuItem6.setText("jMenuItem6");
        jMenu6.add(jMenuItem6);

        jMenuItem7.setText("jMenuItem7");
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jtfBuscarNombreUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarNombreUsuarioKeyReleased
        LISTA_AUX_USUARIOS.clear();
        modelo.clear();
        String txt = jtfBuscarNombreUsuario.getText();
        txt = txt.trim().toUpperCase().replace(" ", "");
        for (OUsuarios o : FabricaCache.MC_USUARIOS.getLista()) {
            if (o.getStringElements(1, 2, 3).toUpperCase().replace(" ", "").contains(txt)) {
                modelo.addElement(o.getNombreStr());
                LISTA_AUX_USUARIOS.add(o);
            }
        }

    }//GEN-LAST:event_jtfBuscarNombreUsuarioKeyReleased

    private void jlSugerenciasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlSugerenciasMouseClicked
        final OUsuarios ub;
        switch (evt.getClickCount()) {
            case 1:
                ub = LISTA_AUX_USUARIOS.get(jlSugerencias.getSelectedIndex());
                jtfBuscarNombreUsuario.setText(ub.getNombreStr());
                break;
            case 2:
                ub = LISTA_AUX_USUARIOS.get(jlSugerencias.getSelectedIndex());
                jtfNombreUsuario.setText(ub.getNombreStr());
                jtfTipoToma.setText(ub.getToma());
                //
                modelo.clear();
                LISTA_AUX_USUARIOS.clear();
                jtfBuscarNombreUsuario.setText(null);
                break;
            
            default:
                throw new AssertionError();
        }

    }//GEN-LAST:event_jlSugerenciasMouseClicked

    private void jmiSalir(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalir
        CONTROLADOR.irLogin();
    }//GEN-LAST:event_jmiSalir

    private void jmiTesoreria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiTesoreria
        activar(menuTesoreria);
    }//GEN-LAST:event_jmiTesoreria

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        activar(menuUsuarios);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        activar(menuTipoTomas);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        SwingUtilities.invokeLater(() -> activar(menuCalles));
    }//GEN-LAST:event_jMenuItem3ActionPerformed
    
    public void activar(JFrame vista) {
        if (!vista.isVisible() || !vista.isActive()) {
            vista.setVisible(true);
        }
    }
    
    public boolean menusActivos() {
        JFrame[] menus = {menuUsuarios, menuCalles, menuTipoTomas, menuTesoreria};
        boolean activo = false;
        for (JFrame menu : menus) {
            if (menu.isVisible() || menu.isActive()) {
                activo = true;
                break;
            }
        }
        return activo;
    }
    
    public void cerrarMenus() {
        JFrame[] menus = {menuUsuarios, menuCalles, menuTipoTomas, menuTesoreria};
        for (JFrame menu : menus) {
            menu.setVisible(false);
            menu.dispose();
        }
    }
    
    public JComboBox<String> getJcbCalle() {
        return jcbCalle;
    }
    
    public void setJcbCalle(JComboBox<String> jcbCalle) {
        this.jcbCalle = jcbCalle;
    }
    
    public JComboBox<String> getJcbTipoToma() {
        return jcbTipoToma;
    }
    
    public void setJcbTipoToma(JComboBox<String> jcbTipoToma) {
        this.jcbTipoToma = jcbTipoToma;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JButton jbtAnterior;
    private javax.swing.JButton jbtBuscarHistorial;
    private javax.swing.JButton jbtCobrar;
    private javax.swing.JButton jbtEliminarFiltros;
    private javax.swing.JButton jbtRecargar;
    private javax.swing.JButton jbtSiguiente;
    private javax.swing.JComboBox<String> jcbCalle;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JComboBox<String> jcbTipoToma;
    private javax.swing.JList<String> jlSugerencias;
    private javax.swing.JPanel jpBuscador;
    private javax.swing.JPanel jpCobros;
    private javax.swing.JPanel jpConPrincipal;
    private javax.swing.JSpinner jsAnio;
    private javax.swing.JSpinner jsDia;
    private javax.swing.JSpinner jsMesesAPagar;
    private javax.swing.JTable jtHistorial;
    private javax.swing.JTable jtPagosDelDia;
    private javax.swing.JTextField jtfBuscarNombreUsuario;
    private javax.swing.JTextField jtfNombreUsuario;
    private javax.swing.JTextField jtfTipoToma;
    private javax.swing.JTabbedPane jtpMenus;
    // End of variables declaration//GEN-END:variables
}
