/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.ventanas;

import com.jblue.vista.jbmarco.ConstTitutlos;
import com.jblue.vista.jbmarco.VentanaExtendida;
import com.jblue.vista.vistas.menucargos.VPerfil;
import com.jblue.vista.vistas.menucargos.administrador.VAdministrador;
import com.jblue.vista.vistas.menucargos.presidente.VPresidente;
import com.jblue.vista.vistas.menucargos.tesorero.VTesorero;
import java.awt.CardLayout;
import java.awt.Container;

/**
 *
 * @author jp
 */
public class MenuCargos extends VentanaExtendida {

    /**
     * Creates new form MenuCargos
     */
    public MenuCargos() {
        super(ConstTitutlos.TL_PERFILES);
        initComponents();
        menu_tesorero = new VTesorero();
        menu_perfil = new VPerfil();
        menu_presidente = new VPresidente();
        menu_administrador = new VAdministrador();

        ly = (CardLayout) getContentPane().getLayout();
        llamable();
    }

    @Override
    protected final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    protected void construirComponentes() {
        Container panel = getContentPane();
        panel.add(menu_tesorero.getName(), menu_tesorero);
        panel.add(menu_perfil.getName(), menu_perfil);
    }

    @Override
    public void componentesEstadoInicial() {
    }

    public void showTesorero() {
        evtCambios(menu_bar, ly, menu_tesorero, ConstTitutlos.TL_PERF_TESORERO);
    }

    public void showPerfil() {
        evtCambios(menu_bar, ly, menu_perfil, ConstTitutlos.TL_PERF_PERFIL);
    }

    public void showPresidente() {
        evtCambios(menu_bar, ly, menu_presidente, ConstTitutlos.TL_PERF_PRESIDENTE);
    }

    public void showAdministrador() {
        evtCambios(menu_bar, ly, menu_administrador, ConstTitutlos.TL_PERF_ADMINISTRADOR);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_bar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new java.awt.CardLayout());

        menu_bar.setPreferredSize(new java.awt.Dimension(100, 30));
        setJMenuBar(menu_bar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar menu_bar;
    // End of variables declaration//GEN-END:variables
    private final CardLayout ly;
    private final VPerfil menu_perfil;
    private final VTesorero menu_tesorero;
    private final VPresidente menu_presidente;
    private final VAdministrador menu_administrador;

}
