/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.ventanas;

import com.jblue.vista.marco.contruccion.ConstTitutlos;
import com.jblue.vista.marco.ventanas.VentanaExtendida;
import com.jblue.vista.vistas.options.VContabilidad;
import com.jblue.vista.vistas.options.VPerfil;
import com.jblue.vista.vistas.options.VPersonal;
import java.awt.BorderLayout;
import javax.swing.JButton;

/**
 *
 * @author jp
 */
public class MenuCargos extends VentanaExtendida {

    /**
     * Creates new form MenuCargos
     */
    public MenuCargos() {
        super(ConstTitutlos.TL_PERFILES);
        view_perfil = new VPerfil();
        view_contabilidad = new VContabilidad();
        view_personal = new VPersonal();
        initComponents();
        llamable();
    }

    @Override
    protected final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    protected void construirComponentes() {
    }

    @Override
    public void componentesEstadoInicial() {
    }

    public int setMenu(String menu) {
        int r = 0;
        switch (menu) {
            case "Perfil" ->
                showPerfil();
            case "Presidente" ->
                showPresidente();
            case "Tesorero" ->
                showTesorero();
            case "Administrador" ->
                showAdministrador();
            default ->
                r = -1;
        }
        return r;
    }

    private void showTesorero() {
        clearMenu();
    }

    private void showPerfil() {
        clearMenu();
        perfil_options = (JButton[]) view_perfil.getOption().toArray(JButton[]::new);
        panel_central.add(view_perfil);
        for (JButton i : perfil_options) {
            panel_option.add(i);
        }
    }

    private void showPresidente() {
        clearMenu();
    }

    private void showAdministrador() {
        panel_central.add(view_personal);
    }

    private void clearMenu() {
        int componentCount = panel_central.getComponentCount();
        if (componentCount > 0) {
            panel_central.removeAll();
        }
        int componentCount2 = panel_option.getComponentCount();
        if (componentCount2 > 0) {
            panel_option.removeAll();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panel_option = new javax.swing.JPanel();
        name_user = new javax.swing.JLabel();
        panel_central = new javax.swing.JPanel();
        menu_bar = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/img2.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(250, 200));
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        panel_option.setPreferredSize(new java.awt.Dimension(250, 400));
        panel_option.setLayout(new java.awt.GridLayout(8, 1));
        jPanel1.add(panel_option, java.awt.BorderLayout.SOUTH);

        name_user.setPreferredSize(new java.awt.Dimension(41, 60));
        jPanel1.add(name_user, java.awt.BorderLayout.PAGE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        panel_central.setLayout(new java.awt.CardLayout());
        getContentPane().add(panel_central, java.awt.BorderLayout.CENTER);

        menu_bar.setPreferredSize(new java.awt.Dimension(100, 30));
        setJMenuBar(menu_bar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menu_bar;
    private javax.swing.JLabel name_user;
    private javax.swing.JPanel panel_central;
    private javax.swing.JPanel panel_option;
    // End of variables declaration//GEN-END:variables
    private VPerfil view_perfil;
    private VContabilidad view_contabilidad;
    private VPersonal view_personal;
    private BorderLayout ly;
    private JButton[] perfil_options;

}
