/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.views;

import com.jblue.modelo.constdb.Const;
import com.jblue.modelo.objetos.OEmployee;
import com.jblue.modelo.objetos.Objeto;
import com.jblue.util.Filters;
import com.jblue.util.Formats;
import com.jblue.util.crypto.EncriptadoAES;
import com.jblue.vista.marco.vistas.DBView;
import com.jutil.swingw.modelos.JTableModel;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import com.jblue.vista.marco.DBValuesModel;
import com.jblue.vista.marco.OptionMenuModel;

/**
 *
 * @author jp
 */
public class EmployeeView extends DBView implements OptionMenuModel, DBValuesModel {

    private final JTableModel model;
    private final CardLayout ly;
    private OEmployee object_search;
    private final JButton option;

    /**
     * Creates new form PersonalC
     *
     *
     */
    public EmployeeView() {
        initComponents();
        model = new JTableModel(Const.getEMPLOYEES().getFields(), 0);
        ly = (CardLayout) root_panel.getLayout();
        this.option = mkButton(getName(), null, null);

    }

    @Override
    public void initialState() {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        np_cp_center = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        np_cp_west = new javax.swing.JPanel();
        search_object = new javax.swing.JButton();
        np_cp_east = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        center_panel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        first_name = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        last_name = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        employee_type_field = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        status_type_field = new javax.swing.JComboBox<>();
        jPanel15 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        user_field = new javax.swing.JPasswordField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel20 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        password_field = new javax.swing.JPasswordField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel25 = new javax.swing.JPanel();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel35 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        options_panel = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        panel_tabla = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        search_field = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        reload_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(700, 600));
        setName("Personal"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(5, 5));

        np_cp_center.setLayout(new java.awt.GridLayout(1, 0, 5, 5));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        register_button.setText("Registar");
        register_button.setActionCommand("register_view");
        np_cp_center.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText("Consultar");
        search_button.setActionCommand("search_view");
        np_cp_center.add(search_button);

        north_panel.add(np_cp_center, java.awt.BorderLayout.CENTER);

        np_cp_west.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_west.setLayout(new java.awt.BorderLayout());

        search_object.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_object.setActionCommand("search_object");
        np_cp_west.add(search_object, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_west, java.awt.BorderLayout.WEST);

        np_cp_east.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_east.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        np_cp_east.add(jButton3, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_east, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);

        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        center_panel.setPreferredSize(new java.awt.Dimension(500, 600));
        center_panel.setLayout(new java.awt.GridLayout(13, 1, 0, 10));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Datos del personal");
        center_panel.add(jLabel11);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel16.setText("Nombre: ");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel6.add(jLabel16, java.awt.BorderLayout.LINE_START);

        first_name.setName("Nombre"); // NOI18N
        jPanel6.add(first_name, java.awt.BorderLayout.CENTER);

        center_panel.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel18.setText("Apellidos: ");
        jLabel18.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel7.add(jLabel18, java.awt.BorderLayout.LINE_START);

        last_name.setName("Apellidos"); // NOI18N
        jPanel7.add(last_name, java.awt.BorderLayout.CENTER);

        center_panel.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel19.setText("Cargo");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel8.add(jLabel19, java.awt.BorderLayout.LINE_START);

        employee_type_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECCIONE UNA OPCION", "PRESIDENTE", "SECRETARIO", "TESORERO", "PASANTE", "ADMINISTRADOR" }));
        employee_type_field.setName("Cargo"); // NOI18N
        jPanel8.add(employee_type_field, java.awt.BorderLayout.CENTER);

        center_panel.add(jPanel8);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel20.setText("Estado: ");
        jLabel20.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel14.add(jLabel20, java.awt.BorderLayout.LINE_START);

        status_type_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ACTIVO.", "INACTIVO.", "BAJA." }));
        status_type_field.setName("Estatus"); // NOI18N
        jPanel14.add(status_type_field, java.awt.BorderLayout.CENTER);

        center_panel.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel21.setText("Usuario: ");
        jLabel21.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel15.add(jLabel21, java.awt.BorderLayout.LINE_START);

        user_field.setName("Usuario"); // NOI18N
        jPanel15.add(user_field, java.awt.BorderLayout.CENTER);

        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jCheckBox1.setPreferredSize(new java.awt.Dimension(50, 20));
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jPanel15.add(jCheckBox1, java.awt.BorderLayout.LINE_END);

        center_panel.add(jPanel15);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel22.setText("Contraseña: ");
        jLabel22.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel20.add(jLabel22, java.awt.BorderLayout.LINE_START);

        password_field.setName("Contraseña"); // NOI18N
        jPanel20.add(password_field, java.awt.BorderLayout.CENTER);

        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jCheckBox2.setPreferredSize(new java.awt.Dimension(50, 20));
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jPanel20.add(jCheckBox2, java.awt.BorderLayout.LINE_END);

        center_panel.add(jPanel20);

        jPanel25.setLayout(new java.awt.BorderLayout());

        jCheckBox3.setText("jCheckBox3");
        jPanel25.add(jCheckBox3, java.awt.BorderLayout.CENTER);

        center_panel.add(jPanel25);

        jPanel35.setLayout(new java.awt.BorderLayout());

        jLabel24.setText("F. Limite: ");
        jLabel24.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel35.add(jLabel24, java.awt.BorderLayout.LINE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox3);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox4);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox5);

        jPanel35.add(jPanel1, java.awt.BorderLayout.CENTER);

        center_panel.add(jPanel35);

        register_panel.add(center_panel, java.awt.BorderLayout.CENTER);

        options_panel.setLayout(new java.awt.GridLayout(2, 0));

        jPanel13.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel13.setLayout(new java.awt.GridLayout(1, 3));

        save_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText("Guardar");
        save_button.setActionCommand("save");
        save_button.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel13.add(save_button);

        update_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/update_x32.png"))); // NOI18N
        update_button.setText("Actualizar");
        update_button.setActionCommand("update");
        update_button.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel13.add(update_button);

        delete_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setActionCommand("delete");
        delete_button.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel13.add(delete_button);

        options_panel.add(jPanel13);

        cancel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText("Cancelar");
        cancel_button.setActionCommand("cancel");
        cancel_button.setPreferredSize(new java.awt.Dimension(500, 40));
        options_panel.add(cancel_button);

        register_panel.add(options_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "register");

        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout(5, 5));

        panel_tabla.setPreferredSize(new java.awt.Dimension(1000, 500));
        panel_tabla.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel30.setMinimumSize(new java.awt.Dimension(980, 30));
        jPanel30.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel30.setLayout(new java.awt.BorderLayout(5, 5));

        search_field.setName("buscador"); // NOI18N
        jPanel30.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel23.setLayout(new java.awt.BorderLayout(5, 5));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        back_button.setActionCommand("back");
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(back_button, java.awt.BorderLayout.WEST);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand("next");
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(next_button, java.awt.BorderLayout.EAST);

        jPanel30.add(jPanel23, java.awt.BorderLayout.LINE_END);

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand("reload");
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel30.add(reload_button, java.awt.BorderLayout.LINE_START);

        panel_tabla.add(jPanel30, java.awt.BorderLayout.NORTH);

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        objects_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        objects_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(objects_table);

        panel_tabla.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_tabla, java.awt.BorderLayout.CENTER);

        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("No.");
        jPanel32.add(jLabel23, java.awt.BorderLayout.CENTER);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        count.setToolTipText("Numero de pagos hechos.");
        count.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range.setText("0 - 0");
        range.setToolTipText("");
        status_bar_panel.add(range, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total:");
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setToolTipText("Numero de pagos hechos.");
        total.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JPanel center_panel;
    private javax.swing.JLabel count;
    private javax.swing.JButton delete_button;
    private javax.swing.JComboBox<String> employee_type_field;
    private javax.swing.JTextField first_name;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField last_name;
    private javax.swing.JButton next_button;
    private javax.swing.JPanel north_panel;
    private javax.swing.JPanel np_cp_center;
    private javax.swing.JPanel np_cp_east;
    private javax.swing.JPanel np_cp_west;
    private javax.swing.JTable objects_table;
    private javax.swing.JPanel options_panel;
    private javax.swing.JPanel panel_tabla;
    private javax.swing.JPasswordField password_field;
    private javax.swing.JLabel range;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton reload_button;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JButton search_object;
    private javax.swing.JPanel search_panel;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JComboBox<String> status_type_field;
    private javax.swing.JLabel total;
    private javax.swing.JButton update_button;
    private javax.swing.JPasswordField user_field;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    @Override
    public String getTextSearchTable() {
        return Filters.clearText(search_field.getText());
    }

    @Override
    public JTable getTable() {
        return objects_table;
    }

    @Override
    public JTableModel getModel() {
        return model;
    }

    @Override
    public void setViewShow(int view_show) {
        this.view_show = view_show;
        String op = switch (view_show) {
            case 2:
                yield search_panel.getName();
            default:
                yield register_panel.getName();
        };
        ly.show(root_panel, op);
    }

    @Override
    public int getViewShow() {
        return view_show;
    }

    @Override
    public void setObjectSearch(Objeto o) {
        this.object_search = (OEmployee) o;
    }

    @Override
    public OEmployee getObjectSearch() {
        return object_search;
    }

    @Override
    public JButton getOption() {
        return option;
    }

    @Override
    public void setEvenOption(ActionListener e) {
        if (option.getActionListeners().length < 1) {
            option.addActionListener(e);
        }
    }

    @Override
    public void setRowsData(String... info) {
        count.setText(info[0]);
        range.setText(info[1]);
        total.setText(info[2]);
    }

    @Override
    public void setScreenTableInfo() {
    }

    @Override
    public boolean isValuesOk() {
        JTextField[] arr = {
            first_name, last_name, user_field, password_field
        };
        for (JTextField i : arr) {
            if (Filters.isNullOrBlank(i.getText())) {
                JOptionPane.showInternalMessageDialog(center_panel, "El campo: \"%s\" no es valido".formatted(i.getName()));
                return false;
            }
        }
        JComboBox[] arr2 = {
            employee_type_field, status_type_field
        };
        for (JComboBox i : arr2) {
            if (i.getSelectedIndex() > 0) {
                JOptionPane.showInternalMessageDialog(center_panel, "El campo: \"%s\" no es valido".formatted(i.getName()));
                return false;
            }
        }
        return true;
    }

    @Override
    public String[] getDbValues(boolean update) {
        String _first_name = first_name.getText();
        String _last_name = first_name.getText();
        String _user_type = String.valueOf(employee_type_field.getSelectedItem());
        String _status = String.valueOf(status_type_field.getSelectedItem());
        String[] credentials = credentials();
        String[] arr = new String[]{
            _first_name, _last_name, _user_type,
            _status, credentials[0], credentials[1]
        };
        return Formats.getDBFormatInputArray(arr);
    }

    private String[] credentials() {
        String _user = null;
        String _password = null;

        try {
            _user = EncriptadoAES.doEncrypt(String.valueOf(user_field.getPassword()),
                    String.valueOf(password_field.getPassword()));
            
            _password = EncriptadoAES.doEncrypt(String.valueOf(password_field.getPassword()),
                    String.valueOf(user_field.getPassword()));
            
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException
                | InvalidKeyException | NoSuchPaddingException
                | IllegalBlockSizeException | BadPaddingException ex) {
            Logger.getLogger(EmployeeView.class.getName()).log(Level.SEVERE, null, ex);
        }
        return new String[]{
            _user, _password
        };
    }

}
