/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.views;

import com.jblue.vista.marco.vistas.SimpleView;
import com.jutil.dbcon.connection.DBConnection;
import com.jutil.framework.LaunchApp;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanp
 */
public final class FlagsView extends SimpleView {

    private static FlagsView instance;

    public synchronized static FlagsView getInstance() {
        if (instance == null) {
            instance = new FlagsView();
        }
        return instance;
    }
    private final String[] parameters;

    /**
     * Creates new form FlagsView
     */
    private FlagsView() {
        initComponents();

        this.parameters = new String[]{
            open_hour_field.getName(),
            close_hour_field.getName(),
            last_pay_day_field.getName(),
            auto_pay_field.getName(),
            master_user_field.getName(),
            master_password_field.getName(),
            hour_validate_field.getName()
        };

    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void components() {
    }

    @Override
    public void events() {
        update_button.addActionListener((e) -> {
            String querys[] = {
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = '%s;",
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = '%s;",
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = '%s;",
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = %s;",
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = %s;",
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = %s;",
                "UPDATE parameters SET value = '%s', date_update=current_timestamp WHERE parameter = %s;"
            };
            String values[] = {
                String.valueOf(open_hour_field.getText()),
                String.valueOf(close_hour_field.getText()),
                String.valueOf(last_pay_day_field.getValue()),
                String.valueOf(auto_pay_field.isSelected()),
                String.valueOf(master_user_field.getText()),
                String.valueOf(master_password_field.getText()),
                String.valueOf(hour_validate_field.isSelected())
            };

            DBConnection connection = (DBConnection) LaunchApp.getInstance().getResources("connection");
            String mess = "Parametros Actualizados";
            int icon = JOptionPane.INFORMATION_MESSAGE;
            for (int i = 0; i < querys.length; i++) {
                try {
                    String query = querys[i];
                    connection.execute(query.formatted(parameters[i], values[i]));
                } catch (SQLException ex) {
                    mess = "Error al actualizar el parametro: %s".formatted(parameters[i]);
                    icon = JOptionPane.ERROR_MESSAGE;
                }
            }
            JOptionPane.showMessageDialog(this, mess, "Parametros", icon);
        });
    }

    @Override
    public void initialState() {
        DBConnection connection = (DBConnection) LaunchApp.getInstance().getResources("connection");
        String query = "SELECT value, data_type FROM parameters";
        try {
            ResultSet rs = connection.query(query);
            for (String i : parameters) {
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FlagsView.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        open_hour_field = new javax.swing.JFormattedTextField();
        close_hour_field = new javax.swing.JFormattedTextField();
        last_pay_day_field = new javax.swing.JSpinner();
        auto_pay_field = new javax.swing.JCheckBox();
        master_user_field = new javax.swing.JTextField();
        master_password_field = new javax.swing.JTextField();
        hour_validate_field = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        update_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jButton8.setText("jButton8");
        jButton8.setPreferredSize(new java.awt.Dimension(100, 30));
        north_panel.add(jButton8, java.awt.BorderLayout.WEST);

        jPanel3.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButton1.setText("Actualizar");
        jPanel3.add(jButton1);

        jButton2.setText("Consultar");
        jPanel3.add(jButton2);

        north_panel.add(jPanel3, java.awt.BorderLayout.CENTER);

        jButton9.setText("jButton9");
        jButton9.setPreferredSize(new java.awt.Dimension(100, 30));
        north_panel.add(jButton9, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.PAGE_START);

        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setLayout(new java.awt.BorderLayout());

        jPanel1.setMinimumSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new java.awt.GridLayout(15, 0));

        jLabel3.setText("HORA DE APERTURA");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel1.add(jLabel3);

        jLabel4.setText("HORA DE CIERRE");
        jPanel1.add(jLabel4);

        jLabel5.setText("DÍA DE COBRO");
        jPanel1.add(jLabel5);

        jLabel6.setText("COBRO AUTOMATICO");
        jPanel1.add(jLabel6);

        jLabel7.setText("USUARIO MAESTRO");
        jPanel1.add(jLabel7);

        jLabel8.setText("CONTRASEÑA MAESTRA");
        jPanel1.add(jLabel8);

        jLabel9.setText("VALIDAR HORA");
        jPanel1.add(jLabel9);

        register_panel.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout(15, 0));

        open_hour_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("kk:mm:ss"))));
        open_hour_field.setName("HORA_DE_APERTURA"); // NOI18N
        jPanel2.add(open_hour_field);

        close_hour_field.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("kk:mm:ss"))));
        close_hour_field.setName("HORA_DE_CIERRE"); // NOI18N
        jPanel2.add(close_hour_field);

        last_pay_day_field.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));
        last_pay_day_field.setName("ULTIMO_DIA_DE_PAGO"); // NOI18N
        jPanel2.add(last_pay_day_field);

        auto_pay_field.setToolTipText("");
        auto_pay_field.setName("RECARGO_AUTOMATICO"); // NOI18N
        jPanel2.add(auto_pay_field);

        master_user_field.setName("USUARIO_MAESTRO"); // NOI18N
        jPanel2.add(master_user_field);

        master_password_field.setName("CONTRASEÑA_MAESTRA"); // NOI18N
        jPanel2.add(master_password_field);

        hour_validate_field.setName("VALIDAR_HORA_DE_EXTRADA"); // NOI18N
        jPanel2.add(hour_validate_field);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        update_button.setText("Actualizar");
        jPanel4.add(update_button);

        cancel_button.setText("Cancelar");
        jPanel4.add(cancel_button);

        jPanel2.add(jPanel4);

        register_panel.add(jPanel2, java.awt.BorderLayout.CENTER);

        root_panel.add(register_panel, "card2");

        search_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel5.setPreferredSize(new java.awt.Dimension(880, 30));
        jPanel5.setLayout(new java.awt.BorderLayout(10, 10));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        jButton4.setPreferredSize(new java.awt.Dimension(100, 23));
        jPanel5.add(jButton4, java.awt.BorderLayout.LINE_START);

        jPanel6.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel6.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        jPanel6.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        jPanel6.add(jButton7);

        jPanel5.add(jPanel6, java.awt.BorderLayout.LINE_END);

        jTextField3.setText("jTextField3");
        jPanel5.add(jTextField3, java.awt.BorderLayout.CENTER);

        search_panel.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Variable", "Valor", "Descripcion"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        search_panel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        root_panel.add(search_panel, "card3");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox auto_pay_field;
    private javax.swing.JButton cancel_button;
    private javax.swing.JFormattedTextField close_hour_field;
    private javax.swing.JCheckBox hour_validate_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JSpinner last_pay_day_field;
    private javax.swing.JTextField master_password_field;
    private javax.swing.JTextField master_user_field;
    private javax.swing.JPanel north_panel;
    private javax.swing.JFormattedTextField open_hour_field;
    private javax.swing.JPanel register_panel;
    private javax.swing.JPanel root_panel;
    private javax.swing.JPanel search_panel;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

}
