/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.proviews;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import jsoftware.com.jblue.controllers.compc.ComboBoxController;
import jsoftware.com.jblue.model.dao.StreetDAO;
import jsoftware.com.jblue.model.dao.WaterIntakeTypeDAO;
import jsoftware.com.jblue.model.dto.EmployeeDTO;
import jsoftware.com.jblue.model.dto.ProcessWrapperDTO;
import jsoftware.com.jblue.model.dto.StreetDTO;
import jsoftware.com.jblue.model.dto.UserDTO;
import jsoftware.com.jblue.model.dto.UserDocumentDTO;
import jsoftware.com.jblue.model.dto.WaterIntakeTypeDTO;
import jsoftware.com.jblue.sys.SystemSession;
import jsoftware.com.jblue.sys.app.AppConfig;
import jsoftware.com.jblue.sys.app.AppFiles;
import jsoftware.com.jblue.util.Filters;
import jsoftware.com.jblue.util.Formats;
import jsoftware.com.jblue.util.Func;
import jsoftware.com.jblue.views.framework.AbstractProcessView;
import jsoftware.com.jblue.views.framework.DBObjectValues;
import jsoftware.com.jblue.views.framework.ProcessViewBuilder;
import jsoftware.com.jutil.util.FuncLogs;

/**
 *
 * @author juanp
 */
public final class UserRegisterView extends AbstractProcessView<UserDocumentDTO> implements DBObjectValues<UserDTO> {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form UserDataView
     */
    public UserRegisterView(ProcessViewBuilder builder) {
        super(builder);
        initComponents();
        build();
    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void components() {
        super.components(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void events() {
        StreetDAO street_dao = new StreetDAO(AppConfig.isDevMessages(), getProcessTypeName());
        WaterIntakeTypeDAO water_intake_dao = new WaterIntakeTypeDAO(AppConfig.isDevMessages(), getProcessTypeName());
        ComboBoxController<StreetDTO> street_1 = new ComboBoxController<>(street1_field, street_dao);
        ComboBoxController<StreetDTO> street_2 = new ComboBoxController<>(street2_field, street_dao);
        ComboBoxController<WaterIntakeTypeDTO> wki_type = new ComboBoxController<>(water_intakes_type_field, water_intake_dao);
        comboBoxInit(street_1, street1_field.getItemCount() <= 0);
        comboBoxInit(street_2, street2_field.getItemCount() <= 0);
        comboBoxInit(wki_type, water_intakes_type_field.getItemCount() <= 0);
    }

    public void comboBoxInit(ComboBoxController<?> c, boolean empty) {
        if (empty) {
            c.loadData();
        }
    }

    @Override
    public void initialState() {
        super.initialState(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void finalState() {
        super.finalState(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        register_panel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        user_data_panel = new javax.swing.JPanel();
        p_curp = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        curp_field = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        pc_nombre = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        first_name_field = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        pc_ap = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        last_name1_field = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        pc_am = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        last_name2_field = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        p_gender = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        gender_field = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        p_water_intake_type = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        water_intakes_type_field = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        p_street1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        street1_field = new javax.swing.JComboBox<>();
        jLabel29 = new javax.swing.JLabel();
        p_street2 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        street2_field = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        p_born_date = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        p_in_number = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        inside_number_field = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        p_out_number = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        outside_number_field = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        complement_data_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        phone_number1_field = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        phone_number2_field = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        add_photo_button = new javax.swing.JButton();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();

        setName("Form"); // NOI18N
        setLayout(new java.awt.CardLayout());

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setName("jTabbedPane1"); // NOI18N

        user_data_panel.setName("user_data_panel"); // NOI18N
        user_data_panel.setPreferredSize(new java.awt.Dimension(500, 600));
        user_data_panel.setLayout(new java.awt.GridLayout(15, 1, 0, 10));

        p_curp.setName("p_curp"); // NOI18N
        p_curp.setLayout(new java.awt.BorderLayout());

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/proviews/Bundle"); // NOI18N
        jLabel22.setText(bundle.getString("UserRegisterView.jLabel22.text")); // NOI18N
        jLabel22.setName("jLabel22"); // NOI18N
        jLabel22.setPreferredSize(new java.awt.Dimension(150, 25));
        p_curp.add(jLabel22, java.awt.BorderLayout.WEST);

        curp_field.setName("CURP"); // NOI18N
        p_curp.add(curp_field, java.awt.BorderLayout.CENTER);

        jLabel23.setName("jLabel23"); // NOI18N
        jLabel23.setPreferredSize(new java.awt.Dimension(60, 30));
        p_curp.add(jLabel23, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_curp);

        pc_nombre.setName("pc_nombre"); // NOI18N
        pc_nombre.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("UserRegisterView.jLabel2.text")); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(60, 20));
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 25));
        pc_nombre.add(jLabel2, java.awt.BorderLayout.WEST);

        first_name_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        first_name_field.setToolTipText(bundle.getString("UserRegisterView.first_name_field.toolTipText")); // NOI18N
        first_name_field.setName("Nombre"); // NOI18N
        first_name_field.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_nombre.add(first_name_field, java.awt.BorderLayout.CENTER);

        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_nombre.add(jLabel7, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(pc_nombre);

        pc_ap.setName("pc_ap"); // NOI18N
        pc_ap.setPreferredSize(new java.awt.Dimension(250, 30));
        pc_ap.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText(bundle.getString("UserRegisterView.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 25));
        pc_ap.add(jLabel3, java.awt.BorderLayout.WEST);

        last_name1_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        last_name1_field.setToolTipText(bundle.getString("UserRegisterView.last_name1_field.toolTipText")); // NOI18N
        last_name1_field.setName("A. Paterno"); // NOI18N
        last_name1_field.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_ap.add(last_name1_field, java.awt.BorderLayout.CENTER);

        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_ap.add(jLabel9, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(pc_ap);

        pc_am.setName("pc_am"); // NOI18N
        pc_am.setPreferredSize(new java.awt.Dimension(250, 30));
        pc_am.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setText(bundle.getString("UserRegisterView.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 25));
        pc_am.add(jLabel4, java.awt.BorderLayout.WEST);

        last_name2_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        last_name2_field.setToolTipText(bundle.getString("UserRegisterView.last_name2_field.toolTipText")); // NOI18N
        last_name2_field.setName("A. Materno"); // NOI18N
        last_name2_field.setPreferredSize(new java.awt.Dimension(100, 30));
        pc_am.add(last_name2_field, java.awt.BorderLayout.CENTER);

        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(60, 30));
        pc_am.add(jLabel10, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(pc_am);

        p_gender.setName("p_gender"); // NOI18N
        p_gender.setLayout(new java.awt.BorderLayout());

        jLabel25.setText(bundle.getString("UserRegisterView.jLabel25.text")); // NOI18N
        jLabel25.setName("jLabel25"); // NOI18N
        jLabel25.setPreferredSize(new java.awt.Dimension(150, 25));
        p_gender.add(jLabel25, java.awt.BorderLayout.LINE_START);

        gender_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No. Definido", "Masculino.", "Femenino." }));
        gender_field.setName("Genero"); // NOI18N
        p_gender.add(gender_field, java.awt.BorderLayout.CENTER);

        jLabel26.setName("jLabel26"); // NOI18N
        jLabel26.setPreferredSize(new java.awt.Dimension(60, 30));
        p_gender.add(jLabel26, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_gender);

        p_water_intake_type.setName("p_water_intake_type"); // NOI18N
        p_water_intake_type.setPreferredSize(new java.awt.Dimension(500, 50));
        p_water_intake_type.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText(bundle.getString("UserRegisterView.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 25));
        p_water_intake_type.add(jLabel5, java.awt.BorderLayout.WEST);

        water_intakes_type_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        water_intakes_type_field.setName("Tipo de toma"); // NOI18N
        water_intakes_type_field.setPreferredSize(new java.awt.Dimension(100, 30));
        p_water_intake_type.add(water_intakes_type_field, java.awt.BorderLayout.CENTER);

        jLabel28.setName("jLabel28"); // NOI18N
        jLabel28.setPreferredSize(new java.awt.Dimension(60, 30));
        p_water_intake_type.add(jLabel28, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_water_intake_type);

        p_street1.setName("p_street1"); // NOI18N
        p_street1.setPreferredSize(new java.awt.Dimension(500, 50));
        p_street1.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText(bundle.getString("UserRegisterView.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 25));
        p_street1.add(jLabel6, java.awt.BorderLayout.WEST);

        street1_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        street1_field.setName("Calle"); // NOI18N
        street1_field.setPreferredSize(new java.awt.Dimension(100, 30));
        p_street1.add(street1_field, java.awt.BorderLayout.CENTER);

        jLabel29.setName("jLabel29"); // NOI18N
        jLabel29.setPreferredSize(new java.awt.Dimension(60, 30));
        p_street1.add(jLabel29, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_street1);

        p_street2.setName("p_street2"); // NOI18N
        p_street2.setLayout(new java.awt.BorderLayout());

        jLabel20.setText(bundle.getString("UserRegisterView.jLabel20.text")); // NOI18N
        jLabel20.setName("jLabel20"); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(150, 25));
        p_street2.add(jLabel20, java.awt.BorderLayout.WEST);

        street2_field.setName("Calle 2"); // NOI18N
        p_street2.add(street2_field, java.awt.BorderLayout.CENTER);

        jLabel36.setName("jLabel36"); // NOI18N
        jLabel36.setPreferredSize(new java.awt.Dimension(60, 30));
        p_street2.add(jLabel36, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_street2);

        p_born_date.setName("p_born_date"); // NOI18N
        p_born_date.setLayout(new java.awt.BorderLayout());

        jLabel27.setText(bundle.getString("UserRegisterView.jLabel27.text")); // NOI18N
        jLabel27.setName("jLabel27"); // NOI18N
        jLabel27.setPreferredSize(new java.awt.Dimension(150, 25));
        p_born_date.add(jLabel27, java.awt.BorderLayout.WEST);

        jLabel38.setName("jLabel38"); // NOI18N
        jLabel38.setPreferredSize(new java.awt.Dimension(60, 30));
        p_born_date.add(jLabel38, java.awt.BorderLayout.LINE_END);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        jFormattedTextField1.setName("jFormattedTextField1"); // NOI18N
        p_born_date.add(jFormattedTextField1, java.awt.BorderLayout.CENTER);

        user_data_panel.add(p_born_date);

        p_in_number.setName("p_in_number"); // NOI18N
        p_in_number.setPreferredSize(new java.awt.Dimension(500, 50));
        p_in_number.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel1.setText(bundle.getString("UserRegisterView.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 25));
        p_in_number.add(jLabel1, java.awt.BorderLayout.WEST);

        inside_number_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        inside_number_field.setToolTipText(bundle.getString("UserRegisterView.inside_number_field.toolTipText")); // NOI18N
        inside_number_field.setName("Numero Interior"); // NOI18N
        inside_number_field.setPreferredSize(new java.awt.Dimension(100, 30));
        p_in_number.add(inside_number_field, java.awt.BorderLayout.CENTER);

        jLabel30.setName("jLabel30"); // NOI18N
        jLabel30.setPreferredSize(new java.awt.Dimension(60, 30));
        p_in_number.add(jLabel30, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_in_number);

        p_out_number.setName("p_out_number"); // NOI18N
        p_out_number.setLayout(new java.awt.BorderLayout());

        jLabel21.setText(bundle.getString("UserRegisterView.jLabel21.text")); // NOI18N
        jLabel21.setName("jLabel21"); // NOI18N
        jLabel21.setPreferredSize(new java.awt.Dimension(150, 25));
        p_out_number.add(jLabel21, java.awt.BorderLayout.WEST);

        outside_number_field.setName("Numero Exterior"); // NOI18N
        p_out_number.add(outside_number_field, java.awt.BorderLayout.CENTER);

        jLabel37.setName("jLabel37"); // NOI18N
        jLabel37.setPreferredSize(new java.awt.Dimension(60, 30));
        p_out_number.add(jLabel37, java.awt.BorderLayout.LINE_END);

        user_data_panel.add(p_out_number);

        jTabbedPane1.addTab(bundle.getString("UserRegisterView.user_data_panel.TabConstraints.tabTitle"), user_data_panel); // NOI18N

        complement_data_panel.setName("complement_data_panel"); // NOI18N
        complement_data_panel.setLayout(new java.awt.GridLayout(11, 1, 10, 10));

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel11.setText(bundle.getString("UserRegisterView.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel2.add(jLabel11, java.awt.BorderLayout.WEST);

        email_field.setName("Correo Electronico"); // NOI18N
        jPanel2.add(email_field, java.awt.BorderLayout.CENTER);

        jLabel32.setName("jLabel32"); // NOI18N
        jLabel32.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel2.add(jLabel32, java.awt.BorderLayout.LINE_END);

        complement_data_panel.add(jPanel2);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel14.setText(bundle.getString("UserRegisterView.jLabel14.text")); // NOI18N
        jLabel14.setName("jLabel14"); // NOI18N
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel3.add(jLabel14, java.awt.BorderLayout.WEST);

        phone_number1_field.setName("Telefono 1"); // NOI18N
        jPanel3.add(phone_number1_field, java.awt.BorderLayout.CENTER);

        jLabel34.setName("jLabel34"); // NOI18N
        jLabel34.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel3.add(jLabel34, java.awt.BorderLayout.LINE_END);

        complement_data_panel.add(jPanel3);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel19.setText(bundle.getString("UserRegisterView.jLabel19.text")); // NOI18N
        jLabel19.setName("jLabel19"); // NOI18N
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel4.add(jLabel19, java.awt.BorderLayout.WEST);

        phone_number2_field.setName("Telefono 2"); // NOI18N
        jPanel4.add(phone_number2_field, java.awt.BorderLayout.CENTER);

        jLabel35.setName("jLabel35"); // NOI18N
        jLabel35.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel4.add(jLabel35, java.awt.BorderLayout.LINE_END);

        complement_data_panel.add(jPanel4);

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        add_photo_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/agregar-archivo.png"))); // NOI18N
        add_photo_button.setText(bundle.getString("UserRegisterView.add_photo_button.text")); // NOI18N
        add_photo_button.setActionCommand(bundle.getString("UserRegisterView.add_photo_button.actionCommand")); // NOI18N
        add_photo_button.setName("add_photo_button"); // NOI18N
        jPanel1.add(add_photo_button, java.awt.BorderLayout.CENTER);

        jLabel39.setName("jLabel39"); // NOI18N
        jLabel39.setPreferredSize(new java.awt.Dimension(60, 30));
        jPanel1.add(jLabel39, java.awt.BorderLayout.LINE_END);

        jLabel40.setText(bundle.getString("UserRegisterView.jLabel40.text")); // NOI18N
        jLabel40.setName("jLabel40"); // NOI18N
        jLabel40.setPreferredSize(new java.awt.Dimension(100, 25));
        jPanel1.add(jLabel40, java.awt.BorderLayout.WEST);

        complement_data_panel.add(jPanel1);

        jTabbedPane1.addTab(bundle.getString("UserRegisterView.complement_data_panel.TabConstraints.tabTitle"), complement_data_panel); // NOI18N

        register_panel.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        add(register_panel, "register");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_photo_button;
    private javax.swing.JPanel complement_data_panel;
    private javax.swing.JTextField curp_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField first_name_field;
    private javax.swing.JComboBox<String> gender_field;
    private javax.swing.JTextField inside_number_field;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField last_name1_field;
    private javax.swing.JTextField last_name2_field;
    private javax.swing.JTextField outside_number_field;
    private javax.swing.JPanel p_born_date;
    private javax.swing.JPanel p_curp;
    private javax.swing.JPanel p_gender;
    private javax.swing.JPanel p_in_number;
    private javax.swing.JPanel p_out_number;
    private javax.swing.JPanel p_street1;
    private javax.swing.JPanel p_street2;
    private javax.swing.JPanel p_water_intake_type;
    private javax.swing.JPanel pc_am;
    private javax.swing.JPanel pc_ap;
    private javax.swing.JPanel pc_nombre;
    private javax.swing.JTextField phone_number1_field;
    private javax.swing.JTextField phone_number2_field;
    private javax.swing.JPanel register_panel;
    private javax.swing.JComboBox<StreetDTO> street1_field;
    private javax.swing.JComboBox<StreetDTO> street2_field;
    private javax.swing.JPanel user_data_panel;
    private javax.swing.JComboBox<WaterIntakeTypeDTO> water_intakes_type_field;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getDataView() {
        ProcessWrapperDTO pw = getProcessWrapper();
        if (pw == null) {
            EmployeeDTO emp = SystemSession.getInstancia().getCurrentEmployee();
            pw = new ProcessWrapperDTO(emp);
            setProcessWrapper(pw);
        }
        if (!isValuesOK()) {
            return;
        }
        UserDTO o = getValues(false);
        pw.setUser(o);
    }

    @Override
    public boolean isValuesOK() {
        boolean res = true; // Empezamos asumiendo que es válido
        String msg = "EL CAMPO %s NO ES VALIDO";
        String field_error = "";
        // --- Validar Textos ---
        JTextField[] field = {
            curp_field,
            first_name_field,
            last_name1_field,
            last_name2_field

        };
        for (JTextField i : field) {
            if (Filters.isNullOrBlank(i.getText())) {
                field_error = i.getName();
                res = false; // Marcamos como inválido
                break;
            }
        }
        // --- Validar Combos (solo si los textos pasaron) ---
        if (res) {
            JComboBox[] field2 = {
                gender_field,
                street1_field,
                water_intakes_type_field
            };
            for (JComboBox i : field2) {
                // Asumo que isValidComboBox devuelve FALSE si no hay selección válida
                if (!Filters.isValidComboBox(i)) {
                    field_error = i.getName();
                    res = false;
                    break;
                }
            }
        }
        // --- Respuesta al usuario ---
        if (!res) {
            JOptionPane.showMessageDialog(this, msg.formatted(field_error));
        }
        // Guardamos el estado real en el Wrapper
        getProcessWrapper().setUser_valid(res);
        return res;
    }

    @Override
    public UserDTO getValues(boolean update) {
        Map<String, Object> map = new HashMap<>();
        UserDTO dto = new UserDTO();
        try {
            // Obtenemos los valores actuales de los campos de texto
            String curp = Formats.geDBInputFormat(curp_field.getText());
            String firstName = Formats.geDBInputFormat(first_name_field.getText());
            String lastName1 = Formats.geDBInputFormat(last_name1_field.getText());
            String lastName2 = Formats.geDBInputFormat(last_name2_field.getText());
            String email = Formats.geDBInputFormat(email_field.getText());
            String number_phone1 = Formats.geDBInputFormat(phone_number1_field.getText());
            String number_phone2 = Formats.geDBInputFormat(phone_number2_field.getText());
            String gender = String.valueOf(gender_field.getSelectedIndex());
            String water_intake_type = water_intakes_type_field.getItemAt(water_intakes_type_field.getSelectedIndex()).getId();
            String street1 = street1_field.getItemAt(street1_field.getSelectedIndex()).getId();
            String street2 = street2_field.getItemAt(street2_field.getSelectedIndex()).getId();
            // --- LÓGICA PARA NUEVO REGISTRO ---
            Func.putIfPresentAndNotBlank(map, "curp", curp);
            Func.putIfPresentAndNotBlank(map, "first_name", firstName);
            Func.putIfPresentAndNotBlank(map, "last_name1", lastName1);
            Func.putIfPresentAndNotBlank(map, "last_name2", lastName2);
            Func.putIfNotNull(map, "gender", gender);
            Func.putIfNotNull(map, "water_intake_type", water_intake_type);
            Func.putIfNotNull(map, "street1", street1);
            if (Func.isNotNull(email)) {
                Func.putIfPresentAndNotBlank(map, "email", email);
            }
            if (Func.isNotNull(number_phone1)) {
                Func.putIfPresentAndNotBlank(map, "number_phone1", number_phone1);
            }
            if (Func.isNotNull(number_phone2)) {
                Func.putIfPresentAndNotBlank(map, "number_phone2", number_phone2);
            }
            if (Func.isNotNull(street2)) {
                Func.putIfNotNull(map, "street2", street2);
            }

        } catch (Exception e) {
            log(e, "getValues");
        }
        dto.setMap(map);
        return dto;
    }

    public String getUserType(String process) {
        return switch (process) {
            case "10":
                yield "1";
            case "11":
                yield "2";
            case "12":
                yield "3";
            default:
                yield "1";
        };
    }

    public void log(Exception e, String method_name) {
        try {
            FuncLogs.logError(AppFiles.DIR_PROG_LOG_TODAY, getClass(), e, getProcessTypeName(), method_name, e.getMessage());
        } catch (IOException ex) {
            ex.printStackTrace(System.err);
        }
    }

}
