/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.proviews;

import jsoftware.com.jblue.model.dto.UserDocumentDTO;
import jsoftware.com.jblue.views.framework.AbstractProcessView;
import jsoftware.com.jblue.views.framework.ProcessViewBuilder;

/**
 *
 * @author juanp
 */
public class WaterIntakeDataView extends AbstractProcessView<UserDocumentDTO> {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form WaterInatkeDataView
     */
    public WaterIntakeDataView(ProcessViewBuilder builder) {
        super(builder);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        p_fields = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        search_user_button = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search_water_intake = new javax.swing.JButton();
        water_intake_types_field = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        operation_cost_field = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        search_street_button = new javax.swing.JButton();
        street1_field = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        search_street2_button = new javax.swing.JButton();
        street2_field = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        location_field = new javax.swing.JTextField();
        p_status = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        status_field = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.CardLayout());

        p_fields.setName("p_fields"); // NOI18N
        p_fields.setPreferredSize(new java.awt.Dimension(500, 620));
        p_fields.setLayout(new java.awt.GridLayout(13, 0, 0, 10));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/proviews/Bundle"); // NOI18N
        jLabel4.setText(bundle.getString("WaterIntakeDataView.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 100));
        p_fields.add(jLabel4);

        jPanel12.setName("jPanel12"); // NOI18N
        jPanel12.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText(bundle.getString("WaterIntakeDataView.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel12.add(jLabel6, java.awt.BorderLayout.WEST);

        user_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        user_field.setName(""); // NOI18N
        jPanel12.add(user_field, java.awt.BorderLayout.CENTER);

        search_user_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_user_button.setToolTipText(bundle.getString("WaterIntakeDataView.search_user_button.toolTipText")); // NOI18N
        search_user_button.setActionCommand(bundle.getString("WaterIntakeDataView.search_user_button.actionCommand")); // NOI18N
        search_user_button.setName("search_user_button"); // NOI18N
        search_user_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel12.add(search_user_button, java.awt.BorderLayout.LINE_END);

        p_fields.add(jPanel12);

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText(bundle.getString("WaterIntakeDataView.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel8.add(jLabel2, java.awt.BorderLayout.WEST);

        search_water_intake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_water_intake.setToolTipText(bundle.getString("WaterIntakeDataView.search_water_intake.toolTipText")); // NOI18N
        search_water_intake.setActionCommand(bundle.getString("WaterIntakeDataView.search_water_intake.actionCommand")); // NOI18N
        search_water_intake.setName("search_water_intake"); // NOI18N
        search_water_intake.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(search_water_intake, java.awt.BorderLayout.LINE_END);

        water_intake_types_field.setName("water_intake_types_field"); // NOI18N
        jPanel8.add(water_intake_types_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel8);

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText(bundle.getString("WaterIntakeDataView.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel9.add(jLabel3, java.awt.BorderLayout.WEST);

        operation_cost_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        operation_cost_field.setName(""); // NOI18N
        jPanel9.add(operation_cost_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel9);

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText(bundle.getString("WaterIntakeDataView.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel10.add(jLabel5, java.awt.BorderLayout.WEST);

        search_street_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_street_button.setToolTipText(bundle.getString("WaterIntakeDataView.search_street_button.toolTipText")); // NOI18N
        search_street_button.setActionCommand(bundle.getString("WaterIntakeDataView.search_street_button.actionCommand")); // NOI18N
        search_street_button.setName("search_street_button"); // NOI18N
        search_street_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel10.add(search_street_button, java.awt.BorderLayout.LINE_END);

        street1_field.setName("street1_field"); // NOI18N
        jPanel10.add(street1_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel10);

        jPanel13.setName("jPanel13"); // NOI18N
        jPanel13.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel7.setText(bundle.getString("WaterIntakeDataView.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel13.add(jLabel7, java.awt.BorderLayout.WEST);

        search_street2_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_street2_button.setToolTipText(bundle.getString("WaterIntakeDataView.search_street2_button.toolTipText")); // NOI18N
        search_street2_button.setActionCommand(bundle.getString("WaterIntakeDataView.search_street2_button.actionCommand")); // NOI18N
        search_street2_button.setName("search_street2_button"); // NOI18N
        search_street2_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel13.add(search_street2_button, java.awt.BorderLayout.LINE_END);

        street2_field.setName("street2_field"); // NOI18N
        jPanel13.add(street2_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel13);

        jPanel14.setName("jPanel14"); // NOI18N
        jPanel14.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel8.setText(bundle.getString("WaterIntakeDataView.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel14.add(jLabel8, java.awt.BorderLayout.WEST);

        location_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        location_field.setName(""); // NOI18N
        jPanel14.add(location_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel14);

        p_status.setName("p_status"); // NOI18N
        p_status.setPreferredSize(new java.awt.Dimension(100, 35));
        p_status.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel9.setText(bundle.getString("WaterIntakeDataView.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 20));
        p_status.add(jLabel9, java.awt.BorderLayout.WEST);

        status_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Estado.", "Activo.", "Inactivo." }));
        status_field.setName(""); // NOI18N
        p_status.add(status_field, java.awt.BorderLayout.CENTER);

        p_fields.add(p_status);

        add(p_fields, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField location_field;
    private javax.swing.JTextField operation_cost_field;
    private javax.swing.JPanel p_fields;
    private javax.swing.JPanel p_status;
    private javax.swing.JButton search_street2_button;
    private javax.swing.JButton search_street_button;
    private javax.swing.JButton search_user_button;
    private javax.swing.JButton search_water_intake;
    private javax.swing.JComboBox<String> status_field;
    private javax.swing.JComboBox<jsoftware.com.jblue.model.dto.StreetDTO> street1_field;
    private javax.swing.JComboBox<jsoftware.com.jblue.model.dto.StreetDTO> street2_field;
    private javax.swing.JTextField user_field;
    private javax.swing.JComboBox<jsoftware.com.jblue.model.dto.WaterIntakesDTO> water_intake_types_field;
    // End of variables declaration//GEN-END:variables
    
    @Override
    public void getDataView() {
    
    }
}
