/*
 * Copyright (C) 2023 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views.components;

import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JFrame;

/**
 *
 * @author juan-campos
 */
public class ChooseFileComponent extends javax.swing.JDialog {

    private static ChooseFileComponent instancia;
    private static final long serialVersionUID = 1L;

    public static File seleccionarDocumento(JFrame padre) {
        initInstancia(padre);
        int in = instancia.jFileChooser1.showSaveDialog(padre);
        if (in != JFileChooser.APPROVE_OPTION) {
            return null;
        }
        return instancia.jFileChooser1.getSelectedFile();
    }

    public synchronized static void initInstancia(JFrame padre) {
        if (instancia == null) {
            instancia = new ChooseFileComponent(padre, true);
        }
    }

    /**
     * Creates new form CSelectorDeArchivos
     *
     * @param parent
     * @param modal
     */
    public ChooseFileComponent(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jFileChooser1.setDialogTitle("Seleccione archivo");
    }

    private JFileChooser getjFileChooser1() {
        return jFileChooser1;
    }

    public void doClose() {
        setVisible(false);
        dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setPreferredSize(new java.awt.Dimension(800, 500));
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
