/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas;

import com.jblue.util.FuncJBlue;
import com.jblue.vista.marco.vistas.VistaExtendida;
import javax.swing.JCheckBox;
import javax.swing.JComponent;

/**
 *
 * @author jp
 */
public class VConfiguraciones extends VistaExtendida {

    JComponent[] campos;

    /**
     * Creates new form VConfiguraciones
     */
    public VConfiguraciones() {
        initComponents();
        campos = new JComponent[]{
            jTextField1,
            jTextField2,
            jTextField3,
            jTextField4
        };
        llamable();
    }

    @Override
    protected final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        eventos();
    }
    
    

    @Override
    public void componentesEstadoInicial() {
        FuncJBlue.habilitarComponentes(false, campos);
    }

    @Override
    protected void eventos() {
        jCheckBox1.addItemListener(e -> evtHabilitarCampo((JCheckBox) e.getSource()));
        jCheckBox2.addItemListener(e -> evtHabilitarCampo((JCheckBox) e.getSource()));
        jCheckBox3.addItemListener(e -> evtHabilitarCampo((JCheckBox) e.getSource()));
        jCheckBox4.addItemListener(e -> evtHabilitarCampo((JCheckBox) e.getSource()));
    }

    public void evtHabilitarCampo(JCheckBox o) {
        if (o == jCheckBox1) {
            jTextField1.setEnabled(o.isSelected());
        } else if (o == jCheckBox2) {
            jTextField2.setEnabled(o.isSelected());
        } else if (o == jCheckBox3) {
            jTextField3.setEnabled(o.isSelected());
        } else if (o == jCheckBox4) {
            jTextField4.setEnabled(o.isSelected());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jCheckBox4 = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setName("Menu Conguraciones"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 660));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridLayout(10, 1));

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Usuario Maestro");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel2.add(jLabel1, java.awt.BorderLayout.LINE_START);
        jPanel2.add(jTextField1, java.awt.BorderLayout.CENTER);

        jCheckBox1.setText("Editar");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.add(jCheckBox1, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Contraseña Maestra");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel3.add(jLabel2, java.awt.BorderLayout.LINE_START);
        jPanel3.add(jTextField2, java.awt.BorderLayout.CENTER);

        jCheckBox2.setText("Editar");
        jCheckBox2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox2.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel3.add(jCheckBox2, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Hora de apertura.");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel3, java.awt.BorderLayout.LINE_START);
        jPanel4.add(jTextField3, java.awt.BorderLayout.CENTER);

        jCheckBox3.setText("Editar");
        jCheckBox3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.add(jCheckBox3, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Hora de cierre.");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel5.add(jTextField4, java.awt.BorderLayout.CENTER);

        jCheckBox4.setText("Editar");
        jCheckBox4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jCheckBox4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(jCheckBox4, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel5);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel6.setPreferredSize(new java.awt.Dimension(1000, 30));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jButton1.setText("Guardar");
        jPanel6.add(jButton1);

        jButton2.setText("Cancelar");
        jPanel6.add(jButton2);

        add(jPanel6, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
