/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.menus.cargos;

import com.jblue.vista.normas.SuperVentana;
import com.jblue.vista.ventanas.vistas.compartidos.VBitacora;
import com.jblue.vista.ventanas.vistas.presidente.VHistorial;
import com.jblue.vista.ventanas.vistas.presidente.VInicio;
import com.jblue.vista.ventanas.vistas.presidente.VInventario;
import java.awt.BorderLayout;
import java.awt.Desktop;
import javax.swing.JPanel;
import javax.swing.event.ChangeEvent;

/**
 *
 * @author jp
 */
public class MenuPresidente extends SuperVentana {

    private final JPanel[] vistas;

    /**
     * Creates new form MenuPresidente
     */
    public MenuPresidente() {
        _TITULO = 7;
        initComponents();
        vistas = new JPanel[4];
        vistas[0] = new VInicio(jtabRoot);
        vistas[1] = new VBitacora();
        vistas[2] = new VInventario();
        vistas[3] = new VHistorial();
        llamable();
    }

    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    protected void addComponentes() {
        for (int i = 0; i < vistas.length; i++) {
            JPanel panel = (JPanel) jtabRoot.getComponentAt(i);
            panel.add(vistas[i], BorderLayout.CENTER);
        }
        jtabRoot.addChangeListener((ChangeEvent e) -> Historial(e));
    }

    public void Historial(ChangeEvent e) {
        JPanel panel = (JPanel) jtabRoot.getComponentAt(3);
        VHistorial vista = (VHistorial) panel.getComponent(0);
        vista.setVisible(panel.isVisible());
    }

    @Override
    public void estadoInicial() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtabRoot = new javax.swing.JTabbedPane();
        panel_inicio = new javax.swing.JPanel();
        panel_bitacora = new javax.swing.JPanel();
        panel_inventario = new javax.swing.JPanel();
        panel_historial = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        panel_inicio.setLayout(new java.awt.BorderLayout());
        jtabRoot.addTab("Inicio", panel_inicio);

        panel_bitacora.setLayout(new java.awt.BorderLayout());
        jtabRoot.addTab("Bitacora", panel_bitacora);

        panel_inventario.setLayout(new java.awt.BorderLayout());
        jtabRoot.addTab("Inventario", panel_inventario);

        panel_historial.setName("Historial de movimientos"); // NOI18N
        panel_historial.setLayout(new java.awt.BorderLayout());
        jtabRoot.addTab("Historial de movimientos", panel_historial);
        panel_historial.getAccessibleContext().setAccessibleName("");

        getContentPane().add(jtabRoot, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane jtabRoot;
    private javax.swing.JPanel panel_bitacora;
    private javax.swing.JPanel panel_historial;
    private javax.swing.JPanel panel_inicio;
    private javax.swing.JPanel panel_inventario;
    // End of variables declaration//GEN-END:variables

}
