/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.menus.cargos;

import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.objetos.OPersonal;
import com.jblue.sistema.Sesion;
import com.jblue.util.cache.FabricaOpraciones;
import com.jblue.util.crypto.EncriptadoAES;
import com.jblue.vista.normas.SuperVentana;
import com.jutil.jexception.Excp;
import java.io.UnsupportedEncodingException;
import java.security.InvalidKeyException;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import javax.crypto.BadPaddingException;
import javax.crypto.IllegalBlockSizeException;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author jp
 */
public class MenuPerfil extends SuperVentana {

    private final Sesion sesion = Sesion.getInstancia();
    private final JTextField[] componnetes;
    private final EncriptadoAES encriptador = new EncriptadoAES();

    /**
     * Creates new form Perfil
     */
    public MenuPerfil() {
        _TITULO = 9;
        initComponents();
        this.componnetes = new JTextField[]{
            cargo, usuario, contraseña, registro, estado, permisos, periodo
        };
        llamable();
    }

    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    public void estadoInicial() {
        Sesion s = Sesion.getInstancia();
        OPersonal personal = s.getUsuario();
        nombre.setText(personal.getNombre());
        apellidos.setText(personal.getApellidos());
        String[] info = Arrays.copyOfRange(personal.getInfo(), 3, personal.getInfo().length);
        for (int i = 0; i < info.length; i++) {
            componnetes[i].setText(info[i]);
            componnetes[i].setEditable(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel11 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        nombre = new javax.swing.JLabel();
        apellidos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cargo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        usuario = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        contraseña = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        registro = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        estado = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        permisos = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        periodo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel11.setLayout(new java.awt.BorderLayout());

        jPanel12.setPreferredSize(new java.awt.Dimension(300, 700));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/usuario.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 400));
        jPanel12.add(jLabel3, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.GridLayout(6, 0));

        nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(nombre);

        apellidos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(apellidos);
        jPanel2.add(jLabel9);

        jButton2.setText("Cambiar Contraseña");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton4.setText("Agregar Foto");
        jButton4.setEnabled(false);
        jPanel2.add(jButton4);

        jPanel12.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel11.add(jPanel12, java.awt.BorderLayout.WEST);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacion de usuario"));
        jPanel1.setLayout(new java.awt.GridLayout(10, 0));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Cargo");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel3.add(jLabel1, java.awt.BorderLayout.LINE_START);
        jPanel3.add(cargo, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Usuario");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel4.add(jLabel2, java.awt.BorderLayout.LINE_START);
        jPanel4.add(usuario, java.awt.BorderLayout.CENTER);

        jPanel10.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel10, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Contraseña");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel5.add(jLabel4, java.awt.BorderLayout.LINE_START);
        jPanel5.add(contraseña, java.awt.BorderLayout.CENTER);

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jButton3.setPreferredSize(new java.awt.Dimension(50, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel13.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel13, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Registro");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel6.add(jLabel5, java.awt.BorderLayout.LINE_START);
        jPanel6.add(registro, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Estado");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel7.add(jLabel6, java.awt.BorderLayout.LINE_START);
        jPanel7.add(estado, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Permisos");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel8.add(jLabel7, java.awt.BorderLayout.LINE_START);
        jPanel8.add(permisos, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Periodo");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel9.add(jLabel8, java.awt.BorderLayout.LINE_START);
        jPanel9.add(periodo, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel9);

        jScrollPane1.setViewportView(jPanel1);

        jPanel11.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel11, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String contra = JOptionPane.showInputDialog("Contraseña");
        if (contra == null || contra.isBlank()) {
            return;
        }
        EncriptadoAES conf;
        String des = null;
        try {
            conf = new EncriptadoAES();
            OPersonal personal = sesion.getUsuario();
            des = conf.desencriptar(personal.getUsuario(), contra);
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
            JOptionPane.showMessageDialog(this, "Contraseña Incorrecta");
            Excp.impTerminal(ex, getClass(), false);
        }
        if (des == null) {
            return;
        }
        usuario.setText(des);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        OPersonal personal = sesion.getUsuario();
        String user = JOptionPane.showInputDialog("Usuario");
        if (user == null || user.isBlank()) {
            return;
        }
        try {
            String des = encriptador.desencriptar(personal.getContra(), user);
            contraseña.setText(des);
        } catch (UnsupportedEncodingException | NoSuchAlgorithmException | InvalidKeyException | NoSuchPaddingException | IllegalBlockSizeException | BadPaddingException ex) {
            JOptionPane.showMessageDialog(this, "Usuario Incorrecta");
            Excp.imp(ex, getClass(), true, false);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            String pass = JOptionPane.showInputDialog("Contraseña");
            if (!_valido(pass)) {
                return;
            }
            OPersonal p = sesion.getUsuario();
            String usu = encriptador.desencriptar(p.getUsuario(), pass);
            //String con = encriptador.desencriptar(p.getContra(), user);

            String new_pass = JOptionPane.showInputDialog("Nueva Contraseña");
            if (!_valido(new_pass)) {
                return;
            }
            String usu2 = encriptador.encriptar(usu, new_pass);
            String con2 = encriptador.encriptar(new_pass, usu);
            p.setUsuario(usu2);
            p.setContra(con2);
            usuario.setText(usu2);
            contraseña.setText(con2);
            //
            Operaciones<OPersonal> personal = FabricaOpraciones.PERSONAL;
            personal.actualizar("usuario", usu2, "id = " + p.getId());
            personal.actualizar("contra", con2, "id = " + p.getId());
            JOptionPane.showMessageDialog(this, "¡Operacion exitosa!");
        } catch (UnsupportedEncodingException
                | NoSuchAlgorithmException
                | InvalidKeyException
                | NoSuchPaddingException
                | IllegalBlockSizeException
                | BadPaddingException ex) {
            JOptionPane.showMessageDialog(this, "Datos No Validos");
            Excp.impTerminal(ex, getClass(), true);
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    boolean _valido(String txt) {
        return txt != null && !txt.isBlank();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel apellidos;
    private javax.swing.JTextField cargo;
    private javax.swing.JTextField contraseña;
    private javax.swing.JTextField estado;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nombre;
    private javax.swing.JTextField periodo;
    private javax.swing.JTextField permisos;
    private javax.swing.JTextField registro;
    private javax.swing.JTextField usuario;
    // End of variables declaration//GEN-END:variables
}
