/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.mod.com;

import javax.swing.JOptionPane;
import jsoftware.com.jblue.controllers.compc.ComboBoxController;
import jsoftware.com.jblue.model.dao.StreetDAO;
import jsoftware.com.jblue.model.dto.EmployeeDTO;
import jsoftware.com.jblue.model.dto.StreetDTO;
import jsoftware.com.jblue.model.dto.wrp.EmployeeRegisterWrapperDTO;
import jsoftware.com.jblue.model.models.AbstractValidation;
import jsoftware.com.jblue.sys.app.AppConfig;
import jsoftware.com.jblue.util.Formats;
import jsoftware.com.jblue.util.Func;
import jsoftware.com.jblue.util.GraphicsUtils;
import jsoftware.com.jblue.views.framework.AbstractModuleView;
import jsoftware.com.jblue.views.framework.DBObjectValues;

/**
 * Clase dedicada a la captura de datos del empleado
 *
 * @author Juan Pablo Campos Casasanero
 */
public final class EmployeeRegistrationView extends AbstractModuleView<EmployeeRegisterWrapperDTO> implements DBObjectValues<EmployeeDTO> {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form EmployeeView
     */
    public EmployeeRegistrationView(EmployeeRegisterWrapperDTO builder) {
        super(builder);
        initComponents();
        build();
    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void events() {
        StreetDAO street_dao = new StreetDAO(AppConfig.isDevMessages(), getDtoWrapper().getModule_name());
        ComboBoxController<StreetDTO> street_1 = new ComboBoxController(street1_field, street_dao);
        ComboBoxController<StreetDTO> street_2 = new ComboBoxController(street2_field, street_dao);
        comboBoxInit(street_1, street1_field.getItemCount() <= 0);
        comboBoxInit(street_2, street2_field.getItemCount() <= 0);
    }

    public void comboBoxInit(ComboBoxController<?> c, boolean empty) {
        if (empty) {
            c.loadData();
        }
    }

    @Override
    public void components() {
    }

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        curp_field = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        first_name_field = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        last_name1_field = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        last_name2_field = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        gender_field = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        birthdate_field = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        email_field = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        phone_number_field = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        street1_field = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        street2_field = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        inside_number_field = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        outside_number_field = new javax.swing.JTextField();

        setName("DATOS DE EMPLEADO"); // NOI18N
        setLayout(new java.awt.CardLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/mod/com/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("EmployeeRegistrationView.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(15, 0));

        jPanel14.setName("jPanel14"); // NOI18N
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel13.setText(bundle.getString("EmployeeRegistrationView.jLabel13.text")); // NOI18N
        jLabel13.setName("jLabel13"); // NOI18N
        jLabel13.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel14.add(jLabel13, java.awt.BorderLayout.WEST);

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/mod/Bundle"); // NOI18N
        curp_field.setText(bundle1.getString("EmployeeView.CURP.text")); // NOI18N
        curp_field.setName("CURP"); // NOI18N
        jPanel14.add(curp_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel14);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText(bundle.getString("EmployeeRegistrationView.jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel3.add(jLabel2, java.awt.BorderLayout.WEST);

        first_name_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        first_name_field.setName("NOMBRE"); // NOI18N
        jPanel3.add(first_name_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3);

        jPanel4.setName("jPanel4"); // NOI18N
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel3.setText(bundle.getString("EmployeeRegistrationView.jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel4.add(jLabel3, java.awt.BorderLayout.WEST);

        last_name1_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        last_name1_field.setName("APELLIDO PATERNO"); // NOI18N
        jPanel4.add(last_name1_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4);

        jPanel5.setName("jPanel5"); // NOI18N
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel4.setText(bundle.getString("EmployeeRegistrationView.jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel4, java.awt.BorderLayout.WEST);

        last_name2_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        last_name2_field.setName("APELLIDO MATERNO"); // NOI18N
        jPanel5.add(last_name2_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel5);

        jPanel6.setName("jPanel6"); // NOI18N
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel5.setText(bundle.getString("EmployeeRegistrationView.jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel6.add(jLabel5, java.awt.BorderLayout.WEST);

        gender_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No. Definido", "Masculino.", "Femenino." }));
        gender_field.setName("GENERO"); // NOI18N
        jPanel6.add(gender_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel6);

        jPanel7.setName("jPanel7"); // NOI18N
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setText(bundle.getString("EmployeeRegistrationView.jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel7.add(jLabel6, java.awt.BorderLayout.WEST);

        birthdate_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        birthdate_field.setName("FECHA DE NACIMIENTO"); // NOI18N
        jPanel7.add(birthdate_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setName("jPanel8"); // NOI18N
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel7.setText(bundle.getString("EmployeeRegistrationView.jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.add(jLabel7, java.awt.BorderLayout.WEST);

        email_field.setText(bundle1.getString("EmployeeView.CORREO ELECTRONICO.text")); // NOI18N
        email_field.setName("CORREO ELECTRONICO"); // NOI18N
        jPanel8.add(email_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setName("jPanel9"); // NOI18N
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setText(bundle.getString("EmployeeRegistrationView.jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel9.add(jLabel8, java.awt.BorderLayout.WEST);

        phone_number_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        phone_number_field.setName("TELEFONO"); // NOI18N
        jPanel9.add(phone_number_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setName("jPanel10"); // NOI18N
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel9.setText(bundle.getString("EmployeeRegistrationView.jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel10.add(jLabel9, java.awt.BorderLayout.WEST);

        street1_field.setName("CALLE 1"); // NOI18N
        jPanel10.add(street1_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setName("jPanel11"); // NOI18N
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel10.setText(bundle.getString("EmployeeRegistrationView.jLabel10.text")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel11.add(jLabel10, java.awt.BorderLayout.WEST);

        street2_field.setName("CALLE 2"); // NOI18N
        jPanel11.add(street2_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        jPanel12.setName("jPanel12"); // NOI18N
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel11.setText(bundle.getString("EmployeeRegistrationView.jLabel11.text")); // NOI18N
        jLabel11.setName("jLabel11"); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel12.add(jLabel11, java.awt.BorderLayout.WEST);

        inside_number_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        inside_number_field.setName("NUMERO INTERIOR"); // NOI18N
        jPanel12.add(inside_number_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jPanel13.setName("jPanel13"); // NOI18N
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel12.setText(bundle.getString("EmployeeRegistrationView.jLabel12.text")); // NOI18N
        jLabel12.setName("jLabel12"); // NOI18N
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel13.add(jLabel12, java.awt.BorderLayout.WEST);

        outside_number_field.setText(bundle1.getString("EmployeeView.jTextField6.text")); // NOI18N
        outside_number_field.setName("NUMERO EXTERIOR"); // NOI18N
        jPanel13.add(outside_number_field, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel13);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField birthdate_field;
    private javax.swing.JTextField curp_field;
    private javax.swing.JTextField email_field;
    private javax.swing.JTextField first_name_field;
    private javax.swing.JComboBox<String> gender_field;
    private javax.swing.JTextField inside_number_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField last_name1_field;
    private javax.swing.JTextField last_name2_field;
    private javax.swing.JTextField outside_number_field;
    private javax.swing.JTextField phone_number_field;
    private javax.swing.JComboBox<String> street1_field;
    private javax.swing.JComboBox<String> street2_field;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean isValuesOK() {
        boolean res;
        AbstractValidation v = new AbstractValidation();
        v.addRuler("curp", curp_field, t -> Func.isNotNull(t) && Func.isNotNullEmptyBlank(t.getText()));
        v.addErrorMessage("curp", "LA CURP NO TIENE EL FORMATO INCORRECTO");

        v.addRuler("first_name", first_name_field, t -> Func.isNotNull(t) && Func.isNotNullEmptyBlank(t.getText()) && Func.isOnlyText(t.getText()));
        v.addErrorMessage("first_name", "EL NOMBRE DEBE SER SOLO TEXTO");

        v.addRuler("last_name1", last_name1_field, t -> Func.isNotNull(t) && Func.isNotNullEmptyBlank(t.getText()) && Func.isOnlyText(t.getText()));
        v.addErrorMessage("last_name1", "EL APELLIDO PATERNO DEBE SER SOLO TEXTO");

        v.addRuler("last_name2", last_name2_field, t -> Func.isNotNull(t) && Func.isNotNullEmptyBlank(t.getText()) && Func.isOnlyText(t.getText()));
        v.addErrorMessage("last_name2", "EL APELLIDO MATERNO DEBE SER SOLO TEXTO");

//        v.addRuler("gender", gender_field, t -> Func.isNotNull(t) && GraphicsUtils.isComboBoxOk(gender_field));
//        v.addErrorMessage("gender", "EL GENERO ES OBLIGATORIO");
        v.addRuler("street1", street1_field, t -> Func.isNotNull(t) && GraphicsUtils.isComboBoxOk(t));
        v.addErrorMessage("street1", "LA CALLE 1 NO ES UNA CALLE VALIDA");
        if (AppConfig.getParameterBoolean("CAMPOS_SECUNDARIOS_OBLIGATORIOS")) {
            v.addRuler("phone_number", phone_number_field, t -> Func.isNotNull(t) && Func.isInteger(t.getText()));
            v.addErrorMessage("phone_number", "EL NUMERO TELEFONICO NO TIENE EL FORMATO CORRECTO");
            v.addRuler("email", email_field, t -> Func.isNotNull(t) && Func.isValidEmail(t.getText()));
            v.addErrorMessage("email", "EL NUMERO TELEFONICO NO TIENE EL FORMATO CORRECTO");
        }
        res = v.isValid();
        if (!res) {
            JOptionPane.showMessageDialog(this, v.getErrorMessage());
        }
        res = v.isValid();
        if (!res) {
            JOptionPane.showMessageDialog(this, v.getErrorMessage(), "CAMPOS NO VALIDOS", JOptionPane.ERROR_MESSAGE);
        }
        return res;
    }

    @Override
    public EmployeeDTO getValues(boolean update) {
        EmployeeDTO dto = new EmployeeDTO();
        Func.putIfNotNull(dto.getMap(), "curp", Formats.getTextFormat(curp_field.getText()));
        Func.putIfNotNull(dto.getMap(), "first_name", Formats.getTextFormat(first_name_field.getText()));
        Func.putIfNotNull(dto.getMap(), "last_name1", Formats.getTextFormat(last_name1_field.getText()));
        Func.putIfNotNull(dto.getMap(), "last_name2", Formats.getTextFormat(last_name2_field.getText()));
        Func.putIfNotNull(dto.getMap(), "gender", gender_field.getSelectedIndex());
        Func.putIfNotNull(dto.getMap(), "birthdate", birthdate_field.getText());
        Func.put(dto.getMap(), "personal_email", email_field.getText());
        Func.put(dto.getMap(), "personal_phone", phone_number_field.getText());
        Func.putIfNotNull(dto.getMap(), "street1", street1_field.getSelectedIndex());
        String s2 = street2_field.getSelectedIndex() <= 0 ? null : String.valueOf(street2_field.getSelectedIndex());
        Func.put(dto.getMap(), "street2", s2);
        Func.put(dto.getMap(), "inside_number", Formats.getTextFormat(inside_number_field.getText()));
        Func.put(dto.getMap(), "outside_number", Formats.getTextFormat(outside_number_field.getText()));
        return dto;
    }

    @Override
    public void getData() {
        boolean res = isValuesOK();
        getValues(false);
        getDtoWrapper().setEmployee_valid(true);
    }

}
