/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views.process;

import java.awt.CardLayout;
import jsoftware.com.jblue.model.dto.UserDTO;
import jsoftware.com.jblue.views.framework.AbstractProcessView;
import jsoftware.com.jblue.views.framework.ProcessViewBuilder;
import jsoftware.com.jblue.views.proviews.PaymentProcessView;
import jsoftware.com.jblue.views.proviews.UserDataView;
import jsoftware.com.jblue.views.proviews.ValidationProcessView;
import jsoftware.com.jblue.views.proviews.WaterIntakeDataView;

/**
 *
 * @author juanp
 */
public final class OwnerRegisterProcessView extends AbstractProcessView<UserDTO> {

    private static final long serialVersionUID = 1L;

    private final UserDataView user_view;
    private final ValidationProcessView validation_process_view;
    private final PaymentProcessView payment_concepts_view;
    private final WaterIntakeDataView water_intake_view;
    private CardLayout ly;

    /**
     * Creates new form ProcessView
     */
    public OwnerRegisterProcessView(ProcessViewBuilder builder) {
        super(builder);
        this.user_view = new UserDataView(builder);
        this.validation_process_view = new ValidationProcessView(builder);
        this.payment_concepts_view = new PaymentProcessView(builder);
        this.water_intake_view = new WaterIntakeDataView(builder);
        initComponents();
        build();
    }

    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    @Override
    public void events() {
        next_panel_button.addActionListener((e) -> {
            ly.next(root_panel);
        });
        last_panel_button.addActionListener((e) -> {
            ly.previous(root_panel);
        });

    }

    @Override
    public void components() {
        this.ly = (CardLayout) root_panel.getLayout();
        this.root_panel.add(user_view, user_view.getName());
        this.root_panel.add(validation_process_view, validation_process_view.getName());
        this.root_panel.add(payment_concepts_view, payment_concepts_view.getName());
        this.root_panel.add(water_intake_view, water_intake_view.getName());
    }

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        np_cp_center = new javax.swing.JPanel();
        last_panel_button = new javax.swing.JButton();
        next_panel_button = new javax.swing.JButton();
        np_cp_west = new javax.swing.JPanel();
        search_object = new javax.swing.JButton();
        np_cp_east = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();

        setName("Registro de titular"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 300));
        setLayout(new java.awt.BorderLayout());

        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        np_cp_center.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        last_panel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        last_panel_button.setText("Regresar");
        last_panel_button.setToolTipText("Seccion Anterior");
        last_panel_button.setActionCommand("register_view");
        np_cp_center.add(last_panel_button);

        next_panel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        next_panel_button.setText("Siguiente");
        next_panel_button.setToolTipText("Siguiente Seccion");
        next_panel_button.setActionCommand("search_view");
        np_cp_center.add(next_panel_button);

        north_panel.add(np_cp_center, java.awt.BorderLayout.CENTER);

        np_cp_west.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_west.setLayout(new java.awt.BorderLayout());

        search_object.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/cruz.png"))); // NOI18N
        search_object.setToolTipText("Cancelar Tramite");
        search_object.setActionCommand("search_object");
        np_cp_west.add(search_object, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_west, java.awt.BorderLayout.WEST);

        np_cp_east.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_east.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton3.setToolTipText("Guardar Informacion Actual");
        np_cp_east.add(jButton3, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_east, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);

        root_panel.setLayout(new java.awt.CardLayout());
        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton last_panel_button;
    private javax.swing.JButton next_panel_button;
    private javax.swing.JPanel north_panel;
    private javax.swing.JPanel np_cp_center;
    private javax.swing.JPanel np_cp_east;
    private javax.swing.JPanel np_cp_west;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton search_object;
    // End of variables declaration//GEN-END:variables

    @Override
    public void getDataView() {

    }
}
