/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.bd;

import com.jblue.modelo.ConstBD;
import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.objetos.OCalles;
import com.jblue.util.FormatoBD;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.MemoCache;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jp
 */
public class MenuCalles extends javax.swing.JFrame {

    private OCalles calle_buscada;
    private final ArrayList<OCalles> lista_auxiliar;
    private final MemoCache<OCalles> memoria_cache;
    private final ArrayList<OCalles> cache;
    private final Operaciones<OCalles> operaciones;
    private boolean buscando;
    //
    private final DefaultTableModel modelo;

    /**
     * Creates new form MenuCalles
     */
    public MenuCalles() {
        buscando = false;
        lista_auxiliar = new ArrayList<>();
        memoria_cache = FabricaCache.MC_CALLES;
        operaciones = FabricaCache.OP_CALLES;
        cache = memoria_cache.getLista();
        //
        initComponents();
        modelo = (DefaultTableModel) jtCalles.getModel();
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowActivated(WindowEvent e) {
                if (isVisible()) {
                    actualizarTabla();
                }
            }

            @Override
            public void windowClosing(WindowEvent e) {
                vaciarTabla();
            }

        });

        jtfCalleNombre.requestFocus();

        init();
    }

    private void init() {
        calle_buscada = null;
        lista_auxiliar.clear();
        jtfCallesBuscar.setText(null);
        jtfCalleNombre.setText(null);
        jtfCalleNumero.setText(null);
        botonesPrimarios();

    }

    public void botonesPrimarios() {
        jbtCalleGuardar.setEnabled(true);
        jbtCalleActualizar.setEnabled(false);
        jbtCalleEliminar.setEnabled(false);
        jbtCalleCancelar.setEnabled(true);
    }

    public void botonesSecundarios() {
        jbtCalleGuardar.setEnabled(false);
        jbtCalleActualizar.setEnabled(true);
        jbtCalleEliminar.setEnabled(true);
        jbtCalleCancelar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCalles = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtCalles = new javax.swing.JTable();
        jPanel14 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtfCalleNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jbtCalleGuardar = new javax.swing.JButton();
        jbtCalleActualizar = new javax.swing.JButton();
        jbtCalleEliminar = new javax.swing.JButton();
        jbtCalleCancelar = new javax.swing.JButton();
        jtfCalleNumero = new javax.swing.JTextField();
        jtfCallesBuscar = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpCalles.setPreferredSize(new java.awt.Dimension(1000, 600));

        jtCalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "NUMERO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtCalles.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jtCalles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtCalles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtCalles.getTableHeader().setReorderingAllowed(false);
        jtCalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtCallesMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(jtCalles);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la calle"));
        jPanel14.setOpaque(false);

        jLabel1.setText("Nombre");

        jtfCalleNombre.setFocusCycleRoot(true);
        jtfCalleNombre.setPreferredSize(new java.awt.Dimension(23, 40));

        jLabel2.setText("Numero");

        jbtCalleGuardar.setText("Guardar");
        jbtCalleGuardar.setPreferredSize(new java.awt.Dimension(70, 40));
        jbtCalleGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalleGuardarActionPerformed(evt);
            }
        });

        jbtCalleActualizar.setText("Actualizar");
        jbtCalleActualizar.setPreferredSize(new java.awt.Dimension(70, 40));
        jbtCalleActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalleActualizarActionPerformed(evt);
            }
        });

        jbtCalleEliminar.setText("Eliminar");
        jbtCalleEliminar.setPreferredSize(new java.awt.Dimension(70, 40));
        jbtCalleEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalleEliminarActionPerformed(evt);
            }
        });

        jbtCalleCancelar.setText("Cancelar");
        jbtCalleCancelar.setPreferredSize(new java.awt.Dimension(70, 40));
        jbtCalleCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCalleCancelarActionPerformed(evt);
            }
        });

        jtfCalleNumero.setPreferredSize(new java.awt.Dimension(23, 40));

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCalleNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCalleGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
                    .addComponent(jbtCalleActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCalleEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtCalleCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfCalleNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCalleNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfCalleNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtCalleGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalleActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalleEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbtCalleCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jtfCallesBuscar.setPreferredSize(new java.awt.Dimension(85, 35));
        jtfCallesBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCallesBuscarKeyReleased(evt);
            }
        });

        jLabel17.setText("Nombre");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jpCallesLayout = new javax.swing.GroupLayout(jpCalles);
        jpCalles.setLayout(jpCallesLayout);
        jpCallesLayout.setHorizontalGroup(
            jpCallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCallesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                    .addGroup(jpCallesLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfCallesBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpCallesLayout.setVerticalGroup(
            jpCallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCallesLayout.createSequentialGroup()
                .addGroup(jpCallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCallesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpCallesLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jpCallesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCallesBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 549, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1027, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpCalles, javax.swing.GroupLayout.DEFAULT_SIZE, 1027, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jpCalles, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCallesBuscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCallesBuscarKeyReleased
        buscando = true;
        vaciarTabla();
        lista_auxiliar.clear();
        String texto_buscado = jtfCallesBuscar.getText();
        texto_buscado = limpiar(texto_buscado);
        if (texto_buscado == null || texto_buscado.isEmpty()) {
            lista_auxiliar.addAll(cache);
            lista_auxiliar.forEach((t) -> {
                modelo.addRow(t.getInfo());
            });
            return;
        }
        for (OCalles oCalles : cache) {
            String calle = limpiar(oCalles.getCalleStr());
            if (calle.contains(texto_buscado)) {
                modelo.addRow(FormatoBD.bdSalida(oCalles.getInfo()));
                lista_auxiliar.add(oCalles);
            }
        }

    }//GEN-LAST:event_jtfCallesBuscarKeyReleased

    private void jtCallesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtCallesMouseClicked

        int clicks = evt.getClickCount();
        ArrayList<OCalles> lista_aux;

        if (buscando) {
            lista_aux = lista_auxiliar;
        } else {
            lista_aux = cache;
        }

        switch (clicks) {
            case 1:
                calle_buscada = lista_aux.get(jtCalles.getSelectedRow());
                jtfCallesBuscar.setText(calle_buscada.getCalleStr());
                break;
            case 2:
                calle_buscada = lista_aux.get(jtCalles.getSelectedRow());
                //
                jtfCalleNombre.setText(calle_buscada.getNombre());
                jtfCalleNumero.setText(calle_buscada.getNumero());
                //
                jtCalles.clearSelection();
                jtfCallesBuscar.setText(null);
                //
                actualizarTabla();
                //
                botonesSecundarios();
                //
                if (buscando) {
                    buscando = false;
                }
                break;
        }

    }//GEN-LAST:event_jtCallesMouseClicked

    private void jbtCalleGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalleGuardarActionPerformed
        if (!camposValidos()) {
            JOptionPane.showMessageDialog(jpCalles, "Error al guardar");
            init();
            return;
        }
        String[] arr = {
            jtfCalleNombre.getText(),
            jtfCalleNumero.getText()
        };
        arr = FormatoBD.bdEntrada(arr);
        operaciones.insertar(arr);
        memoria_cache.actualizar();
        actualizarTabla();
        init();
    }//GEN-LAST:event_jbtCalleGuardarActionPerformed

    private void jbtCalleActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalleActualizarActionPerformed
        if (!camposValidos()) {
            JOptionPane.showMessageDialog(jpCalles, "Error al actualizar");
            init();
            return;
        }
        String[] arr = {
            jtfCalleNombre.getText(),
            jtfCalleNumero.getText()
        };
        arr = FormatoBD.bdEntrada(arr);
        String[] ca = Arrays.copyOfRange(ConstBD.BD_CALLES, 1, ConstBD.BD_CALLES.length);
        operaciones.actualizar(ca, arr, "id = " + calle_buscada.getId());
        memoria_cache.actualizar();
        actualizarTabla();
        init();
    }//GEN-LAST:event_jbtCalleActualizarActionPerformed

    private void jbtCalleEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalleEliminarActionPerformed
        if (calle_buscada == null) {
            JOptionPane.showMessageDialog(this, "Error de operacion", "Inserccion de elemento", JOptionPane.ERROR_MESSAGE);
            return;
        }
        operaciones.eliminar("id = " + calle_buscada.getId());
        memoria_cache.actualizar();
        actualizarTabla();
        init();
    }//GEN-LAST:event_jbtCalleEliminarActionPerformed

    private void jbtCalleCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCalleCancelarActionPerformed
        int o = JOptionPane.showConfirmDialog(this, "¿Seguro que desea cancelar esta operacion?", "Cancelar", JOptionPane.YES_OPTION, JOptionPane.WARNING_MESSAGE);
        if (o == JOptionPane.OK_OPTION) {
            init();
        }
    }//GEN-LAST:event_jbtCalleCancelarActionPerformed

    String limpiar(String txt) {
        return txt.trim().replace(" ", "").toUpperCase();
    }

    void cargarTabla() {
        for (OCalles oCalles : cache) {
            modelo.addRow(oCalles.getInfo());
        }
    }

    void vaciarTabla() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    void actualizarTabla() {
        vaciarTabla();
        cargarTabla();
    }

    boolean camposValidos() {
        JTextField[] arr = {jtfCalleNombre, jtfCalleNumero};
        for (JTextField o : arr) {
            if (o.getText() == null || o.getText().isEmpty()) {
                return false;
            }
        }
        if (!jtfCalleNumero.getText().matches("[0-9]{1,3}")) {
            JOptionPane.showMessageDialog(jpCalles, "El numero es demaciado grande");
            return false;
        }
        return true;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JButton jbtCalleActualizar;
    private javax.swing.JButton jbtCalleCancelar;
    private javax.swing.JButton jbtCalleEliminar;
    private javax.swing.JButton jbtCalleGuardar;
    private javax.swing.JPanel jpCalles;
    private javax.swing.JTable jtCalles;
    private javax.swing.JTextField jtfCalleNombre;
    private javax.swing.JTextField jtfCalleNumero;
    private javax.swing.JTextField jtfCallesBuscar;
    // End of variables declaration//GEN-END:variables
}
