/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.bd;

import com.jblue.modelo.ConstBD;
import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.envoltorios.env.EnvUsuario;
import com.jblue.modelo.objetos.OCalles;
import com.jblue.modelo.objetos.OTipoTomas;
import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.MemoCache;
import com.jblue.util.tiempo.Fecha;
import com.jblue.vista.conf.SuperVentana;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jp
 */
public class MenuUsuarios extends SuperVentana {

    private OUsuarios usuario_seleccionado;

    private boolean buscando;
    private final ArrayList<OUsuarios> LISTA_AUX;
    private final DefaultListModel<String> MODELO_LISTA;
    private final Fecha fecha;
    private final Operaciones<OUsuarios> operaciones;
    private final MemoCache<OUsuarios> cache;
    private final ArrayList<OUsuarios> lista_cache;
    private final DefaultTableModel modelo_tabla_usuarios;

    /**
     * Creates new form MenuUsuarios
     */
    public MenuUsuarios() {
        this.LISTA_AUX = new ArrayList<>();
        this.MODELO_LISTA = new DefaultListModel<>();
        this.fecha = new Fecha();
        this.operaciones = FabricaCache.OP_USUARIOS;
        this.cache = FabricaCache.MC_USUARIOS;
        this.lista_cache = cache.getLista();
        this.buscando = false;

        this.initComponents();
        this.modelo_tabla_usuarios = (DefaultTableModel) jtUsuarios.getModel();
        this.jlUsuarios.setModel(MODELO_LISTA);

        this.llamable();
    }

    @Override
    public final void llamable() {
        estadoFinal();
        estadoInicial();
        eventos();
        _cargarTodosJcb();
    }

    @Override
    public void estadoInicial() {
    }

    @Override
    protected void estadoFinal() {
        jcbUsuariosCalle.addItem("SELECCIONAR CALLE");
        jcbUsuariosToma.addItem("SELECCIONAR TIPO DE TOMA");
        jcbUsuariosEst.addItem("SELECCIONAR ESTADO");
        jcbUsuariosRoll.addItem("SELECCIONAR ROLL");
        jcbUsuariosTitular.addItem("SELECCIONAR TITULAR");
    }

    @Override
    protected void addEventos() {
        super.addEventos(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    public void eventos() {
        jtpUsuarios.addChangeListener((e) -> {
            if (jpConsultas.isVisible()) {
                _cargarTabla();
            } else {
                _vaciarTabla();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jtpUsuarios = new javax.swing.JTabbedPane();
        jpRegistros = new javax.swing.JPanel();
        jtfUsuariosNom = new javax.swing.JTextField();
        jtfUsuariosAp = new javax.swing.JTextField();
        jtfUsuariosAm = new javax.swing.JTextField();
        jcbUsuariosToma = new javax.swing.JComboBox<>();
        jcbUsuariosCalle = new javax.swing.JComboBox<>();
        jcbUsuariosRoll = new javax.swing.JComboBox<>();
        jcbUsuariosEst = new javax.swing.JComboBox<>();
        jcbUsuariosTitular = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jchbTitularesCalle = new javax.swing.JCheckBox();
        jchbTitularesTomas = new javax.swing.JCheckBox();
        jchbTitularesRoll = new javax.swing.JCheckBox();
        jchbTitularesEst = new javax.swing.JCheckBox();
        jchbTitular = new javax.swing.JCheckBox();
        jbtUsuariosGuardar = new javax.swing.JButton();
        jbtUsuariosEliminar = new javax.swing.JButton();
        jbtUsuariosActualizar = new javax.swing.JButton();
        jbtUsuariosCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlUsuarios = new javax.swing.JList<>();
        jLabel16 = new javax.swing.JLabel();
        jtfBuscarUsuarioEnLista = new javax.swing.JTextField();
        jpConsultas = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jtfBuscarUsuarioEnTabla = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jtpUsuarios.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jtpUsuariosStateChanged(evt);
            }
        });

        jtfUsuariosNom.setPreferredSize(new java.awt.Dimension(250, 35));

        jtfUsuariosAp.setPreferredSize(new java.awt.Dimension(250, 35));

        jtfUsuariosAm.setPreferredSize(new java.awt.Dimension(250, 35));

        jcbUsuariosToma.setMinimumSize(new java.awt.Dimension(200, 35));
        jcbUsuariosToma.setPreferredSize(new java.awt.Dimension(250, 35));

        jcbUsuariosCalle.setMinimumSize(new java.awt.Dimension(200, 35));
        jcbUsuariosCalle.setPreferredSize(new java.awt.Dimension(250, 35));

        jcbUsuariosRoll.setMinimumSize(new java.awt.Dimension(200, 35));
        jcbUsuariosRoll.setPreferredSize(new java.awt.Dimension(250, 35));

        jcbUsuariosEst.setMinimumSize(new java.awt.Dimension(200, 35));
        jcbUsuariosEst.setPreferredSize(new java.awt.Dimension(250, 35));

        jcbUsuariosTitular.setPreferredSize(new java.awt.Dimension(250, 35));

        jLabel7.setText("A. Parerno");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel8.setText("Nombre");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel9.setText("A. Materno");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel10.setText("Roll.");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel11.setText("Calle");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel13.setText("T. Toma");
        jLabel13.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel14.setText("Estado");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel15.setText("Titular.");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 35));

        jchbTitularesCalle.setText("Mantener");
        jchbTitularesCalle.setPreferredSize(new java.awt.Dimension(100, 35));

        jchbTitularesTomas.setText("Mantener");
        jchbTitularesTomas.setPreferredSize(new java.awt.Dimension(100, 35));

        jchbTitularesRoll.setText("Mantener");
        jchbTitularesRoll.setPreferredSize(new java.awt.Dimension(100, 35));

        jchbTitularesEst.setText("Mantener");
        jchbTitularesEst.setPreferredSize(new java.awt.Dimension(100, 35));

        jchbTitular.setText("Mantener");
        jchbTitular.setPreferredSize(new java.awt.Dimension(100, 35));

        jbtUsuariosGuardar.setText("Guardar");
        jbtUsuariosGuardar.setPreferredSize(new java.awt.Dimension(250, 35));
        jbtUsuariosGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUsuariosGuardarActionPerformed(evt);
            }
        });

        jbtUsuariosEliminar.setText("Eliminar");
        jbtUsuariosEliminar.setPreferredSize(new java.awt.Dimension(250, 35));
        jbtUsuariosEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUsuariosEliminarActionPerformed(evt);
            }
        });

        jbtUsuariosActualizar.setText("Actualizar");
        jbtUsuariosActualizar.setPreferredSize(new java.awt.Dimension(250, 35));
        jbtUsuariosActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUsuariosActualizarActionPerformed(evt);
            }
        });

        jbtUsuariosCancelar.setText("Cancelar");
        jbtUsuariosCancelar.setPreferredSize(new java.awt.Dimension(250, 35));
        jbtUsuariosCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUsuariosCancelarActionPerformed(evt);
            }
        });

        jlUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jlUsuarios);

        jLabel16.setText("Usuarios");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 35));

        jtfBuscarUsuarioEnLista.setPreferredSize(new java.awt.Dimension(250, 35));
        jtfBuscarUsuarioEnLista.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarUsuarioEnListaKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jpRegistrosLayout = new javax.swing.GroupLayout(jpRegistros);
        jpRegistros.setLayout(jpRegistrosLayout);
        jpRegistrosLayout.setHorizontalGroup(
            jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRegistrosLayout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbUsuariosToma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpRegistrosLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbUsuariosCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchbTitularesCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchbTitularesTomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbUsuariosRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jchbTitularesRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsuariosNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsuariosAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfUsuariosAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRegistrosLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbUsuariosEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpRegistrosLayout.createSequentialGroup()
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jcbUsuariosTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jchbTitularesEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchbTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jbtUsuariosGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtUsuariosActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtUsuariosEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbtUsuariosCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(279, 279, 279)
                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtfBuscarUsuarioEnLista, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpRegistrosLayout.setVerticalGroup(
            jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRegistrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUsuariosNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfUsuariosAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfBuscarUsuarioEnLista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpRegistrosLayout.createSequentialGroup()
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfUsuariosAm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUsuariosToma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchbTitularesCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUsuariosCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchbTitularesTomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbUsuariosRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jchbTitularesRoll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpRegistrosLayout.createSequentialGroup()
                                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbUsuariosEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jpRegistrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jcbUsuariosTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jpRegistrosLayout.createSequentialGroup()
                                .addComponent(jchbTitularesEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jchbTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtUsuariosGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtUsuariosActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtUsuariosEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbtUsuariosCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        jtpUsuarios.addTab("Registros", jpRegistros);

        jpConsultas.setLayout(new java.awt.BorderLayout());

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "A. PATERNO", "A. MATERNO", "CALLE", "TIPO DE TOMA", "F. REGISTRO", "ESTADO", "TITULAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtUsuarios.getTableHeader().setReorderingAllowed(false);
        jtUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtUsuarios);

        jpConsultas.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel8.setPreferredSize(new java.awt.Dimension(0, 100));
        jPanel8.setLayout(new javax.swing.BoxLayout(jPanel8, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel9.setMinimumSize(new java.awt.Dimension(0, 50));

        jButton10.setText("Editar");
        jButton10.setPreferredSize(new java.awt.Dimension(100, 35));

        jPanel10.setPreferredSize(new java.awt.Dimension(1160, 50));

        jLabel19.setText("Buscar");
        jLabel19.setPreferredSize(new java.awt.Dimension(100, 35));

        jtfBuscarUsuarioEnTabla.setPreferredSize(new java.awt.Dimension(250, 35));
        jtfBuscarUsuarioEnTabla.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfBuscarUsuarioEnTablaKeyReleased(evt);
            }
        });

        jButton11.setText("sig");
        jButton11.setPreferredSize(new java.awt.Dimension(100, 35));

        jButton12.setText("ant");
        jButton12.setPreferredSize(new java.awt.Dimension(100, 35));

        jButton13.setText("rec");
        jButton13.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("-");
        jLabel20.setPreferredSize(new java.awt.Dimension(100, 35));

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtfBuscarUsuarioEnTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jtfBuscarUsuarioEnTabla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel8.add(jPanel9);

        jpConsultas.add(jPanel8, java.awt.BorderLayout.NORTH);

        jtpUsuarios.addTab("Consultas", jpConsultas);

        jPanel1.add(jtpUsuarios, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtUsuariosGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUsuariosGuardarActionPerformed
        String[] info = _getInfo();
        if (info == null) {
            JOptionPane.showMessageDialog(this.jpRegistros, "Hay Campos No Validos", "Error de inserccion", JOptionPane.ERROR_MESSAGE);
            return;
        }
        for (String string : info) {
            if (string == null) {
                JOptionPane.showMessageDialog(this.jpRegistros, "Hay Campos No Validos", "Error de inserccion", JOptionPane.ERROR_MESSAGE);
            }
        }
        operaciones.insertar(info);
        _actualizarTabla();
    }//GEN-LAST:event_jbtUsuariosGuardarActionPerformed

    private void jbtUsuariosEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUsuariosEliminarActionPerformed
        String id = (String) jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), jtUsuarios.getSelectedColumn());

    }//GEN-LAST:event_jbtUsuariosEliminarActionPerformed

    private void jbtUsuariosActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUsuariosActualizarActionPerformed
        String id = (String) jtUsuarios.getValueAt(jtUsuarios.getSelectedRow(), jtUsuarios.getSelectedColumn());
        String campos[] = Arrays.copyOf(ConstBD.BD_USUARIOS, 1);
        operaciones.actualizar(campos, _getInfo(), "id = " + id);
    }//GEN-LAST:event_jbtUsuariosActualizarActionPerformed

    private void jbtUsuariosCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUsuariosCancelarActionPerformed


    }//GEN-LAST:event_jbtUsuariosCancelarActionPerformed

    private void jlUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlUsuariosMouseClicked
        int click = evt.getClickCount();
        int select = jlUsuarios.getSelectedIndex();
        OUsuarios usuarioSeleccionado = LISTA_AUX.get(select);
        switch (click) {
            case 1:
                jtfBuscarUsuarioEnLista.setText(usuarioSeleccionado.getNombreStr());
                jlUsuarios.clearSelection();
                break;
            case 2:
                jtfBuscarUsuarioEnLista.setText(usuarioSeleccionado.getNombreStr());
                jlUsuarios.clearSelection();
                jtfUsuariosNom.setText(usuarioSeleccionado.getNombre());
                jtfUsuariosAp.setText(usuarioSeleccionado.getAp());
                jtfUsuariosAm.setText(usuarioSeleccionado.getAm());
                jcbUsuariosCalle.setSelectedItem(
                        EnvUsuario.getCalle(usuarioSeleccionado.getCalle()).getCalleStr()
                );
                jcbUsuariosToma.setSelectedItem(
                        EnvUsuario.getTipo_Toma(usuarioSeleccionado.getToma()).getTipo()
                );
                jcbUsuariosRoll.setSelectedIndex(usuarioSeleccionado.getTitutlar() == -1 ? 1 : 2);
                jcbUsuariosEst.setSelectedIndex(usuarioSeleccionado.getEstado() == 1 ? 1 : 2);
                if (usuarioSeleccionado.getTitutlar() != -1) {
                    jcbUsuariosTitular.setSelectedItem(
                            EnvUsuario.getUsuario(usuarioSeleccionado.getTitutlar() + "")
                                    .getNombreStr()
                    );
                }
                break;
        }
    }//GEN-LAST:event_jlUsuariosMouseClicked

    private void jtfBuscarUsuarioEnListaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarUsuarioEnListaKeyReleased
        MODELO_LISTA.removeAllElements();
        LISTA_AUX.clear();
        String buscar = jtfBuscarUsuarioEnLista.getText();
        buscar = buscar.trim().replace(" ", "").toUpperCase();
        for (OUsuarios oUsuarios : lista_cache) {
            String nombre = oUsuarios.getNombreStr().trim().replace(" ", "").toUpperCase();
            if (nombre.contains(buscar)) {
                MODELO_LISTA.addElement(oUsuarios.getNombreStr());
                LISTA_AUX.add(oUsuarios);
            }
        }
    }//GEN-LAST:event_jtfBuscarUsuarioEnListaKeyReleased

    private void jtfBuscarUsuarioEnTablaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfBuscarUsuarioEnTablaKeyReleased
        this.buscando = true;
        String buscar = jtfBuscarUsuarioEnTabla.getText();
        buscar = buscar.trim().replace(" ", "").toUpperCase();
        _vaciarTabla();
        for (OUsuarios oUsuarios : lista_cache) {
            if (oUsuarios.getNombreStr().toUpperCase().replace(" ", "").contains(buscar)) {
                modelo_tabla_usuarios.addRow(oUsuarios.getInfoSinFK());
                LISTA_AUX.add(oUsuarios);
            }
        }
    }//GEN-LAST:event_jtfBuscarUsuarioEnTablaKeyReleased

    private void jtUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuariosMouseClicked
        int clicks = evt.getClickCount();
        if (buscando) {
            this.usuario_seleccionado = LISTA_AUX.get(jtUsuarios.getSelectedRow());
            switch (clicks) {
                case 1:
                    jtfBuscarUsuarioEnTabla.setText(usuario_seleccionado.getNombreStr());
                    break;
                case 2:
                    String info[] = usuario_seleccionado.getInfoSinFK();
                    jtfUsuariosNom.setText(info[1]);
                    jtfUsuariosAp.setText(info[2]);
                    jtfUsuariosAm.setText(info[3]);
                    jcbUsuariosCalle.setSelectedItem(info[4]);
                    jcbUsuariosToma.setSelectedItem(info[5]);
                    if (usuario_seleccionado.isTitular()) {
                        jcbUsuariosTitular.setSelectedItem(EnvUsuario.getUsuario(info[6]));
                    }
                    jcbUsuariosEst.setSelectedIndex(usuario_seleccionado.isActivo() ? 1 : 2);
                    jcbUsuariosRoll.setSelectedItem(info[4]);
                    jtpUsuarios.setSelectedIndex(0);
                    jtfBuscarUsuarioEnTabla.setText(null);
                    jtUsuarios.clearSelection();
                    buscando = false;
                    break;
            }
        } else {
            this.usuario_seleccionado = lista_cache.get(jtUsuarios.getSelectedRow());
            if (clicks == 2) {

            }
        }
    }//GEN-LAST:event_jtUsuariosMouseClicked

    private void jtpUsuariosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jtpUsuariosStateChanged

    }//GEN-LAST:event_jtpUsuariosStateChanged

    String[] _getInfo() {
        String toma = null, calle = null, estado = null, titular = "-1", fch = null;
        calle = EnvUsuario.getCalle(jcbUsuariosCalle.getItemAt(jcbUsuariosCalle.getSelectedIndex())).getId();
        System.out.println(calle);
        toma = EnvUsuario.getTipo_Toma(jcbUsuariosToma.getItemAt(jcbUsuariosToma.getSelectedIndex())).getId();
        fch = this.fecha.getFechaActualString();
        estado = jcbUsuariosEst.getSelectedIndex() == 1 ? "1" : "-1";
        if (jcbUsuariosRoll.getSelectedIndex() == 2) {
            titular = EnvUsuario.getUsuario(jcbUsuariosTitular.getItemAt(jcbUsuariosTitular.getSelectedIndex())).getId();
        }
        return new String[]{
            jtfUsuariosNom.getText(),
            jtfUsuariosAp.getText(),
            jtfUsuariosAm.getText(),
            calle,
            toma,
            fch,
            estado,
            titular
        };
    }

    public void validar() {

    }

    void _cargarTodosJcb() {
        _cargarJcbCalles();
        _cargarJcbTitulares();
        _cargarJcbTomas();
    }

    void _actualizarTabla() {
        _vaciarTabla();
        _cargarTabla();
    }

    void _cargarTabla() {
        for (OUsuarios usuario : lista_cache) {
            modelo_tabla_usuarios.addRow(usuario.getInfoSinFK());
        }
    }

    void _vaciarTabla() {
        while (modelo_tabla_usuarios.getRowCount() > 0) {
            modelo_tabla_usuarios.removeRow(0);
        }
    }

    void _cargarJcbTomas() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) jcbUsuariosToma.getModel();
        for (OTipoTomas o : FabricaCache.MC_TIPOS_DE_TOMAS.getLista()) {
            modelo.addElement(o.getTipo());
        }
    }

    void _cargarJcbCalles() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) jcbUsuariosCalle.getModel();
        for (OCalles o : FabricaCache.MC_CALLES.getLista()) {
            modelo.addElement(o.getCalleStr());
        }
    }

    void _cargarJcbTitulares() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) jcbUsuariosTitular.getModel();
        for (OUsuarios o : lista_cache) {
            if (o.isTitular()) {
                modelo.addElement(o.getNombreStr());
            }
        }
    }

    public void actualizarJcbCalles() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) jcbUsuariosCalle.getModel();
        modelo.removeAllElements();
        _cargarJcbCalles();
    }

    public void actualizarJcbTomas() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) jcbUsuariosToma.getModel();
        modelo.removeAllElements();
        _cargarJcbTomas();
    }

    public void actualizarJcbTitulares() {
        DefaultComboBoxModel<String> modelo = (DefaultComboBoxModel<String>) jcbUsuariosTitular.getModel();
        modelo.removeAllElements();
        _cargarJcbTitulares();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbtUsuariosActualizar;
    private javax.swing.JButton jbtUsuariosCancelar;
    private javax.swing.JButton jbtUsuariosEliminar;
    private javax.swing.JButton jbtUsuariosGuardar;
    private javax.swing.JComboBox<String> jcbUsuariosCalle;
    private javax.swing.JComboBox<String> jcbUsuariosEst;
    private javax.swing.JComboBox<String> jcbUsuariosRoll;
    private javax.swing.JComboBox<String> jcbUsuariosTitular;
    private javax.swing.JComboBox<String> jcbUsuariosToma;
    private javax.swing.JCheckBox jchbTitular;
    private javax.swing.JCheckBox jchbTitularesCalle;
    private javax.swing.JCheckBox jchbTitularesEst;
    private javax.swing.JCheckBox jchbTitularesRoll;
    private javax.swing.JCheckBox jchbTitularesTomas;
    private javax.swing.JList<String> jlUsuarios;
    private javax.swing.JPanel jpConsultas;
    private javax.swing.JPanel jpRegistros;
    private javax.swing.JTable jtUsuarios;
    private javax.swing.JTextField jtfBuscarUsuarioEnLista;
    private javax.swing.JTextField jtfBuscarUsuarioEnTabla;
    private javax.swing.JTextField jtfUsuariosAm;
    private javax.swing.JTextField jtfUsuariosAp;
    private javax.swing.JTextField jtfUsuariosNom;
    private javax.swing.JTabbedPane jtpUsuarios;
    // End of variables declaration//GEN-END:variables

}
