/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.jblue.vista.ventanas.bd;

import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.MemoCache;
import com.jblue.util.tiempo.Fecha;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jp
 */
public class NewMenuUsuarios extends javax.swing.JFrame {

    private OUsuarios usuario_seleccionado;

    private boolean buscando;
    private final ArrayList<OUsuarios> LISTA_AUX;
    private final DefaultListModel<String> MODELO_LISTA;
    private final Fecha fecha;
    private final Operaciones<OUsuarios> operaciones;
    private final MemoCache<OUsuarios> cache;
    private final ArrayList<OUsuarios> lista_cache;
    private final DefaultTableModel modelo_tabla_usuarios;

    /**
     * Creates new form NewUsuarios
     */
    public NewMenuUsuarios() {
        this.LISTA_AUX = new ArrayList<>();
        this.MODELO_LISTA = new DefaultListModel<>();
        this.fecha = new Fecha();
        this.operaciones = FabricaCache.OP_USUARIOS;
        this.cache = FabricaCache.MC_USUARIOS;
        this.lista_cache = cache.getLista();
        this.buscando = false;

        this.initComponents();
        this.modelo_tabla_usuarios = (DefaultTableModel) jtUsuarios.getModel();
        this.jlUsuarios.setModel(MODELO_LISTA);

        //this.llamable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel17 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlUsuarios = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel16 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jPanel18 = new javax.swing.JPanel();
        jPanel19 = new javax.swing.JPanel();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jPanel25 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel26 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel29 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jPanel24 = new javax.swing.JPanel();
        jPanel27 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel28 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel31 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jPanel32 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jTextField6 = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtUsuarios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel17.setLayout(new javax.swing.BoxLayout(jPanel17, javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jTextField1.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel1.add(jTextField1, java.awt.BorderLayout.PAGE_START);

        jlUsuarios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jlUsuarios);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel1);

        jSeparator1.setPreferredSize(new java.awt.Dimension(5, 662));
        jPanel17.add(jSeparator1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos Del Usuario");
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel4.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Nombre: ");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel4.add(jLabel2, java.awt.BorderLayout.WEST);
        jPanel4.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel4);

        jPanel5.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("A. Paterno");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel5.add(jLabel3, java.awt.BorderLayout.WEST);
        jPanel5.add(jTextField3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel5);

        jPanel6.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("A. Materno");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel6.add(jLabel4, java.awt.BorderLayout.WEST);
        jPanel6.add(jTextField4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel6);

        jPanel7.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("T. Toma");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel7.add(jLabel5, java.awt.BorderLayout.WEST);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel7.add(jComboBox1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel7);

        jPanel8.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Calle: ");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel8.add(jLabel6, java.awt.BorderLayout.WEST);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel8.add(jComboBox2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Roll: ");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel9.add(jLabel7, java.awt.BorderLayout.WEST);

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel9.add(jComboBox3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Estado: ");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel10.add(jLabel8, java.awt.BorderLayout.WEST);

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel10.add(jComboBox4, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel10);

        jPanel11.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Titular");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel11.add(jLabel9, java.awt.BorderLayout.WEST);

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel11.add(jComboBox5, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel11);

        jPanel12.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel12.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel12);

        jPanel13.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jButton7.setText("Guardar");
        jPanel13.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jButton2.setText("Actualizar");
        jPanel14.add(jButton2, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel14);

        jPanel15.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Eliminar");
        jPanel15.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel15);

        jPanel16.setPreferredSize(new java.awt.Dimension(500, 50));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Cancelar");
        jPanel16.add(jButton3, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel16);

        jPanel2.add(jPanel3, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel2);

        jTabbedPane1.addTab("Registro de usuarios", jPanel17);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jPanel19.setPreferredSize(new java.awt.Dimension(980, 162));
        jPanel19.setLayout(new java.awt.BorderLayout());

        jPanel21.setLayout(new javax.swing.BoxLayout(jPanel21, javax.swing.BoxLayout.LINE_AXIS));

        jPanel22.setLayout(new javax.swing.BoxLayout(jPanel22, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel25.setLayout(new java.awt.BorderLayout());

        jLabel11.setText("Calle");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel25.add(jLabel11, java.awt.BorderLayout.WEST);

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel25.add(jComboBox6, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel25);

        jPanel26.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("T. Toma");
        jLabel12.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel26.add(jLabel12, java.awt.BorderLayout.WEST);

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel26.add(jComboBox7, java.awt.BorderLayout.CENTER);

        jPanel22.add(jPanel26);

        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel13.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel29.add(jLabel13, java.awt.BorderLayout.WEST);

        jPanel22.add(jPanel29);

        jPanel21.add(jPanel22);

        jPanel24.setLayout(new javax.swing.BoxLayout(jPanel24, javax.swing.BoxLayout.PAGE_AXIS));

        jPanel27.setLayout(new java.awt.BorderLayout());

        jLabel14.setText("Roll");
        jLabel14.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel27.add(jLabel14, java.awt.BorderLayout.WEST);

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel27.add(jComboBox8, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel27);

        jPanel28.setLayout(new java.awt.BorderLayout());

        jLabel15.setText("Estado");
        jLabel15.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel28.add(jLabel15, java.awt.BorderLayout.WEST);

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel28.add(jComboBox9, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel28);

        jPanel31.setLayout(new java.awt.BorderLayout());

        jLabel16.setText("Titular");
        jLabel16.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel31.add(jLabel16, java.awt.BorderLayout.WEST);
        jPanel31.add(jTextField5, java.awt.BorderLayout.CENTER);

        jPanel24.add(jPanel31);

        jPanel21.add(jPanel24);

        jPanel19.add(jPanel21, java.awt.BorderLayout.CENTER);

        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel17.setText("Filtros");
        jLabel17.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.add(jLabel17, java.awt.BorderLayout.CENTER);

        jButton6.setText("Quitar filtros");
        jPanel32.add(jButton6, java.awt.BorderLayout.LINE_END);

        jPanel19.add(jPanel32, java.awt.BorderLayout.NORTH);

        jPanel18.add(jPanel19, java.awt.BorderLayout.NORTH);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jPanel30.setPreferredSize(new java.awt.Dimension(980, 30));
        jPanel30.setLayout(new java.awt.BorderLayout());

        jToggleButton2.setText("Recargar");
        jToggleButton2.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel30.add(jToggleButton2, java.awt.BorderLayout.LINE_START);
        jPanel30.add(jTextField6, java.awt.BorderLayout.CENTER);

        jPanel23.setPreferredSize(new java.awt.Dimension(200, 40));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jButton4.setText("jButton4");
        jButton4.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel23.add(jButton4, java.awt.BorderLayout.LINE_START);

        jButton5.setText("jButton5");
        jButton5.setPreferredSize(new java.awt.Dimension(100, 40));
        jPanel23.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel30.add(jPanel23, java.awt.BorderLayout.LINE_END);

        jPanel20.add(jPanel30, java.awt.BorderLayout.NORTH);

        jtUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "A. PATERNO", "A. MATERNO", "CALLE", "TIPO DE TOMA", "F. REGISTRO", "ESTADO", "TITULAR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtUsuarios.getTableHeader().setReorderingAllowed(false);
        jtUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtUsuariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jtUsuarios);

        jPanel20.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel18.add(jPanel20, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Consulta de usuarios", jPanel18);

        getContentPane().add(jTabbedPane1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtUsuariosMouseClicked

        
        
    }//GEN-LAST:event_jtUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JList<String> jlUsuarios;
    private javax.swing.JTable jtUsuarios;
    // End of variables declaration//GEN-END:variables
}
