/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.jblue.vista.ventanas.vistas.principal;

import com.jblue.modelo.envoltorios.Operaciones;
import com.jblue.modelo.envoltorios.env.EnvUsuario;
import com.jblue.modelo.objetos.OPagosRecargos;
import com.jblue.modelo.objetos.OPersonal;
import com.jblue.modelo.objetos.OTipoTomas;
import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.sistema.Sesion;
import com.jblue.util.FormatoBD;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.FabricaOpraciones;
import com.jblue.util.tiempo.Fecha;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author jp
 */
public class VRecargos extends javax.swing.JPanel {

    private boolean buscando;
    //
    private OUsuarios usuario_buscado;
    private final ArrayList<OUsuarios> lista_aux;
    private final ArrayList<OUsuarios> cache;
    private final Operaciones<OPagosRecargos> op;
    //
    private final DefaultListModel<String> modelo;

    /**
     * Creates new form VRecargos
     */
    public VRecargos() {
        op = FabricaOpraciones.PAGOS_X_RECARGOS;
        cache = FabricaCache.MC_USUARIOS.getLista();
        lista_aux = new ArrayList<>(cache.size());
        //
        modelo = new DefaultListModel<>();
        initComponents();
        //
        jlListaUsuarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        buscar = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jlListaUsuarios = new javax.swing.JList<>();
        jPanel7 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jcbMes = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jbtGuardar = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(1200, 675));
        setLayout(new java.awt.BorderLayout());

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1200, 675));

        jPanel3.setLayout(new java.awt.BorderLayout(5, 0));

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 675));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel24.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel24.setLayout(new java.awt.BorderLayout());

        buscar.setMaximumSize(new java.awt.Dimension(400, 30));
        buscar.setMinimumSize(new java.awt.Dimension(400, 30));
        buscar.setPreferredSize(new java.awt.Dimension(400, 30));
        buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarKeyReleased(evt);
            }
        });
        jPanel24.add(buscar, java.awt.BorderLayout.CENTER);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/buscar.png"))); // NOI18N
        jPanel24.add(jLabel15, java.awt.BorderLayout.LINE_START);

        jPanel1.add(jPanel24, java.awt.BorderLayout.NORTH);

        jPanel23.setPreferredSize(new java.awt.Dimension(500, 540));
        jPanel23.setLayout(new java.awt.BorderLayout());

        jScrollPane1.setMinimumSize(new java.awt.Dimension(500, 550));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 540));

        jlListaUsuarios.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jlListaUsuarios.setPreferredSize(new java.awt.Dimension(400, 500));
        jScrollPane1.setViewportView(jlListaUsuarios);

        jPanel23.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel23, java.awt.BorderLayout.CENTER);

        jPanel3.add(jPanel1, java.awt.BorderLayout.WEST);

        jPanel7.setLayout(new javax.swing.BoxLayout(jPanel7, javax.swing.BoxLayout.Y_AXIS));

        jPanel12.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel12.setLayout(new javax.swing.BoxLayout(jPanel12, javax.swing.BoxLayout.LINE_AXIS));

        jPanel15.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Mes");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel15.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jcbMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ENE", "FEB", "MAR", "ABR", "MAY", "JUN", "JUL", "AGO", "SEP", "OCT", "NOV", "DIC" }));
        jPanel15.add(jcbMes, java.awt.BorderLayout.CENTER);

        jPanel12.add(jPanel15);

        jPanel7.add(jPanel12);

        jPanel17.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Total");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel17.add(jLabel3, java.awt.BorderLayout.LINE_START);
        jPanel17.add(jTextField1, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel17);

        jPanel16.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel10.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel16.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jPanel7.add(jPanel16);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel12.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel18.add(jLabel12, java.awt.BorderLayout.LINE_START);

        jbtGuardar.setText("Hacer Recargo");
        jbtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtGuardarActionPerformed(evt);
            }
        });
        jPanel18.add(jbtGuardar, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel18);

        jPanel19.setLayout(new java.awt.BorderLayout());

        jLabel13.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel19.add(jLabel13, java.awt.BorderLayout.LINE_START);

        jButton5.setText("Pagar Recargo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel19.add(jButton5, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel19);

        jPanel20.setLayout(new java.awt.BorderLayout());

        jLabel14.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel20.add(jLabel14, java.awt.BorderLayout.LINE_START);

        jPanel7.add(jPanel20);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Registro De Recargos", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Historial De Recargos");
        jLabel2.setPreferredSize(new java.awt.Dimension(1200, 50));
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel5.setPreferredSize(new java.awt.Dimension(1200, 40));
        jPanel5.setLayout(new java.awt.BorderLayout());

        jButton3.setText("Recargar");
        jPanel5.add(jButton3, java.awt.BorderLayout.WEST);
        jPanel5.add(jTextField2, java.awt.BorderLayout.CENTER);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jButton1.setText("Ant");
        jPanel6.add(jButton1, java.awt.BorderLayout.WEST);

        jButton2.setText("Sig");
        jPanel6.add(jButton2, java.awt.BorderLayout.EAST);

        jPanel5.add(jPanel6, java.awt.BorderLayout.EAST);

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Personal", "Usuario", "Mes Pagado", "Monto", "Dia", "Mes", "Año"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Consulta de Recargos", jPanel4);

        add(jTabbedPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jbtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtGuardarActionPerformed

        if (usuario_buscado == null) {
            return;
        }
        String[] info = getInfo("-1");
        info = FormatoBD.bdEntrada(info);
        op.insertar(info);

    }//GEN-LAST:event_jbtGuardarActionPerformed

    Fecha fh = new Fecha();

    public String[] getInfo(String estado) {
        OPersonal personal = Sesion.getInstancia().getUsuario();
        String _personal = personal.getId();
        String _usuario = usuario_buscado.getId();
        OTipoTomas toma = EnvUsuario.getTipo_De_Toma(usuario_buscado.getToma());
        String _mes = String.valueOf(toma.getRecargo());
        String _estado = estado;
        String _registro = fh.getNewFechaActualString();
        return new String[]{
            _personal, _usuario, _mes, _estado, _registro
        };
    }

    private void buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarKeyReleased
        buscando = true;

        lista_aux.clear();
        modelo.removeAllElements();
        //

        String entrada = buscar.getText();
        entrada = _limpiar(entrada);

        for (OUsuarios i : cache) {
            String aux = _limpiar(i.getStringR());
            if (!aux.contains(entrada)) {
                continue;
            }
            modelo.addElement(i.getStringR());
            lista_aux.add(i);
        }
    }//GEN-LAST:event_buscarKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        if (usuario_buscado == null) {
            return;
        }

        op.actualizar("estado", "1", "usuario = '" + usuario_buscado.getId() + "'");

    }//GEN-LAST:event_jButton5ActionPerformed

    String _limpiar(String txt) {
        return txt.trim().replace(" ", "").replace("_", "").toLowerCase();
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        _cargarListaUsuarios();
    }

    void _cargarListaUsuarios() {
        if (cache.isEmpty()) {
            return;
        }
        for (OUsuarios i : cache) {
//            if (!i.isActivo()) {
//                continue;
//            }
            modelo.addElement(i.getStringR());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField buscar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbtGuardar;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JList<String> jlListaUsuarios;
    // End of variables declaration//GEN-END:variables
}
