/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.ventanas.menus.herramientas;

import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.sistema.app.AppProp;
import com.jblue.util.cache.FabricaCache;
import com.jblue.vista.normas.SuperVentana;
import com.jblue.vista.comp.CSelectorObjeto;
import java.io.File;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JProgressBar;

/**
 *
 * @author jp
 */
public class MenuDirectorios extends SuperVentana {

    private final File dir_usuarios;
    private final ArrayList<OUsuarios> cache;
    private final ArrayList<OUsuarios> lista_aux;
    private final DefaultListModel<String> modelo_lista;
    private int usuario_seleccionado;

    /**
     * Creates new form MenuDirectorios
     */
    public MenuDirectorios() {
        _TITULO = 10;
        dir_usuarios = AppProp.FIL_DIR_PROG_USUARIOS;
        cache = FabricaCache.MC_USUARIOS.getLista();
        lista_aux = new ArrayList<>(cache.size());
        modelo_lista = new DefaultListModel<>();
        initComponents();
        usuarios_sin_dir.setModel(modelo_lista);
        //crear_dir.setEnabled(false);
        llamable();
        //BasicFileAttributes readAttributes = Files.readAttributes(dir_usuarios.toPath(), BasicFileAttributes.class);
        // System.out.println(readAttributes.creationTime());
    }

    @Override
    protected final void llamable() {
        addComponentes();
        estadoFinal();
        estadoInicial();
        addEventos();
    }

    @Override
    public void estadoInicial() {
        if (modelo_lista.getSize() > 0) {
            modelo_lista.clear();
        }
        crear_dir.setEnabled(false);
    }
    String dir_nom_formato = "%s - %s";

    private void cargarLista() {
        if (modelo_lista.getSize() > 0) {
            modelo_lista.clear();
        }
        String[] dirs = dir_usuarios.list();
        if (dirs.length == cache.size()) {
            return;
        }
        ArrayList<String> lista = new ArrayList<>();
        lista.addAll(Arrays.asList(dirs));
        for (OUsuarios i : cache) {

            int index = lista.indexOf(String.format(dir_nom_formato, i.getId(), i.getStringR()));
            if (index < 0) {
                modelo_lista.addElement(i.getStringR());
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_usuario_sin_dir = new javax.swing.JPanel();
        panel_izq = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        usuarios_sin_dir = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        panel_der = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        crear_dir = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel_usuario_sin_dir.setName("Usuarios sin directorio"); // NOI18N
        panel_usuario_sin_dir.setPreferredSize(new java.awt.Dimension(700, 600));
        panel_usuario_sin_dir.setLayout(new java.awt.BorderLayout());

        panel_izq.setLayout(new java.awt.BorderLayout());

        jScrollPane2.setPreferredSize(new java.awt.Dimension(300, 300));

        usuarios_sin_dir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usuarios_sin_dirMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(usuarios_sin_dir);

        panel_izq.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuarios sin directorio");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 40));
        panel_izq.add(jLabel1, java.awt.BorderLayout.NORTH);

        panel_usuario_sin_dir.add(panel_izq, java.awt.BorderLayout.CENTER);

        panel_der.setPreferredSize(new java.awt.Dimension(400, 232));
        panel_der.setLayout(new java.awt.GridLayout(8, 0));

        jButton5.setText("Crear Directorio a todos");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panel_der.add(jButton5);

        crear_dir.setText("Crear Directorio");
        crear_dir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crear_dirActionPerformed(evt);
            }
        });
        panel_der.add(crear_dir);

        jToggleButton1.setText("Eliminar Directorio");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        panel_der.add(jToggleButton1);

        panel_usuario_sin_dir.add(panel_der, java.awt.BorderLayout.EAST);

        getContentPane().add(panel_usuario_sin_dir, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JProgressBar jp = new JProgressBar(WIDTH, NORMAL);
        int x = 0;
        for (OUsuarios i : cache) {
            StringBuilder s = new StringBuilder(dir_usuarios.getAbsolutePath());
            s.append("/").append(String.format(dir_nom_formato, i.getId(), i.getStringR()));
            File j = new File(s.toString());
            if (j.mkdir()) {
                x++;
            }
        }
        JOptionPane.showMessageDialog(this, "Se crearon: " + x + " directorios");
        cargarLista();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void usuarios_sin_dirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarios_sin_dirMouseClicked
        int index = usuarios_sin_dir.getSelectedIndex();
        if (index < 0 || index > modelo_lista.getSize()) {
            return;
        }
        crear_dir.setEnabled(true);
        usuario_seleccionado = index;
    }//GEN-LAST:event_usuarios_sin_dirMouseClicked

    private void crear_dirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crear_dirActionPerformed
        OUsuarios usuario = CSelectorObjeto.selectorUsuarios(this);
        System.out.println(usuario);
//        String rm = modelo_lista.remove(usuario_seleccionado);
//        StringBuilder s = new StringBuilder(dir_usuarios.getAbsolutePath());
//        s.append("/").append(rm);
//        File f = new File(s.toString());
//        System.out.println(f.getAbsolutePath());
//        if (f.mkdir()) {
//            JOptionPane.showMessageDialog(this, "El directorio se creo correctamente");
//        }
    }//GEN-LAST:event_crear_dirActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        JFileChooser file = new JFileChooser(dir_usuarios);
        file.setMultiSelectionEnabled(false);
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int opc = file.showOpenDialog(this);
        if (opc != JFileChooser.APPROVE_OPTION) {
            return;
        }
        File seleccionado = file.getSelectedFile();
        String aux = "Directorio %s borrado";
        if (seleccionado.delete()) {
            JOptionPane.showMessageDialog(this, String.format(aux, seleccionado.getName()));
        }
        cargarLista();

    }//GEN-LAST:event_jToggleButton1ActionPerformed

    @Override
    public void setVisible(boolean b) {
        super.setVisible(b); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        if (b) {
            cargarLista();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crear_dir;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JPanel panel_der;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JPanel panel_usuario_sin_dir;
    private javax.swing.JList<String> usuarios_sin_dir;
    // End of variables declaration//GEN-END:variables
}
