SET FOREIGN_KEY_CHECKS = 0; -- DESACTIVAMOS EL CHECK DE LAS LLAVES FORANEAS

TRUNCATE TABLE `jblue`.`cat_status`; -- TRUNCAMOS LA TABLA

SET FOREIGN_KEY_CHECKS = 1;-- ACTIVAMOS EL CHECK DE LAS LLAVES FORANEAS

SELECT * FROM jblue.`cat_status`; -- VERIFICAMPOS EL MOVIMIENTO