SET FOREIGN_KEY_CHECKS = 0; -- DESACTIVAMOS EL CHECK DE LAS LLAVES FORANEAS

TRUNCATE TABLE jblue.pym_payment_concept; -- TRUNCAMOS LA TABLA

SET FOREIGN_KEY_CHECKS = 1;-- ACTIVAMOS EL CHECK DE LAS LLAVES FORANEAS

SELECT * FROM jblue.pym_payment_concept; -- VERIFICAMPOS EL MOVIMIENTO