/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas.menucargos;

import com.jblue.util.fabricas.FabricaCache;
import com.jblue.util.modelo.MemoCache;
import com.jblue.vista.marco.vistas.VistaExtendida;
import com.jblue.vista.vistas.menucargos.util.VPersonal;

/**
 *
 * @author jp
 */
public class VAdministrador extends VistaExtendida {

    /**
     * Creates new form VAdministrador
     */
    public VAdministrador() {
        initComponents();
        memo_cache = FabricaCache.MC_PERSONAL;
        VPersonal personal_consultas = new VPersonal(this);
        llamable();
        panel_central.add(personal_consultas.getName(), personal_consultas);

    }

    @Override
    protected final void llamable() {
    }

    @Override
    public void componentesEstadoInicial() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        panel_central = new javax.swing.JPanel();

        setName("Administrador"); // NOI18N
        setPreferredSize(new java.awt.Dimension(1000, 600));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(200, 600));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/usuario.png"))); // NOI18N
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 200));
        jPanel1.add(jLabel3, java.awt.BorderLayout.NORTH);

        jPanel3.setLayout(new java.awt.GridLayout(6, 0));

        jButton1.setText("Usuarios");
        jPanel3.add(jButton1);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.WEST);

        panel_central.setPreferredSize(new java.awt.Dimension(800, 600));
        panel_central.setLayout(new java.awt.CardLayout());
        add(panel_central, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_central;
    // End of variables declaration//GEN-END:variables
    private final MemoCache memo_cache;

    public MemoCache getMemo_cache() {
        return memo_cache;
    }

}
