/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views;

import jsoftware.com.jblue.controllers.viewc.AdministrationHistoryController;
import jsoftware.com.jblue.model.dto.EmployeeDTO;
import jsoftware.com.jblue.views.framework.SimpleView;

/**
 *
 * @author juanp
 */
public final class AdministrationHistoryView extends SimpleView {

    private static final long serialVersionUID = 1L;

    /**
     * Creates new form AdministrationHistoryView
     */
    public AdministrationHistoryView() {
        initComponents();
        controller = new AdministrationHistoryController(this);
        build();
    }

    @Override
    public void build() {
        components();
        events();
        initComponents();
        finalState();
    }

    @Override
    public void events() {
        save_button.addActionListener(controller);
        update_button.addActionListener(controller);
        delete_button.addActionListener(controller);
        cancel_button.addActionListener(controller);

    }

    @Override
    public void components() {
}

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        np_cp_center = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        np_cp_west = new javax.swing.JPanel();
        search_object = new javax.swing.JButton();
        np_cp_east = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel14 = new javax.swing.JPanel();
        jPanel15 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        root_employee = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        admin_employee = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        president_employee = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tesurer_employee = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox<>();
        option_panel = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        panel_tabla = new javax.swing.JPanel();
        jPanel30 = new javax.swing.JPanel();
        search_field = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        reload_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Administracion"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        np_cp_center.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        register_button.setText("Registar");
        register_button.setActionCommand("register_view");
        np_cp_center.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText("Consultar");
        search_button.setActionCommand("search_view");
        np_cp_center.add(search_button);

        north_panel.add(np_cp_center, java.awt.BorderLayout.CENTER);

        np_cp_west.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_west.setLayout(new java.awt.BorderLayout());

        search_object.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_object.setActionCommand("search_object");
        np_cp_west.add(search_object, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_west, java.awt.BorderLayout.WEST);

        np_cp_east.setPreferredSize(new java.awt.Dimension(100, 30));
        np_cp_east.setLayout(new java.awt.BorderLayout());

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        np_cp_east.add(jButton3, java.awt.BorderLayout.CENTER);

        north_panel.add(np_cp_east, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);

        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel14.setLayout(new java.awt.BorderLayout(10, 10));

        jPanel15.setPreferredSize(new java.awt.Dimension(200, 50));
        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel12.setText("Año de la administracion");
        jLabel12.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel15.add(jLabel12, java.awt.BorderLayout.LINE_START);

        jSpinner1.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel15.add(jSpinner1, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel15, java.awt.BorderLayout.NORTH);

        jPanel5.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel5.setLayout(new java.awt.BorderLayout(10, 10));

        jLabel11.setText("Observaciones");
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel5.add(jLabel11, java.awt.BorderLayout.NORTH);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(150, 30));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel5.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel14.add(jPanel5, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Informacion de la Administracion", jPanel14);

        jPanel1.setLayout(new java.awt.GridLayout(12, 0));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Root");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel4.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel4.add(root_employee, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel10.setText("Administrador");
        jLabel10.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel13.add(jLabel10, java.awt.BorderLayout.LINE_START);

        jPanel13.add(admin_employee, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel13);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("Presidente");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel6.add(jLabel3, java.awt.BorderLayout.LINE_START);

        jPanel6.add(president_employee, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel6);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("Tesorero");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel3.add(jLabel2, java.awt.BorderLayout.LINE_START);

        jPanel3.add(tesurer_employee, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jTabbedPane1.addTab("Personal Obligatorio", jPanel1);

        jPanel2.setLayout(new java.awt.GridLayout(12, 0));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("Secretario");
        jLabel4.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel7.add(jLabel4, java.awt.BorderLayout.LINE_START);

        jPanel7.add(jComboBox4, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel5.setText("Plomero");
        jLabel5.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel8.add(jLabel5, java.awt.BorderLayout.LINE_START);

        jPanel8.add(jComboBox5, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel6.setText("Residente 1");
        jLabel6.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel9.add(jLabel6, java.awt.BorderLayout.LINE_START);

        jPanel9.add(jComboBox6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel9);

        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel7.setText("Residente 2");
        jLabel7.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel10.add(jLabel7, java.awt.BorderLayout.LINE_START);

        jPanel10.add(jComboBox7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel10);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel8.setText("Residente 3");
        jLabel8.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel11.add(jLabel8, java.awt.BorderLayout.LINE_START);

        jPanel11.add(jComboBox8, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel11);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel9.setText("Administrador");
        jLabel9.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel12.add(jLabel9, java.awt.BorderLayout.LINE_START);

        jPanel12.add(jComboBox9, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel12);

        jTabbedPane1.addTab("Personal Administrativo", jPanel2);

        register_panel.add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        option_panel.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel17.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel17.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        save_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText("Guardar");
        save_button.setActionCommand("save");
        save_button.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel17.add(save_button);

        update_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/update_x32.png"))); // NOI18N
        update_button.setText("Actualizar");
        update_button.setActionCommand("update");
        update_button.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel17.add(update_button);

        delete_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setActionCommand("delete");
        delete_button.setPreferredSize(new java.awt.Dimension(166, 40));
        jPanel17.add(delete_button);

        option_panel.add(jPanel17);

        cancel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText("Cancelar");
        cancel_button.setActionCommand("cancel");
        cancel_button.setPreferredSize(new java.awt.Dimension(500, 40));
        option_panel.add(cancel_button);

        register_panel.add(option_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "card2");

        search_panel.setMinimumSize(new java.awt.Dimension(900, 700));
        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout());

        panel_tabla.setPreferredSize(new java.awt.Dimension(1000, 500));
        panel_tabla.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel30.setMinimumSize(new java.awt.Dimension(980, 30));
        jPanel30.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel30.setLayout(new java.awt.BorderLayout(5, 5));

        search_field.setName("buscador"); // NOI18N
        jPanel30.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel23.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel23.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        back_button.setActionCommand("back");
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(back_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand("next");
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(next_button);

        jPanel30.add(jPanel23, java.awt.BorderLayout.LINE_END);

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand("reload");
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel30.add(reload_button, java.awt.BorderLayout.LINE_START);

        panel_tabla.add(jPanel30, java.awt.BorderLayout.NORTH);

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        objects_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        objects_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(objects_table);

        panel_tabla.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_tabla, java.awt.BorderLayout.CENTER);

        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No.");
        jPanel32.add(jLabel18, java.awt.BorderLayout.CENTER);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        count.setToolTipText("Numero de pagos hechos.");
        count.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range.setText("0 - 0");
        range.setToolTipText("");
        status_bar_panel.add(range, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total:");
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setToolTipText("Numero de pagos hechos.");
        total.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<EmployeeDTO> admin_employee;
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel count;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<EmployeeDTO> jComboBox4;
    private javax.swing.JComboBox<EmployeeDTO> jComboBox5;
    private javax.swing.JComboBox<EmployeeDTO> jComboBox6;
    private javax.swing.JComboBox<EmployeeDTO> jComboBox7;
    private javax.swing.JComboBox<EmployeeDTO> jComboBox8;
    private javax.swing.JComboBox<EmployeeDTO> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton next_button;
    private javax.swing.JPanel north_panel;
    private javax.swing.JPanel np_cp_center;
    private javax.swing.JPanel np_cp_east;
    private javax.swing.JPanel np_cp_west;
    private javax.swing.JTable objects_table;
    private javax.swing.JPanel option_panel;
    private javax.swing.JPanel panel_tabla;
    private javax.swing.JComboBox<EmployeeDTO> president_employee;
    private javax.swing.JLabel range;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton reload_button;
    private javax.swing.JComboBox<EmployeeDTO> root_employee;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JButton search_object;
    private javax.swing.JPanel search_panel;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JComboBox<EmployeeDTO> tesurer_employee;
    private javax.swing.JLabel total;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
}
