/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views;

import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jsoftware.com.jblue.controllers.compc.TableController;
import jsoftware.com.jblue.model.dao.TableComponentDAO;
import jsoftware.com.jblue.views.framework.SimpleView;
import jsoftware.com.jblue.views.framework.TableSearchViewModel;
import jsoftware.com.jutil.db.JDBMapObject;
import jsoftware.com.jutil.swingw.modelos.JTableModel;

/**
 *
 * @author juanp
 */
public final class CatalogViewerView<T extends JDBMapObject> extends SimpleView implements TableSearchViewModel {

    private static final long serialVersionUID = 1L;

    private final JTableModel model;
    private final TableController<T> controller;

    /**
     * Creates new form CatalogViewerView
     */
    public CatalogViewerView(JTableModel model, TableComponentDAO<T> dao) {
        initComponents();
        this.controller = new TableController<>(this, dao);
        this.controller.loadData();
        this.model = model;
        this.objects_table.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        table_panel = new javax.swing.JPanel();
        search_items_table = new javax.swing.JPanel();
        search_field = new javax.swing.JTextField();
        jPanel23 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        reload_button = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        count_label = new javax.swing.JLabel();
        count_field = new javax.swing.JLabel();
        range_field = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        total_label = new javax.swing.JLabel();
        total_field = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        table_panel.setName("table_panel"); // NOI18N
        table_panel.setPreferredSize(new java.awt.Dimension(1000, 500));
        table_panel.setLayout(new java.awt.BorderLayout(5, 5));

        search_items_table.setMinimumSize(new java.awt.Dimension(980, 30));
        search_items_table.setName("search_items_table"); // NOI18N
        search_items_table.setPreferredSize(new java.awt.Dimension(500, 30));
        search_items_table.setLayout(new java.awt.BorderLayout(5, 5));

        search_field.setName("buscador"); // NOI18N
        search_items_table.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel23.setName("jPanel23"); // NOI18N
        jPanel23.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel23.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/Bundle"); // NOI18N
        back_button.setActionCommand(bundle.getString("CatalogViewerView.back_button.actionCommand")); // NOI18N
        back_button.setName("back_button"); // NOI18N
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(back_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand(bundle.getString("CatalogViewerView.next_button.actionCommand")); // NOI18N
        next_button.setName("next_button"); // NOI18N
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel23.add(next_button);

        search_items_table.add(jPanel23, java.awt.BorderLayout.LINE_END);

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand(bundle.getString("CatalogViewerView.reload_button.actionCommand")); // NOI18N
        reload_button.setName("reload_button"); // NOI18N
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        search_items_table.add(reload_button, java.awt.BorderLayout.LINE_START);

        table_panel.add(search_items_table, java.awt.BorderLayout.NORTH);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        objects_table.setName("objects_table"); // NOI18N
        objects_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        objects_table.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(objects_table);

        table_panel.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        add(table_panel, java.awt.BorderLayout.CENTER);

        status_bar_panel.setName("status_bar_panel"); // NOI18N
        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setName("jPanel32"); // NOI18N
        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        count_label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count_label.setText(bundle.getString("CatalogViewerView.count_label.text")); // NOI18N
        count_label.setName("count_label"); // NOI18N
        jPanel32.add(count_label, java.awt.BorderLayout.CENTER);

        count_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count_field.setText(bundle.getString("CatalogViewerView.count_field.text")); // NOI18N
        count_field.setToolTipText(bundle.getString("CatalogViewerView.count_field.toolTipText")); // NOI18N
        count_field.setName("count_field"); // NOI18N
        count_field.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count_field, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range_field.setText(bundle.getString("CatalogViewerView.range_field.text")); // NOI18N
        range_field.setToolTipText(bundle.getString("CatalogViewerView.range_field.toolTipText")); // NOI18N
        range_field.setName("range_field"); // NOI18N
        status_bar_panel.add(range_field, java.awt.BorderLayout.CENTER);

        jPanel29.setName("jPanel29"); // NOI18N
        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        total_label.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        total_label.setText(bundle.getString("CatalogViewerView.total_label.text")); // NOI18N
        total_label.setName("total_label"); // NOI18N
        jPanel29.add(total_label, java.awt.BorderLayout.CENTER);

        total_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_field.setText(bundle.getString("CatalogViewerView.total_field.text")); // NOI18N
        total_field.setToolTipText(bundle.getString("CatalogViewerView.total_field.toolTipText")); // NOI18N
        total_field.setName("total_field"); // NOI18N
        total_field.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total_field, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        add(status_bar_panel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents

    @Override
    public void build() {
    }

    @Override
    public void events() {
    }

    @Override
    public void components() {
    }

    @Override
    public void initialState() {
        if (isVisible()) {
            controller.loadData();
        } else {
            model.removeAllRows();
        }
    }

    @Override
    public void finalState() {
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JLabel count_field;
    private javax.swing.JLabel count_label;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton next_button;
    private javax.swing.JTable objects_table;
    private javax.swing.JLabel range_field;
    private javax.swing.JButton reload_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_items_table;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JPanel table_panel;
    private javax.swing.JLabel total_field;
    private javax.swing.JLabel total_label;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    @Override
    public String getTextSearchTable() {
        return search_field.getText().trim().replace(" ", "");
    }

    @Override
    public JTable getTable() {
        return objects_table;
    }

    @Override
    public void setViewShow(int i) {
    }

    @Override
    public int getViewShow() {
        return -1;
    }

    @Override
    public <T extends JDBMapObject> void setObjectSearch(T o) {
    }

    @Override
    public <T extends JDBMapObject> T getObjectSearch() {
        return null;
    }

    @Override
    public void setRowsData(String... info) {
        count_field.setText(info[0]);
        range_field.setText(info[1]);
        total_field.setText(info[2]);
    }

    @Override
    public void setScreenTableInfo() {
    }

    @Override
    public DefaultTableModel getModel() {
        return model;
    }

}
