/*
 * Copyright (C) 2024 juan pablo campos casasanero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views;

import java.awt.CardLayout;
import java.util.Map;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import jsoftware.com.jblue.model.dto.PaymentConceptDTO;
import jsoftware.com.jblue.util.GraphicsUtils;
import jsoftware.com.jblue.views.framework.DBObjectValues;
import jsoftware.com.jblue.views.framework.DBView;
import jsoftware.com.jutil.db.JDBMapObject;
import jsoftware.com.jutil.swingw.modelos.JTableModel;
import org.apache.commons.collections4.map.HashedMap;

/**
 *
 * @author juan pablo campos casasanero
 */
public final class PaymentConceptView extends DBView<PaymentConceptDTO> implements DBObjectValues<PaymentConceptDTO> {

    private static final long serialVersionUID = 1L;

    private JTableModel model;
    private PaymentConceptDTO object_search;
    private final CardLayout ly;

    /**
     * Creates new form NewTipoDePagos
     */
    public PaymentConceptView() {
        initComponents();
        ly = (CardLayout) root_panel.getLayout();
        build();
    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void components() {
        super.components(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void events() {
        date_end_field.addItemListener((e) -> {
            GraphicsUtils.disableTreeLock(date_end_field.isSelected(), date_panel_field);
        });

    }

    @Override
    public void initialState() {
        GraphicsUtils.disableTreeLock(date_end_field.isSelected(), date_panel_field);
    }

    @Override
    public void finalState() {
        super.finalState(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tools_panel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel15 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        p_fields = new javax.swing.JPanel();
        p_fields_1 = new javax.swing.JPanel();
        p_concept = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        type_field = new javax.swing.JTextField();
        p_current_price = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        price_field = new javax.swing.JTextField();
        p_previous_price = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        price_field1 = new javax.swing.JTextField();
        p_mandatory_payment = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        p_module = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        date_end_field = new javax.swing.JCheckBox();
        date_panel_field = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        p_description = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        description_fiel = new javax.swing.JTextArea();
        options_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btn_recargar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btn_ant = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        panel_izq = new javax.swing.JPanel();
        tabla_usuarios = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        count_field = new javax.swing.JLabel();
        range_field = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total_field = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(900, 500));
        setName("Conceptos de pago"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        tools_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        tools_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jToggleButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/desbloquear.png"))); // NOI18N
        tools_panel.add(jToggleButton2, java.awt.BorderLayout.WEST);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        register_button.setText("Registrar Tipo de Tomas");
        register_button.setActionCommand("register_view");
        jPanel15.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText("Consultar los Tipos de Tomas");
        search_button.setActionCommand("search_view");
        jPanel15.add(search_button);

        tools_panel.add(jPanel15, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        tools_panel.add(jButton2, java.awt.BorderLayout.EAST);

        add(tools_panel, java.awt.BorderLayout.NORTH);

        root_panel.setName("Otros tipos de pagos"); // NOI18N
        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout(10, 10));

        p_fields.setPreferredSize(new java.awt.Dimension(500, 620));
        p_fields.setLayout(new java.awt.BorderLayout());

        p_fields_1.setLayout(new java.awt.GridLayout(12, 0));

        p_concept.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Motivo: ");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));
        p_concept.add(jLabel2, java.awt.BorderLayout.WEST);

        type_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        type_field.setName("Tipo de toma"); // NOI18N
        p_concept.add(type_field, java.awt.BorderLayout.CENTER);

        p_fields_1.add(p_concept);

        p_current_price.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Precio Actual:");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 20));
        p_current_price.add(jLabel3, java.awt.BorderLayout.WEST);

        price_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        price_field.setName("Costo"); // NOI18N
        p_current_price.add(price_field, java.awt.BorderLayout.CENTER);

        p_fields_1.add(p_current_price);

        p_previous_price.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText("Precio Anterior:");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 20));
        p_previous_price.add(jLabel6, java.awt.BorderLayout.WEST);

        price_field1.setEditable(false);
        price_field1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        price_field1.setName("Costo"); // NOI18N
        p_previous_price.add(price_field1, java.awt.BorderLayout.CENTER);

        p_fields_1.add(p_previous_price);

        p_mandatory_payment.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel7.setText("Pago Obligatorio:");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        p_mandatory_payment.add(jLabel7, java.awt.BorderLayout.WEST);
        p_mandatory_payment.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        p_fields_1.add(p_mandatory_payment);

        p_module.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel8.setText("Modulo Asignado:");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 20));
        p_module.add(jLabel8, java.awt.BorderLayout.WEST);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        p_module.add(jComboBox1, java.awt.BorderLayout.CENTER);

        p_fields_1.add(p_module);

        date_end_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        date_end_field.setText("Poner fecha limite");
        date_end_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        p_fields_1.add(date_end_field);

        date_panel_field.setLayout(new java.awt.BorderLayout());

        jLabel4.setText("F. Limite");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 30));
        date_panel_field.add(jLabel4, java.awt.BorderLayout.WEST);

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd/MM/yyyy"))));
        date_panel_field.add(jFormattedTextField1, java.awt.BorderLayout.CENTER);

        p_fields_1.add(date_panel_field);

        p_fields.add(p_fields_1, java.awt.BorderLayout.CENTER);

        p_description.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("Descripcion");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 20));
        p_description.add(jLabel5, java.awt.BorderLayout.WEST);

        description_fiel.setColumns(20);
        description_fiel.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        description_fiel.setRows(5);
        jScrollPane1.setViewportView(description_fiel);

        p_description.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        p_fields.add(p_description, java.awt.BorderLayout.SOUTH);

        register_panel.add(p_fields, java.awt.BorderLayout.CENTER);

        options_panel.setPreferredSize(new java.awt.Dimension(500, 80));
        options_panel.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText("Guardar");
        jPanel3.add(save_button);

        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/sincronizar.png"))); // NOI18N
        update_button.setText("Actualizar");
        jPanel3.add(update_button);

        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText("Eliminar");
        jPanel3.add(delete_button);

        options_panel.add(jPanel3);

        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText("Cancelar");
        options_panel.add(cancel_button);

        register_panel.add(options_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "register");

        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout());

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 40));
        jPanel5.setLayout(new java.awt.BorderLayout(10, 10));

        btn_recargar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        btn_recargar.setPreferredSize(new java.awt.Dimension(200, 30));
        jPanel5.add(btn_recargar, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel6.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2));

        btn_ant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        btn_ant.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(btn_ant);

        btn_sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        btn_sig.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(btn_sig);

        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        search_panel.add(jPanel5, java.awt.BorderLayout.NORTH);

        panel_izq.setPreferredSize(new java.awt.Dimension(500, 700));
        panel_izq.setLayout(new java.awt.BorderLayout(10, 10));

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tabla_usuarios.setViewportView(objects_table);

        panel_izq.add(tabla_usuarios, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_izq, java.awt.BorderLayout.CENTER);

        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No.");
        jPanel32.add(jLabel18, java.awt.BorderLayout.CENTER);

        count_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count_field.setText("0");
        count_field.setToolTipText("Numero de pagos hechos.");
        count_field.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count_field, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range_field.setText("0 - 0");
        range_field.setToolTipText("");
        status_bar_panel.add(range_field, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total:");
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total_field.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total_field.setText("0");
        total_field.setToolTipText("Numero de pagos hechos.");
        total_field.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total_field, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ant;
    private javax.swing.JButton btn_recargar;
    private javax.swing.JButton btn_sig;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel count_field;
    private javax.swing.JCheckBox date_end_field;
    private javax.swing.JPanel date_panel_field;
    private javax.swing.JButton delete_button;
    private javax.swing.JTextArea description_fiel;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTable objects_table;
    private javax.swing.JPanel options_panel;
    private javax.swing.JPanel p_concept;
    private javax.swing.JPanel p_current_price;
    private javax.swing.JPanel p_description;
    private javax.swing.JPanel p_fields;
    private javax.swing.JPanel p_fields_1;
    private javax.swing.JPanel p_mandatory_payment;
    private javax.swing.JPanel p_module;
    private javax.swing.JPanel p_previous_price;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JTextField price_field;
    private javax.swing.JTextField price_field1;
    private javax.swing.JLabel range_field;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_panel;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JScrollPane tabla_usuarios;
    private javax.swing.JPanel tools_panel;
    private javax.swing.JLabel total_field;
    private javax.swing.JTextField type_field;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    @Override
    public String getTextSearchTable() {
        return search_field.getText().trim().replace(" ", "");
    }

    @Override
    public JTable getTable() {
        return objects_table;
    }

    @Override
    public DefaultTableModel getModel() {
        return model;
    }

    @Override
    public void setViewShow(int view_show) {
        this.view_show = view_show;
        String op = switch (view_show) {
            case 2:
                yield search_panel.getName();
            default:
                yield register_panel.getName();
        };
        ly.show(root_panel, op);
    }

    @Override
    public int getViewShow() {
        return view_show;
    }

    @Override
    public void setObjectSearch(JDBMapObject o) {
        this.object_search = (PaymentConceptDTO) o;
    }

    @Override
    public PaymentConceptDTO getObjectSearch() {
        return object_search;
    }

    @Override
    public void setRowsData(String... info) {
        count_field.setText(info[0]);
        range_field.setText(info[1]);
        total_field.setText(info[2]);

    }

    @Override
    public void setScreenTableInfo() {

    }

    @Override
    public boolean isValuesOK() {
        return true;
    }

    @Override
    public PaymentConceptDTO getValues(boolean update) {
        Map<String, Object> map = new HashedMap<>(7);
        if (update) {
        } else {
        }
        return new PaymentConceptDTO(map);
    }

}
