/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import jsoftware.com.jblue.controllers.FactoryController;
import jsoftware.com.jblue.controllers.compc.TableController;
import jsoftware.com.jblue.model.dtos.OStreet;
import jsoftware.com.jblue.model.dtos.Objects;
import jsoftware.com.jblue.model.factories.CacheFactory;
import jsoftware.com.jblue.model.factories.TableModelFactory;
import jsoftware.com.jblue.util.Filters;
import jsoftware.com.jblue.util.Formats;
import jsoftware.com.jblue.views.framework.DBValuesModel;
import jsoftware.com.jblue.views.framework.DBView;
import jsoftware.com.jutil.swingw.modelos.JTableModel;

/**
 *
 * @author juan-campos
 */
public final class StreetsView extends DBView implements DBValuesModel {

    private static final long serialVersionUID = 1L;

    private OStreet object_search;
    private final CardLayout ly;

    /**
     * Creates new form NewCalles
     */
    public StreetsView() {
        initComponents();
        model = TableModelFactory.getStreetTableModel();
        objects_table.setModel(model);
        ly = (CardLayout) root_panel.getLayout();
        ly.show(root_panel, register_panel.getName());
        build();
    }

    /**
     *
     */
    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    /**
     *
     */
    @Override
    public void components() {
        streed_name_field.setText(null);
        object_search = null;
        pop_menu.add(edit_item);
        pop_menu.add(delete_item);
        objects_table.setComponentPopupMenu(pop_menu);
    }

    /**
     *
     */
    @Override
    public void events() {
        controller = FactoryController.getStreetsController(this);
        table_controller = new TableController(this, CacheFactory.STREETS);
        back_button.addActionListener(table_controller);
        next_button.addActionListener(table_controller);
        reload_button.addActionListener(table_controller);
        register_button.addActionListener(table_controller);
        search_button.addActionListener(table_controller);
        //
        save_button.addActionListener(controller);
        update_button.addActionListener(controller);
        delete_button.addActionListener(controller);
        cancel_button.addActionListener(controller);
        maps_button.addActionListener(controller);
        //
        objects_table.addMouseListener(table_controller);
        //

    }

    /**
     *
     */
    @Override
    public void initialState() {
        object_search = null;
        streed_name_field.setText(null);
        streed_location_field.setText(null);
        view_show = 1;
        save_button.setEnabled(true);
        update_button.setEnabled(false);
        delete_button.setEnabled(false);
    }

    /**
     *
     */
    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pop_menu = new javax.swing.JPopupMenu();
        edit_item = new javax.swing.JMenuItem();
        delete_item = new javax.swing.JMenuItem();
        tools_panel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel15 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        streed_name_field = new javax.swing.JTextField();
        jPanel13 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        streed_location_field = new javax.swing.JTextField();
        maps_button = new javax.swing.JButton();
        option_panel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        reload_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        panel_izq = new javax.swing.JPanel();
        tabla_usuarios = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        edit_item.setText("Editar");
        pop_menu.add(edit_item);

        delete_item.setText("Eliminar");
        pop_menu.add(delete_item);

        setName("Calles"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        tools_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        tools_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jToggleButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/desbloquear.png"))); // NOI18N
        tools_panel.add(jToggleButton2, java.awt.BorderLayout.WEST);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        register_button.setText("Registrar Calle");
        register_button.setActionCommand("register_view");
        jPanel15.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText("Consultar Calles");
        search_button.setActionCommand("search_view");
        jPanel15.add(search_button);

        tools_panel.add(jPanel15, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        tools_panel.add(jButton2, java.awt.BorderLayout.EAST);

        add(tools_panel, java.awt.BorderLayout.NORTH);

        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(500, 620));
        jPanel1.setLayout(new java.awt.GridLayout(13, 1, 0, 10));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos de la Calle");
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel1.add(jLabel4);

        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Nombre:");
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel8.add(jLabel2, java.awt.BorderLayout.WEST);

        streed_name_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        streed_name_field.setName("Nombre"); // NOI18N
        jPanel8.add(streed_name_field, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel8);

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("Ubicacion:");
        jLabel5.setOpaque(true);
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 30));
        jPanel13.add(jLabel5, java.awt.BorderLayout.WEST);

        streed_location_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        streed_location_field.setName("Numero"); // NOI18N
        jPanel13.add(streed_location_field, java.awt.BorderLayout.CENTER);

        maps_button.setText("maps");
        maps_button.setActionCommand("google-maps");
        jPanel13.add(maps_button, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel13);

        register_panel.add(jPanel1, java.awt.BorderLayout.CENTER);

        option_panel.setPreferredSize(new java.awt.Dimension(500, 80));
        option_panel.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        save_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText("Guardar");
        save_button.setActionCommand("save");
        jPanel2.add(save_button);

        update_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/sincronizar.png"))); // NOI18N
        update_button.setText("Actualizar");
        update_button.setActionCommand("update");
        jPanel2.add(update_button);

        delete_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setActionCommand("delete");
        jPanel2.add(delete_button);

        option_panel.add(jPanel2);

        cancel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText("Cancelar");
        cancel_button.setActionCommand("cancel");
        option_panel.add(cancel_button);

        register_panel.add(option_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "register");

        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel5.setMinimumSize(new java.awt.Dimension(500, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 30));
        jPanel5.setLayout(new java.awt.BorderLayout(10, 10));

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand("reload");
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(reload_button, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel6.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        back_button.setActionCommand("back");
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(back_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand("next");
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(next_button);

        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        search_panel.add(jPanel5, java.awt.BorderLayout.NORTH);

        panel_izq.setPreferredSize(new java.awt.Dimension(500, 700));
        panel_izq.setLayout(new java.awt.BorderLayout(10, 10));

        objects_table.setAutoCreateRowSorter(true);
        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        objects_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        objects_table.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        objects_table.setShowGrid(true);
        objects_table.getTableHeader().setReorderingAllowed(false);
        tabla_usuarios.setViewportView(objects_table);

        panel_izq.add(tabla_usuarios, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_izq, java.awt.BorderLayout.CENTER);

        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No.");
        jPanel32.add(jLabel18, java.awt.BorderLayout.CENTER);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        count.setToolTipText("Numero de pagos hechos.");
        count.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range.setText("0 - 0");
        range.setToolTipText("");
        status_bar_panel.add(range, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total:");
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setToolTipText("Numero de pagos hechos.");
        total.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel count;
    private javax.swing.JButton delete_button;
    private javax.swing.JMenuItem delete_item;
    private javax.swing.JMenuItem edit_item;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JButton maps_button;
    private javax.swing.JButton next_button;
    private javax.swing.JTable objects_table;
    private javax.swing.JPanel option_panel;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JPopupMenu pop_menu;
    private javax.swing.JLabel range;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton reload_button;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_panel;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JTextField streed_location_field;
    private javax.swing.JTextField streed_name_field;
    private javax.swing.JScrollPane tabla_usuarios;
    private javax.swing.JPanel tools_panel;
    private javax.swing.JLabel total;
    private javax.swing.JButton update_button;
    // End of variables declaration//GEN-END:variables
    private final JTableModel model;

    /**
     *
     * @return
     */
    @Override
    public boolean isValuesOk() {
        boolean rt = Filters.isNullOrBlank(streed_name_field.getText());
        String mess = "El campo %s no es valido";
        if (rt) {
            JOptionPane.showMessageDialog(this, mess, "Campos Validos", JOptionPane.ERROR_MESSAGE);
        }
        return !rt;
    }

    /**
     *
     * @param update
     * @return
     */
    @Override
    public String[] getDbValues(boolean update) {
        String _name = streed_name_field.getText();
        return Formats.getDBFormatInputArray(_name);
    }

    /**
     *
     * @return
     */
    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    /**
     *
     * @return
     */
    @Override
    public String getTextSearchTable() {
        return Filters.clearText(search_field.getText());
    }

    /**
     *
     * @return
     */
    @Override
    public JTable getTable() {
        return objects_table;
    }

    /**
     *
     * @return
     */
    @Override
    public JTableModel getModel() {
        return model;
    }

    /**
     *
     * @param view_show
     */
    @Override
    public void setViewShow(int view_show) {
        this.view_show = view_show;
        String op = switch (view_show) {
            case 2:
                yield search_panel.getName();
            default:
                yield register_panel.getName();
        };
        ly.show(root_panel, op);
    }

    /**
     *
     * @return
     */
    @Override
    public int getViewShow() {
        return view_show;
    }

    /**
     *
     * @return
     */
    @Override
    public OStreet getObjectSearch() {
        return object_search;
    }

    /**
     *
     * @param o
     */
    @Override
    public void setObjectSearch(Objects o) {
        object_search = (OStreet) o;
    }

    /**
     *
     * @param info
     */
    @Override
    public void setRowsData(String... info) {
        count.setText(info[0]);
        range.setText(info[1]);
        total.setText(info[2]);
    }

    /**
     *
     */
    @Override
    public void setScreenTableInfo() {
        streed_name_field.setText(object_search.getNombre());
        save_button.setEnabled(false);
        update_button.setEnabled(true);
        delete_button.setEnabled(true);
    }
}
