/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import javax.swing.DefaultListModel;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import jsoftware.com.jblue.model.dto.UserDocumentDTO;
import jsoftware.com.jblue.sys.app.AppFiles;
import jsoftware.com.jblue.views.framework.AbstractProcessView;
import jsoftware.com.jblue.views.framework.ProcessViewBuilder;

/**
 *
 * @author juanp
 */
public class ValidationProcessView extends AbstractProcessView<UserDocumentDTO> {

    private DefaultListModel<File> model;

    /**
     * Creates new form ValidationProcess
     */
    public ValidationProcessView(ProcessViewBuilder builder) {
        super(builder);
        initComponents();
        this.model = new DefaultListModel<>();
        document_list.setModel(model);
        this.add_doc1.addActionListener((e) -> {
            File file = getSelectFile();
            addItem(add_doc1, file);
            System.out.println(file.getAbsoluteFile());
        });
        this.add_doc2.addActionListener((e) -> {
            File file = getSelectFile();
            addItem(add_doc2, file);
            System.out.println(file.getAbsoluteFile());
        });
        this.add_doc3.addActionListener((e) -> {
            File file = getSelectFile();
            addItem(add_doc3, file);
            System.out.println(file.getAbsoluteFile());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file_chooser = new javax.swing.JFileChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        document_list = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        add_doc1 = new javax.swing.JButton();
        add_doc2 = new javax.swing.JButton();
        add_doc3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        file_chooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        file_chooser.setMinimumSize(new java.awt.Dimension(900, 700));
        file_chooser.setName("file_chooser"); // NOI18N
        file_chooser.setPreferredSize(new java.awt.Dimension(900, 700));

        setName("Validacion De Usuario"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setName("jPanel1"); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 40));
        jPanel1.setLayout(new java.awt.BorderLayout(10, 10));

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("jsoftware/com/jblue/views/Bundle"); // NOI18N
        jLabel1.setText(bundle.getString("ValidationProcessView.jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jTextField1.setText(bundle.getString("ValidationProcessView.jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        jPanel1.add(jTextField1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setName("jPanel2"); // NOI18N
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 20, 20));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        document_list.setName("document_list"); // NOI18N
        jScrollPane1.setViewportView(document_list);

        jPanel2.add(jScrollPane1);

        jPanel3.setName("jPanel3"); // NOI18N
        jPanel3.setLayout(new java.awt.GridLayout(12, 0));

        add_doc1.setText(bundle.getString("ValidationProcessView.Añadir.text")); // NOI18N
        add_doc1.setActionCommand(bundle.getString("ValidationProcessView.add_doc1.actionCommand")); // NOI18N
        add_doc1.setName("Añadir"); // NOI18N
        jPanel3.add(add_doc1);

        add_doc2.setText(bundle.getString("ValidationProcessView.Quitar.text")); // NOI18N
        add_doc2.setActionCommand(bundle.getString("ValidationProcessView.add_doc2.actionCommand")); // NOI18N
        add_doc2.setName("Quitar"); // NOI18N
        jPanel3.add(add_doc2);

        add_doc3.setText(bundle.getString("ValidationProcessView.add_doc3.text")); // NOI18N
        add_doc3.setActionCommand(bundle.getString("ValidationProcessView.add_doc3.actionCommand")); // NOI18N
        add_doc3.setName("add_doc3"); // NOI18N
        jPanel3.add(add_doc3);

        jLabel2.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel2.setName(""); // NOI18N
        jPanel3.add(jLabel2);

        jLabel4.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel4.setName(""); // NOI18N
        jPanel3.add(jLabel4);

        jLabel5.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel5.setName(""); // NOI18N
        jPanel3.add(jLabel5);

        jLabel6.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel6.setName(""); // NOI18N
        jPanel3.add(jLabel6);

        jLabel7.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel7.setName(""); // NOI18N
        jPanel3.add(jLabel7);

        jLabel8.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel8.setName(""); // NOI18N
        jPanel3.add(jLabel8);

        jLabel9.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel9.setName(""); // NOI18N
        jPanel3.add(jLabel9);

        jLabel10.setText(bundle.getString("ValidationProcessView.text")); // NOI18N
        jLabel10.setName(""); // NOI18N
        jPanel3.add(jLabel10);

        jButton3.setText(bundle.getString("ValidationProcessView.jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jPanel3.add(jButton3);

        jPanel2.add(jPanel3);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_doc1;
    private javax.swing.JButton add_doc2;
    private javax.swing.JButton add_doc3;
    private javax.swing.JList<File> document_list;
    private javax.swing.JFileChooser file_chooser;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public File getSelectFile() {
        int res = file_chooser.showSaveDialog(this);
        if (res == JFileChooser.APPROVE_OPTION || res == JFileChooser.SAVE_DIALOG) {
            return file_chooser.getSelectedFile();
        }
        return null;
    }
// Dentro de ValidationProcessView (o la clase que contenga los botones)

// Necesitas una función auxiliar para obtener la extensión del archivo
    private String getFileExtension(File file) {
        String name = file.getName();
        int lastIndexOf = name.lastIndexOf(".");
        if (lastIndexOf == -1) {
            return ""; // No tiene extensión
        }
        return name.substring(lastIndexOf + 1);
    }

    public void addItem(JButton e, File file) {
        // 1. Obtener el nombre base del documento usando ActionCommand (Mejora)
        String nameBase = e.getActionCommand();

        if (file == null) {
            // Manejar el caso donde el diálogo fue cancelado
            return;
        }

        // 2. Lógica de deduplicación (Corregida: solo se cuenta el sufijo)
        // Nota: Esta lógica aún asume que document_list contiene objetos que
        // tienen un método getName() que devuelve el nombre de la copia.
        int count = 1;
        String namePrefix = nameBase.replaceAll(" ", "_").toUpperCase(); // Limpia el nombre base

        for (int j = 0; j < document_list.getModel().getSize(); j++) {
            // ASUMIMOS que el elemento en el modelo es un File o un objeto que expone el nombre.
            // Si el nombre en la lista coincide con el prefijo, incrementamos el contador
            // Esto previene sobrescribir: IDENTIFICACION1, IDENTIFICACION2, etc.
            if (document_list.getModel().getElementAt(j).getName().startsWith(namePrefix)) {
                count++;
            }
        }

        // 3. Crear el nombre final, incluyendo la extensión original.
        String extension = getFileExtension(file);
        String finalName = namePrefix + count + (extension.isEmpty() ? "" : "." + extension);

        // 4. Llamar al método de copia, pasando el nombre deseado
        File f = copySelectedFileToProgramDirectory(this, file_chooser, file, finalName);

        if (f != null) {
            // 5. Agregar el archivo copiado (f) al modelo.
            // Es crucial agregar el archivo 'f' (el copiado) y no 'file' (el original).
            model.addElement(f);
            System.out.println("Archivo copiado y registrado: " + finalName);
        }
    }
    // Reemplaza la versión anterior por esta (debería estar dentro de ValidationProcessView o un servicio)

    public File copySelectedFileToProgramDirectory(Component parentComponent, JFileChooser fileChooser, File sourceFile, String desiredFileName) {

        // Nota: Eliminamos la necesidad de showOpenDialog y getSelectedFile,
        // ya que eso se hizo previamente en addItem.
        if (sourceFile == null || !sourceFile.exists()) {
            JOptionPane.showMessageDialog(parentComponent, "El archivo de origen no existe.", "Error de Archivo", JOptionPane.ERROR_MESSAGE);
            return null;
        }

        try {
            // 1. Definir rutas de origen y destino usando java.nio.file.Path
            Path origen = sourceFile.toPath();

            // 2. Construir la ruta de destino usando el nombre proporcionado
            Path destinoDir = Paths.get(AppFiles.DIR_PROG_USUARIOS);

            // **APLICAMOS EL CAMBIO DE NOMBRE AQUÍ:**
            Path destino = destinoDir.resolve(desiredFileName);

            // 3. Asegurar que la carpeta de destino exista
            if (!Files.exists(destinoDir)) {
                Files.createDirectories(destinoDir);
            }

            // 4. Copiar el archivo.
            Files.copy(origen, destino, StandardCopyOption.REPLACE_EXISTING);

            // 5. Notificar y retornar el archivo copiado
            JOptionPane.showMessageDialog(parentComponent,
                    "Archivo copiado exitosamente a:\n" + destino.toString(),
                    "Éxito", JOptionPane.INFORMATION_MESSAGE);

            return destino.toFile();

        } catch (IOException e) {
            System.err.println("Error al copiar el archivo: " + e.getMessage());
            e.printStackTrace();

            JOptionPane.showMessageDialog(parentComponent,
                    "Error I/O al copiar el archivo. Revise permisos o si el archivo está en la nube.",
                    "Error de Operación", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }
}
