/*
 * Copyright (C) 2024 juan pablo campos casasanero
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views;

import java.awt.event.ActionListener;
import java.time.LocalDate;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import jsoftware.com.jblue.controllers.viewc.ContableController;
import jsoftware.com.jblue.views.framework.OptionMenuModel;

/**
 *
 * @author juan pablo campos casasanero
 */
public class VContabilidad extends javax.swing.JPanel implements OptionMenuModel {

    private static final long serialVersionUID = 1L;

    public ContableController controller;

    /**
     * Creates new form VContabilidad
     */
    public VContabilidad() {
        initComponents();
        option = mkButton(getName(), null, null);
        controller = new ContableController(this);
        loadDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        total_day_field = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        total_month_field = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        total_year_field = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        day_field = new javax.swing.JComboBox<>();
        jPanel8 = new javax.swing.JPanel();
        Mes = new javax.swing.JLabel();
        month_field = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        year_field = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        total_field = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();

        setMinimumSize(new java.awt.Dimension(750, 600));
        setName("Contabilidad"); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 600));
        setLayout(new java.awt.GridLayout(12, 1, 10, 10));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel1.setText("Saldo del dia acumulado: ");
        jLabel1.setToolTipText("");
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        total_day_field.setEditable(false);
        total_day_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel1.add(total_day_field, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Saldo del mes acumulado: ");
        jLabel2.setToolTipText("");
        jLabel2.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel2.add(jLabel2, java.awt.BorderLayout.WEST);

        total_month_field.setEditable(false);
        total_month_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel2.add(total_month_field, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Saldo del año acumulado: ");
        jLabel3.setToolTipText("");
        jLabel3.setPreferredSize(new java.awt.Dimension(200, 19));
        jPanel3.add(jLabel3, java.awt.BorderLayout.WEST);

        total_year_field.setEditable(false);
        total_year_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel3.add(total_year_field, java.awt.BorderLayout.CENTER);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel4.setText("Consultar Fecha");
        jLabel4.setToolTipText("");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 19));
        jPanel4.add(jLabel4, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.GridLayout(1, 0));

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel6.setText("Dia");
        jLabel6.setPreferredSize(new java.awt.Dimension(10, 15));
        jPanel7.add(jLabel6, java.awt.BorderLayout.NORTH);

        day_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        day_field.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel7.add(day_field, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        Mes.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        Mes.setText("Mes");
        Mes.setPreferredSize(new java.awt.Dimension(10, 15));
        jPanel8.add(Mes, java.awt.BorderLayout.NORTH);

        month_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        month_field.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel8.add(month_field, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Año");
        jLabel8.setPreferredSize(new java.awt.Dimension(10, 15));
        jPanel9.add(jLabel8, java.awt.BorderLayout.NORTH);

        year_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        year_field.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel9.add(year_field, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel9);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jButton1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jButton1.setText("Consultar");
        jPanel4.add(jButton1, java.awt.BorderLayout.EAST);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel5.setText("Saldo Total:");
        jLabel5.setToolTipText("");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 19));
        jPanel5.add(jLabel5, java.awt.BorderLayout.WEST);

        total_field.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jPanel5.add(total_field, java.awt.BorderLayout.CENTER);

        add(jPanel5);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        add(jPanel10);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mes;
    private javax.swing.JComboBox<String> day_field;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JComboBox<String> month_field;
    private javax.swing.JTextField total_day_field;
    private javax.swing.JTextField total_field;
    private javax.swing.JTextField total_month_field;
    private javax.swing.JTextField total_year_field;
    private javax.swing.JComboBox<String> year_field;
    // End of variables declaration//GEN-END:variables
private JButton option;

    @Override
    public JButton getOption() {
        return option;
    }

    @Override
    public void setEvenOption(ActionListener e) {
        if (option.getActionListeners().length < 1) {
            option.addActionListener(e);
        }

    }

    public void setDay_field(double day_field) {
        this.total_day_field.setText(String.valueOf(day_field));
    }

    public void setMonth_field(double month_field) {
        this.total_month_field.setText(String.valueOf(month_field));
    }

    public void setYear_field(double year_field) {
        this.total_year_field.setText(String.valueOf(year_field));
    }

    public void setTotal_field(double total_field) {
        this.total_field.setText(String.valueOf(total_field));
    }

    private void loadDate() {
        LocalDate ld = LocalDate.now();
        //
        dateList(day_field, 1, ld.getMonth().length(ld.isLeapYear()));
        day_field.setSelectedIndex(ld.getDayOfMonth() - 1);
        //
        dateList(month_field, 1, 12);
        month_field.setSelectedIndex(ld.getMonthValue()-1);
        //
        dateList(year_field, ld.getYear(), ld.getYear());
        year_field.setSelectedItem(ld.getYear());
    }

    private void dateList(JComboBox<String> com, int min, int max) {
        DefaultComboBoxModel<String> model = (DefaultComboBoxModel) com.getModel();
        for (int i = min; i <= max; i++) {
            model.addElement(String.valueOf(i));
        }
    }
}
