/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views;

import java.awt.CardLayout;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import jsoftware.com.jblue.controllers.FactoryController;
import jsoftware.com.jblue.model.dto.ProcessWrapperDTO;
import jsoftware.com.jblue.model.dto.StreetDTO;
import jsoftware.com.jblue.model.dto.UserDTO;
import jsoftware.com.jblue.model.dto.WaterIntakeTypesDTO;
import jsoftware.com.jblue.model.dto.WaterIntakesDTO;
import jsoftware.com.jblue.model.factories.TableModelFactory;
import jsoftware.com.jblue.util.Filters;
import jsoftware.com.jblue.views.framework.AbstractProcessView;
import jsoftware.com.jblue.views.framework.DBValuesMapModel;
import jsoftware.com.jblue.views.framework.ProcessViewBuilder;
import jsoftware.com.jblue.views.framework.TableSearchViewModel;
import jsoftware.com.jutil.db.JDBMapObject;
import jsoftware.com.jutil.swingw.modelos.JTableModel;

/**
 *
 * @author juanp
 */
public final class WaterIntakesView extends AbstractProcessView<WaterIntakesDTO> implements DBValuesMapModel, TableSearchViewModel {

    private static final long serialVersionUID = 1L;

    private final CardLayout ly;
    private final JTableModel model;
    private WaterIntakesDTO object_search;
    private UserDTO user_search;
    private WaterIntakeTypesDTO water_intake_types_search;
    private StreetDTO street1_search;
    private StreetDTO street2_search;

    private boolean process;

    /**
     * Creates new form WaterIntakesView
     */
    public WaterIntakesView(ProcessViewBuilder builder) {
        super(builder);
        initComponents();
        ly = (CardLayout) root_panel.getLayout();
        ly.show(root_panel, register_panel.getName());
        model = TableModelFactory.getWaterIntakesTableModel();
        controller = FactoryController.getWaterIntakesController(this);
        build();
    }

    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    @Override
    public void components() {
        objects_table.setModel(model);
    }

    @Override
    public void events() {
        back_button.addActionListener(table_controller);
        next_button.addActionListener(table_controller);
        reload_button.addActionListener(table_controller);
        objects_table.addMouseListener(table_controller);
        save_button.addActionListener(controller);

        update_button.addActionListener(controller);
        delete_button.addActionListener(controller);
        cancel_button.addActionListener(controller);
        register_button.addActionListener(table_controller);
        search_button.addActionListener(table_controller);
        //
        search_user_button.addActionListener(controller);
        search_street_button.addActionListener(controller);
        search_street2_button.addActionListener(controller);
        search_water_intake.addActionListener(controller);
    }

    @Override
    public void initialState() {
        object_search = null;
        view_show = 1;
        save_button.setEnabled(true);
        update_button.setEnabled(false);
        delete_button.setEnabled(false);
    }

    @Override
    public void finalState() {
        System.out.println(getProcessName() + ":");
        System.out.println("ES UN PROCESO?: " + isProcess() + " - " + getProcessId());
        north_panel.setVisible(!isProcess());
        p_status.setVisible(!isProcess());
        p_date_register.setVisible(!isProcess());
        p_date_update.setVisible(!isProcess());
        options_panel.setVisible(!isProcess());
        search_street2_button.setVisible(!isProcess());
        search_street_button.setVisible(!isProcess());
        search_user_button.setVisible(!isProcess());
        search_water_intake.setVisible(!isProcess());
    }

    @Override
    public WaterIntakesDTO getObjectSearch() {
        return object_search;
    }

    @Override
    public void setObjectSearch(JDBMapObject o) {
        object_search = (WaterIntakesDTO) o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel15 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        p_fields = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        search_user_button = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        search_water_intake = new javax.swing.JButton();
        water_intake_types_field = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        operation_cost_field = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        search_street_button = new javax.swing.JButton();
        street1_field = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        search_street2_button = new javax.swing.JButton();
        street2_field = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        location_field = new javax.swing.JTextField();
        p_status = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        status_field = new javax.swing.JComboBox<>();
        p_date_update = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        date_update_field = new javax.swing.JTextField();
        p_date_register = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        date_register = new javax.swing.JTextField();
        options_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        reload_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        panel_izq = new javax.swing.JPanel();
        tabla_usuarios = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setName("Tomas Registradas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jToggleButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/desbloquear.png"))); // NOI18N
        north_panel.add(jToggleButton2, java.awt.BorderLayout.WEST);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        register_button.setText("Registrar Tipo de Tomas");
        register_button.setActionCommand("register_view");
        jPanel15.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText("Consultar los Tipos de Tomas");
        search_button.setActionCommand("search_view");
        jPanel15.add(search_button);

        north_panel.add(jPanel15, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        north_panel.add(jButton2, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);

        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        p_fields.setPreferredSize(new java.awt.Dimension(500, 620));
        p_fields.setLayout(new java.awt.GridLayout(13, 0, 0, 10));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos del tipo de toma");
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 100));
        p_fields.add(jLabel4);

        jPanel12.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText("Titular");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel12.add(jLabel6, java.awt.BorderLayout.WEST);

        user_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        user_field.setName(""); // NOI18N
        jPanel12.add(user_field, java.awt.BorderLayout.CENTER);

        search_user_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_user_button.setToolTipText("Seleccionar titular");
        search_user_button.setActionCommand("search_user");
        search_user_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel12.add(search_user_button, java.awt.BorderLayout.LINE_END);

        p_fields.add(jPanel12);

        jPanel8.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Tipo Toma de agua");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel8.add(jLabel2, java.awt.BorderLayout.WEST);

        search_water_intake.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_water_intake.setToolTipText("Seleccionar Tipo de toma");
        search_water_intake.setActionCommand("search_water_intake_type");
        search_water_intake.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(search_water_intake, java.awt.BorderLayout.LINE_END);

        water_intake_types_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanel8.add(water_intake_types_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Costo de operacion");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel9.add(jLabel3, java.awt.BorderLayout.WEST);

        operation_cost_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        operation_cost_field.setName(""); // NOI18N
        jPanel9.add(operation_cost_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("Calle 1: ");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel10.add(jLabel5, java.awt.BorderLayout.WEST);

        search_street_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_street_button.setToolTipText("Seleccionar Calle 1");
        search_street_button.setActionCommand("search_street1");
        search_street_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel10.add(search_street_button, java.awt.BorderLayout.LINE_END);

        street1_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanel10.add(street1_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel10);

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel7.setText("Calle 2: ");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel13.add(jLabel7, java.awt.BorderLayout.WEST);

        search_street2_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_street2_button.setToolTipText("Seleccionar Calle 2");
        search_street2_button.setActionCommand("search_street2");
        search_street2_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel13.add(search_street2_button, java.awt.BorderLayout.LINE_END);

        street2_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jPanel13.add(street2_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel8.setText("Ubicacion");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel14.add(jLabel8, java.awt.BorderLayout.WEST);

        location_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        location_field.setName(""); // NOI18N
        jPanel14.add(location_field, java.awt.BorderLayout.CENTER);

        p_fields.add(jPanel14);

        p_status.setPreferredSize(new java.awt.Dimension(100, 35));
        p_status.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel9.setText("Estado: ");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 20));
        p_status.add(jLabel9, java.awt.BorderLayout.WEST);

        status_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        status_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Estado.", "Activo.", "Inactivo." }));
        status_field.setName(""); // NOI18N
        p_status.add(status_field, java.awt.BorderLayout.CENTER);

        p_fields.add(p_status);

        p_date_update.setPreferredSize(new java.awt.Dimension(100, 35));
        p_date_update.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel10.setText("Fecha de actualizacion");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 20));
        p_date_update.add(jLabel10, java.awt.BorderLayout.WEST);

        date_update_field.setEditable(false);
        date_update_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        date_update_field.setName(""); // NOI18N
        p_date_update.add(date_update_field, java.awt.BorderLayout.CENTER);

        p_fields.add(p_date_update);

        p_date_register.setPreferredSize(new java.awt.Dimension(100, 35));
        p_date_register.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de registro.");
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 20));
        p_date_register.add(jLabel11, java.awt.BorderLayout.WEST);

        date_register.setEditable(false);
        date_register.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        date_register.setName(""); // NOI18N
        p_date_register.add(date_register, java.awt.BorderLayout.CENTER);

        p_fields.add(p_date_register);

        register_panel.add(p_fields, java.awt.BorderLayout.CENTER);

        options_panel.setPreferredSize(new java.awt.Dimension(500, 80));
        options_panel.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        save_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText("Guardar");
        save_button.setActionCommand("save");
        jPanel3.add(save_button);

        update_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/sincronizar.png"))); // NOI18N
        update_button.setText("Actualizar");
        update_button.setActionCommand("update");
        jPanel3.add(update_button);

        delete_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setActionCommand("delete");
        jPanel3.add(delete_button);

        options_panel.add(jPanel3);

        cancel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText("Cancelar");
        cancel_button.setActionCommand("cancel");
        options_panel.add(cancel_button);

        register_panel.add(options_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "register");

        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.setLayout(new java.awt.BorderLayout(5, 5));

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand("reload");
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(reload_button, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel6.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        back_button.setActionCommand("back");
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(back_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand("next");
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(next_button);

        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        search_panel.add(jPanel5, java.awt.BorderLayout.NORTH);

        panel_izq.setPreferredSize(new java.awt.Dimension(500, 700));
        panel_izq.setLayout(new java.awt.BorderLayout(10, 10));

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setShowGrid(true);
        tabla_usuarios.setViewportView(objects_table);

        panel_izq.add(tabla_usuarios, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_izq, java.awt.BorderLayout.CENTER);

        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No.");
        jPanel32.add(jLabel18, java.awt.BorderLayout.CENTER);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        count.setToolTipText("Numero de pagos hechos.");
        count.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range.setText("0 - 0");
        range.setToolTipText("");
        status_bar_panel.add(range, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total:");
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setToolTipText("Numero de pagos hechos.");
        total.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel count;
    private javax.swing.JTextField date_register;
    private javax.swing.JTextField date_update_field;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField location_field;
    private javax.swing.JButton next_button;
    private javax.swing.JPanel north_panel;
    private javax.swing.JTable objects_table;
    private javax.swing.JTextField operation_cost_field;
    private javax.swing.JPanel options_panel;
    private javax.swing.JPanel p_date_register;
    private javax.swing.JPanel p_date_update;
    private javax.swing.JPanel p_fields;
    private javax.swing.JPanel p_status;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JLabel range;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton reload_button;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_panel;
    private javax.swing.JButton search_street2_button;
    private javax.swing.JButton search_street_button;
    private javax.swing.JButton search_user_button;
    private javax.swing.JButton search_water_intake;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JComboBox<String> status_field;
    private javax.swing.JComboBox<jsoftware.com.jblue.model.dto.StreetDTO> street1_field;
    private javax.swing.JComboBox<jsoftware.com.jblue.model.dto.StreetDTO> street2_field;
    private javax.swing.JScrollPane tabla_usuarios;
    private javax.swing.JLabel total;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField user_field;
    private javax.swing.JComboBox<jsoftware.com.jblue.model.dto.WaterIntakesDTO> water_intake_types_field;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    @Override
    public String getTextSearchTable() {
        return Filters.clearText(search_field.getText());
    }

    @Override
    public JTable getTable() {
        return objects_table;
    }

    @Override
    public JTableModel getModel() {
        return model;
    }

    @Override
    public void setViewShow(int view_show) {
        this.view_show = view_show;
        String op = switch (view_show) {
            case 2:
                yield search_panel.getName();
            default:
                yield register_panel.getName();
        };
        ly.show(root_panel, op);
    }

    @Override
    public int getViewShow() {
        return view_show;
    }

    @Override
    public boolean isValuesOk() {
        boolean ok = true;
        JTextField[] text_fields = {};
        for (JTextField i : text_fields) {
            if (Filters.isNullOrBlank(i.getText())) {
                JOptionPane.showMessageDialog(this, "El campo %s no es valido", "Campo no valido", JOptionPane.ERROR_MESSAGE);
                ok = false;
                break;
            }
        }
        return ok;
    }

    @Override
    public Map<String, Object> getValues(boolean update) {
        Map<String, Object> map;
        String _user = user_search.getId();
        String _water_inatke = water_intake_types_search.getId();
        String _cost_procedure = operation_cost_field.getText();
        String _street1 = street1_search.getId();
        String _street2 = street2_search.getId();
        String _location = location_field.getText();
        String _description = "";
        String _status = "1";
        if (isProcess()) {
            _status = status_field.getSelectedIndex() + "";
        }
        if (update) {
            map = saveUpdate(object_search, _cost_procedure, _water_inatke, _user, user_search.toString(), _street1, _street2, _location, _description, _status);
        } else {
            map = saveInsert(_cost_procedure, _water_inatke, _user, user_search.toString(), _street1, _street2, _location, _description, _status);
        }
        return map;
    }

    public Map<String, Object> saveInsert(
            String _cost_procedure, String _water_inatke, String _user, String user_name,
            String _street1, String _street2, String _location, String _description,
            String _status) {

        // Inicialización con capacidad inicial precisa (9 campos)
        Map<String, Object> map = new HashMap<>(10);

        // 1. Campos que deben ser Obligatorios y No Vacíos (Usamos putIfPresentAndNotBlank)
        // Aplicable a identificadores o valores centrales.
        Filters.putIfPresentAndNotBlank(map, "cost_procedure", _cost_procedure);
        Filters.putIfPresentAndNotBlank(map, "water_intake_id", _water_inatke);
        Filters.putIfPresentAndNotBlank(map, "user_id", _user);
        Filters.putIfPresentAndNotBlank(map, "user_name", user_name);
        Filters.putIfPresentAndNotBlank(map, "street1", _street1);

        // 2. Campos que podrían ser Opcionales o Aceptar Cadenas Vacías (Usamos putIfNotNull)
        // Aplicable a direcciones secundarias, descripciones o estados.
        Filters.putIfNotNull(map, "street2", _street2);
        Filters.putIfNotNull(map, "location", _location);
        Filters.putIfNotNull(map, "description", _description);
        Filters.putIfNotNull(map, "status", _status);

        return map;
    }

    public Map<String, Object> saveUpdate(
            WaterIntakesDTO originalProcedure, // Objeto con datos actuales
            String _cost_procedure, String _water_inatke, String _user, String _user_name,
            String _street1, String _street2, String _location, String _description,
            String _status) {

        // Verificar el objeto base (Fail-Fast)
        if (originalProcedure == null) {
            throw new NullPointerException("El objeto de procedimiento original (originalProcedure) no puede ser null para una actualización.");
        }

        Map<String, Object> map = new HashMap<>();

        // 1. Campos Obligatorios/Centrales
        // Compara el valor nuevo (ej. _cost_procedure) con el valor original (originalProcedure.getCostProcedure())
        Filters.addIfChanged(map, "cost_procedure", originalProcedure.getConstProcedure(), _cost_procedure);

        // Asumiendo que el campo 'water_intake_id' es un String en el objeto original:
        Filters.addIfChanged(map, "water_intake_id", originalProcedure.getWaterIntakeType(), _water_inatke);

        // Asumiendo que el campo 'user_id' es un String en el objeto original:
        Filters.addIfChanged(map, "user_id", originalProcedure.getUser(), _user);

        // El parámetro 'toString' de tu función original fue renombrado a '_user_name' para ser claro.
        // Asumiendo que el campo 'user_name' es un String en el objeto original:
        Filters.addIfChanged(map, "user_name", originalProcedure.getUserName(), _user_name);

        // 2. Campos Opcionales/Descriptivos
        Filters.addIfChanged(map, "street1", originalProcedure.getStreet1(), _street1);
        Filters.addIfChanged(map, "street2", originalProcedure.getStreet2(), _street2);
        Filters.addIfChanged(map, "location", originalProcedure.getLocation(), _location);
        Filters.addIfChanged(map, "description", originalProcedure.getDescription(), _description);

        // Asumiendo que el estado se guarda como String:
        Filters.addIfChanged(map, "status", String.valueOf(originalProcedure.getStatus()), _status);
        return map;
    }

    @Override
    public void setRowsData(String... info) {
        count.setText(info[0]);
        range.setText(info[1]);
        total.setText(info[2]);
    }

    @Override
    public void setScreenTableInfo() {
        if (!isProcess()) {
            setInfo();
        } else {
            setInfoProcess();
        }
    }

    public void setInfoProcess() {
        ProcessWrapperDTO wp = getProcessWrapper();
        if (wp == null) {
            return;
        }
        UserDTO user = wp.getUser();

    }

    protected void setInfo() {
        if (user_search != null) {
            user_field.setText(user_search.toString());
            water_intake_types_field.setSelectedItem(water_intake_types_search);
            street1_field.setSelectedItem(street1_search);
            street2_field.setSelectedItem(street2_search);
            status_field.setSelectedIndex(1);
        }
        save_button.setEnabled(false);
        update_button.setEnabled(true);
        delete_button.setEnabled(true);
    }

    public void setUserSearch(UserDTO user_search) {
        this.user_search = user_search;
    }

    public void setWater_intake_types_search(WaterIntakeTypesDTO water_intake_types_search) {
        this.water_intake_types_search = water_intake_types_search;
    }

    public void setStreet1_search(StreetDTO street1_search) {
        this.street1_search = street1_search;
    }

    public void setStreet2_search(StreetDTO street2_search) {
        this.street2_search = street2_search;
    }

    @Override
    public void getDataView() {

    }
    
}
