/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas.menuprincipal;

import com.jblue.vista.vistas.menuprincipal.sub.VCobrosR;
import com.jblue.vista.vistas.menuprincipal.sub.VCobrosC;
import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.MemoCache;
import com.jblue.vista.comp.CSelectorObjeto;
import com.jblue.vista.comp.CVisorUsuario;
import com.jblue.vista.jbmarco.VistaExtendida;
import java.awt.CardLayout;

/**
 *
 * @author jp
 */
public class VCobros extends VistaExtendida {

    /**
     * Creates new form VUsuarios
     */
    public VCobros() {
        initComponents();
        memoria_cache = FabricaCache.MC_USUARIOS;
        registros = new VCobrosR(this);
        consultas = new VCobrosC(this);
        ly_root = (CardLayout) panel_root.getLayout();
        llamable();
    }

    @Override
    protected final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    protected void componentesEstadoFinal() {
        panel_root.add(registros.getName(), registros);
        panel_root.add(consultas.getName(), consultas);
    }

    @Override
    public void componentesEstadoInicial() {
    }

    @Override
    protected void manejoEventos() {
        bnt_registros.addActionListener(e -> {
            if (registros.isVisible()) {
                return;
            }
            ly_root.show(panel_root, registros.getName());
        });

        btn_consultas.addActionListener(e -> {
            if (consultas.isVisible()) {
                return;
            }
            ly_root.show(panel_root, consultas.getName());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        bnt_registros = new javax.swing.JButton();
        btn_consultas = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panel_root = new javax.swing.JPanel();

        setName("Cobros"); // NOI18N
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(1200, 660));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        bnt_registros.setText("Registros");
        jPanel2.add(bnt_registros);

        btn_consultas.setText("Consultas");
        jPanel2.add(btn_consultas);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jPanel3.setOpaque(false);
        jPanel3.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setPreferredSize(new java.awt.Dimension(30, 250));
        jPanel3.add(jLabel3, java.awt.BorderLayout.CENTER);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/buscar.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.EAST);

        jPanel1.add(jPanel3, java.awt.BorderLayout.EAST);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        panel_root.setOpaque(false);
        panel_root.setLayout(new java.awt.CardLayout());
        add(panel_root, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        OUsuarios o = CSelectorObjeto.selectorUsuarios(null);
        
        if (o == null) {
            return;
        }
        
        CVisorUsuario.showVisor(o);
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bnt_registros;
    private javax.swing.JButton btn_consultas;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel panel_root;
    // End of variables declaration//GEN-END:variables
    private final VCobrosR registros;
    private final VCobrosC consultas;
    private final MemoCache<OUsuarios> memoria_cache;
    private final CardLayout ly_root;

    public MemoCache<OUsuarios> getMemoria_cache() {
        return memoria_cache;
    }

}
