/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.views.win;

import com.jblue.controllers.winc.ProfileController;
import com.jblue.views.framework.AbstractAppWindows;
import com.jblue.views.EmployeeView;
import com.jblue.views.HistoryView;
import com.jblue.views.VContabilidad;
import com.jblue.views.VPerfil;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author juanp
 */
public final class ProfileWindow extends AbstractAppWindows {

    private final EmployeeView employee_view;
    private final VPerfil profile_view;
    private final VContabilidad contabilidad;
    private final CardLayout ly;
    private final ProfileController controller;

    //
    private final HistoryView history_view;

    /**
     * Creates new form MenuWindow
     */
    public ProfileWindow() {
        this.employee_view = new EmployeeView();
        this.profile_view = new VPerfil();
        this.contabilidad = new VContabilidad();
        this.history_view = new HistoryView();
        initComponents();
        ly = (CardLayout) root_panel.getLayout();
        this.controller = new ProfileController(this);

        build();
    }

    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    @Override
    public void components() {
        root_panel.add(employee_view.getName(), employee_view);
        root_panel.add(contabilidad.getName(), contabilidad);
        root_panel.add(profile_view.getName(), profile_view);
        root_panel.add(history_view.getName(), history_view);
    }

    @Override
    public void events() {
        employee_view_button.addActionListener(controller);
        contable_view_button.addActionListener(controller);
        profile_view_button.addActionListener(controller);
        history_view_button.addActionListener(controller);
    }

    @Override
    public void initialState() {
        ly.show(root_panel, profile_view.getName());
        updateTitle(profile_view.getName());
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        profile_view_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        employee_view_button = new javax.swing.JButton();
        contable_view_button = new javax.swing.JButton();
        history_view_button = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        setName("Perfil"); // NOI18N

        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(250, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(250, 250));
        jPanel1.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.GridLayout(12, 0));

        profile_view_button.setText("Datos de empleado");
        profile_view_button.setActionCommand("Datos de usuario");
        jPanel3.add(profile_view_button);

        jButton2.setText("Administracion de usuarios");
        jPanel3.add(jButton2);

        employee_view_button.setText("Administracion de empleados");
        employee_view_button.setActionCommand("Personal");
        jPanel3.add(employee_view_button);

        contable_view_button.setText("Contabilidad");
        jPanel3.add(contable_view_button);

        history_view_button.setText("Historial de actividad");
        jPanel3.add(history_view_button);

        jButton6.setText("Administracion de suministros");
        jPanel3.add(jButton6);

        jButton7.setText("jButton1");
        jPanel3.add(jButton7);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        root_panel.setLayout(new java.awt.CardLayout());
        getContentPane().add(root_panel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton contable_view_button;
    private javax.swing.JButton employee_view_button;
    private javax.swing.JButton history_view_button;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton profile_view_button;
    private javax.swing.JPanel root_panel;
    // End of variables declaration//GEN-END:variables

    public CardLayout getCardLayout() {
        return ly;
    }

    public JPanel getRootPanel() {
        return root_panel;
    }

}
