/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.mod.pro;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import jsoftware.com.jblue.controllers.viewc.EmployeeRegisterController;
import jsoftware.com.jblue.model.dto.wrp.EmployeeRegisterWrapperDTO;
import jsoftware.com.jblue.views.framework.AbstractModuleView;
import jsoftware.com.jblue.views.mod.com.EmployeeRegistrationView;
import jsoftware.com.jblue.views.mod.com.EmployeeUserDataView;
import jsoftware.com.jblue.views.vabst.AbstractWizardView;

/**
 *
 * @author juanp
 */
public final class EmployeeRegisterProcess extends AbstractWizardView<EmployeeRegisterWrapperDTO> {

    private static final long serialVersionUID = 1L;
    private final EmployeeRegistrationView register_view;
    private final EmployeeUserDataView data_view;

    /**
     * Creates new form EmployeeRegisterProcess
     */
    public EmployeeRegisterProcess(EmployeeRegisterWrapperDTO dto) {
        super(dto);
        register_view = new EmployeeRegistrationView(dto);
        data_view = new EmployeeUserDataView(dto);
        //
        views = new ArrayList<>(2);
        views.add(register_view);
        views.add(data_view);
        //
        card_layout = (CardLayout) root_panel.getLayout();
        build();
    }

    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    @Override
    public void events() {
        //
        EmployeeRegisterController employee_controller = (EmployeeRegisterController) getDtoWrapper().getController("CONTROLLER");
        employee_controller.setView(this);
        
        next_panel_button.addActionListener(employee_controller);

    }

    @Override
    public void components() {
        root_panel.add(register_view, register_view.getName());
        root_panel.add(data_view, data_view.getName());
    }

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("REGISTRO DE EMPLEADOS"); // NOI18N
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public boolean nextStep() {
        getData();
        boolean valid = switch (current_index) {
            case 0 ->
                getDtoWrapper().isEmployee_valid();
            case 1 ->
                getDtoWrapper().isEmployee_user_valid();
            default ->
                false;
        };
        if (!valid) {
            JOptionPane.showMessageDialog(root_panel,
                    "Por favor, complete correctamente los campos obligatorios de esta sección.",
                    "Validación", JOptionPane.WARNING_MESSAGE);
        }
        return !valid;
    }

    @Override
    public void executeFinal() {
        for (AbstractModuleView<EmployeeRegisterWrapperDTO> v : views) {
            v.getData();
        }
        EmployeeRegisterWrapperDTO pw = getDtoWrapper();
        // 2. Aquí llamarías a tu Service: userService.save(...)
        JOptionPane.showMessageDialog(this, "Iniciando persistencia de datos en base de datos...");
        //controller.save();

    }

    @Override
    public List<AbstractModuleView<EmployeeRegisterWrapperDTO>> getViews() {
        return views;
    }
}
