/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.mod.pro;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import jsoftware.com.jblue.controllers.viewc.EmployeeRegisterController;
import jsoftware.com.jblue.model.dto.wrp.EmployeeRegisterWrapperDTO;
import jsoftware.com.jblue.views.framework.AbstractModuleView;
import jsoftware.com.jblue.views.framework.ShowDataModel;
import jsoftware.com.jblue.views.mod.com.EmployeeRegistrationView;
import jsoftware.com.jblue.views.mod.com.EmployeeUserDataView;
import jsoftware.com.jblue.views.vabst.AbstractWizardView;

/**
 *
 * @author juanp
 */
public final class EmployeeRegisterProcess extends AbstractWizardView<EmployeeRegisterWrapperDTO> implements ShowDataModel {

    private static final long serialVersionUID = 1L;
    private final EmployeeRegistrationView register_view;
    private final EmployeeUserDataView data_view;

    /**
     * Creates new form EmployeeRegisterProcess
     */
    public EmployeeRegisterProcess(EmployeeRegisterWrapperDTO dto) {
        super(dto);
        register_view = new EmployeeRegistrationView(dto);
        data_view = new EmployeeUserDataView(dto);
        //
        views = new ArrayList<>(2);
        views.add(register_view);
        views.add(data_view);
        card_layout = (CardLayout) root_panel.getLayout();
        //
        build();
    }

    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    @Override
    public void events() {
        // Registrar esta vista contenedora principal en el controlador de negocio de Empleados
        EmployeeRegisterController employeeController = (EmployeeRegisterController) getDtoWrapper().getController("CONTROLLER");
        if (employeeController != null) {
            employeeController.setView(this);
            next_panel_button.addActionListener(employeeController);
        }
        // NOTA: El botón "next_panel_button" NO recibe listeners de negocio aquí; 
        // es gobernado de forma limpia por bindController() mediante el WizardController.
    }

    @Override
    public void components() {
        root_panel.add(register_view, register_view.getName());
        root_panel.add(data_view, data_view.getName());
    }

    @Override
    public void initialState() {
        super.initialState();
        for (AbstractModuleView<EmployeeRegisterWrapperDTO> i : views) {
            i.initialState();
        }
        getDtoWrapper().clear();
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName(""); // NOI18N
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    @Override
    public boolean nextStep() {
        // Sincroniza los componentes visuales del paso actual hacia los Strings del mapa del DTO
        getData();

        // Evaluar las banderas de validación del DTO según el paso del asistente
        boolean valid = switch (current_index) {
            case 0 ->
                getDtoWrapper().isEmployee_valid();
            default ->
                getDtoWrapper().isEmployee_user_valid();
        };
        if (!valid) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor, complete correctamente los campos obligatorios de esta sección.",
                    "Validación de Datos", JOptionPane.WARNING_MESSAGE);
        }
        return valid;
    }

    @Override
    public void executeFinal() {
        // 1. Forzar la recolección masiva de la data de todos los sub-paneles
        for (AbstractModuleView<EmployeeRegisterWrapperDTO> v : views) {
            v.getData();
        }
        // 2. Recuperar el controlador del caso de uso encargado de la persistencia
        EmployeeRegisterController employeeController = (EmployeeRegisterController) getDtoWrapper().getController("CONTROLLER");
        if (employeeController != null) {
            // El controlador leerá el WrapperDTO enriquecido, aplicará los casts numéricos en el DAO y guardará en MySQL
            JOptionPane.showMessageDialog(this, "Guardando registro del nuevo empleado en el sistema...", "Procesando", JOptionPane.INFORMATION_MESSAGE);

            // Suponiendo que tu controlador implementa el método de persistencia:
            // employeeController.insert(); 
        }

    }

    @Override
    public List<AbstractModuleView<EmployeeRegisterWrapperDTO>> getViews() {
        return views;
    }

    @Override
    public void showData() {
        for (AbstractModuleView<EmployeeRegisterWrapperDTO> i : views) {
            System.out.println(i.getName());
            if (i instanceof ShowDataModel s) {
                s.showData();
            }
        }
    }

    public void beforeSaveData() {
        next_panel_button.setEnabled(false);
    }

    public void afterSaveData(boolean mov) {
        next_panel_button.setEnabled(true);
        if (mov) {
            initialState();
        }
        
    }

}
