/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package jsoftware.com.jblue.views.mod.pro;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import jsoftware.com.jblue.controllers.viewc.EmployeeRegisterController;
import jsoftware.com.jblue.controllers.viewc.OwnerRegisterProcessController;
import jsoftware.com.jblue.model.dto.wrp.ProcessWrapperDTO;
import jsoftware.com.jblue.views.framework.AbstractModuleView;
import jsoftware.com.jblue.views.framework.ShowDataModel;
import jsoftware.com.jblue.views.mod.com.EndProcessView;
import jsoftware.com.jblue.views.mod.com.PaymentProcessView;
import jsoftware.com.jblue.views.mod.com.StreetRegisterView;
import jsoftware.com.jblue.views.mod.com.UserRegisterView;
import jsoftware.com.jblue.views.mod.com.ValidationProcessView;
import jsoftware.com.jblue.views.vabst.AbstractWizardView;

/**
 *
 * @author juanp
 */
public final class OwnerRegisterProcess extends AbstractWizardView<ProcessWrapperDTO> implements ShowDataModel {

    private static final long serialVersionUID = 1L;

    private final UserRegisterView step1;
    private final StreetRegisterView step2;
    private final ValidationProcessView step3;
    private final PaymentProcessView step4;
    private final EndProcessView step5;

    public OwnerRegisterProcess(ProcessWrapperDTO dto) {
        super(dto);
        step1 = new UserRegisterView(dto);
        step2 = new StreetRegisterView(dto);
        step3 = new ValidationProcessView(dto);
        step4 = new PaymentProcessView(dto);
        step5 = new EndProcessView(dto);
        views = new ArrayList<>(5);
        views.addAll(Arrays.asList(step1, step2, step3, step4, step5));
        build();
    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void events() {
        // Registrar esta vista contenedora principal en el controlador de negocio de Empleados
        OwnerRegisterProcessController employeeController = (OwnerRegisterProcessController) getDtoWrapper().getController("CONTROLLER");
        if (employeeController != null) {
            employeeController.setView(this);
            next_panel_button.addActionListener(employeeController);
        }
        // NOTA: El botón "next_panel_button" NO recibe listeners de negocio aquí; 
        // es gobernado de forma limpia por bindController() mediante el WizardController.
    }

    @Override
    public void components() {
        for (AbstractModuleView<ProcessWrapperDTO> i : views) {
            root_panel.add(i, i.getName());
        }
    }

    @Override
    public void initialState() {
        super.initialState();
        for (AbstractModuleView<ProcessWrapperDTO> i : views) {
            i.initialState();
        }
        getDtoWrapper().clear();
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Registro de titular"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 300));
        setLayout(null);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean nextStep() {
        // Sincroniza los componentes visuales del paso actual hacia los Strings del mapa del DTO
        getData();

        // Evaluar las banderas de validación del DTO según el paso del asistente
        boolean valid = switch (current_index) {
            case 0 ->
                true;
            case 1 ->
                true;
            case 3 ->
                true;
            default ->
                true;
        };
        if (!valid) {
            JOptionPane.showMessageDialog(
                    this,
                    "Por favor, complete correctamente los campos obligatorios de esta sección.",
                    "Validación de Datos", JOptionPane.WARNING_MESSAGE);
        }
        return valid;
    }

    @Override
    public void executeFinal() {
        // 1. Forzar la recolección masiva de la data de todos los sub-paneles
        for (AbstractModuleView<ProcessWrapperDTO> v : views) {
            v.getData();
        }
        // 2. Recuperar el controlador del caso de uso encargado de la persistencia
        EmployeeRegisterController employeeController = (EmployeeRegisterController) getDtoWrapper().getController("CONTROLLER");
        if (employeeController != null) {
            // El controlador leerá el WrapperDTO enriquecido, aplicará los casts numéricos en el DAO y guardará en MySQL
            JOptionPane.showMessageDialog(this, "Guardando registro del nuevo empleado en el sistema...", "Procesando", JOptionPane.INFORMATION_MESSAGE);

            // Suponiendo que tu controlador implementa el método de persistencia:
            // employeeController.insert(); 
        }

    }

    @Override
    public List<AbstractModuleView<ProcessWrapperDTO>> getViews() {
        return views;
    }

    @Override
    public void showData() {
        for (AbstractModuleView<ProcessWrapperDTO> i : views) {
            if (i instanceof ShowDataModel s) {
                s.showData();
            }
        }
    }

    public void beforeSaveData() {
        next_panel_button.setEnabled(false);
    }

    public void afterSaveData(boolean mov) {
        next_panel_button.setEnabled(true);
        if (mov) {
            initialState();
        }

    }
}
