/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jsoftware.com.jblue.views.mod.pro;

import javax.swing.JTabbedPane;
import jsoftware.com.jblue.model.dto.wrp.UserRegisterWrapperDTO;
import jsoftware.com.jblue.views.framework.FormModel;
import jsoftware.com.jblue.views.mod.com.AddressRegisterView;
import jsoftware.com.jblue.views.mod.com.UserRegisterView;
import jsoftware.com.jblue.views.vabst.AbstractFormView;

/**
 *
 * @author juanp
 */
public final class UserRegisterProcess extends AbstractFormView<UserRegisterWrapperDTO> implements FormModel<UserRegisterWrapperDTO>{

    private static final long serialVersionUID = 1L;

    private final UserRegisterView<UserRegisterWrapperDTO> user_view;
    private final AddressRegisterView<UserRegisterWrapperDTO> address_view;

    /**
     * Creates new form RegusterUserProcess
     */
    public UserRegisterProcess(UserRegisterWrapperDTO dto) {
        super(dto);
        initComponents();
        user_view = UserRegisterView.getInstance(dto);
        address_view = AddressRegisterView.getInstance(dto);
    }

    @Override
    public void components() {
        JTabbedPane tab = new JTabbedPane(2);
        tab.add(user_view.getName(), user_view);
        tab.add(address_view.getName(), address_view);
        root_panel.add(tab);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setName("Form"); // NOI18N
        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
