/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.otros.news.ventanas;

import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.otros.news.vistas.NewCalles;
import com.jblue.otros.news.vistas.NewMenuType;
import com.jblue.otros.news.vistas.NewTipoDeTomas;
import com.jblue.otros.news.vistas.NewUsuarios;
import com.jblue.otros.news.vistas.NewVCaja;
import com.jblue.sistema.Sesion;
import com.jblue.vista.componentes.CSelectorObjeto;
import com.jblue.vista.componentes.CVisorUsuario;
import com.jblue.vista.ventanas.Login;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author juan-campos
 */
public class NewMenuPrincipal extends javax.swing.JFrame {

    private final NewVCaja caja;
    private final NewMenuType menu_type;
    private final NewUsuarios usuarios;
    private final NewCalles calles;
    private final NewTipoDeTomas tipo_de_tomas;

    private final CardLayout ly;
    private final Login LOGIN;

    /**
     * Creates new form NewMenuPrincipal
     *
     * @param LOGIN
     */
    public NewMenuPrincipal(Login LOGIN) {
        initComponents();
        this.LOGIN = LOGIN;
        caja = new NewVCaja();
        usuarios = new NewUsuarios();
        menu_type = new NewMenuType(this);
        calles = new NewCalles();
        tipo_de_tomas = new NewTipoDeTomas();

        btn_tipo_pagos.setComponentPopupMenu(jPopupMenu1);
        ly = (CardLayout) views_panel.getLayout();

        views_panel.add(caja, caja.getName());
        views_panel.add(usuarios, usuarios.getName());
        views_panel.add(calles, calles.getName());
        views_panel.add(tipo_de_tomas, tipo_de_tomas.getName());
        views_panel.add(menu_type, menu_type.getName());
        eventos();
    }

    private void eventos() {
        btn_home.addActionListener(e -> setView(0));
        btn_usuarios.addActionListener(e -> setView(1));
        btn_calles.addActionListener(e -> setView(2));
        btn_tipo_tomas.addActionListener(e -> setView(3));
        btn_tipo_pagos.addActionListener(e -> setView(4));
        menu_button.addActionListener(e -> setView(5));

        search_button.addActionListener(e -> {
            OUsuarios obj = CSelectorObjeto.selectorUsuarios(this);
            CVisorUsuario.showVisor(obj);
        });
    }

    private void setView(int option) {
        String op = switch (option) {
            case 0:
                yield caja.getName();
            case 1:
                yield usuarios.getName();
            case 2:
                yield calles.getName();
            case 3:
                yield tipo_de_tomas.getName();
            case 5:
                yield menu_type.getName();
            case 6:
                yield OUT;
            default:
                JOptionPane.showMessageDialog(center_panel, "Esta opcion aun no esta disponible", "Opcion No encontrada", JOptionPane.INFORMATION_MESSAGE);
                yield caja.getName();
        };
        if (op.equals(OUT)) {
            this.dispose();
            return;
        }
        ly.show(views_panel, op);
    }

    public void goToHome() {
        ly.show(views_panel, caja.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        search_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        menu_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_home = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        btn_usuarios = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btn_calles = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        btn_tipo_tomas = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        btn_tipo_pagos = new javax.swing.JButton();
        exit_button = new javax.swing.JButton();
        center_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        views_panel = new javax.swing.JPanel();

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/perfil.png"))); // NOI18N
        jMenuItem1.setText("Perfil");
        jPopupMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/presidente.png"))); // NOI18N
        jMenuItem2.setText("Presidente");
        jPopupMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/cofre-del-tesoro.png"))); // NOI18N
        jMenuItem3.setText("Tesorero");
        jPopupMenu1.add(jMenuItem3);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/perfil.png"))); // NOI18N
        jMenuItem4.setText("Administrador");
        jPopupMenu1.add(jMenuItem4);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1200, 700));
        getContentPane().setLayout(new java.awt.BorderLayout(5, 5));

        jPanel1.setPreferredSize(new java.awt.Dimension(300, 700));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel3.setPreferredSize(new java.awt.Dimension(300, 50));
        jPanel3.setLayout(new java.awt.BorderLayout());

        search_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(search_button, java.awt.BorderLayout.LINE_START);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Home");
        jPanel3.add(jLabel1, java.awt.BorderLayout.CENTER);

        menu_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/menu.png"))); // NOI18N
        menu_button.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel3.add(menu_button, java.awt.BorderLayout.LINE_END);

        jPanel1.add(jPanel3, java.awt.BorderLayout.PAGE_START);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/usuario.png"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(41, 200));
        jPanel4.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.GridLayout(8, 0));

        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_home.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btn_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/home.png"))); // NOI18N
        btn_home.setText("Inicio");
        btn_home.setHideActionText(true);
        btn_home.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_home.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel2.add(btn_home, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel2);

        jPanel6.setLayout(new java.awt.BorderLayout());

        btn_usuarios.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btn_usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/usuario.png"))); // NOI18N
        btn_usuarios.setText("Usuarios");
        btn_usuarios.setHideActionText(true);
        btn_usuarios.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_usuarios.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel6.add(btn_usuarios, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        btn_calles.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btn_calles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/calles.png"))); // NOI18N
        btn_calles.setText("Calles");
        btn_calles.setHideActionText(true);
        btn_calles.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_calles.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel7.add(btn_calles, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.BorderLayout());

        btn_tipo_tomas.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btn_tipo_tomas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/toma agua.png"))); // NOI18N
        btn_tipo_tomas.setText("Tipo de tomas");
        btn_tipo_tomas.setHideActionText(true);
        btn_tipo_tomas.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_tipo_tomas.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel8.add(btn_tipo_tomas, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel8);

        jPanel9.setLayout(new java.awt.BorderLayout());

        btn_tipo_pagos.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        btn_tipo_pagos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/tipo de pago.png"))); // NOI18N
        btn_tipo_pagos.setText("Tipo de pagos");
        btn_tipo_pagos.setHideActionText(true);
        btn_tipo_pagos.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        btn_tipo_pagos.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel9.add(btn_tipo_pagos, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel9);

        jPanel4.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel4, java.awt.BorderLayout.CENTER);

        exit_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerrar-sesion.png"))); // NOI18N
        exit_button.setText("Salir");
        exit_button.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        exit_button.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel1.add(exit_button, java.awt.BorderLayout.SOUTH);

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        center_panel.setLayout(new java.awt.BorderLayout());

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(10, 10));
        center_panel.add(jSeparator1, java.awt.BorderLayout.WEST);

        views_panel.setLayout(new java.awt.CardLayout());
        center_panel.add(views_panel, java.awt.BorderLayout.CENTER);

        getContentPane().add(center_panel, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_calles;
    private javax.swing.JButton btn_home;
    private javax.swing.JButton btn_tipo_pagos;
    private javax.swing.JButton btn_tipo_tomas;
    private javax.swing.JButton btn_usuarios;
    private javax.swing.JPanel center_panel;
    private javax.swing.JButton exit_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton menu_button;
    private javax.swing.JButton search_button;
    private javax.swing.JPanel views_panel;
    // End of variables declaration//GEN-END:variables
    private final String OUT = "OUT";

    @Override
    public void dispose() {
        Sesion.getInstancia().finSesion();
        super.dispose(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
        SwingUtilities.invokeLater(() -> {
            LOGIN.setVisible(true);
            LOGIN.limpiarInstancia();
        });
    }

}
