/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas.cobros;

import com.jblue.modelo.ConstGs;
import com.jblue.modelo.cache.MemoListCache;
import com.jblue.modelo.fabricas.FabricaFuncionesBD;
import com.jblue.modelo.objetos.OPagosServicio;
import com.jblue.util.Filtros;
import com.jblue.util.FuncJBlue;
import com.jblue.vista.marco.vistas.SimpleView;
import com.jblue.vista.vistas.VCobros;
import com.jutil.swingw.modelos.JTableModel;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 *
 * @author jp
 */
public final class VCCobros extends SimpleView {

    /**
     * Creates new form VCobrosR
     *
     * @param root
     */
    public VCCobros(VCobros root) {
        this.memo_cache = new MemoListCache(FabricaFuncionesBD.getPagosXServicio());
        memo_cache.loadData();
        modelo = new JTableModel(ConstGs.TABLA_PAGOS_X_SERVICIO, 0);
        modelo.setCellsEditables(false);
        initComponents();
        jTable2.setModel(modelo);
        llamable();
    }

    @Override
    protected void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        eventos();
    }

    @Override
    public void componentesEstadoInicial() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_filtros = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        filtro_personal = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        filtro_mes_pagado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        panel_tabla = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_rec = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_ant = new javax.swing.JButton();
        btn_sig = new javax.swing.JButton();
        filtro_buscador = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_resultados = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        lbl_rango = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        lbl_total_r = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setName("Cobros realizados"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        panel_filtros.setName("Cobros realizados"); // NOI18N
        panel_filtros.setPreferredSize(new java.awt.Dimension(1200, 100));
        panel_filtros.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setText("Filtros");
        jCheckBox1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jCheckBox1.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel4.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Quitar filtros");
        jButton1.setPreferredSize(new java.awt.Dimension(150, 29));
        jPanel4.add(jButton1, java.awt.BorderLayout.LINE_END);

        panel_filtros.add(jPanel4, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(1, 4));

        jPanel6.setLayout(new java.awt.BorderLayout());

        filtro_personal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel6.add(filtro_personal, java.awt.BorderLayout.CENTER);

        jLabel4.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Personal");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel6.add(jLabel4, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel6);

        jPanel13.setLayout(new java.awt.BorderLayout());

        filtro_mes_pagado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel13.add(filtro_mes_pagado, java.awt.BorderLayout.CENTER);

        jLabel6.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Mes Pagado");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Fecha de Inicio.");
        jLabel7.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel14.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel14);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Ubuntu Mono", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Fecha de Fin");
        jLabel8.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel15.add(jLabel8, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(jPanel15);

        panel_filtros.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(panel_filtros, java.awt.BorderLayout.NORTH);

        panel_tabla.setPreferredSize(new java.awt.Dimension(1000, 400));
        panel_tabla.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel2.setLayout(new java.awt.BorderLayout());

        btn_rec.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        btn_rec.setPreferredSize(new java.awt.Dimension(100, 27));
        btn_rec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recActionPerformed(evt);
            }
        });
        jPanel2.add(btn_rec, java.awt.BorderLayout.LINE_START);

        jPanel3.setPreferredSize(new java.awt.Dimension(200, 35));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2));

        btn_ant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        btn_ant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_antActionPerformed(evt);
            }
        });
        jPanel3.add(btn_ant);

        btn_sig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        btn_sig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sigActionPerformed(evt);
            }
        });
        jPanel3.add(btn_sig);

        jPanel2.add(jPanel3, java.awt.BorderLayout.LINE_END);

        filtro_buscador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                filtro_buscadorKeyTyped(evt);
            }
        });
        jPanel2.add(filtro_buscador, java.awt.BorderLayout.CENTER);

        panel_tabla.add(jPanel2, java.awt.BorderLayout.NORTH);

        jScrollPane3.setPreferredSize(new java.awt.Dimension(1000, 370));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTable2);

        panel_tabla.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jPanel11.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel3.setText("No. resultados: ");
        jPanel11.add(jLabel3, java.awt.BorderLayout.LINE_START);

        lbl_resultados.setText(" 0");
        jPanel11.add(lbl_resultados, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel11, java.awt.BorderLayout.WEST);

        jPanel10.setLayout(new java.awt.BorderLayout());

        lbl_rango.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_rango.setText("0 - 0");
        jPanel10.add(lbl_rango, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel12.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel12.setLayout(new java.awt.BorderLayout());

        lbl_total_r.setText("0");
        jPanel12.add(lbl_total_r, java.awt.BorderLayout.CENTER);

        jLabel5.setText("Total: ");
        jPanel12.add(jLabel5, java.awt.BorderLayout.WEST);

        jPanel9.add(jPanel12, java.awt.BorderLayout.EAST);

        panel_tabla.add(jPanel9, java.awt.BorderLayout.SOUTH);

        add(panel_tabla, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_recActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recActionPerformed
        FuncJBlue.pintarTabla(modelo, memo_cache.getList());
        updateTableInfo();
    }//GEN-LAST:event_btn_recActionPerformed

    private void btn_antActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_antActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (!memo_cache.back()) {
                JOptionPane.showMessageDialog(this, "No hay mas datos disponibles", "Datos", JOptionPane.INFORMATION_MESSAGE);
                memo_cache.next();

            }
            FuncJBlue.pintarTabla(modelo, memo_cache.getList());
            updateTableInfo();
        });
    }//GEN-LAST:event_btn_antActionPerformed

    private void filtro_buscadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_filtro_buscadorKeyTyped
        String aux = Filtros.limpiar(filtro_buscador.getText());
        if (Filtros.isNullOrBlank(aux)) {
            FuncJBlue.pintarTabla(modelo, memo_cache.getList());
            return;
        }
        buscador(aux);
    }//GEN-LAST:event_filtro_buscadorKeyTyped

    private void btn_sigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sigActionPerformed
        SwingUtilities.invokeLater(() -> {
            if (!memo_cache.next()) {
                JOptionPane.showMessageDialog(this, "No hay mas datos disponibles", "Datos", JOptionPane.INFORMATION_MESSAGE);
                memo_cache.back();
            }

            FuncJBlue.pintarTabla(modelo, memo_cache.getList());
            updateTableInfo();
        });

    }//GEN-LAST:event_btn_sigActionPerformed

    private void buscador(final String aux) {
        List<OPagosServicio> lista = memo_cache.getList(e -> {
            String a = Filtros.limpiar(e.toString());
            return a.contains(aux);
        });
        FuncJBlue.pintarTabla(modelo, lista);
        updateTableInfo();
    }

    @Override
    public void setVisible(boolean aFlag) {
        super.setVisible(aFlag);
        if (aFlag) {
            FuncJBlue.pintarTabla(modelo, memo_cache.getList());
            updateTableInfo();
        } else {
            if (modelo.getRowCount() > 0) {
                modelo.removeAllRows();
            }
        }
    }

    public void updateTableInfo() {
        ArrayList<OPagosServicio> list = memo_cache.getList();
        lbl_resultados.setText(String.valueOf(list.size()));
        lbl_rango.setText(
                "%s - %s".formatted(memo_cache.getIndexMin(),
                        memo_cache.getIndexMax()));

        lbl_total_r.setText(String.valueOf(memo_cache.count()));
    }

    void filtros() {

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ant;
    private javax.swing.JButton btn_rec;
    private javax.swing.JButton btn_sig;
    private javax.swing.JTextField filtro_buscador;
    private javax.swing.JComboBox<String> filtro_mes_pagado;
    private javax.swing.JComboBox<String> filtro_personal;
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel lbl_rango;
    private javax.swing.JLabel lbl_resultados;
    private javax.swing.JLabel lbl_total_r;
    private javax.swing.JPanel panel_filtros;
    private javax.swing.JPanel panel_tabla;
    // End of variables declaration//GEN-END:variables

    //private final MemoCache<OPagosServicio> memo_cache;
    private final MemoListCache<OPagosServicio> memo_cache;
    private final JTableModel modelo;
}
