/*
 * Copyright (C) 2023 jp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.vista.vistas.cobros;

import com.jblue.modelo.objetos.OUsuarios;
import com.jblue.util.cache.FabricaCache;
import com.jblue.util.cache.MemoCache;
import com.jblue.vista.vistas.normas.Vista;
import java.awt.CardLayout;

/**
 *
 * @author jp
 */
public class VCobros extends Vista {

    /**
     * Creates new form VUsuarios
     */
    public VCobros() {
        initComponents();
        memoria_cache = FabricaCache.MC_USUARIOS;
        registros = new VCobrosR(this);
        consultas = new VCobrosC(this);
        ly_root = (CardLayout) panel_root.getLayout();
        llamable();
    }

    @Override
    protected final void llamable() {
        construirComponentes();
        componentesEstadoFinal();
        componentesEstadoInicial();
        manejoEventos();
    }

    @Override
    protected void componentesEstadoFinal() {
        panel_root.add(registros.getName(), registros);
        panel_root.add(consultas.getName(), consultas);
    }

    @Override
    public void componentesEstadoInicial() {
    }

    @Override
    protected void manejoEventos() {
        jButton1.addActionListener(e -> {
            ly_root.show(panel_root, registros.getName());
        });
        jButton2.addActionListener(e -> {
            ly_root.show(panel_root, consultas.getName());
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        panel_root = new javax.swing.JPanel();

        setName("Cobros"); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        jPanel2.setLayout(new java.awt.GridLayout());

        jButton1.setText("Registros");
        jPanel2.add(jButton1);

        jButton2.setText("Consultas");
        jPanel2.add(jButton2);

        jPanel1.add(jPanel2, java.awt.BorderLayout.CENTER);

        jLabel2.setPreferredSize(new java.awt.Dimension(300, 30));
        jPanel1.add(jLabel2, java.awt.BorderLayout.LINE_END);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        panel_root.setLayout(new java.awt.CardLayout());
        add(panel_root, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel panel_root;
    // End of variables declaration//GEN-END:variables
    private final VCobrosR registros;
    private final VCobrosC consultas;
    private final MemoCache<OUsuarios> memoria_cache;
    private final CardLayout ly_root;

    public MemoCache<OUsuarios> getMemoria_cache() {
        return memoria_cache;
    }

}
