/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.views;

import com.jblue.controllers.winc.ConfigController;
import com.jblue.sys.app.AppConfig;
import com.jblue.views.framework.SimpleView;
import com.jblue.views.win.ConfigWindow;
import com.jutil.framework.LaunchApp;
import com.jutil.platf.So;
import static com.sun.java.accessibility.util.AWTEventMonitor.addWindowListener;
import java.awt.CardLayout;
import java.awt.event.ActionListener;
import java.time.LocalTime;
import java.util.Properties;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JPasswordField;
import javax.swing.SpinnerNumberModel;
import javax.swing.filechooser.FileNameExtensionFilter;
import com.jblue.views.framework.DBValuesModel;
import com.jblue.views.framework.OptionMenuModel;

/**
 *
 * @author juanp
 */
public final class ConfigurationPanel extends SimpleView implements OptionMenuModel, DBValuesModel {

    private JButton option;
    private final CardLayout ly;
    private final ConfigController controller;
    private Properties properties;
    private ConfigWindow root;

    /**
     * Creates new form ConfigurationPanel
     *
     * @param root
     */
    public ConfigurationPanel(ConfigWindow root) {
        initComponents();
        ly = (CardLayout) root_panel.getLayout();
        controller = new ConfigController(this);
        properties = (Properties) LaunchApp.getInstance().getResources("propierties");
        this.option = mkButton(getName(), null, null);
        if (root != null) {
            this.root = root;
            this.root.addWindowListener(controller);
        }
        build();

    }

    public void disposeWin() {
        if (root != null) {
            synchronized (root) {
                root.dispose();
                root.notify();
            }
        }
    }

    @Override
    public void build() {
        components();
        events();
        initialState();
        finalState();
    }

    @Override
    public void events() {
        addWindowListener(controller);

        show_user.addActionListener(controller);
        show_password.addActionListener(controller);
        //
        save_db_button.addActionListener(controller);
        test_db_button.addActionListener(controller);
        //
        search_icon.addActionListener(e -> {
            JFileChooser o = new JFileChooser(So.USER_HOME);
            o.setMultiSelectionEnabled(false);
            o.setDialogTitle("Icono del programa");
            o.setFileSelectionMode(JFileChooser.FILES_ONLY);
            o.addChoosableFileFilter(new FileNameExtensionFilter("JPG", ".jpg", ".jpeg", ".jpe", ".jif", ".jfif", ".jfi"));
            o.addChoosableFileFilter(new FileNameExtensionFilter("PNG", "png"));
            o.showSaveDialog(this);
            if (o.getSelectedFile() != null) {
                icon_image_field.setText(o.getSelectedFile().getAbsolutePath());
            }
        });
    }

    @Override
    public void components() {
    }

    @Override
    public void initialState() {
        if (!properties.isEmpty()) {
            db_user.setText(properties.getProperty(AppConfig.DB_USER));
            db_password.setText(properties.getProperty(AppConfig.DB_PASSWORD));
            name_db.setText(properties.getProperty(AppConfig.DB_NAME));

            //
            title1_field.setText(properties.getProperty(AppConfig.TITLE1));
            title2_field.setText(properties.getProperty(AppConfig.TITLE2));
            icon_image_field.setText(properties.getProperty(AppConfig.LOGIN_ICON));
        }
    }

    @Override
    public void finalState() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        root_panel = new javax.swing.JPanel();
        program_info_panel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        db_user = new javax.swing.JPasswordField();
        show_user = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        db_password = new javax.swing.JPasswordField();
        show_password = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        motor = new javax.swing.JComboBox<>();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        host = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        port = new javax.swing.JTextField();
        jPanel14 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        name_db = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        test_db_button = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        title1_field = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        title2_field = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        icon_image_field = new javax.swing.JTextField();
        search_icon = new javax.swing.JButton();
        option_panel = new javax.swing.JPanel();
        save_db_button = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Panel de Configuracion"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        root_panel.setPreferredSize(new java.awt.Dimension(800, 500));
        root_panel.setLayout(new java.awt.CardLayout());

        program_info_panel.setLayout(new java.awt.GridLayout(18, 0));

        jLabel15.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Base de datos");
        program_info_panel.add(jLabel15);

        jPanel1.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel1.setText("Usuario");
        jLabel1.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel1.add(jLabel1, java.awt.BorderLayout.WEST);

        db_user.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        db_user.setText("program_user");
        jPanel1.add(db_user, java.awt.BorderLayout.CENTER);

        show_user.setActionCommand("show_user");
        show_user.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_user.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        show_user.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        show_user.setPreferredSize(new java.awt.Dimension(50, 30));
        show_user.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jPanel1.add(show_user, java.awt.BorderLayout.EAST);

        program_info_panel.add(jPanel1);

        jPanel4.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Contraeña");
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel4.add(jLabel2, java.awt.BorderLayout.WEST);

        db_password.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        db_password.setText("00000");
        db_password.setToolTipText("");
        db_password.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel4.add(db_password, java.awt.BorderLayout.CENTER);

        show_password.setActionCommand("show_password");
        show_password.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        show_password.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        show_password.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        show_password.setPreferredSize(new java.awt.Dimension(50, 30));
        show_password.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img3.png"))); // NOI18N
        jPanel4.add(show_password, java.awt.BorderLayout.EAST);

        program_info_panel.add(jPanel4);

        jPanel6.setPreferredSize(new java.awt.Dimension(800, 80));
        jPanel6.setLayout(new java.awt.GridLayout(1, 2));

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel9.setText("Motor");
        jLabel9.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(jLabel9, java.awt.BorderLayout.WEST);

        motor.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        motor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "mysql" }));
        motor.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel5.add(motor, java.awt.BorderLayout.CENTER);

        jPanel6.add(jPanel5);

        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel10.setText("Host");
        jLabel10.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel12.add(jLabel10, java.awt.BorderLayout.WEST);

        host.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        host.setText("localhost");
        host.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel12.add(host, java.awt.BorderLayout.CENTER);

        jLabel18.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel12.add(jLabel18, java.awt.BorderLayout.LINE_END);

        jPanel6.add(jPanel12);

        program_info_panel.add(jPanel6);

        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Puerto");
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel13.add(jLabel3, java.awt.BorderLayout.WEST);

        port.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        port.setText("3306");
        port.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel13.add(port, java.awt.BorderLayout.CENTER);

        jPanel17.add(jPanel13);

        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel11.setText("nombre");
        jLabel11.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel14.add(jLabel11, java.awt.BorderLayout.WEST);

        name_db.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        name_db.setText("jblue");
        name_db.setPreferredSize(new java.awt.Dimension(100, 50));
        jPanel14.add(name_db, java.awt.BorderLayout.CENTER);

        jLabel19.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel14.add(jLabel19, java.awt.BorderLayout.LINE_END);

        jPanel17.add(jPanel14);

        program_info_panel.add(jPanel17);

        jPanel7.setPreferredSize(new java.awt.Dimension(800, 50));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel7.add(jLabel7, java.awt.BorderLayout.WEST);

        test_db_button.setText("Probar conexion");
        test_db_button.setActionCommand("test db");
        jPanel7.add(test_db_button, java.awt.BorderLayout.CENTER);

        jLabel20.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel7.add(jLabel20, java.awt.BorderLayout.LINE_END);

        program_info_panel.add(jPanel7);

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 14)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Pantalla de inicio");
        program_info_panel.add(jLabel16);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setText("Titulo 1: ");
        jLabel4.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel2.add(jLabel4, java.awt.BorderLayout.WEST);
        jPanel2.add(title1_field, java.awt.BorderLayout.CENTER);

        jLabel21.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel2.add(jLabel21, java.awt.BorderLayout.LINE_END);

        program_info_panel.add(jPanel2);

        jPanel11.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("Titulo 2: ");
        jLabel5.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel11.add(jLabel5, java.awt.BorderLayout.WEST);
        jPanel11.add(title2_field, java.awt.BorderLayout.CENTER);

        jLabel22.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel11.add(jLabel22, java.awt.BorderLayout.LINE_END);

        program_info_panel.add(jPanel11);

        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText("Icon image");
        jLabel6.setPreferredSize(new java.awt.Dimension(100, 20));
        jPanel18.add(jLabel6, java.awt.BorderLayout.WEST);
        jPanel18.add(icon_image_field, java.awt.BorderLayout.CENTER);

        search_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        search_icon.setPreferredSize(new java.awt.Dimension(50, 30));
        jPanel18.add(search_icon, java.awt.BorderLayout.LINE_END);

        program_info_panel.add(jPanel18);

        root_panel.add(program_info_panel, "card3");

        add(root_panel, java.awt.BorderLayout.CENTER);

        option_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        option_panel.setLayout(new java.awt.GridLayout(1, 0));

        save_db_button.setText("Guardar");
        save_db_button.setActionCommand("save db");
        option_panel.add(save_db_button);

        add(option_panel, java.awt.BorderLayout.SOUTH);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField db_password;
    private javax.swing.JPasswordField db_user;
    private javax.swing.JTextField host;
    private javax.swing.JTextField icon_image_field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JComboBox<String> motor;
    private javax.swing.JTextField name_db;
    private javax.swing.JPanel option_panel;
    private javax.swing.JTextField port;
    private javax.swing.JPanel program_info_panel;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_db_button;
    private javax.swing.JButton search_icon;
    private javax.swing.JCheckBox show_password;
    private javax.swing.JCheckBox show_user;
    private javax.swing.JButton test_db_button;
    private javax.swing.JTextField title1_field;
    private javax.swing.JTextField title2_field;
    // End of variables declaration//GEN-END:variables

    public void nextView() {
        ly.next(root_panel);
    }

    public void backView() {
        ly.last(root_panel);
    }

    public JPasswordField getUser() {
        return db_user;
    }

    public JPasswordField getPassword() {
        return db_password;
    }

    public String getSUser() {
        return String.valueOf(db_user.getPassword());
    }

    public String getSPassword() {
        return String.valueOf(db_password.getPassword());
    }

    public String getURL() {
        return String.format("jdbc:%s://%s:%s/%s",
                motor.getItemAt(motor.getSelectedIndex()),
                host.getText(),
                port.getText(),
                name_db.getText()
        );
    }

    public String getTitle1() {
        return title1_field.getText();
    }

    public String getTitle2() {
        return title2_field.getText();
    }

    public String getIconPath() {
        return icon_image_field.getText();
    }

    public String getMotor() {
        return motor.getItemAt(motor.getSelectedIndex());
    }

    public String getPort() {
        return port.getText();
    }

    public String getHost() {
        return host.getText();
    }

    public String getDataBaseName() {
        return name_db.getText();
    }

    @Override
    public JButton getOption() {

        return option;
    }

    @Override
    public void setEvenOption(ActionListener e) {
        if (option.getActionListeners().length < 1) {
            option.addActionListener(e);
        }
    }

    @Override
    public boolean isValuesOk() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public String[] getDbValues(boolean update) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
