/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.views;

import com.jblue.controllers.viewc.OtherOptionsController;
import com.jblue.model.dtos.OEmployee;
import com.jblue.views.win.WMainMenu;
import com.jblue.sys.Session;
import com.jblue.util.ObjectUtils;
import com.jblue.views.framework.SimpleView;
import com.jblue.views.win.AcercaDe;
import com.jblue.views.win.ConfigWindow;
import com.jblue.views.win.MenuCargos;
import javax.swing.JButton;
import javax.swing.JFrame;

/**
 *
 * @author juan-campos
 */
public class OtherOptions extends SimpleView {

    private final WMainMenu father;
    private final JButton[] options;
    private final MenuCargos profile;
    private final JFrame[] arr_win_opt;
    private final ConfigWindow config_windows;
    //
    private final AcercaDe acerca;

    /**
     * Creates new form NewMenuType
     *
     * @param father
     */
    public OtherOptions(WMainMenu father) {
        initComponents();

        this.profile = new MenuCargos();
        controller = new OtherOptionsController(this, profile);
        this.arr_win_opt = new JFrame[]{
            profile
        };
        config_windows = new ConfigWindow();
        options = new JButton[]{
            profile_button, config_button, tools_button,
            secretary_button, presidente_button, admin_button,
            tesorero_button, new_button, help_button
        };

        this.father = father;

        for (JButton i : options) {
            i.addActionListener(e -> {
                this.father.goToHome();
            });
        }

        acerca = new AcercaDe();

        profile_button.addActionListener(controller);
        secretary_button.addActionListener(controller);
        tesorero_button.addActionListener(controller);
        presidente_button.addActionListener(controller);
        admin_button.addActionListener(controller);
        
        config_button.addActionListener(e -> {config_windows.setVisible(true);});
        
        help_button.addActionListener(e -> acerca.setVisible(true));
        checkToUserType();
    }

    @Override
    public void build() {
    }

    @Override
    public void events() {
    }

    @Override
    public void components() {
    }

    @Override
    public void initialState() {
    }

    @Override
    public void finalState() {
    }

    public void setWIn(JButton i) {
        int index = profile.setMenu(i.getName());
        if (index == -1) {
            return;
        }
        profile.setVisible(true);
    }

    public void closeWindows() {
        for (JFrame i : arr_win_opt) {
            i.setVisible(false);
            i.dispose();
        }
    }

    private void checkToUserType() {
        OEmployee usuario = Session.getInstancia().getUsuario();
        secretary_button.setEnabled(ObjectUtils.isSecretario(usuario));
        tesorero_button.setEnabled(ObjectUtils.isTesorero(usuario));
        presidente_button.setEnabled(ObjectUtils.isPresidente(usuario));
        admin_button.setEnabled(ObjectUtils.isAdministrador(usuario));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        help_button = new javax.swing.JButton();
        profile_button = new javax.swing.JButton();
        secretary_button = new javax.swing.JButton();
        tesorero_button = new javax.swing.JButton();
        presidente_button = new javax.swing.JButton();
        admin_button = new javax.swing.JButton();
        config_button = new javax.swing.JButton();
        tools_button = new javax.swing.JButton();
        new_button = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(900, 700));
        setName("Menu"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.GridLayout(3, 3, 10, 10));

        help_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        help_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/help_x128.png"))); // NOI18N
        help_button.setText("Ayuda");
        help_button.setActionCommand("help");
        help_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        help_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(help_button);

        profile_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        profile_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x128/usuario.png"))); // NOI18N
        profile_button.setText("Perfil");
        profile_button.setActionCommand("profile");
        profile_button.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        profile_button.setName("Perfil"); // NOI18N
        profile_button.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        add(profile_button);

        secretary_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        secretary_button.setText("Secretario");
        secretary_button.setActionCommand("secretary");
        secretary_button.setName("Secretario"); // NOI18N
        add(secretary_button);

        tesorero_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tesorero_button.setText("Tesorero");
        tesorero_button.setActionCommand("tesorero");
        tesorero_button.setName("Tesorero"); // NOI18N
        add(tesorero_button);

        presidente_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        presidente_button.setText("Presidente");
        presidente_button.setActionCommand("presidente");
        presidente_button.setName("Presidente"); // NOI18N
        add(presidente_button);

        admin_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        admin_button.setText("Administrador");
        admin_button.setActionCommand("admin");
        admin_button.setName("Administrador"); // NOI18N
        add(admin_button);

        config_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        config_button.setText("Configuraciones");
        config_button.setActionCommand("config");
        add(config_button);

        tools_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        tools_button.setText("Herramientas del Software");
        tools_button.setActionCommand("tools");
        add(tools_button);

        new_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        new_button.setText("Previos");
        new_button.setActionCommand("new");
        new_button.setName(""); // NOI18N
        add(new_button);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton admin_button;
    private javax.swing.JButton config_button;
    private javax.swing.JButton help_button;
    private javax.swing.JButton new_button;
    private javax.swing.JButton presidente_button;
    private javax.swing.JButton profile_button;
    private javax.swing.JButton secretary_button;
    private javax.swing.JButton tesorero_button;
    private javax.swing.JButton tools_button;
    // End of variables declaration//GEN-END:variables

}
