/*
 * Copyright (C) 2024 juan-campos
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.views;

import com.jblue.model.constants.Const;
import com.jblue.model.dtos.OEmployee;
import com.jblue.sys.SystemSession;
import com.jblue.views.framework.SimpleView;
import java.awt.event.ActionListener;
import java.time.format.DateTimeFormatter;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import com.jblue.views.framework.OptionMenuModel;

/**
 *
 * @author juan-campos
 */
public final class VPerfil extends SimpleView implements OptionMenuModel {

    private final OEmployee personal;

    /**
     * Creates new form VPerfil
     */
    public VPerfil() {
        initComponents();
        this.option = mkButton(getName(), null, null);
        personal = SystemSession.getInstancia().getUsuario();
        setInfoGrafica();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        campo_apellidos = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        campo_cargo = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campo_estado = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        campo_usuario = new javax.swing.JTextField();
        mostrar_usuario = new javax.swing.JCheckBox();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        campo_contra = new javax.swing.JTextField();
        mostrar_contra = new javax.swing.JCheckBox();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        campo_fecha_registro = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(750, 600));
        setName("Datos de usuario"); // NOI18N
        setPreferredSize(new java.awt.Dimension(750, 600));
        setLayout(new java.awt.GridLayout(12, 1));

        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Nombre:");
        jLabel1.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel1.add(jLabel1, java.awt.BorderLayout.LINE_START);

        campo_nombre.setEditable(false);
        jPanel1.add(campo_nombre, java.awt.BorderLayout.CENTER);

        add(jPanel1);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Apellidos");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel2.add(jLabel2, java.awt.BorderLayout.LINE_START);

        campo_apellidos.setEditable(false);
        jPanel2.add(campo_apellidos, java.awt.BorderLayout.CENTER);

        add(jPanel2);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Cargo");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel3.add(jLabel3, java.awt.BorderLayout.LINE_START);

        campo_cargo.setEditable(false);
        jPanel3.add(campo_cargo, java.awt.BorderLayout.CENTER);

        add(jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Estado");
        jLabel4.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel4.add(jLabel4, java.awt.BorderLayout.LINE_START);

        campo_estado.setEditable(false);
        jPanel4.add(campo_estado, java.awt.BorderLayout.CENTER);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Usuario");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel5.add(jLabel5, java.awt.BorderLayout.LINE_START);

        campo_usuario.setEditable(false);
        jPanel5.add(campo_usuario, java.awt.BorderLayout.CENTER);

        mostrar_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jPanel5.add(mostrar_usuario, java.awt.BorderLayout.LINE_END);

        add(jPanel5);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Contraseña");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel6.add(jLabel6, java.awt.BorderLayout.LINE_START);

        campo_contra.setEditable(false);
        jPanel6.add(campo_contra, java.awt.BorderLayout.CENTER);

        mostrar_contra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/img2.png"))); // NOI18N
        jPanel6.add(mostrar_contra, java.awt.BorderLayout.LINE_END);

        add(jPanel6);

        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Fecha de registro");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 17));
        jPanel7.add(jLabel7, java.awt.BorderLayout.LINE_START);

        campo_fecha_registro.setEditable(false);
        jPanel7.add(campo_fecha_registro, java.awt.BorderLayout.CENTER);

        add(jPanel7);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_apellidos;
    private javax.swing.JTextField campo_cargo;
    private javax.swing.JTextField campo_contra;
    private javax.swing.JTextField campo_estado;
    private javax.swing.JTextField campo_fecha_registro;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JCheckBox mostrar_contra;
    private javax.swing.JCheckBox mostrar_usuario;
    // End of variables declaration//GEN-END:variables
private final JButton option;

    public void setInfoGrafica() {
        if (!isInfoValid()) {
            return;
        }
        campo_nombre.setText(personal.getName());
        campo_apellidos.setText(personal.getLastNames());
        campo_cargo.setText(personal.getCargoString());
        campo_estado.setText(personal.getStatus() + "");
        campo_usuario.setText(personal.getUser());
        campo_contra.setText(personal.getPassword());
        campo_fecha_registro.setText(personal.getDateRegister().format(DateTimeFormatter.ofPattern(Const.DATE_TIME_FORMAT)));
    }

    public boolean isInfoValid() {
        return personal != null;
    }

    public void cambiarContraseña() {
        int input = JOptionPane.showConfirmDialog(this,
                "¿Esta seguro de que quiere cambiar su contraseña?",
                "Cambior contraseña",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE
        );
        if (input != JOptionPane.YES_OPTION) {
            return;
        }
        String usuario = personal.getUser();
        String contraseña = JOptionPane.showInputDialog(this,
                "Ingrese Contraseña Actual",
                "Cambio de contraseña",
                JOptionPane.QUESTION_MESSAGE
        );

    }

    public void cambiarFoto() {

    }

    @Override
    public JButton getOption() {
        return option;
    }

    @Override
    public void setEvenOption(ActionListener e) {
        if (option.getActionListeners().length < 1) {
            option.addActionListener(e);
        }

    }

    @Override
    public void build() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void events() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void components() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void initialState() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void finalState() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
