/*
 * Copyright (C) 2025 juanp
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.jblue.views;

import com.jblue.controllers.FactoryController;
import com.jblue.controllers.compc.ComboBoxController;
import com.jblue.controllers.compc.TableController;
import com.jblue.model.dtos.OStreet;
import com.jblue.model.dtos.OWaterIntakeTypes;
import com.jblue.model.dtos.OWaterIntakes;
import com.jblue.model.dtos.Objects;
import com.jblue.model.factories.CacheFactory;
import com.jblue.model.factories.TableModelFactory;
import com.jblue.util.Filters;
import com.jblue.views.framework.DBValuesModel;
import com.jblue.views.framework.DBView;
import com.jblue.views.framework.TableSearchViewModel;
import com.jutil.swingw.modelos.JTableModel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author juanp
 */
public final class WaterIntakesView extends DBView implements DBValuesModel, TableSearchViewModel {

    private final CardLayout ly;
    private final JTableModel model;
    private OWaterIntakes object_search;
    private ComboBoxController<OStreet> street_cat_1;
    private ComboBoxController<OStreet> street_cat_2;
    private ComboBoxController<OWaterIntakeTypes> water_intake;

    /**
     * Creates new form WaterIntakesView
     */
    public WaterIntakesView() {
        initComponents();
        ly = (CardLayout) root_panel.getLayout();
        ly.show(root_panel, register_panel.getName());
        model = TableModelFactory.getWaterIntakesTableModel();
        controller = FactoryController.getWaterIntakesController(this);
        table_controller = new TableController(this, CacheFactory.WATER_INTAKES);
        water_intake = new ComboBoxController(water_intake_types_field, CacheFactory.WATER_INTAKES_TYPES);
        street_cat_1 = new ComboBoxController(street1_field, CacheFactory.STREETS);
        street_cat_2 = new ComboBoxController(street2_field, CacheFactory.STREETS);
        build();
    }

    @Override
    public void build() {
        components();
        events();
        finalState();
        initialState();
    }

    @Override
    public void components() {
        objects_table.setModel(model);
    }

    @Override
    public void events() {
        back_button.addActionListener(table_controller);
        next_button.addActionListener(table_controller);
        reload_button.addActionListener(table_controller);
        objects_table.addMouseListener(table_controller);
        save_button.addActionListener(controller);

        update_button.addActionListener(controller);
        delete_button.addActionListener(controller);
        cancel_button.addActionListener(controller);
        register_button.addActionListener(table_controller);
        search_button.addActionListener(table_controller);
    }

    @Override
    public void initialState() {

        //
        object_search = null;
        view_show = 1;
        save_button.setEnabled(true);
        update_button.setEnabled(false);
        delete_button.setEnabled(false);
    }

    @Override
    public void finalState() {
        street_cat_1.loadData();
        street_cat_2.loadData();
        water_intake.loadData();
    }

    @Override
    public OWaterIntakes getObjectSearch() {
        return object_search;
    }

    @Override
    public void setObjectSearch(Objects o) {
        object_search = (OWaterIntakes) o;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        north_panel = new javax.swing.JPanel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jPanel15 = new javax.swing.JPanel();
        register_button = new javax.swing.JButton();
        search_button = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        root_panel = new javax.swing.JPanel();
        register_panel = new javax.swing.JPanel();
        panel_campos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        user_field = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        water_intake_types_field = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        operation_cost_field = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        street1_field = new javax.swing.JComboBox<>();
        jPanel13 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        street2_field = new javax.swing.JComboBox<>();
        jPanel14 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        location_field = new javax.swing.JTextField();
        jPanel16 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        status_field = new javax.swing.JComboBox<>();
        jPanel17 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        date_update_field = new javax.swing.JTextField();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        date_register = new javax.swing.JTextField();
        options_panel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        save_button = new javax.swing.JButton();
        update_button = new javax.swing.JButton();
        delete_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        search_panel = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        reload_button = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        search_field = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        back_button = new javax.swing.JButton();
        next_button = new javax.swing.JButton();
        panel_izq = new javax.swing.JPanel();
        tabla_usuarios = new javax.swing.JScrollPane();
        objects_table = new javax.swing.JTable();
        status_bar_panel = new javax.swing.JPanel();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        count = new javax.swing.JLabel();
        range = new javax.swing.JLabel();
        jPanel29 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();

        setName("Tomas Registradas"); // NOI18N
        setPreferredSize(new java.awt.Dimension(900, 700));
        setLayout(new java.awt.BorderLayout());

        north_panel.setPreferredSize(new java.awt.Dimension(900, 30));
        north_panel.setLayout(new java.awt.BorderLayout(10, 10));

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jToggleButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        jToggleButton2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/desbloquear.png"))); // NOI18N
        north_panel.add(jToggleButton2, java.awt.BorderLayout.WEST);

        jPanel15.setLayout(new java.awt.GridLayout(1, 0, 10, 10));

        register_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        register_button.setText("Registrar Tipo de Tomas");
        register_button.setActionCommand("register_view");
        jPanel15.add(register_button);

        search_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        search_button.setText("Consultar los Tipos de Tomas");
        search_button.setActionCommand("search_view");
        jPanel15.add(search_button);

        north_panel.add(jPanel15, java.awt.BorderLayout.CENTER);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/configuraciones.png"))); // NOI18N
        jButton2.setPreferredSize(new java.awt.Dimension(100, 30));
        north_panel.add(jButton2, java.awt.BorderLayout.EAST);

        add(north_panel, java.awt.BorderLayout.NORTH);

        root_panel.setLayout(new java.awt.CardLayout(10, 10));

        register_panel.setName("register"); // NOI18N
        register_panel.setLayout(new java.awt.BorderLayout());

        panel_campos.setPreferredSize(new java.awt.Dimension(500, 620));
        panel_campos.setLayout(new java.awt.GridLayout(13, 0, 0, 10));

        jLabel4.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Datos del tipo de toma");
        jLabel4.setPreferredSize(new java.awt.Dimension(500, 100));
        panel_campos.add(jLabel4);

        jPanel12.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel12.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel6.setText("Titular");
        jLabel6.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel12.add(jLabel6, java.awt.BorderLayout.WEST);

        user_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        user_field.setName(""); // NOI18N
        jPanel12.add(user_field, java.awt.BorderLayout.CENTER);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jButton3.setToolTipText("Seleccionar titular");
        jButton3.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel12.add(jButton3, java.awt.BorderLayout.LINE_END);

        panel_campos.add(jPanel12);

        jPanel8.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel8.setLayout(new java.awt.BorderLayout());

        jLabel2.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel2.setText("Tipo Toma de agua");
        jLabel2.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel8.add(jLabel2, java.awt.BorderLayout.WEST);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jButton1.setToolTipText("Seleccionar Tipo de toma");
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel8.add(jButton1, java.awt.BorderLayout.LINE_END);

        jPanel8.add(water_intake_types_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel8);

        jPanel9.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel9.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel3.setText("Costo de operacion");
        jLabel3.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel9.add(jLabel3, java.awt.BorderLayout.WEST);

        operation_cost_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        operation_cost_field.setName(""); // NOI18N
        jPanel9.add(operation_cost_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel9);

        jPanel10.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel10.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel5.setText("Calle 1: ");
        jLabel5.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel10.add(jLabel5, java.awt.BorderLayout.WEST);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jButton4.setToolTipText("Seleccionar Calle 1");
        jButton4.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel10.add(jButton4, java.awt.BorderLayout.LINE_END);

        jPanel10.add(street1_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel10);

        jPanel13.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel13.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel7.setText("Calle 2: ");
        jLabel7.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel13.add(jLabel7, java.awt.BorderLayout.WEST);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jButton5.setToolTipText("Seleccionar Calle 2");
        jButton5.setPreferredSize(new java.awt.Dimension(50, 50));
        jPanel13.add(jButton5, java.awt.BorderLayout.LINE_END);

        jPanel13.add(street2_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel13);

        jPanel14.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel14.setLayout(new java.awt.BorderLayout());

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel8.setText("Ubicacion");
        jLabel8.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel14.add(jLabel8, java.awt.BorderLayout.WEST);

        location_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        location_field.setName(""); // NOI18N
        jPanel14.add(location_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel14);

        jPanel16.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel16.setLayout(new java.awt.BorderLayout());

        jLabel9.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel9.setText("Estado: ");
        jLabel9.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel16.add(jLabel9, java.awt.BorderLayout.WEST);

        status_field.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Estado.", "Activo.", "Inactivo." }));
        status_field.setName(""); // NOI18N
        jPanel16.add(status_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel16);

        jPanel17.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel17.setLayout(new java.awt.BorderLayout());

        jLabel10.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel10.setText("Fecha de actualizacion");
        jLabel10.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel17.add(jLabel10, java.awt.BorderLayout.WEST);

        date_update_field.setEditable(false);
        date_update_field.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        date_update_field.setName(""); // NOI18N
        jPanel17.add(date_update_field, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel17);

        jPanel18.setPreferredSize(new java.awt.Dimension(100, 35));
        jPanel18.setLayout(new java.awt.BorderLayout());

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        jLabel11.setText("Fecha de registro.");
        jLabel11.setPreferredSize(new java.awt.Dimension(150, 20));
        jPanel18.add(jLabel11, java.awt.BorderLayout.WEST);

        date_register.setEditable(false);
        date_register.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        date_register.setName(""); // NOI18N
        jPanel18.add(date_register, java.awt.BorderLayout.CENTER);

        panel_campos.add(jPanel18);

        register_panel.add(panel_campos, java.awt.BorderLayout.CENTER);

        options_panel.setPreferredSize(new java.awt.Dimension(500, 80));
        options_panel.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jPanel3.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        save_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        save_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/disquete.png"))); // NOI18N
        save_button.setText("Guardar");
        save_button.setActionCommand("save");
        jPanel3.add(save_button);

        update_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        update_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/sincronizar.png"))); // NOI18N
        update_button.setText("Actualizar");
        update_button.setActionCommand("update");
        jPanel3.add(update_button);

        delete_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        delete_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/eliminar.png"))); // NOI18N
        delete_button.setText("Eliminar");
        delete_button.setActionCommand("delete");
        jPanel3.add(delete_button);

        options_panel.add(jPanel3);

        cancel_button.setFont(new java.awt.Font("Liberation Sans", 0, 14)); // NOI18N
        cancel_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x32/cerca.png"))); // NOI18N
        cancel_button.setText("Cancelar");
        cancel_button.setActionCommand("cancel");
        options_panel.add(cancel_button);

        register_panel.add(options_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(register_panel, "register");

        search_panel.setName("consult"); // NOI18N
        search_panel.setLayout(new java.awt.BorderLayout(5, 5));

        jPanel5.setMinimumSize(new java.awt.Dimension(100, 30));
        jPanel5.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.setLayout(new java.awt.BorderLayout(5, 5));

        reload_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/recargar.png"))); // NOI18N
        reload_button.setActionCommand("reload");
        reload_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel5.add(reload_button, java.awt.BorderLayout.WEST);

        jPanel6.setLayout(new java.awt.BorderLayout(5, 5));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/search.png"))); // NOI18N
        jLabel1.setPreferredSize(new java.awt.Dimension(30, 30));
        jPanel6.add(jLabel1, java.awt.BorderLayout.WEST);
        jPanel6.add(search_field, java.awt.BorderLayout.CENTER);

        jPanel5.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel11.setLayout(new java.awt.GridLayout(1, 2, 5, 5));

        back_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/previous.png"))); // NOI18N
        back_button.setActionCommand("back");
        back_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(back_button);

        next_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/jblue/media/img/x24/next-button.png"))); // NOI18N
        next_button.setActionCommand("next");
        next_button.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel11.add(next_button);

        jPanel5.add(jPanel11, java.awt.BorderLayout.EAST);

        search_panel.add(jPanel5, java.awt.BorderLayout.NORTH);

        panel_izq.setPreferredSize(new java.awt.Dimension(500, 700));
        panel_izq.setLayout(new java.awt.BorderLayout(10, 10));

        objects_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        objects_table.setShowGrid(true);
        tabla_usuarios.setViewportView(objects_table);

        panel_izq.add(tabla_usuarios, java.awt.BorderLayout.CENTER);

        search_panel.add(panel_izq, java.awt.BorderLayout.CENTER);

        status_bar_panel.setPreferredSize(new java.awt.Dimension(100, 30));
        status_bar_panel.setLayout(new java.awt.BorderLayout());

        jPanel32.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel32.setLayout(new java.awt.BorderLayout());

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("No.");
        jPanel32.add(jLabel18, java.awt.BorderLayout.CENTER);

        count.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        count.setText("0");
        count.setToolTipText("Numero de pagos hechos.");
        count.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel32.add(count, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel32, java.awt.BorderLayout.WEST);

        range.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        range.setText("0 - 0");
        range.setToolTipText("");
        status_bar_panel.add(range, java.awt.BorderLayout.CENTER);

        jPanel29.setPreferredSize(new java.awt.Dimension(100, 30));
        jPanel29.setLayout(new java.awt.BorderLayout());

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Total:");
        jPanel29.add(jLabel17, java.awt.BorderLayout.CENTER);

        total.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        total.setText("0");
        total.setToolTipText("Numero de pagos hechos.");
        total.setPreferredSize(new java.awt.Dimension(50, 16));
        jPanel29.add(total, java.awt.BorderLayout.LINE_END);

        status_bar_panel.add(jPanel29, java.awt.BorderLayout.EAST);

        search_panel.add(status_bar_panel, java.awt.BorderLayout.SOUTH);

        root_panel.add(search_panel, "consult");

        add(root_panel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back_button;
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel count;
    private javax.swing.JTextField date_register;
    private javax.swing.JTextField date_update_field;
    private javax.swing.JButton delete_button;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JTextField location_field;
    private javax.swing.JButton next_button;
    private javax.swing.JPanel north_panel;
    private javax.swing.JTable objects_table;
    private javax.swing.JTextField operation_cost_field;
    private javax.swing.JPanel options_panel;
    private javax.swing.JPanel panel_campos;
    private javax.swing.JPanel panel_izq;
    private javax.swing.JLabel range;
    private javax.swing.JButton register_button;
    private javax.swing.JPanel register_panel;
    private javax.swing.JButton reload_button;
    private javax.swing.JPanel root_panel;
    private javax.swing.JButton save_button;
    private javax.swing.JButton search_button;
    private javax.swing.JTextField search_field;
    private javax.swing.JPanel search_panel;
    private javax.swing.JPanel status_bar_panel;
    private javax.swing.JComboBox<String> status_field;
    private javax.swing.JComboBox<OStreet> street1_field;
    private javax.swing.JComboBox<OStreet> street2_field;
    private javax.swing.JScrollPane tabla_usuarios;
    private javax.swing.JLabel total;
    private javax.swing.JButton update_button;
    private javax.swing.JTextField user_field;
    private javax.swing.JComboBox<OWaterIntakes> water_intake_types_field;
    // End of variables declaration//GEN-END:variables

    @Override
    public JTextField getTextComponenteTable() {
        return search_field;
    }

    @Override
    public String getTextSearchTable() {
        return Filters.clearText(search_field.getText());
    }

    @Override
    public JTable getTable() {
        return objects_table;
    }

    @Override
    public JTableModel getModel() {
        return model;
    }

    @Override
    public void setViewShow(int view_show) {
        this.view_show = view_show;
        String op = switch (view_show) {
            case 2:
                yield search_panel.getName();
            default:
                yield register_panel.getName();
        };
        ly.show(root_panel, op);
    }

    @Override
    public int getViewShow() {
        return view_show;
    }

    @Override
    public boolean isValuesOk() {
        boolean ok = true;
        JTextField[] text_fields = {};
        for (JTextField i : text_fields) {
            if (Filters.isNullOrBlank(i.getText())) {
                JOptionPane.showMessageDialog(this, "El campo %s no es valido", "Campo no valido", JOptionPane.ERROR_MESSAGE);
                ok = false;
                break;
            }
        }
        return ok;
    }

    @Override
    public String[] getDbValues(boolean update) {
        return null;
    }

    @Override
    public void setRowsData(String... info) {
        count.setText(info[0]);
        range.setText(info[1]);
        total.setText(info[2]);
    }

    @Override
    public void setScreenTableInfo() {
        //
        save_button.setEnabled(false);
        update_button.setEnabled(true);
        delete_button.setEnabled(true);
    }

    void hiddenNorthPanel(boolean b) {
        this.north_panel.setVisible(b);
    }
}
